### ISSUE TITLE
On org.openrewrite.java.tree.J  interface, add a method String printAST() which prints the element and it's children

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#10]
`J.printAST()` should operate similarly to the `print()` method in that it returns a String representation of the AST element which includes all of its children.
Unlike `print()`, `printAST()` is not expected to return Java source code, but instead directly transcribe the AST itself. The intended purpose of this is as a debugging tool for our own convenience as the developers of this software.
Implementing `printAST()` will likely involve creating a `PrintJavaAST` class that operates similarly to the existing `org.openrewrite.java.internal.PrintJava` class.

One thing I've grappled with trying to work on this codebase is thinking in terms of the AST, rather than in terms of the source code. I suspect that easily being able to interrogate any such AST element for both its source code representation and its AST representation will be a useful debugging and onboarding-to-the-concepts tool.

The output of this method may resemble JSON, yaml, or a similar data format.
So for java source like:
```java
    package a;
    public class A {
       public void nonStatic() {}
    }
```
Example output of printAST(), in a pseudo-JSON-ish format, may resemble something along these lines:
```
{ CompilationUnit :
    sourcePath: "A.java"
    imports: []
    classes: [
        { ClassDecl:
            name: { Ident(A)}
            annotations: []
            modifiers: [ {Modifier.Public} ]
            typeParameters: null
            extendings: null
            body: { Block:
                statik: null
                statements: [
                    { MethodDecl:
                        annotations: []
                        modifiers: [ { Modifier.Public }]
                        typeParameters: null
                        returnTypeExpr: { Primitive:
                            type: { "Void" }
                        }
                        params: { MethodDecl.Parameters
                            params: [ Empty ]
                        }
                        throwz: null
                        defaultValue: null
                        body: {
                            statik: null
                            statements: []
                        }
                    }
                ]
            }
        }
    ]
}
```

**Comment by jkschneider** [comment]
Might suggest Graphviz's `dot` output format instead of a proprietary one. [Graphviz Java implementation](https://github.com/nidi3/graphviz-java).

**Comment by jkschneider** [comment]
Another future enhancement idea... Does bracketing the thing we care about, and pruning the tree to only the ancestors of that thing help?

```java
public class A {
    class B {
       public void method() {
           m1();
           <<m2();>>
           logger.info("log something");
       }
    }
}
```

Could be implemented relatively easily by string replacing with a marker comment before parsing like this:


```java
```java
public class A {
    class B {
       public void method() {
           m1();
           /*PLOTME*/m2();
           logger.info("log something");
       }
    }
}
```

...and then implementing a visitor that simply looks for any tree element with a formatting prefix containing `/*PLOTME*/`, and plot everything in its cursor hierarchy.

**Comment by sambsnyd** [comment]
I love the graphviz idea. Maybe at some point in the future we have some kind of visual UI for creating or viewing rewrite recipes... this would slot neatly into that.

**Comment by jkschneider** [comment]
Good digraph examples including tags, in this case of Huffman encoding, but could be similar for our trees:

http://huffman.ooz.ie/tree.dot?text=WITH%20160,000%20BRITONS%20REPORTED%20TO%20BE%20IN%20FRANCE,%20PORTS%20AND%20AIRPORTS%20FACE%20A%20SCRAMBLE%20TO%20RETURN.

![image](https://user-images.githubusercontent.com/1697736/90276293-87f84e80-de18-11ea-81db-131da0cb9409.png)
