### ISSUE TITLE
Null Pointer Exception When Upgrading Past Version 7.11

### ISSUE THREAD

**Issue by chrismhess** [openrewrite/rewrite#1019]
When we attempt to run recipes using versions later than 7.11 the Run method inside the Recipe class gets executed, it throws a null pointer exception that we cannot track down. 

Rolling back to 7.11 or earlier solves the issue.

**Comment by sambsnyd** [comment]
@chrismhess can you provide more details? Which recipe are you trying to run? What's the full stack trace? You can also [join our slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) and message us directly to share more details.

**Comment by traceyyoshima** [comment]
@chrismhess Thanks for opening an issue! I suspect this was related to the addition of Javadoc elements in the AST, and many of the NPEs have been fixed now.

Closing the issues due to inactivity. Please let us know if you have any other problems with a stack trace and we'll track it down
