### ISSUE TITLE
Handle this enum case

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#103]
This should fail parsing currently:

```java
class Scratch {
  public enum State {
    @Deprecated
    MOVING {
      @Override
      public SomeType.Inner toInner() {
        return SomeType.Inner.WORKING;
      }
    }
  }
}
```

> 15:19:48.731 [main] ERROR org.openrewrite.java.Java11ParserVisitor - --- BEGIN PATH ---
> 15:19:48.731 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCCompilationUnit(sourceFile = OMITTED)
> 15:19:48.741 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCClassDecl(name = DbMoneyMovement, line = 32)
> 15:19:48.741 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCClassDecl(name = MoneyMoverState, line = 206)
> 15:19:48.742 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCVariableDecl(name = MOVING_MONEY, line = 207)
> 15:19:48.746 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCNewClass(line = 208)
> 15:19:48.747 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCMethodDecl(line = 209)

**Comment by sambsnyd** [comment]
I'll look into this

**Comment by sambsnyd** [comment]
I've confirmed that this duplicates #105 and #107. The fixes for those issues also address this one.
