### ISSUE TITLE
Parser failure for annotated parameter

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#105]
```java
public enum AppMessageCriterion {
    public Matcher<Install> getMatcher(Manager manager, FeatureFlags featureFlagManager, List<Install> installs,
      @Nullable List<String> arguments) {
    }
}
```

> 15:26:10.225 [main] ERROR org.openrewrite.java.Java11ParserVisitor - Failed to convert JCVariableDecl for the following cursor stack:
> 15:26:10.226 [main] ERROR org.openrewrite.java.Java11ParserVisitor - --- BEGIN PATH ---
> 15:26:10.226 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCCompilationUnit(sourceFile = OMITTED)
> 15:26:10.234 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCClassDecl(name = AppMessageCriterion, line = 55)
> 15:26:10.240 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCMethodDecl(line = 153)
> 15:26:10.240 [main] ERROR org.openrewrite.java.Java11ParserVisitor - --- END PATH ---
> 15:26:10.240 [main] ERROR org.openrewrite.java.Java11ParserVisitor - Failed to convert JCMethodDecl for the following cursor stack:
> 15:26:10.240 [main] ERROR org.openrewrite.java.Java11ParserVisitor - --- BEGIN PATH ---
> 15:26:10.240 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCCompilationUnit(sourceFile =  OMITTED)
> 15:26:10.240 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCClassDecl(name = AppMessageCriterion, line = 55)
> 15:26:10.240 [main] ERROR org.openrewrite.java.Java11ParserVisitor - --- END PATH ---
> 15:26:10.241 [main] ERROR org.openrewrite.java.Java11ParserVisitor - Failed to convert JCClassDecl for the following cursor stack:
> 15:26:10.241 [main] ERROR org.openrewrite.java.Java11ParserVisitor - --- BEGIN PATH ---
> 15:26:10.241 [main] ERROR org.openrewrite.java.Java11ParserVisitor - JCCompilationUnit(sourceFile = OMITTED)
> 15:26:10.241 [main] ERROR org.openrewrite.java.Java11ParserVisitor - --- END PATH ---
> java.lang.IndexOutOfBoundsException: Illegal start index
> 	at java.base/java.util.regex.Matcher.find(Matcher.java:771)
> 	at org.openrewrite.java.Java11ParserVisitor.lambda$visitVariables$42(Java11ParserVisitor.java:1185)

**Comment by tkvangorder** [comment]
I will investigate this one.
