### ISSUE TITLE
RemoveUnusedimports removes used imports

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1066]
I ran this recipe on a few private repositories, and I had some compilation failures because of imports that where removed, but were in fact used. I fail to fin a pattern to explain the error, and thus create a unit test: sometimes the class was used in javadoc (`@throws` or `@link`), sometimes in annotations, ...

So I played a bit with Moderne to reproduce on some public repositories.
Here's one: https://github.com/code4craft/webmagic/pull/1037/files
```
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ webmagic-extension ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 24 source files to /tmp/webmagic/webmagic-extension/target/test-classes
[INFO] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/MockPageModelPipeline.java: Some input files use or override a deprecated API.
[INFO] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/MockPageModelPipeline.java: Recompile with -Xlint:deprecation for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/downloader/MockGithubDownloader.java:[932,26] cannot find symbol
  symbol:   class Request
  location: class us.codecraft.webmagic.downloader.MockGithubDownloader
[ERROR] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/downloader/MockGithubDownloader.java:[932,43] cannot find symbol
  symbol:   class Task
  location: class us.codecraft.webmagic.downloader.MockGithubDownloader
[ERROR] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/downloader/MockGithubDownloader.java:[932,12] cannot find symbol
  symbol:   class Page
  location: class us.codecraft.webmagic.downloader.MockGithubDownloader
[ERROR] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/downloader/MockGithubDownloader.java:[933,9] cannot find symbol
  symbol:   class Page
  location: class us.codecraft.webmagic.downloader.MockGithubDownloader
[ERROR] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/downloader/MockGithubDownloader.java:[933,25] cannot find symbol
  symbol:   class Page
  location: class us.codecraft.webmagic.downloader.MockGithubDownloader
[ERROR] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/downloader/MockGithubDownloader.java:[936,29] cannot find symbol
  symbol:   class Request
  location: class us.codecraft.webmagic.downloader.MockGithubDownloader
[ERROR] /tmp/webmagic/webmagic-extension/src/test/java/us/codecraft/webmagic/downloader/MockGithubDownloader.java:[937,25] cannot find symbol
  symbol:   class PlainText
  location: class us.codecraft.webmagic.downloader.MockGithubDownloader
[INFO] 7 errors 

```

**Comment by traceyyoshima** [comment]
@murdos thanks for reporting the issue!

I looked into the cause and the removed used imports are typically missing type attribution.
In the linked example, the classes belong to different source sets but have the same FQN.

Ex:
`us.codecraft.webmagic.SpiderTest` is in:
"webmagic/webmagic-core/src/test/java/us/codecraft/webmagic/SpiderTest.java"
and
"webmagic/webmagic-samples/src/test/java/us/codecraft/webmagic/SpiderTest.java"

The source files are collected in the parser and processed at the same time. So, the compiler throws a duplicate class exception.

Unassignning myself, since I think this one will require Jon or Tyler.

**Comment by murdos** [comment]
FYI I still reproduce this kind of issue (probably with a different origin) while applying the recipe to https://github.com/murdos/OpenCyclos/blob/master/src/main/java/nl/strohalm/cyclos/controls/accounts/cards/SearchCardsAsBrokerAction.java using last code from main branches of rewrite and rewrite-maven-plugin.

![image](https://user-images.githubusercontent.com/155828/140626009-d9e195ec-fec4-47f9-8475-ce6e392cc585.png)

**Comment by matteobaccan** [comment]
Hi

I have the same problem with enums
For example in this enum: RemoveUnusedImports remove SerializedName

```
import com.google.gson.annotations.SerializedName;

public enum PKIState {
    @SerializedName("active") ACTIVE,
    @SerializedName("dismissed") DISMISSED
}
```

all the best
matteo baccan

**Comment by tkvangorder** [comment]
@matteobaccan I have moved your problem to a separate issue #1251

**Comment by tkvangorder** [comment]
@murdos Finally got some time to investigate your last issue: 

Having a `@link` immediately after an `@See` is illegal according to the JavaDoc specification. OpenRewrite relies on the Javadoc parsing that is native to the platform and `@see {@link ActionPolicyRepository} to view the required permissions` is parsed as an `ErroneousTree` and therefore the link is never visited (nor is the type information in the link collected).

The solution to this specific issue is to either use `@See ActionPolicyRepository` or `{@link ActionPolicyRepository}` (without the `@See`).

A couple of references that describe this specific behavior:

https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#see
https://stackoverflow.com/a/65511981

**Comment by murdos** [comment]
@tkvangorder: I don't think this issue should be closed, the original issue is still investigated, according to last comment of @traceyyoshima : https://github.com/openrewrite/rewrite/issues/1066#issuecomment-952123316

**Comment by traceyyoshima** [comment]
@murdos the new type cache accounts for the same FQN in multiple packages, but we're still working on a release.
