### ISSUE TITLE
Recipe for deleting properties from Properties files.

### ISSUE THREAD

**Issue by jvillarb** [openrewrite/rewrite#1070]
Good morning, I would like to ask you a question. Just as there is a recipe for deleting properties from YAML configuration files ( org.openrewrite.yaml.DeleteProperty), I think it would be very useful to be able to delete obsolete properties from "Properties" configuration files. Is there any reason why there is no such equivalence?

**Comment by sambsnyd** [comment]
Good idea @jvillarb. [org.openrewrite.properties.DeleteProperty](https://github.com/openrewrite/rewrite/blob/e648a38c25eb2c92d8630556b44209e87d4ce901/rewrite-properties/src/main/java/org/openrewrite/properties/DeleteProperty.java) will be in the 7.15.0 release.
