### ISSUE TITLE
update the groupId and artifactId of a dependency

### ISSUE THREAD

**Issue by jvillarb** [openrewrite/rewrite#1073]
Good afternoon,

Is there any recipe or set of recipes to be able to change the groupId and artifactId of existing dependencies in the POM to a new groupId and artifactId?

As far as I have been able to see in the documentation, you can only change the version or scope of a dependency, it would be interesting if there was an option to also change the groupId and artifactId.

**Comment by aegershman** [comment]
Hey @jvillarb right on, thanks for opening this-- I don't believe we have this as a standalone recipe at the moment, but let me see about adding something to solve this. Is there a specific use-case in mind you're trying to solve? No worries if not, but if there is, I'd be curious to hear about it. I'll get back to you on this, though 👍

**Comment by aegershman** [comment]
@jvillarb I've added this in https://github.com/openrewrite/rewrite/pull/1074 if you try it out, let me know if it meets what you had in mind 👍

**Comment by jvillarb** [comment]
Thank you very much, when do you plan to release the version where it can be available?

**Comment by aegershman** [comment]
This will be available in the next release when 7.15.0 is cut. In the mean time, if you're interested, you can use the latest `7.15.0-SNAPSHOT` to use the recipe. You could consume them in the plugins by using the latest [`rewrite-maven-plugin` from source](https://github.com/openrewrite/rewrite-maven-plugin/blob/3e18b87da8c593ff93b3b638d780170c4d4a7f0d/pom.xml#L7), or the same using the latest `rewrite-gradle-plugin`.

I'll go ahead and close this for the time being, but please @ me in this issue if you have any questions or difficulties, and we can re-open it (or pop over to our slack: https://rewriteoss.slack.com/join/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA#/shared-invite/email).

Thanks again for logging this 👍

**Comment by jvillarb** [comment]
Good morning @aegershman, reviewing the proposed solution, it would also be very interesting if there was a recipe that allows you to change the groupId, artifactId and version of the parent, because now you can only update the version of the parent.

**Comment by jvillarb** [comment]
thank you very much for your excellent work
