### ISSUE TITLE
Maven parsing fails for managed dependency entries without version tag

### ISSUE THREAD

**Issue by danielnorberg** [openrewrite/rewrite#1084]
Parsing a (surprisingly valid) pom like the below (with assertions enabled) causes the parser to throw an exception.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>2.11.1</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <!-- no version! -->
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

```
java.lang.AssertionError
	at org.openrewrite.maven.internal.RawMavenResolver.processDependencyManagement(RawMavenResolver.java:158)
	at org.openrewrite.maven.internal.RawMavenResolver.processTask(RawMavenResolver.java:131)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:114)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:99)
	at org.openrewrite.maven.internal.RawMavenResolver.resolve(RawMavenResolver.java:77)
	at org.openrewrite.maven.MavenParser.parseInputs(MavenParser.java:90)
	at org.openrewrite.Parser.parse(Parser.java:39)
```

**Comment by jkschneider** [comment]
Hi @danielnorberg. Thanks for the report and all the explanation. I've removed the assert and a couple later checks as well that assumed that there would be a version. In addition, wrote a cleanup recipe for Maven that does what I suppose you want to do as well, which is to remove these `dependencyManagement` dependencies which have no versions.

It is available to run as `org.openrewrite.maven.cleanup.DependencyManagementDependencyRequiresVersion`.

Thanks again!

**Comment by jkschneider** [comment]
@danielnorberg I ran this recipe on [app.moderne.io](https://app.moderne.io) once it had a chance to recreate all the ASTs just to see what would happen. I think you'll appreciate the irony of this result (look closely at the file name):

![image](https://user-images.githubusercontent.com/1697736/136500905-ad76d5d8-98f8-49ea-b842-298b198ac127.png)
