### ISSUE TITLE
It should not be mandatory to set version in dependencyManagement

### ISSUE THREAD

**Issue by jvillarb** [openrewrite/rewrite#1085]
Good afternoon,

When processing the dependencyManagement, I believe that you do not have to check that the dependencies have a defined version for the following reason:

https://github.com/openrewrite/rewrite/blob/23db64458562e4012aadc9654b52133c1c16af53/rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawMavenResolver.java#L153

If the purpose of the parent POM in defining a dependencyManagement is to exclude a transitive dependency and make sure that any child referencing the dependency does not load the excluded transitive dependencies, I do not see the need to specify the version, it should be the child who defines the version it needs. If the version is defined it can lead to unexpected consequences. If an older version is specified, you force the child to use the older version, and it may fail.

For example, in my case, I have defined in the parent POM the following dependencyManagement to exclude from the spring-ws library the spring-core library.

```
  <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-ws</artifactId>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
        </dependencies>
  </dependencyManagement>
```

**Comment by jkschneider** [comment]
I think this has been fixed now @jvillarb. Please let me know if we've missed something!
