### ISSUE TITLE
Recipe to add a dependency without version

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1091]
Good morning, 

Good morning, I would like to ask a question. Is there any way to add a dependency without adding the version, since the version is inherited from the parent. Now the AddDependency recipe the version field is mandatory, I think it would be very useful to be able to include dependencies without their version.

Thank you very much.

**Comment by tkvangorder** [comment]
Hi @josemariavillar ,

The maven project is initially parsed with the `santander-spring-boot-starter-parent:17.1.RELEASE` and therefore the maven model (and associated poms) are all based on the original parent. 

When the parent is changed, we do not (currently) reparse/regenerate the model, so the decisions being made when the `AddDependency` executes is based on the original model. 

We are currently looking at improving the speed of Maven resolution and are hoping to fix this soon.

**Comment by josemariavillar** [comment]
Thank you very much,

I am waiting for a possible solution to fix this soon.

**Comment by rdifrango** [comment]
related it would be nice if we could use `latest.version` so that the most recent is pulled.
