### ISSUE TITLE
HiddenField renames constructor and setter parameter names

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#1129]
![image](https://user-images.githubusercontent.com/8549033/138172493-05bfbb11-5c67-4437-89a8-07db74172aef.png)

No need to rename from `date` to `date1`

**Comment by tkvangorder** [comment]
HiddenField recipe/visitor are driven by a "HiddenFileStyle" and the defaults are to ignore constructors and setters. It is possible that a checkstyle explicitly changes these defaults:

https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java#L203-L216
