### ISSUE TITLE
Use consistent matcher pattern semantics for UsesType, UsesMethod, etc.

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#1147]
In order to ensure consistent syntax for identifying a `type` via `FindTypes`, `UsesMethod`, etc., extract the common matcher logic for re-use across these common tools.

E.g., `MethodMatcher` will match on methods within subpackages off `org.openrewrite` using `..*`, as in `org.openrewrite..* *(..)`. Whereas `FindTypes` is less forgiving about matching sub-packages. It will not match on subpackages when provided with `org.openrewrite..*` -- it will only accept immediate first-level packages, as in `org.openrewrite.*`.

**Comment by sambsnyd** [comment]
This would be a good thing to do, but I think we're likely to keep kicking this down the road for a while longer.
