### ISSUE TITLE
UpgradeDependencyVersion should detect if a managed dependency's version is using a property

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#1157]
Add Option to update the bom instead if the bom is in the same project

**Comment by pway99** [comment]
notice spring-pet-clinic is downgraded
![image](https://user-images.githubusercontent.com/22326988/139510017-0d1e5966-6786-4902-9a66-c8ea157378d1.png)

**Comment by tkvangorder** [comment]
UpgradeDependencyVersion should detect if a managed dependency's version is expressed as a property and should either update or add a property to a pom that will override the property value.
