### ISSUE TITLE
Anchors disappear in YamlParser for Scalar keys, Sequences, and Mapping nodes.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#1161]
`Anchor` and `Alias` have been added to the Yaml model, but only work on Scalar values.
Anchors on Scalar keys, Sequences, and Mapping nodes will disappear.
Aliases for any of the mentioned Anchors will NPE.

Notes:
- Based on the Yaml spec, each Yaml#Node includes an Anchor.
- Scalar, Sequences, Mapping, and Alias are Yaml#Nodes.
- Our equivalent to Yaml#Node is Yaml#Block, since Scalar, Sequence, Mapping, and Alias implement Block.
- Yaml `MappingNode` is a key: `Node` =>  value: `Node`, but our `Mapping#Entry` is a key: `Yaml#Scalar` => value: `Yaml#Block`.

**Comment by nmck257** [comment]
@traceyyoshima - do you recall if there were any technical blockers with this item? Or has there just not been sufficient reason/demand to implement it?

Looks like the NPE on the Alias case occurs during the print operation, which causes the whole file to get blanked out, not just the unsupported syntax. Extra fun.

**Comment by nmck257** [comment]
On a related note, would be interested to get opinions on supporting Merge Key syntax:
https://yaml.org/type/merge.html
It's still a draft spec, but some yaml parsers do support it regardless, so it's feasible that OR would encounter it.

Currently, OpenRewrite throws something like this on each occurrence during the parse:
```
[WARNING] java.nio.file.InvalidPathException: Illegal char <<> at index 28: my.mapping.<<
```

**Comment by traceyyoshima** [comment]
> do you recall if there were any technical blockers with this item? Or has there just not been sufficient reason/demand to implement it?

Hi @nmck257, there weren't any blockers aside from priority. I added tests for the cases mentioned in the issue, but as you mentioned, we didn't know if the case would occur in code.

I don't have time to add it immediately, but I'd be happy to help/review if you add support in the grammar. @pway99 may be available to add more resilience to the YamlParser to prevent blank files and implement the fixes. Otherwise, I'll get to the issues as soon as I can.

I think adding support for `merge` is reasonable. From a glance, it looks fairly simple to add support for in the `yaml` grammar. I opened an issue for the request [here](https://github.com/openrewrite/rewrite/issues/2133).

Are the parsing issues heavily impacting your work?

**Comment by nmck257** [comment]
Not a heavy impact at this time, no. I only recently encountered someone using these yaml features in the wild.

And for the `merge` syntax, I haven't isolated/verified, but since it's logging an error per occurrence (within the same file), I expect the parser is recovering each time and parsing the rest of the doc, which is good -- the syntax would probably get dropped when printed back out, though.

I'll definitely appreciate your review if I get to this first -- though like you said, it's a prioritization thing.

**Comment by pway99** [comment]
Hi @nmck257 and @traceyyoshima, I should be able to start focusing on the YamlParser early next week.

**Comment by pway99** [comment]
@traceyyoshima and @nmck257, just created a PR #2140 for this one would you mind having a look?

**Comment by pway99** [comment]
Re-Opening since keys having anchors and aliases are still not functional
