### ISSUE TITLE
`AutoFormat` supports the options the tabs/indentation/spaces that IDEs support.

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#117]
It should support all the options available in IDE code style:

![image](https://user-images.githubusercontent.com/1697736/101961038-b830dd80-3bbd-11eb-9016-383cb3f7b2fa.png)

- [x] #116 
- [x] #113
- [x] #149
- [ ] #163

**Comment by sambsnyd** [comment]
@gadams00 is already in-progress on this, so assigning it to him
