### ISSUE TITLE
DeleteKey removed workflow_dispatch in `.github/workflows/ci.yml`

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#1175]
### Problem
> Describe the issue you are experiencing.

Configured `DeleteKey` with `$.jobs.build.strategy.fail-fast`, and it appears to have removed `workflow_dispatch`. But it did remove `fail-fast` as expected.

### Expected behavior
> Describe what you expected to see.

Not having `workflow_dispatch` removed. Also note how it shifted `{}` next to `main`, which is interesting.

### Example diff
```diff
       - "*"
   pull_request:
     branches:
-      - main
-  workflow_dispatch: {}
+      - main {}
   schedule:
     - cron: "0 18 * * *"
 
 jobs:
   build:
     strategy:
-      fail-fast: false
       matrix:
         java: ["11"]
         os: ["ubuntu-latest"]
```

#### Recipes in example diff:
- org.openrewrite.yaml.DeleteKey

### References:
- Recipe ID: `yG2Zw`
- Recipe Name: "Delete key"
- Repository: openrewrite/rewrite-jhipster
- Created at Thu Nov 04 2021 01:34:46 GMT-0500 (Central Daylight Time)

**Comment by aegershman** [comment]
Note, this appears to be because `removeUnused()` is called over the whole file. Which means "unused" keys, such as `workflow_dispatch: {}` will be removed, even though they are not part of the original scope of what was intended to be removed.

**Comment by traceyyoshima** [comment]
Update:
The `{}` shifts because the yaml flow style is not supported [yet](https://github.com/openrewrite/rewrite/issues/423).

The mapping is removed by `removeUnused()`. The `removeUnused` is not constrained to a parent yaml, and applies to each entry.
