### ISSUE TITLE
Warnings: unable to download pom artifact on multi modules maven

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1179]
In a multi module maven, modules can be resolved again each other without being installed in local maven repository.
Seen using main branches of rewrite and rewrite-maven-plugin: I now have warnings:
```
[INFO] Validating active recipes...
[WARNING] Unable to download my.project:my-project-services:1.59.1-SNAPSHOT. Including POM is at RawMaven{from=file:///home/amino/git/enedis-six/six-apps/my-project/my-project-api/pom.xml / pom=RawPom(groupId=my.project, artifactId=my-project-api, version=1.59.1-SNAPSHOT, snapshotVersion=null)}
[WARNING] Unable to download my.project:my-project-api:1.59.1-SNAPSHOT. Including POM is at RawMaven{from=file:///home/amino/git/enedis-six/six-apps/my-project/my-project-api/pom.xml / pom=RawPom(groupId=my.project, artifactId=my-project-api, version=1.59.1-SNAPSHOT, snapshotVersion=null)}
[INFO] Parsing Java main files...
```

**Comment by tkvangorder** [comment]
Hi @murdos 

We are currently in the process of refactoring the Maven resolution and this issue will be on our radar as we rework things.

**Comment by tkvangorder** [comment]
@murdos This should be working correctly with the new Maven resolution. I am going to close this issue, if you find this is still happening we can re-open.
