### ISSUE TITLE
Maven recipe was observed inserting a version with node-style selector

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#1199]
Found while running a JUnit 4 to 5 upgrade on legacy source code:

The maven pom was updated with versions like Mockito `3.14.x`

The resulting dependency ended up as follows: 

```
     <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-junit-jupiter</artifactId>
        <version>3.12.x</version>
        <scope>test</scope>
     </dependency>
```

Rewrite should be replacing the `x` with the latest stable patch version.

**Comment by pway99** [comment]
@tkvangorder I am not able to reproduce this issue.
