### ISSUE TITLE
NoValueOfOnStringType removes necessary call to String#valueOf in string concatenation

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1200]
Discovered on [OpenCyclos](https://github.com/murdos/OpenCyclos/blob/master/src/main/java/nl/strohalm/cyclos/entities/settings/LocalSettings.java#L395)

![image](https://user-images.githubusercontent.com/155828/141250818-910aea3d-40c9-4254-aa11-3df6e576c075.png)

**Comment by aegershman** [comment]
@murdos I've put a test reproducing it in https://github.com/openrewrite/rewrite/commit/80198bb979b82fb964625bbcc0367660b27f5bf0 -- we'll fix this up. Thanks for going to the trouble of reporting it, good catch 👍

**Comment by aegershman** [comment]
@murdos this should be fixed up in latest snapshot, I've tested this against `OpenCyclos`; this should be fixed up. @-me or feel free to open up other issues if something else does not look right. But in any case, this should be good to go. 

Thanks again for logging this, I/we genuinely appreciate it 👍
