### ISSUE TITLE
Add/Change import and annotations

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1202]
Good afternoon

I am trying to create a recipe to migrate from SpringFox to OpenApi 3, and I have some doubts, is there any recipe to add or change "import"? and is there any recipe to add or change annotations at class or method level?

Thank you very much for everything

**Comment by tkvangorder** [comment]
hi @josemariavillar 

A SpringFox -> OpenApi 3 recipe sounds very interesting, if you would like some help sorting out some of these details, we can schedule some time to do some pair programming. 

As for your questions: 

There is an `AddImport` recipe that can handle both normal and static imports. In fact, this recipe/visitor is also aware of import styles and will insert the import in the correct location and also handle things like folding imports into a *.

The inverse of this is the `RemoveImport` which is style-aware and also will manage things like unfolding imports from a "*". 

The good news with these two visitors is that there are helper methods on the JavaVisitor to make this relatively painless: 

![image](https://user-images.githubusercontent.com/1878529/141335445-81f243fd-b8be-42dd-b56a-c83f5b26cb1e.png)

These methods will only add an import if the type is actually in use within the compilation unit.

As for adding/changing an annotation, there is no dedicated recipe for this however, this can be easily accomplished using the `JavaTemplate`

The template allows you to write a small snippet of code (as text) which is then compiled into an AST. It then uses a coordinate system to either insert or replace the newly generated elements into your existing AST.

There are good examples of how this can be accomplished in the JavaTemplateTest:

![image](https://user-images.githubusercontent.com/1878529/141336590-4ca1b872-c726-4fa0-8be7-d7cc45fa8df4.png)

The first time you use JavaTemplate, it can be a bit overwhelming, we have some guides in our documentation to help you get started: https://docs.openrewrite.org/tutorials/modifying-methods-with-javatemplate

This will cover things like the coordinate system and introducing new types into your template.

**Comment by josemariavillar** [comment]
thank you very much for everything
