### ISSUE TITLE
XmlParsingException on xml document with embedded DTD

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1203]
Discovered on [OpenCyclos](https://github.com/mateli/OpenCyclos/blob/master/src/main/resources/nl/strohalm/cyclos/setup/changelog.xml)

>org.openrewrite.xml.XmlParsingException: Syntax error in /tmp/OpenCyclos/src/main/resources/nl/strohalm/cyclos/setup/changelog.xml at line 3:17 extraneous input '\n\t]>\n' expecting '<'.
    at org.openrewrite.xml.XmlParser$ForwardingErrorListener.syntaxError (XmlParser.java:99)

Reproduced with this simple sample:
```xml
<?xml version="1.0"?>
<!DOCTYPE p [
 <!ELEMENT p ANY>
]>
<p>Hello world!</p>
```

**Comment by sambsnyd** [comment]
Thanks for reporting @murdos ! We will look into it
