### ISSUE TITLE
UnnecessaryThrows removes throws from parent class and breaks subclasses overriding methods

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1207]
Related to #897 and discovered on OpenCyclos ([parent class](https://github.com/mateli/OpenCyclos/blob/master/src/main/java/nl/strohalm/cyclos/controls/BaseFormAction.java#L119) / [subclass](https://github.com/mateli/OpenCyclos/blob/master/src/main/java/nl/strohalm/cyclos/controls/invoices/AcceptInvoiceAction.java#L157)).

Test to demonstrate the issue:
```kotlin
    @Test
    fun parentBreaksSubclass(jp: JavaParser) = assertUnchanged(
        before = """
            public class ParentFoo {
                public void bar() throws Exception { // this throws should not be removed
                }
            }
            
            class Foo extends ParentFoo {
                @Override
                public void bar() throws Exception {
                    // no-op
                }
            }
        """
    )
```

Since checking all sub classes might not be easy, and won't be enough if the codebase is a library used by other projects that extends/overrides the class, I wonder what would be the best solution.
Either restrict the recipe to unchecked exceptions as [suggested by Jon](https://github.com/openrewrite/rewrite/issues/897#issuecomment-899989196).
Or at least exclude the recipe from [cleanup recipes](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/resources/META-INF/rewrite/static-analysis-cleanup.yml).

**Comment by tkvangorder** [comment]
@murdos good catch.

For checked exceptions, I think the only "safe" places where we can remove them are : 

- The class or method are final
- The method is private

Otherwise, the rules could only be applied to unchecked exceptions.

**Comment by tkvangorder** [comment]
Reworked the rules for the UnnecessaryThrows recipe based on [RSPEC-1130 documentation](https://jira.sonarsource.com/browse/RSPEC-1130).

This recipe will only remove unused, checked exception if:

The declaring class or method declaration is final
The method declaration is static or private
If the method is an override and a thrown exception is not defined in the overridden method's declaration
If the method is public or protected and the exception is not documented via a JavaDoc as a @throws tag
