### ISSUE TITLE
UnnecessaryExplicitTypeArguments can lead to uncompilable code due to introduced ambiguity

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1211]
Sample code:
```java
import java.util.Collection;

public class Test {

    <G> G foo() {
        return null;
    }

    <E> E fetch(E entity) {
        return null;
    }

    <E> Collection<E> fetch(Collection<E> entity) {
        return null;
    }

    void test() {
        Integer bar = fetch(this.<Integer>foo());
    }

}
```

Recipe currently changes `Integer bar = fetch(this.<Integer>foo());` to `Integer bar = fetch(this.foo());`.
Codes doesn't compile anymore since there's an ambiguity with the different `fetch(...)` methods.

Discovered on [OpenCyclos](https://github.com/mateli/OpenCyclos/blob/master/src/main/java/nl/strohalm/cyclos/services/permissions/PermissionServiceImpl.java#L318)

**Comment by sambsnyd** [comment]
Thanks for reporting, @murdos ! Appreciate the great test case. 
For now I've disabled removing the type parameter if there are any other methods on the declaring class with the same name. So with my fix some unnecessary type parameters could be preserved, but that's better than introducing ambiguity.

**Comment by murdos** [comment]
Thanks! FYI I tested on code where I found the issue, and I confirm the issue is fixed :-)

**Comment by timtebeek** [comment]
Figured I'd chime in here with another ambiguity issue I found similar to this one; Using the same example but adding:
```diff
    void test() {
        Integer bar = fetch(this.<Integer>foo());
+       var baz = this.<Integer>foo();
+       fetch(baz);
    }
```

This is then rewritten to
```diff
-       var baz = this.<Integer>foo();
+       var baz = this.foo();
```

Which again leads to the ambiguity previously recorded here. Didn't think it worth opening up a new issue, but might be worth reopening this issue, or adding a quick fix.
