### ISSUE TITLE
kotlin standard library ships as transitive dependency of all modules

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#122]
We apply the kotlin gradle plugin for our unit tests. We do not use, or plan to use, kotlin or its standard library in the main source sets so this dependency is not necessary. 

I _believe_ that in the past the kotlin plugin didn't automatically add its standard library to the classpath, but that behavior changed and now it does. We should exclude this "dependency" that we don't actually use.

**Comment by vlsi** [comment]
@sambsnyd , you probably want adding `kotlin.stdlib.default.dependency=false` Gradle property rather than dealing with `exclude(..)`

See https://kotlinlang.org/docs/gradle-configure-project.html#dependency-on-the-standard-library
