### ISSUE TITLE
Issue discovered with `/github/workspace/build.gradle`

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#1236]
### Problem

![image](https://user-images.githubusercontent.com/1697736/142478583-9f36b760-7835-4c3b-b863-024b7b2d0b06.png)

#### Recipes in example diff:
- org.openrewrite.java.format.EmptyNewlineAtEndOfFile

### References:
- Recipe ID: `BPCOR`
- Recipe Name: "Common static analysis issues"
- Repository: Netflix/servo
- Created at Thu Nov 18 2021 10:53:10 GMT-0800 (Pacific Standard Time)

**Comment by sambsnyd** [comment]
After fixing #1258, #1260, and #1261 I've validated that this build.gradle now parses successfully
