### ISSUE TITLE
UpgradeDependencyVersion recipe on locked dependency using maven version ranges fail

### ISSUE THREAD

**Issue by maddenj-ie** [openrewrite/rewrite#1248]
# Observed Behaviour
Given the folowing pom where the junit dependency is locked to use a specific version:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mycompany.app</groupId>
    <artifactId>my-app</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>my-app</name>
    <url>http://www.example.com</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>[4.11]</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>4.16.0</version>
                <configuration>
                    <activeRecipes>
                        <recipe>com.myapp.upgradeLockedVersion</recipe>
                    </activeRecipes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

Running the following rewrite recipe

```yml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.myapp.upgradeLockedVersion
recipeList:
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: junit
      artifactId: junit
      newVersion: 4.13
      trustParent: false
```

Results in the recipe not being executed and the following warnings issued.

```bash
[WARNING] Syntax error at line 1:5 missing ',' at ']'
[WARNING] Unable to download junit:junit:5.0-SNAPSHOT. Including POM is at RawMaven{from=file:///home/maddenj-ie/projects/prototypes/openrewrite/my-app/pom.xml / pom=RawPom(groupId=com.mycompany.app, artifactId=my-app, version=1.0-SNAPSHOT, snapshotVersion=null)}

```
# Expected Behavior
Rewrite tolerates version ranges specified in poms

# Questions
- I think rewrite has its own version range support, how does this work when the pom has version ranges specified.
- Would it be possible to allow the recipe so that it ignores interpretation of the version ranges and the pom updated directly with the newVersion string?

**Comment by traceyyoshima** [comment]
hi @maddenj-ie, thanks for reporting the issue - taking a look!

**Comment by maddenj-ie** [comment]
Hi @traceyyoshima Thanks for the quick response.

Is it possible to use the brackets in the recipe configuration and have the pom updated with them also?

I'm sorry I wasn't able to test this myself, I'd no luck building the main branch.  Thanks.

**Comment by traceyyoshima** [comment]
Hi @maddenj-ie, my pleasure, thanks again for reporting the issue.

No, adding version range specifications isn't supported at the moment. It's probably best if @tkvangorder chimes in.

In the meantime, I think a custom recipe should be simple to construct, since it is just a search and replace.
Happy to chat in our [slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) channel too.
