### ISSUE TITLE
RemoveUnusedimports is incorrectly removing an import for a javadoc @link

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1255]
Discovered on [OpenCyclos](https://github.com/murdos/OpenCyclos/tree/rewrite-playground):
![image](https://user-images.githubusercontent.com/155828/144197619-e41a110b-206e-45bc-a350-baa6a0707fc5.png)

See related discussion: https://github.com/openrewrite/rewrite/issues/1066#issuecomment-983051195
This one seems to be legal javadoc.

**Comment by traceyyoshima** [comment]
Hi @murdos, thanks for opening an issue!
Ya, that looks unexpected, taking a look!

**Comment by traceyyoshima** [comment]
@murdos I looked into the issue and it seems related to the project.

A local test of `RemoveUnusedImports` works with:
```java
    @Test
    fun test() = assertUnchanged(
        before = """
            import java.util.List;
            import org.apache.lucene.document.Document; // added dependency for type attribution
            
            /**
             * Text {@link List}s more text {@link Document}s
             * 
             * @author name
             */
            class A {}
        """
    )
```

I wasn't able to run the plugin using J8 and produced the issue with J11:
- cloned repo and checked out branch
- adjusted heap size
- used AdoptOpenJDK 11.0.10.hs
- ran `mvn rewrite:run`
- noticed that most of the unexpected removed imports were related to `javax` packages that were removed from J11.

Afterward, I added the necessary dependencies,  reran the plugin and it worked fine.

Question:
Did you run with J11?

**Comment by traceyyoshima** [comment]
@murdos Quick update: I've tracked down the cause of the missing type info, and am looking for a fix.
