### ISSUE TITLE
xml parser cant handle byte order mark

### ISSUE THREAD

**Issue by delanym** [openrewrite/rewrite#1268]
The org.openrewrite.xml.XmlParsingException can't handle UTF8 files with a BOM

**Comment by sambsnyd** [comment]
Thanks for reporting, we'll take a look

**Comment by traceyyoshima** [comment]
Hi @delanym,
I'll gladly look into the parsing issue - would you please share what the XML looks likes?
Thanks in advance!

**Comment by delanym** [comment]
[AndroidManifest.zip](https://github.com/openrewrite/rewrite/files/7682565/AndroidManifest.zip)

**Comment by traceyyoshima** [comment]
Thanks for sample XML @delanym!
I took a look at the examples and the parsing issues are fixed on the main branch.
We're working really hard on getting a release out of 7.17.
Thanks again for the report
