### ISSUE TITLE
Unable to download artifacts when a repository is defined as local file path.

### ISSUE THREAD

**Issue by delanym** [openrewrite/rewrite#1276]
Split off openrewrite/rewrite-maven-plugin#133 

I get warnings for not being able to download artifacts that are **both** in the ~/.m2/repository and in a local Maven repository

```xml
<repositories>
  <repository>
    <id>thirdparty</id>
    <name>Third-party Artefacts</name>
    <url>file:///tmp/provided</url>
  </repository>
</repositories>
```

**Comment by rdifrango** [comment]
@aegershman i can't post the Maven settings file here as its company propertiary but the short answer is we aren't allowed to download from Maven central directly so all calls must go through our internal systems that do connect to it.

**Comment by rdifrango** [comment]
ok, @aegershman I can open a different ticket but here's the failure:

```
cause: org.rocksdb.RocksDBException: While open a file for random read: /Users/my-user-name/.rewrite-cache/000207.ldb: No such file or directory
```

**Comment by rdifrango** [comment]
cross posting this:

Just as an FYI, I removed that directory and re-ran and it looks like whatever its doing for auth isn't correct either:

```
cause: org.openrewrite.maven.internal.MavenDownloadingException: HTTP response code: 401
```

In my case, the username/passwords are in a server block like:

```
<servers>
        <server>
            <username></username>
            <password></password>
            <id>central</id>
        </server>
        <server>
            <username></username>
            <password></password>
            <id>snapshots</id>
        </server>
    </servers>
```

I'll also add that in some environments one needs to go through a corporate proxy so if `proxies` is configured in the settings file it should also be taken into account.

**Comment by aegershman** [comment]
@delanym to follow-up on this, the use-case of handling repositories defined on the filesystem is not prioritized to make it into the next release right now. I'm under the impression these problems will not prevent rewrite from executing where it can, even if there are repositories and dependencies it cannot resolve, despite the warning messages. I'd like to leave this issue open, still. I just wanted to let you know the current status of prioritization on it, though.

**Comment by rdifrango** [comment]
@tkvangorder - I'll test it out tomorrow just to verify it works as advertised.

**Comment by delanym** [comment]
@tkvangorder I don't know if you saw #1399
