### ISSUE TITLE
Documentation Update for org.openrewrite.maven.ChangePropertyValue

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite#1285]
I was attempting to use `org.openrewrite.maven.ChangePropertyValue` and notice that per the name it only updates the property if it exists.

It would be nice if there was an option that allowed one to allow it to insert the property if it didn't exist previously.

**Comment by rdifrango** [comment]
ok, after looking at the code, this seems to be a documentation issue as the is the flag `addIfMissing` that when set to true will add it but I didn't see it documented [here](https://docs.openrewrite.org/reference/recipes/maven/changepropertyvalue).

```
addIfMissing: true
```

**Comment by pway99** [comment]
Hello @rdifrango,  
It turns out that `addIfMissing` is a new feature that will be available in the `7.17.0` release.
Going to close this one since the docs will be updated once `7.17.0` is released.
Thanks for your help :)
