### ISSUE TITLE
Classgraph missing type information for methods on abstract classes that return or accept array types

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#1289]
In some circumstances the `elementClassInfo` field we use to determine the type of the array is `null`. 
It seems like this happens when the array info is a parameter or return type of a method on an abstract class. We haven't proved that's the only circumstance, but it's a commonality in all the instances we looked at.

![image](https://user-images.githubusercontent.com/8549033/146627445-0efede82-0027-493c-bcd7-474f5942655b.png)

**Comment by traceyyoshima** [comment]
Additional note:

The elementClassInfo in arrayClassInfo from `methodInfo.getTypeDescriptor().getResultType()` will also be null on Object[], and primitive array types. In some cases the class is not abstract, so it may be related to the return type too.

**Comment by traceyyoshima** [comment]
Fixed on latest: I checked locally with `JavaTypeMappingTest` with an Object[] and int[], but instances returned a `JavaType.Array` with the correct element info.
