### ISSUE TITLE
XmlParsingException: mismatched input '﻿' expecting '<'. with file endoded in UTF-8 with BOM

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1295]
> org.openrewrite.xml.XmlParsingException: Syntax error in logback-test.xml at line 1:0 mismatched input '﻿' expecting '<'.

Content of logback-test.xml is attached: [logback-test.xml.gz](https://github.com/openrewrite/rewrite/files/7775736/logback-test.xml.gz)

I suspect that this is because the xml file is encoded in UTF-8 with BOM:
> $file logback-test.xml
> logback-test.xml: XML 1.0 document, Unicode text, UTF-8 (with BOM) text

**Comment by traceyyoshima** [comment]
Hi @murdos, happy holidays! Thanks, for reporting the issue, we'll take a look!
