### ISSUE TITLE
org.openrewrite.java.cleanup.UnnecessaryThrows Exception in case of @Test annotated method

### ISSUE THREAD

**Issue by hetzijzo** [openrewrite/rewrite#1298]
In a test situation, I would accept a test method having a `throws Exception` in the method signature. 
When a method with a `throws IOException, ClientProtocolException` is called by the test method (annotated with @Test), I (like to) expect a `throws Exception` on the test method to be valid and not removed by the recipe.

In the following example, the `execute` method throws an SQLException and ClientProtocolException. The actual behavior is that the recipe just removes the exception declaration on the test method, making the test code not compilable anymore. 

In a normal (production code) situation it is valid to remove the general Exception, but for a @Test annotated method a (general) Exception in the method signature could be valid.

```
class MyTest {
  
  @Mock private CloseableHttpClient httpClient;

  @Test
  void shouldInvokeAuthWithNotFoundExcepton() throws Exception {
     when(httpClient.execute(any(HttpPost.class))).thenThrow(createResponseException(HttpStatus.NOT_FOUND));
  }
}
```

```
package org.apache.http.impl.client;

@Contract(threading = ThreadingBehavior.SAFE)
public abstract class CloseableHttpClient implements HttpClient, Closeable {

  @Override
  public CloseableHttpResponse execute(
          final HttpUriRequest request) throws IOException, ClientProtocolException {
      return execute(request, (HttpContext) null);
  }
}
```

**Comment by sambsnyd** [comment]
@hetzijzo is a checked exception thrown by `shouldInvokeAuthWithNotFoundExcepton`?
If it throws only `RuntimeException` derived exceptions then the recipe is correct to remove `throws Exception`.

**Comment by hetzijzo** [comment]
Hi @sambsnyd thanks for reviewing my initial comment. I have further elaborated my original comment to match with the case and make it better understandable.

**Comment by sambsnyd** [comment]
Sorry for losing track of this issue @hetzijzo. Thanks to your clarification, I was able to create [a test](https://github.com/openrewrite/rewrite/commit/0b16e4e8214dd9432f111a4e949240b14138b989#diff-f7f013da14513a234c1e09693ecf967fadded97e2517f4b2a3b69cf72b5c197bR195) for this. This issue doesn't reproduce for me as of rewrite 7.18.2. Let me know if it's still occurring in your code base on the current version of rewrite.

Feel free to poke us [on slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) if we're slow to respond to an issue.
