### ISSUE TITLE
Build Issue Main branch

### ISSUE THREAD

**Issue by shresthaujjwal** [openrewrite/rewrite#1308]
I am trying to build this framework to make some contribution but i am running into lot of issue. 
`./gradlew build test`

is there any prerequisite to be able to build this application. Please advise

i get this error
```
> Task :rewrite-properties:compileJava
github/rewrite/rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java:20: error: package org.intellij.lang.annotations does not exist
import org.intellij.lang.annotations.Language;
                                    ^
github/rewrite/rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java:42: error: cannot find symbol
    public List<Properties.File> parse(@Language("properties") String... sources) {
                                        ^
  symbol:   class Language
  location: class PropertiesParser
2 errors
```

**Comment by sambsnyd** [comment]
Hi @shresthaujjwal. I haven't seen that build problem before.
The `@Language` annotation comes from org.jetbrains:annotations:13.0, which is published to [maven central](https://search.maven.org/artifact/org.jetbrains/annotations/13.0/jar). 

Are you perhaps on a corporate network that disallows access to public repositories such as Maven Central? If so, you'll need to get that artifact copied to a repository approved for use within your organization.

**Comment by shresthaujjwal** [comment]
Still trying to troubleshoot this issue. Could be my corporate proxy issue but odd part is everything else gets downloaded from except for this jar. Let me debug more. Got sidetracked this week due to other priorities

Thanks for looking into this

**Comment by tkvangorder** [comment]
@shresthaujjwal Any update on this?

**Comment by shresthaujjwal** [comment]
@tkvangorder i got busy with another priority and didn't get a chance to test/research this. Feel free to close this issue.

**Comment by tkvangorder** [comment]
👍
