### ISSUE TITLE
MavenParser should support profile activation mechanism <file>

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#132]
Within a maven settings.xml maven users may specify that a [profile](https://maven.apache.org/guides/introduction/introduction-to-profiles.html) is active when a particular file is present on the filesystem at build time. 

A settings.xml I received from design partner 1 has a profile that makes use of this feature, but in an unimportant profile not relevant to our scenarios. As such this is currently a low priority issue for us.

**Comment by okundzich** [comment]
What is the priority of this issue? Are they blocked without this?
