### ISSUE TITLE
Existence of schema.sql and data.sql in resources must be verifiable

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite#1324]
Some recipes in rewrite-spring for upgrades of Spring Boot 2.4 to 2.5 require detecting the existence of `schema.sql` and `data.sql` in `src/main/resources` and `src/test/resources`.

The parsing should be adjusted to allow checking for the existence of (at least) these resources.

Providing this information for **all files** under `src` would be helpful. 
E.g. in openrewrite/rewrite-spring/issues/131 the existence (and probably content) of flyway or liquibase config files could be helpful to verify the condition.

**Comment by pway99** [comment]
Hi @fabapp2, going to close this issue since it will be resolved by https://github.com/openrewrite/rewrite/issues/1315
