### ISSUE TITLE
Javac TypeMapping may produce variants due to parameterized super-types.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#1327]
Use the symbolType#supertype_field for consistent results to prevent unexpected variants.

**Comment by jkschneider** [comment]
Reverting -- cuts generic type variable propagation beyond the first level.

**Comment by traceyyoshima** [comment]
Closing in favor of https://github.com/openrewrite/rewrite/issues/1349.
The type mapping issue goes beyond just class supertypes and may occur on interfaces, method return types, method parameters, etc.
1349 contain more details on what's been discovered so far.
