### ISSUE TITLE
Issue discovered with `eureka-client/src/main/java/com/netflix/discovery/AbstractAzToRegionMapper.java`

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#1337]
### Problem

Private method is used but removed.

### Example diff

```diff
         }
         return null;
     }
-
-    private void populateDefaultAZToRegionMap() {
-        defaultRegionVsAzMap.put("us-east-1", "us-east-1a");
-        defaultRegionVsAzMap.put("us-east-1", "us-east-1c");
-        defaultRegionVsAzMap.put("us-east-1", "us-east-1d");
-        defaultRegionVsAzMap.put("us-east-1", "us-east-1e");
-
-        defaultRegionVsAzMap.put("us-west-1", "us-west-1a");
-        defaultRegionVsAzMap.put("us-west-1", "us-west-1c");
-
-        defaultRegionVsAzMap.put("us-west-2", "us-west-2a");
-        defaultRegionVsAzMap.put("us-west-2", "us-west-2b");
-        defaultRegionVsAzMap.put("us-west-2", "us-west-2c");
-
-        defaultRegionVsAzMap.put("eu-west-1", "eu-west-1a");
-        defaultRegionVsAzMap.put("eu-west-1", "eu-west-1b");
-        defaultRegionVsAzMap.put("eu-west-1", "eu-west-1c");
-    }
 }
```

#### Recipes in example diff:
- org.openrewrite.java.cleanup.RemoveUnusedPrivateMethods
- org.openrewrite.java.cleanup.UseDiamondOperator
- org.openrewrite.java.cleanup.UseLambdaForFunctionalInterface

### References:
- Recipe ID: `lF1C7`
- Recipe Name: "Common static analysis issues"
- Repository: Netflix/eureka/master
- Created at Thu Jan 20 2022 09:59:31 GMT-0800 (Pacific Standard Time)

**Comment by sambsnyd** [comment]
I've confirmed that this method is no longer removed on latest openrewrite. The only private method that gets removed in eureka-client really is unused.
