### ISSUE TITLE
RemoveImport doesn't account for referencedFields of same name, but different type

### ISSUE THREAD

**Issue by SofiaBrittoSchwartz** [openrewrite/rewrite#134]
In `RemoveImport`  `referencedFields`  are being stored as simpleNames, which caused an issue in the situation below when trying to remove import `org.junit.jupiter.api.Assertions.fail`.

```java
import org.junit.Test;

import static org.junit.jupiter.api.Assertions.fail;
import static org.assertj.core.api.Assertions.fail;

public class A {

    @Test
    public void test() {
        fail("This should fail"); // this is of type org.assertj.core.api.Assertions.fail
    }
}
```

Because `referencedFields` is only storing the simpleName, `RemoveImport` fails to remove `import static org.junit.jupiter.api.Assertions.fail;`.

**Comment by jkschneider** [comment]
I can see where we'd get into this situation depending on the order of visitors, but just to be clear having both of these static imports isn't compilable Java code.
