### ISSUE TITLE
Issue discovered with `src/main/java/org/openrewrite/java/security/spring/GenerateWebSecurityConfigurerAdapter.java`

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#1340]
### Problem

Incorrectly removed static import.

### Example diff

```diff
 import java.util.concurrent.atomic.AtomicReference;
 
 import static java.util.Collections.singletonList;
-import static org.openrewrite.Tree.randomId;
 
 @RequiredArgsConstructor
 public class GenerateWebSecurityConfigurerAdapter {
```

#### Recipes in example diff:
- org.openrewrite.java.RemoveUnusedImports

### References:
- Recipe ID: `iUzMW`
- Recipe Name: "Clean up my code"
- Repository: openrewrite/rewrite-java-security/main
- Created at Thu Jan 20 2022 11:33:35 GMT-0800 (Pacific Standard Time)

**Comment by sambsnyd** [comment]
This is fixed on latest openrewrite
