### ISSUE TITLE
Maven project - "war" pom packaging type prevents java sources from being read

### ISSUE THREAD

**Issue by kmccarp** [openrewrite/rewrite#1348]
From issue in `moderne-help`: https://github.com/moderneinc/moderne-help/issues/2

The project [murdos/OpenCyclos](https://github.com/murdos/OpenCyclos) fails to ingest.

The cause is in [rewrite-maven](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/tree/Maven.java#L98), we only allow pom packing types of `jar` and `bundle`.

**Comment by jkschneider** [comment]
cc / @murdos . A fix for this is incorporated into the in-progress Maven resolution work going on now.
