### ISSUE TITLE
Issue discovered with `src/test/java/org/openrewrite/cli/RewriteTemplateGeneratorTest.java`

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#1355]
### Problem

Removed an import while attempting to use static?

### Example diff

```diff
 import java.io.PrintStream;
 import java.util.concurrent.atomic.AtomicBoolean;
 
-import static org.assertj.core.api.Assertions.assertThat;
 import static org.assertj.core.api.Assertions.fail;
 
 public class RewriteTemplateGeneratorTest {
```

#### Recipes in example diff:
- org.openrewrite.java.UseStaticImport

### References:
- Recipe ID: `uaggd`
- Recipe Name: "Use static import"
- Repository: openrewrite/rewrite-template-generator/main
- Created at Thu Jan 27 2022 17:01:12 GMT-0800 (Pacific Standard Time)

**Comment by sambsnyd** [comment]
I just tried this with rewrite 7.18.2 and could not reproduce with either the gradle plugin or app.moderne.io. I can run `UseStaticImport` successfully and no imports are mangled.
