### ISSUE TITLE
Empty JavaVisitor corrupts AST that has incomplete assignment

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#1368]
Eats the `=` symbol. `@Scope(value=)` becomes `@Scope(value)`

See the test case below:

interface JavaParserTest : JavaRecipeTest{

        @Test
        fun incompleteAssignment(jp: JavaParser) {

            val source =
            """
                package org.test;
                
                import org.springframework.context.annotation.Bean;
                import org.springframework.context.annotation.Scope;
                
                @Scope(value=)
                public class TestScopeCompletion {
                    
                    @Bean
                    @Scope("onMethod")
                    public Object myBean() {
                        return null;
                    }
                }
            """.trimIndent()

            val cu = JavaParser.fromJavaVersion().build().parse(source).get(0);

            assertThat(cu.printAll()).isEqualTo(source);

            val newCu = JavaVisitor<ExecutionContext>().visit(cu, InMemoryExecutionContext()) as J.CompilationUnit;

            assertThat(newCu.printAll()).isEqualTo(source);

        }

}

**Comment by jkschneider** [comment]
Interesting, had no idea that was valid.

**Comment by jkschneider** [comment]
Shorter test repro:

```java
@Test
fun incompleteAssignment(jp: JavaParser) = assertParsePrintAndProcess(
    jp, CompilationUnit, """
       @Deprecated(since=)
       public class A {}
    """
)
```

**Comment by jkschneider** [comment]
@BoykoAlex This doesn't appear to be valid java code?

**Comment by BoykoAlex** [comment]
> Interesting, had no idea that was valid.

AST isn't valid but we'd like to parse it anyway. For example context assist use case: `@Scope(value=<*>)` where `<*>` is the cursor at which completion proposal is invoked.

**Comment by BoykoAlex** [comment]
Here is how we'd propose to fix it in `JavaVisitor`:
```
    public <T> JLeftPadded<T> visitLeftPadded(JLeftPadded<T> left, JLeftPadded.Location loc, P p) {
        if (left == null) {
            return null;
        }

        setCursor(new Cursor(getCursor(), left));

        Space before = visitSpace(left.getBefore(), loc.getBeforeLocation(), p);
        T t = left.getElement();

        if (t instanceof J) {
            //noinspection unchecked
            t = visitAndCast((J) left.getElement(), p);
        }

        setCursor(getCursor().getParent());

        return (before == left.getBefore() && t == left.getElement()) ? left : new JLeftPadded<>(before, t, left.getMarkers());
    }

```

If this looks okay @kdvolder and I will submit a PR Monday.

**Comment by sambsnyd** [comment]
Closing this since the PR was merged
