### ISSUE TITLE
We get JavaType unknown in integration tests

### ISSUE THREAD

**Issue by x650702** [openrewrite/rewrite#1393]
Hello!

I'm having a problem doing the built in rewrite tests. I explain it below:
To check if certain classes have been replaced I have tried some static methods like **FindTypes.find** or the **typesInUse** field of our **JavaSourceFile**.
The problem is that for our application's own types, the JavaType is **Unknow**. I understand that this is because we are only parsing the specific source that we are verifying.

The way we have to parse is as follows:
```
	public static Function<Predicate<JavaSourceFile>, Condition<String>> checkJava = predicate -> new Condition<>(
			sourceFile -> {

				List<J.CompilationUnit> javaFiles;
				try {
					JavaParser parser = JavaParser.fromJavaVersion().build();
					javaFiles = parser.parse(sourceFile);
				}
				catch (Exception e) {
					return false;
				}

				return predicate.test(javaFiles.iterator().next());
			}, "Check Java file");
```

How could we get the types of our project correctly?

Thanks in advance.

**Comment by pway99** [comment]
Hello @x650702,
Most likely the JavaParser does not have Type information for your source files.  
Try one of the following:
- setting the parser class path e.g. [RemoveUnusedPrivateMethodsTest](https://github.com/openrewrite/rewrite/blob/2e8c9f7077e49c72f6fbd9f16ec75af9f2ae0844/rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedPrivateMethodsTest.kt#L26)
- adding a type to the java parser itself e.g. [ChangeStaticFieldToMethod](https://github.com/openrewrite/rewrite/blob/2e8c9f7077e49c72f6fbd9f16ec75af9f2ae0844/rewrite-java/src/main/java/org/openrewrite/java/ChangeStaticFieldToMethod.java#L132)

Also, feel free to join our community forum on [Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA)
