### ISSUE TITLE
ChangePackage does not rename directory if only case changed: myCompany -> mycompany (windows) (rewrite-java)

### ISSUE THREAD

**Issue by gako** [openrewrite/rewrite#1403]
I was trying to use the ChangePackage recipe to fix some of my illegal packageNames from camcelcase to lowercase.
The code itself is changed correctly but the directory name is still the old one with camcelcase. 
I asume that this may be operating system dependent since I had similiar problems with renamed directory case under windows. But I'm not sure.

If I change not only the case of the package the new directory is created (e.g mycompany1)

e.g
---
type: specs.openrewrite.org/v1beta/recipe
name: changePackageCase
recipeList:  
  - org.openrewrite.java.ChangePackage:
      oldPackageName: com.myCompany.example
      newPackageName: com.mycompany.example

**Comment by traceyyoshima** [comment]
Hi @gako, thank you for reporting an issue, we'll take a look!

**Comment by pway99** [comment]
Hi @gako, I have created an issue for both the rewrite Gradle and Maven plugins for this issue.
https://github.com/openrewrite/rewrite-maven-plugin/issues/303
https://github.com/openrewrite/rewrite-gradle-plugin/issues/98

**Comment by gako** [comment]
Thanks, if this will work, it would simplify our upgrade problems greatly. 
At the moment I'm fiddling around with a mix of openrewrite rules and external bash scripts afterwards to get it working which is not very nice.

**Comment by pway99** [comment]
yeah sounds like a bit of a pain, I just pushed plugin fixes so this should be ready for the next release.
thanks again for reporting :)
