### ISSUE TITLE
Delombok OpenRewrite source code before publishing

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#1407]
The published source code contains Lombok annotations. These annotations make debugging really hard as the Java byte code and source code differ from each other.

Please consider to delombok the source code before publishing.

**Comment by pway99** [comment]
Hi @thomaszub, unfortunately, rewrite does not yet support lombok annotations.  You can follow issue #1297 for progress on lombok annotation support.

**Comment by thomaszub** [comment]
Hi @pway99, I was not completely clear in my above statement. I did not mean the Lombok support of rewrite as is already tracked by #1297, but the Lombok annotations in the rewrite source code itself.

Take for example
[https://github.com/openrewrite/rewrite/blob/5f79c2babfff71a2016b6f7bdeac12c62fc9f531/rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyArtifactId.java](ChangeDependencyArtifactId.javal)

This code can be hardly debugged because the published source code differs from the Java Byte code. This makes debugging really hard. Please consider to delombok the rewrite source code before publishing.

**Comment by fupgang** [comment]
To clarify, some example:
When debugging using the sources fetched from maven central, the line numbers do not match. Thus I was not able to place some breakpoints.
(This problem does not exist when I import the rewrite modules in my workspace instead, the IDE than handles lombok correctly.)

**Comment by pway99** [comment]
@thomaszub  and @fupgang thanks for the clarification.

**Comment by pway99** [comment]
Hi @thomaszub, After a bit more review, I have found an experience similar to what @fupgang mentioned where rewrite modules added to the workspace can be debugged with some slight differences between the source and decompiled class files.  Would you like to [join us on Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) where we can discuss further and even meet up if that would help?

**Comment by pway99** [comment]
Hello @thomaszub and @fupgang,  This issue can only be reproduced by mismatched dependency versions between the rewrite-maven-plugin, rewrite-*, and the test recipe.

Thanks again for your help, and please don't hesitate to ping us on Slack if you have any further questions.
