### ISSUE TITLE
Refactor and fix dependency management in rewrite

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#1423]
Hi,

currently I have some issues to build this project locally. After checking the build files, I have the following suggestions to the overall dependency management/handling in rewrite:

1. Update Gradle wrapper to 7.4
2. Pull out commonly used dependencies like `io.micrometer:micrometer-core` into a version catalog (https://docs.gradle.org/current/userguide/platforms.html) 
3. Remove `latest.release` in the dependency versions and pin the dependency to a specific version or at least a patch version range like `1.8.+`

The pinning of the dependency versions is imho important as this makes the builds reproducible. Currently an old tag of the project could not be easily reproduced as the dependencies are potentially updated. This can even break old builds.

Btw, I can work at PRs for this if needed.

Best regards
Thomas

**Comment by tkvangorder** [comment]
Hi @thomaszub 

Thank you for the suggestions. We totally understand the tradeoff we are making by using the "latest" dependencies. 

The thought here is that we want to advance our dependencies on the main branch as new, stable versions of any third-party dependencies are released. If we create any release branches, we will lock the dependencies on those branches.

We would accept a PR to move the Gradle wrapper to 7.4. 

Finally, if you are running into difficulty building locally, we would love to help you triage and improve the onboarding experience. Feel free to reach out on our [slack org](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA)

**Comment by thomaszub** [comment]
Hi @tkvangorder,

thanks for the explanation. Would you also accept a PR with version catalogs centralizing the dependency versions in the parent Gradle file?
