### ISSUE TITLE
Parsers should record original character encoding on ASTs

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#1434]
Currently we always print ASTs out UTF-8 encoded. This can be a problem when writing the results of recipe execution back to a non-UTF-8 file. If parsers recorded the original encoding on the AST, then at printing time we could write back to the file in the same encoding it came in.

**Comment by traceyyoshima** [comment]
Fixed by: https://github.com/openrewrite/rewrite/commit/255967d1624da16bdf4606ae9af6ecb42051fd15
