### ISSUE TITLE
Update JsonPathMatcherTests to assert that returned values are also accurate

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#1437]
Update `JsonPathMatcherTest` that only assert the number of results by adding assertions for the content as well.
e.g.
https://github.com/openrewrite/rewrite/blob/c7db34b243d0fdc561a272b5e88d183e4ce92f64/rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/JsonPathMatcherTest.kt#L107

**Comment by traceyyoshima** [comment]
I'm closing the issue to update the test because all of the tests would be disabled.
There is quite a bit of work necessary to fix #1419
