### ISSUE TITLE
InsertDependencyComparator: Comparison method violates its general contract

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#1442]
Hi,

in some circumstances the call `ideallySortedDependencies.sort(dependencyComparator);` in the class `org.openrewrite.maven.internal.InsertDependencyComparator` can lead to a `java.lang.IllegalArgumentException: Comparison method violates its general contract!`

This issues occurs if the Maven dependencies-Element contains a bigger number of dependencies and at least two comments. The `sort` chooses the `TimSort` algorithm leading to the exception as the two comments are not correctly handled by the `dependencyComparator`.

I reproduced the issue in the project https://github.com/thomaszub/rewrite-add-dep-issue-example

Kind regards
Thomas

**Comment by pway99** [comment]
Thanks for the example project Thomas, We'll have a look.
