### ISSUE TITLE
org.openrewrite.maven.AddDependency: Inaccurate check of existing dependencies

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#1443]
Hi,

the `AddDependency`-Recipe checks if the dependency is already existing before adding it to the pom. Imho it should not take transitive dependencies into account.

Take as an example `jackson-databind` as a direct project dependency. This pulls in `jackson-core` as a transitive dependency, effectively disallowing to add `jackson-core` with the `AddDependency` recipe. If the project uses `jackson-core` directly it should be added as a direct dependency. 

For an example, see the project https://github.com/thomaszub/rewrite-add-dep-issue-example (remove the second AddDependency as this triggers an error).

Kind regards
Thomas

**Comment by jkschneider** [comment]
Makes sense. Perhaps we make this another recipe option?

**Comment by thomaszub** [comment]
An optional flag for excluding transitive dependencies sounds good.

**Comment by jkschneider** [comment]
I think you're right that this is the expected behavior in most cases. Can defer a flag until later if such a case arises.
