### ISSUE TITLE
After adding a managed-dependenncy remove any affected dependency versions

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#1445]
`AddManagedDependency` added via #1443 adds managed dependencies to a pom.
Once the managed dependency has been added `version` tags should be removed from any concrete dependencies.

before:
```xml
<project>
    <groupId>com.mycompany.app</groupId>
    <artifactId>my-app</artifactId>
    <version>1</version>
    <dependencies>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.17.2</version>
        </dependency>
    </dependencies>
</project>
```
after:
```xml
<project>
    <groupId>com.mycompany.app</groupId>
    <artifactId>my-app</artifactId>
    <version>1</version>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>2.17.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
        </dependency>
    </dependencies>
</project>
```

**Comment by traceyyoshima** [comment]
@pway99 What do you think about limiting removing tags to matching versions to cover breaking API changes?

**Comment by pway99** [comment]
@traceyyoshima, I think that is a good strategy.  Fyi I am looking at  `UpgradeDependency` and `ManageDependencies` to maintain separation of concerns while keeping `AddManageDependency` focused on its stated purpose

**Comment by pway99** [comment]
Closing this issue as `ManageDependencies` has been updated via the following changes and is a suitable recipe for following the `AddManagedDependencies` recipe.
https://github.com/openrewrite/rewrite/commit/cce3b8e00455da296bf8e56e8d78eb74ae37b664
https://github.com/openrewrite/rewrite/commit/f9ae7bcc3ddb4a1f53498873d713eb3a4f153731
https://github.com/openrewrite/rewrite/commit/be9f41a4ed6b78845880a9ada61c9eefbb743ef1
https://github.com/openrewrite/rewrite/commit/1cd4073cfacc50a6233619ef07e866c7a2fd626b
