### ISSUE TITLE
AddManagedDependency: Allow wildcard only match on artifact

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#1448]
Hi,

the `onlyIfUsing' condition currently does not allow a wildcard only match on the artifact, e.g. `org.example.group:*`.

I made the PR [#1447](https://github.com/openrewrite/rewrite/pull/1447) for the extended regex to allow wildcard-only match on the artifact. I made also two minor changes:
- Set required = false on onlyIfusing as it works without
- Annotated addToRootPom with Nullable

If you want to have a look at extended regex, see: https://regex101.com/r/eJZfi3/1

Kind regards
Thomas

**Comment by pway99** [comment]
Thanks @thomaszub :)

**Comment by pway99** [comment]
closed via #1447
