### ISSUE TITLE
Replace value VariableDeclaration with comments. Error concat method duplicated

### ISSUE THREAD

**Issue by x650702** [openrewrite/rewrite#1456]
Hello!

I am having problems with JavaTemplate when trying to do a replace of a VariableDeclaration. If the value contains comments, the concatenated methods are duplicated. 

For example:
This not work:
```java
HttpClient client = HttpClient.create()
		.tcpConfiguration(conf ->
				conf.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 50).doOnConnected((Connection connection) -> connection
						// Read Timeout
						.addHandlerLast(new ReadTimeoutHandler(50, TimeUnit.MILLISECONDS))
						// Write Timeout
						.addHandlerLast(new WriteTimeoutHandler(50, TimeUnit.MILLISECONDS))));
```

This work:
```java
HttpClient client = HttpClient.create()
		.tcpConfiguration(conf ->
				conf.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 50).doOnConnected((Connection connection) -> connection
						.addHandlerLast(new ReadTimeoutHandler(50, TimeUnit.MILLISECONDS))
						.addHandlerLast(new WriteTimeoutHandler(50, TimeUnit.MILLISECONDS))));
```

My code is this, maybe I'm using it incorrectly:
```java
@Override
public J.VariableDeclarations visitVariableDeclarations(J.VariableDeclarations multiVariable,
		ExecutionContext ctx) {
	if (multiVariable.getType() != null
			&& multiVariable.getType().toString().equals("reactor.netty.tcp.TcpClient")) {
		String newMultiVariable = multiVariable.toString();
		newMultiVariable = newMultiVariable.replace("TcpClient", "HttpClient");
		newMultiVariable = newMultiVariable.replace("HttpClient.create()",
				"HttpClient.create().tcpConfiguration(conf -> conf");
		newMultiVariable = newMultiVariable + ")";
		JavaTemplate template = JavaTemplate.builder(this::getCursor, newMultiVariable).build();
		return multiVariable.withTemplate(template, multiVariable.getCoordinates().replace());
	}
	return multiVariable;
}
```
Thank you.

**Comment by pway99** [comment]
hello @x650702, I hope you don't mind I have taken the liberty and updated your code blocks with [syntax-highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)

**Comment by pway99** [comment]
It may be possible to simply replace the `create()` method invocation rather than the entire statement, however; It's a bit difficult to answer your question without a snippet of the code prior to the transformation. Can you provide a before snippet?   

here are a few suggestions:
 - invoke super first, then each method invocation of the variable-declarations's initializer will be visited and can be transformed accordingly.
     ```java
     J.VariableDeclarations varDecls = super.visitVariableDeclarations(multiVariable, ctx);
     ```
 - use `TypeUtils` for comparing types:
     ```java
     TypeUtils.isOfClassType(varDecls.getType(), "reactor.netty.tcp.TcpClient")`
     ````
 - use `ChangeType` for changing types: 
     ```java
         varDecls = (J.VariableDeclarations)
                            new ChangeType("reactor.netty.tcp.TcpClient", "reactor.netty.http.client.HttpClient", false)
                                    .getVisitor().visitNonNull(varDecls, ctx);
     ```
 - It should be possible to replace the `create()` method by implementing `visitMethodInvocation` and using the JavaTemplate for replacing per your requirements.

**Comment by pway99** [comment]
Hello @x650702,  Closing this issue please do not hesitate to [join us on slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) if you have any questions :)
