### ISSUE TITLE
Update rewrite-maven okhttp dependency to 5.x when 5.0.0 is released

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#1481]
[okhttp](https://github.com/openrewrite/rewrite/blob/665e8a0f65755baee280ae490d80a37fc5540eea/rewrite-maven/build.gradle.kts#L42) is pinned to 4.9.3 per: #1479 

https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp

Update to 5.x once 5.0.0 is released

**Comment by timtebeek** [comment]
We actually have some recipes now to automate this migration: https://docs.openrewrite.org/recipes/okhttp/upgradeokhttp5
Would be good to see how what automated migration pans out, and if that requires any additional cases to be covered.

**Comment by AdityaKompalli** [comment]
Hi, this is my first time contributing to open-source. Wanted to know if I can pick this up.

**Comment by timtebeek** [comment]
hi @AdityaKompalli ; thanks for the offer to help! It looks like there's still only alpha versions available of okhttp:
https://square.github.io/okhttp/changelogs/changelog/
We're working towards automated migration recipes to v5 in https://github.com/openrewrite/rewrite-okhttp.
If you'd like to help out with those migration recipes then you're most than welcome to chime in there!

The rewrite-maven module here we'll likely only update if a v5 of okhttp becomes available, which could be a while still.
I think it makes sense to for now close this issue as it's not actionable yet, and instead revisit once 5.0 is out.
