### ISSUE TITLE
ResourceLeak with Retry and Closeable resources

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#1491]
Hi,

there is currently an issue with Retry from resilience4j and Closeable resources. After a new retry attempt the previous retry does not get closed leading to a resource leak. See the open issues [https://github.com/resilience4j/resilience4j/pull/1634](https://github.com/resilience4j/resilience4j/pull/1634) and [https://github.com/resilience4j/resilience4j/issues/1253](https://github.com/resilience4j/resilience4j/issues/1253).

This affects at least the `MavenPomDownloader` in the field `sendRequest` as the `okhttp3.Response` is a `Closeable` and does not get closed after a failed retry.

Kind regards
Thomas

**Comment by tkvangorder** [comment]
Thanks for reporting this issue, you are absolutely correct.
