### ISSUE TITLE
Most documention links do not work 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1496]
Most of them do not work but some work occasionally 

![](https://user-images.githubusercontent.com/8935151/159849059-f6c6de36-2984-4106-8faf-055d7f869cfa.gif)

In this case in particular, the issue is that all links point to https://docs.openrewrite.org/reference/recipes/java/testing/junit5 instead of the specific pages

Sample page : https://docs.openrewrite.org/reference/recipes/java/testing/junit5

**Comment by tkvangorder** [comment]
Thanks for reporting, we have a tool that generates these docs, clearly, something is amiss. 8)

**Comment by tkvangorder** [comment]
This appears to be a syncing issue between when the rewrite-docs repository to `docs.rewrite.org`. The links are now working but we will keep an eye on this for our next release.

**Comment by yeikel** [comment]
Is `docs.rewrite.org` a future work? Because that does not return anything for me

**Comment by okundzich** [comment]
Tyler meant https://docs.openrewrite.org/. We opened an issue with gitbook (tool that we are using for docs) as it is not refreshing the links from the docs git repo.
https://github.com/openrewrite/rewrite-docs/tree/master/reference/recipes/java/testing/junit5

**Comment by yeikel** [comment]
> Tyler meant https://docs.openrewrite.org/. We opened an issue with gitbook (tool that we are using for docs) as it is not refreshing the links from the docs git repo.
> https://github.com/openrewrite/rewrite-docs/tree/master/reference/recipes/java/testing/junit5

Thank you. It seems that I am better off  using the docs from this repo until that's fixed

**Comment by tkvangorder** [comment]
@yeikel Sorry for the confusion, yes the correct URL for our docs is https://docs.openrewrite.org/

I have once again generated the documentation and I believe it is now working.

One thing to notice, at the bottom of each category page, is a timestamp of when the page was last modified. 

<img width="901" alt="image" src="https://user-images.githubusercontent.com/1878529/160026051-35fe24ca-7829-455f-9949-55a002b258b1.png">
 

I have found a couple of cases where my browser was caching an older version of the page. In chrome, I just use shift+reload to force the page to reload. This may be part of the problem.

**Comment by tkvangorder** [comment]
I have confirmed that the links are now working after regenerating the recipe references again.

**Comment by yeikel** [comment]
> I have confirmed that the links are now working after regenerating the recipe references again. 

They're working 

Thanks
