### ISSUE TITLE
JavaType.Class should contain full info on annotations, methods, constructors, superclasses

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#150]
Some visitors (like https://github.com/openrewrite/rewrite-spring/issues/9)  may benefit from or outright require the ability to look up information about classes, their methods, their annotations, that aren't sources being parsed as part of the current run. i.e.: Any symbol or class coming from a dependency. We do have access to this information since without it the java compiler wouldn't be able to successfully parse & type attribute java source into ASTs. 

`JavaType.Class` is the appropriate place for this information to go.

**Comment by okundzich** [comment]
@tkvangorder - is this still an issue or is it taken care of by your work on java template?

**Comment by sambsnyd** [comment]
This is still an issue

**Comment by jkschneider** [comment]
Annotations are available on

type -> tsym -> metadata -> attributes -> [n] -> type

`org.openjdk.tools.javac.code.Attribute` always refers to an annotation.

**Comment by sambsnyd** [comment]
Yes, we now have this capability.
