### ISSUE TITLE
RemoveUnusedImports fails to remove imports when the imports are in the same package as the compilation unit

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#1509]
Hi! Working through a blogpost on OpenRewrite I came across an issue with `org.openrewrite.java.RemoveUnusedImports`.

These are the steps to reproduce:
```bash
git clone https://github.com/spring-projects/spring-petclinic.git;
cd spring-petclinic;
git checkout -b 1.5.x;
./mvnw org.openrewrite.maven:rewrite-maven-plugin:4.21.0:init \
  -DactiveRecipes=org.openrewrite.java.RemoveUnusedImports
```

I would expect OpenRewrite to remove [the unused imports in VetControllerTests lines 20-23](https://github.com/spring-projects/spring-petclinic/blob/1.5.x/src/test/java/org/springframework/samples/petclinic/vet/VetControllerTests.java#L20-L23).
These imports are retained however, and I fail to see how to get them removed.
Am I missing something? Or is this perhaps an issue with the current implementation?

**Comment by tkvangorder** [comment]
@timtebeek Thanks for reporting, this should be working once the snapshots are published.

**Comment by timtebeek** [comment]
Thanks for the quick turn around time! Much appreciated :)
