### ISSUE TITLE
Recipe to transform calls to Objects.isNull and Objects.nonNull with a simple null check 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1547]
As per the [Java docs](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#nonNull-java.lang.Object-) :

    API Note:

    This method exists to be used as a [Predicate](https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html), filter(Objects::nonNull)

While using this method does not cause any problem, using it outside of stream predicates is not idiomatic

Example :
```java

if (isNull(a)){

// do something

}


if (nonNull(a)){

// do something

}
```

Should be replaced with

```java
if (a == null){

// do something

}


if (a != null){

// do something

}
```

Note : This recipe should not impact Streams

The following code should remain untouched : 

```java
        List<String> elements = new ArrayList<>();
        elements.add("hello");
        elements.add(null);

        Set<String>  nonNulList = elements.stream().filter(Objects::nonNull).collect(Collectors.toSet()
```

**Comment by yeikel** [comment]
@pway99 is your commit closing the right issue? Because it seems unrelated to this issue

**Comment by PatrickViry** [comment]
It's the other Patrick here. Yes it fixes a problem with operator precedence in recipe RemoveObjectsIsNull. See RemoveObjectsIsNullTest.kt.

**Comment by yeikel** [comment]
> It's the other Patrick here. Yes it fixes a problem with operator precedence in recipe RemoveObjectsIsNull. See RemoveObjectsIsNullTest.kt.

Apologies for tagging the wrong person. I was on mobile

Thank you for clarifying :)

**Comment by yeikel** [comment]
Where can I find the recipe `RemoveObjectsIsNull`? I tried searching in the org but it returned no results

**Comment by pway99** [comment]
Thanks @yeikel, that was a typo on the issue number I will re-open and fix

**Comment by pway99** [comment]
[PatrickViry](https://github.com/PatrickViry) closed this in https://github.com/openrewrite/rewrite/commit/a3b991e6829b6c185b144660b4587301c3af19bd [8 hours ago](https://github.com/openrewrite/rewrite/issues/1547#event-6604229152)
