### ISSUE TITLE
RSPEC-1124: Modifiers should be declared in the correct order

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1553]
> The Java Language Specification recommends listing modifiers in the following order:
> 
> Annotations
> public
> protected
> private
> abstract
> static
> final
> transient
> volatile
> synchronized
> native
> default
> strictfp

Noncompliant Code Example

```java
static public void main(String[] args) {   // Noncompliant
}
```

Compliant Solution

```java
public static void main(String[] args) {   // Compliant
}

```

Source : https://rules.sonarsource.com/java/tag/convention/RSPEC-1124

**Comment by yeikel** [comment]
This should be easy enough for first time contributors unless I am overlooking its complexity

**Comment by murdos** [comment]
There's already a recipe that does exactly what you describe: https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/cleanup/ModifierOrder.java

Hint: you can search in the code base the RSPEC number to check if there's already an existing recipe: https://github.com/openrewrite/rewrite/search?q=RSPEC-1124

**Comment by yeikel** [comment]
Thank you for letting me know and sharing the tip. Closing
