### ISSUE TITLE
Recipe to migrate from takari/maven-wrapper to the official maven wrapper

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1566]
Migrate from `takari/maven-wrapper` to the official maven wrapper. 

See https://github.com/spring-io/initializr/issues/1294 and https://github.com/spring-io/initializr/commit/7dab3f2268b53b8794f51463acbbf78236eb1080 for more details

Also https://github.com/takari/maven-wrapper

It seems that for this migration all we need to do is to run `mvn wrapper:wrapper` and to delete `MavenWrapperDownloader.java`

**Comment by shanman190** [comment]
Completed via https://github.com/openrewrite/rewrite/pull/3392.
