### ISSUE TITLE
Replace switch statements with if-else when the number of cases is small

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1588]
Example : 

```java

String a = getChar();
               switch(a) {
            case "A":
                break;
            default :
            
        }

```

```java



 if (a.equals("A")){
            
        }else {
            
        }

```

Notes : 

IDEA considers that anything < 3 should be replaced with an if statement

**Comment by traceyyoshima** [comment]
Hi @yeikel , thanks for reporting the issue!

Closing this issue since it's already covered by `org.openrewrite.java.cleanup.MinimumSwitchCases`.

**Comment by yeikel** [comment]
My bad. Thank you
