### ISSUE TITLE
Recipe : change scope of dependency

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1594]
In both [Maven ](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope)and [Gradle](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph), there are different dependency scopes

Example : 

Before(Maven) : 

```xml
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-api</artifactId>
    <version>5.8.2</version> 
    <!--  Scope defaults to compile -->
</dependency>
```

After(Maven) : 

```xml
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-api</artifactId>
    <version>5.8.2</version>
    <scope>test</scope> <!--  Adds the test scope -->
</dependency>
```

Follow up question : Can [AddDependency](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java) do this? 

That is, it should not add the dependency if it is already there, but it should change the scope if that's the difference between the two

**Comment by tkvangorder** [comment]
This can already be achieved via a composite recipe that uses RemoveDependency (from a given scope) and AddDependency (where the type is present in the given scope)

**Comment by jkschneider** [comment]
> RemoveDependency (from a given scope) and AddDependency (where the type is present in the given scope)

This would potentially change the order of dependencies in the POM. I think this recipe makes sense.

**Comment by shanman190** [comment]
@tkvangorder, I believe that this is fully implemented across both build tools and has for a little while now. So this issue can probably be closed.

https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyScope.java
https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyConfiguration.java
