### ISSUE TITLE
Add dynamic applicable tests that prevent a recipe from running on a particular class.

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1596]
Is there any way to ignore specific recipes from a line or class? 

For example, when I faced https://github.com/openrewrite/rewrite/issues/1478 and https://github.com/openrewrite/rewrite/issues/1536, I had to disable the individual recipes from my entire build until it was fixed. It would have been better if I had a way to disable that specific instance instead

Another example : currently, https://github.com/openrewrite/rewrite-testing-frameworks/issues/201 forced me to disable `org.openrewrite.java.testing.cleanup.BestPractices` for all my projects until it is fixed

In my particular example, I have the  rewrite configuration in a parent pom that is inherited by all my projects, if any of my individual projects encounters any rewrite bug, I'd need to create a release or overwrite the entire rewrite configuration in the individual module. Both of these options are not desirable 

There are also other scenarios where I simply do not want to run specific recipes for specific classes (For example [`org.openrewrite.java.cleanup.FinalClass` ](https://docs.openrewrite.org/reference/recipes/java/cleanup/finalclass) )

If it helps in any way, in Sonar we have 

`//NOSONAR` and also `@SuppressWarnings("squid:S2078")` 

In an ideal world, this inline functionality should be easily removable with another recipe :)

**Comment by jkschneider** [comment]
Three forms exist in an initial implementation:

1. Skip by name
<img width="931" alt="image" src="https://user-images.githubusercontent.com/1697736/162810701-0b6e8942-998f-43da-a541-aa97a6e0ac37.png">

2. Skip by class
<img width="925" alt="image" src="https://user-images.githubusercontent.com/1697736/162810742-657aee07-2348-4f6c-9f25-c096c5e5d949.png">

3. Skip all
<img width="929" alt="image" src="https://user-images.githubusercontent.com/1697736/162810769-e21c26a5-af31-470e-abc3-91b9efcd49a9.png">

**Comment by yeikel** [comment]
> Three forms exist in an initial implementation:
> 
> 1. Skip by name
> <img width="931" alt="image" src="https://user-images.githubusercontent.com/1697736/162810701-0b6e8942-998f-43da-a541-aa97a6e0ac37.png">
> 
> 2. Skip by class
> <img width="925" alt="image" src="https://user-images.githubusercontent.com/1697736/162810742-657aee07-2348-4f6c-9f25-c096c5e5d949.png">
> 
> 3. Skip all
> <img width="929" alt="image" src="https://user-images.githubusercontent.com/1697736/162810769-e21c26a5-af31-470e-abc3-91b9efcd49a9.png">
> 

Thank you. This is a great start

I would like to have the option to disable specific lines as well so if you don't mind let's leave the issue open until that's feasible

**Comment by traceyyoshima** [comment]
Hi @yeikel, I spoke with the team and we won't be pursuing exclusions. Info on some of the complexities may be found [here](https://github.com/openrewrite/rewrite/issues/1731).

We'd like to improve our style detection so that recipes won't execute if there are additional configurations like `//NOSONAR`, `@SuppressWarnings("squid:S2078")`, `check-style` configurations, and/or `@RewriteSkip`.

Happy to fix bugs if anything else comes up, please let me know if you have any questions.

**Comment by yeikel** [comment]
> Hi @yeikel, I spoke with the team and we won't be pursuing exclusions. Info on some of the complexities may be found [here](https://github.com/openrewrite/rewrite/issues/1731).
> 
> We'd like to improve our style detection so that recipes won't execute if there are additional configurations like `//NOSONAR`, `@SuppressWarnings("squid:S2078")`, `check-style` configurations, and/or `@RewriteSkip`.
> 
> Happy to fix bugs if anything else comes up, please let me know if you have any questions.

This is unfortunate but I understand that it is complex

My reasoning is not only for bugs but also for personal preference

Without a mechanism to have exclusions, I'll have to revert the recipe application with each execution, and that's quite tedious and error prone to be honest

**Comment by traceyyoshima** [comment]
Ah, I see. 

> Without a mechanism to have exclusions, I'll have to revert the recipe application with each execution, and that's quite tedious and error prone to be honest

A potential workaround would be to automate adding the `@RewriteSkip(...)` annotation to specific files via a recipe. The annotation would prevent unwanted executions. Then a separate recipe may remove the annotations afterward.

**Comment by yeikel** [comment]
> Ah, I see. 
> 
> > Without a mechanism to have exclusions, I'll have to revert the recipe application with each execution, and that's quite tedious and error prone to be honest
> 
> A potential workaround would be to automate adding the `@RewriteSkip(...)` annotation to specific files via a recipe. The annotation would prevent unwanted executions. Then a separate recipe may remove the annotations afterward.

I believe that `@RewriteSkip` even if manual should do the job for me but it would be nice to have some way to automate its removal

**Comment by traceyyoshima** [comment]
> but it would be nice to have some way to automate its removal

Ya, an internal recipe may take in a set of class FQNs like `AddRewriteSkip` and `RemoveRewriteSkip`.
In `visitClassDecl` the class FQN may be checked if it's contained in the specified list.
Then use the java template to add the annotation.

A similar process may be used to remove the annotation automatically as well.

**Comment by jkschneider** [comment]
@traceyyoshima reopening because the mechanism does not exist yet to apply this functionality. Likely the best option right now is to enhance YAML configuration of a recipe to allow the application of dynamic applicable tests. Something _like_ this:

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/1697736/166042729-84bd8728-3e6d-4d29-8321-5faf108f0980.png">

cc / @yeikel

**Comment by knutwannheden** [comment]
This looks interesting. There could then possibly also be a predicate to check for a given class or possibly even Maven module on the classpath.

**Comment by jkschneider** [comment]
@knutwannheden There is a visitor called `HasTypeOnClasspathSourceSet` currently.
