### ISSUE TITLE
Regenerate antlr code with 4.10.1

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#1615]
Update ANTLR generated files to be compatible with version 4.10.1.

**Comment by traceyyoshima** [comment]
ANTLR 4.10 does not support java 8.

**Comment by tkvangorder** [comment]
We are unable to move to antlr 4.10.0 because the runtime was compiled against java 11 (even though the target and source were set to Java 8). 

This manifests in the following error when running our tests in `rewrite-java-8`:

```
Caused by:
        java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
```

I've submitted a PR to the antlr project to fix this issue. 

https://github.com/antlr/antlr4/pull/3648

**Comment by traceyyoshima** [comment]
Update: ANTLR is pinned back to 4.9.3.

There are several downstream projects that have dependencies that are not compatible with antlr `4.10.1`.
- `rewrite-maven-plugin`: `checkstyle`
- `graphql-java`

**Comment by tkvangorder** [comment]
It appears checkstyle is now updated. 

https://github.com/checkstyle/checkstyle/commit/1e862ff74bcfd34eaa10d8e0bb7c11abf26d8927

**Comment by tkvangorder** [comment]
So the only downstream dependency that is preventing this is the graphql project?

**Comment by traceyyoshima** [comment]
> So the only downstream dependency that is preventing this is the graphql project?

Yes. `checkstyle` was updated pretty quickly, but `graphql-java` has essentially stated it's not a priority.

**Comment by rsynek** [comment]
I (probably) ran into this issue, using the `org.openrewrite.recipe:rewrite-recipe-bom:1.12.3`:

```
ANTLR Tool version 4.9.3 used for code generation does not match the current runtime version 4.10.1
ANTLR Runtime version 4.9.3 used for parser compilation does not match the current runtime version 4.10.1
```

Overriding the Antlr version to `4.9.3` helps.

Are there any plans to upgrade to a newer Antlr version?
