### ISSUE TITLE
Maven recipe: prefix POM expressions with project.

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#1621]
[MNG-7404] Will drop support for prefixless expressions in POM https://github.com/apache/maven/pull/696
Although it's been deprecated for quite some time already, it will only be removed in Maven 4.
It seems like OpenRewrite would be well suited to already recognize & fix unprefixed expressions.

**Comment by pway99** [comment]
Thanks @timtebeek, this is very helpful

**Comment by mthmulders** [comment]
In fact, there are two things changing in Maven 4:
1. `${version}` will no longer work - should become `${project.version}`
1. `${pom.version}` will no longer work - should also become `${project.version}`

The latter one is probably simple, the former one can be more challenging...

**Comment by timtebeek** [comment]
> Can someone check how much of the new recipes overlaps with https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/NormalizeMavenVariables.java? To my understanding that was already half of the work at least.

You're right! Replaced now in #3600
