### ISSUE TITLE
Recipe: ReplaceLiteralWithConstant

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#1622]
As an inverse to [ReplaceConstant](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/ReplaceConstant.java). `ReplaceConstant` allows users to replace a constant with a literal value, for instance to phase out usage of Guava's `Charsets.UTF_8`.

I propose to add an inverse recipe as well to replace String literals with constants. For instance to replace string literals such as `"application/json"` with  Spring's constant `MediaType.APPLICATION_JSON_VALUE`.
I don't think one would typically want to add a dependency merely to use a constant, but perhaps that should be possible to define as well.

This way there's an easy flow for users to add to migration recipes to clean up common string literals throughout multiple projects.

**Comment by tkvangorder** [comment]
Thanks for the suggestion!

**Comment by knutwannheden** [comment]
I think it would in this context also make sense to consider supporting replacing a constant with another constant. E.g. `Charsets.UTF_8` with `StandardCharsets.UTF_8`.
