### ISSUE TITLE
replace Anonymous class with Lambda 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1631]
```java


Address address = new Address() {
            @Override
            public int compareTo(Address o) {
                return 0;
            }
        };

```

```java

Address address = o -> 0;

```

**Comment by jkschneider** [comment]
@yeikel I think this is covered by https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseLambdaForFunctionalInterface.java ?

**Comment by jkschneider** [comment]
Closing for now, unless I'm mistaken and we're missing something from `UseLambdaForFunctionalInterface`. Thanks!
