### ISSUE TITLE
ParameterizedLogging improve

### ISSUE THREAD

**Issue by delanym** [openrewrite/rewrite#1635]
This recipe needs some work. It converts the tutorial example
https://docs.openrewrite.org/tutorials/slf4j-parameterized-logging
but won't do `logger.debug(this.thread.getName() + " started" + " today");`

**Comment by pway99** [comment]
Hello @delanym,
Can you check for missing type information by running the [FindMissingTypes](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.javal) recipe?

There is a good chance that `this.thread` is an unknown type which results in the `logger.debug` statement also having a null type.  That would prevent the `ParameterizedLogging` recipe from detecting and converting the logging statement.

**Comment by delanym** [comment]
What does this mean?

``` diff
-    super(message);
+    /*~~(type information has a different method name '<constructor>')~~>*/super(message);
```

**Comment by pway99** [comment]
That looks like a bug in `FindMissingTypes`, thanks for sharing.
https://github.com/openrewrite/rewrite/issues/1675

**Comment by pway99** [comment]
@delanym, is the `slf4j-parameterized-logging` recipe still not working for you?

**Comment by pway99** [comment]
Just FYI working on https://github.com/openrewrite/rewrite/issues/1678 since it turns out `FindMissingTypes` is only validating `MethodInvocations`

**Comment by pway99** [comment]
Closing this issue, please feel free to re-open or ping us on slack if have any questions
