### ISSUE TITLE
`Collection.isEmpty()` should be used to test for emptiness.`RSPEC-1155`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1648]
https://rules.sonarsource.com/java/quickfix/RSPEC-1155

**Comment by traceyyoshima** [comment]
Hi @yeikel, I think this is covered by: `IsEmptyCallOnCollections`.

**Comment by yeikel** [comment]
That seems to be the case. I searched for it but I could not find it

Can we add the tag RSPEC-1155 to it?

**Comment by yeikel** [comment]
It looks that the current `RSPEC-3981` (the current tag) is a different recipe. Did we make a mistake when tagging it? 

https://rules.sonarsource.com/java/RSPEC-3981

**Comment by yeikel** [comment]
Well never mind, from the tests, it seems that you're covering both

Maybe we need to add that extra tag to it?

**Comment by traceyyoshima** [comment]
> Maybe we need to add that extra tag to it?

Yes, it looks like you're right, it's missing a tag - I'll update the tags in a moment.
