### ISSUE TITLE
Replace `java.util.Random` with `java.security.SecureRandom`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1658]
This recipe should only be used in security contexts as `SecureRandom` is considerably slower by default

To do "not harm" we should warn users about the same

See : https://kostenko.org/blog/2019/04/java-spedup-random-generation.html

**Comment by pway99** [comment]
Hi @yeikel,  Thanks for the reference article, 
rewrite-java-security has a [SecureRandom](https://github.com/openrewrite/rewrite-java-security/blob/main/src/main/java/org/openrewrite/java/security/SecureRandom.java) recipe, it's optimized to not convert instances in test classes.

Going to close this issue please feel free to re-open it if you have suggestions on how it can be improved.
