### ISSUE TITLE
`String.replace` should be preferred to `String.replaceAll` if the first parameter doesn’t contains a regular expression or pattern. `RSPEC-5361`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1660]
https://rules.sonarsource.com/java/RSPEC-5361

**Comment by tkvangorder** [comment]
Agreed. This would a useful recipe. This could be scoped to only replace literals that only contain alpha and numeric characters.

**Comment by traceyyoshima** [comment]
This will be fixed by: https://github.com/openrewrite/rewrite/pull/1711
