### ISSUE TITLE
Statements should be on separate lines. `RSPEC-122`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1667]
> For better readability, do not put more than one statement on a single line.

**Noncompliant Code Example**

```java
if(someCondition) doSomething();
```

**Compliant Solution**

```java

if(someCondition) {
  doSomething();
}

```

https://rules.sonarsource.com/java/RSPEC-122

**More examples :** 

```java

argv++; argc--;


```

```java

argv++;
argc--;

```

See also : https://www.oracle.com/java/technologies/javase/codeconventions-declarations.html

**Comment by pway99** [comment]
`RSPEC-121` is handled by [NeedBraces](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/cleanup/NeedBraces.java).  AutoFormat should handle RSPEC-122

**Comment by yeikel** [comment]
You're right. I was sure that I checked before creating it but it seems that I missed it

Closing :)
