### ISSUE TITLE
The `Object.finalize()` method should not be called

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1683]
https://rules.sonarsource.com/java/RSPEC-1111

The implemention should be very similar to https://github.com/openrewrite/rewrite/issues/1664

**Comment by mccartney** [comment]
Already done in #770?
I see code in `rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoFinalizer.java`

**Comment by timtebeek** [comment]
For anyone looking to pick this up: a [very similar recipe was merged last week](https://github.com/openrewrite/rewrite/pull/2309).
