### ISSUE TITLE
Format detection needs to detect the correct style when an if condition does not have curly braces

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1685]
Depending on the recipe, new changes may require a format change by the underlying formatting framework. 

Would it be possible for rewrite to detect(and apply) formatting frameworks without explicit rewrite configuration? 

I encountered this while running `org.openrewrite.java.cleanup.IsEmptyCallOnCollections` on [kubernetes-client/java](https://github.com/kubernetes-client/java/pull/2215)

Sample PR : https://github.com/kubernetes-client/java/pull/2215

For this case, I had to run `mvn spotless:apply` after the recipe execution as spotless is in the classpath and the recipe updates did not pass that check

**Comment by traceyyoshima** [comment]
Hi @yeikel, I think it's possible, but may not be a priority for a while. This looks like a question for @tkvangorder, @sambsnyd, or @jkschneider.

**Comment by tkvangorder** [comment]
My instinct here is that we would not want to go down this road because there are going to be n-number of formatting frameworks and we would not necessarily want to build support for (or have dependencies on) those libraries. However, if the source that rewrite is producing is not idiomatically consistent with the project's source, I would be interested in capturing those differences to see if we can improve our format detection.

**Comment by yeikel** [comment]
> @yeikel I looked at the PR you submitted and it looks like you rebased after running the formatting framework. Do you have an example where the formatting was different?

I recreated the branches. See : https://github.com/yeikel/java/compare/original-recipe-application...yeikel:style-changes?expand=1

**Comment by traceyyoshima** [comment]
Closing the issue.

> My instinct here is that we would not want to go down this road because there are going to be n-number of formatting frameworks and we would not necessarily want to build support for (or have dependencies on) those libraries. However, if the source that rewrite is producing is not idiomatically consistent with the project's source, I would be interested in capturing those differences to see if we can improve our format detection.

The recipe respected the project's formatting, but the plugin uses new rules that apply to new or changed code.
There isn't any actionable work if we are not going to support the n-number of formatting frameworks.
