### ISSUE TITLE
 **.properties** files encoding in ISO ISO-8859-1

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1693]
Good afternoon, 

I have a question, and know how I could solve it. I have several projects that the **.properties** files are encoded in ISO ISO-8859-1 and when migrating these files automatically changes this encoding to UTF-8, this can cause that when lifting these application once migrated the special characters are not well seen. Is it possible to configure the **.properties** files to respect the original encoding?

Thank you very much for your help.

**Comment by tkvangorder** [comment]
Hello @josemariavillar , We are aware of this issue and will likely add a marker to the AST to preserve the encoding. See #1434 for more information. I am going to close this as a duplicate and we will try to get this one done.

**Comment by traceyyoshima** [comment]
This changes the scope of the original request since UTF encodings are based on a BOM and only require checking the first 4 bytes of a file.

ISO-8859-1 includes Latin characters and reading the source to statistically guess the encoding.

**Comment by traceyyoshima** [comment]
@josemariavillar I think this is fixed on the latest snapshot. Would you please confirm the changes are detected for you or add an example of the issue on your test project?

Thanks in advance!

**Comment by traceyyoshima** [comment]
Closing the issue since it's been a week with no response.

Thank you for reporting the issue @josemariavillar and please don't hesitate to reach out if your issue still exists!
