### ISSUE TITLE
`org.openrewrite.java.RemoveUnusedImports` removes used imports

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1698]
Example : 

```java

package pgnio;

import com.github.jasync.sql.db.pool.PooledObject;
import pgnio.QueryReadyConnection.AutoCommit;

public class TestClass implements PooledObject {
    private AutoCommit autoCommit;
    private long creation = System.currentTimeMillis();

    public TestClass(AutoCommit ac) {
        autoCommit = ac;
    }

    @Override
    public long getCreationTime() {
        return creation;
    }

    @Override
    public String getId() {
        return autoCommit.toString();
    }

    public boolean isOpen() {
        return autoCommit.ctx.io.isOpen();
    }

}


```

```diff

index d50617875..07644c5e1 100644
--- a/pgnio/TestClass.java
+++ b/pgnio/TestClass.java
@@ -1,7 +1,6 @@
 package pgnio;
 
 import com.github.jasync.sql.db.pool.PooledObject;
-import pgnio.QueryReadyConnection.AutoCommit;
 
 public class TestClass implements PooledObject {
     private AutoCommit autoCommit;


```

I am running it using 

`mvn rewrite:run -Drewrite.activeRecipes=org.openrewrite.java.RemoveUnusedImports`

In this case, it is removing the `AutoCommit` class when it is clearly used in the private field below

**Comment by tkvangorder** [comment]
@yeikel Is QueryReadyConnection in the same project as the test class or is it in a different module of a multi-module maven project? 

This feels like missing type attribution on autoCommit.

**Comment by yeikel** [comment]
No `QueryReadyConnection` is a a class from the package `

```
<dependency>
    <groupId>com.github.cretz.pgnio</groupId>
    <artifactId>pgnio-driver</artifactId>
    <version>0.2.0</version>
</dependency>
```

See : https://github.com/cretz/pgnio/blob/master/driver/src/main/java/pgnio/QueryReadyConnection.java

**Comment by yeikel** [comment]
The package names are coincidentally the same name in case it matters

**Comment by traceyyoshima** [comment]
@yeikel Taking a look!

**Comment by traceyyoshima** [comment]
> This feels like missing type attribution on autoCommit.

```java
    @Nullable
    @Override
    protected TreeVisitor<?, ExecutionContext> getSingleSourceApplicableTest() {
        return new NoMissingTypes();
    }
```
Should catch missing type info, the cause is a change that looks for imports in the same package:
```java
                    if (types == null || sourcePackage.equals(elem.getPackageName())) {
                        anImport.used = false;
                        changed = true;
```

**Comment by traceyyoshima** [comment]
@yeikel I think the code to remove imports with the same package name will happen much more often than classes that happen to share the same package.

Fixing this issue will probably need to wait until we can associate types to [GAV](https://github.com/openrewrite/rewrite/issues/1316) coordinates.
