### ISSUE TITLE
`org.openrewrite.java.cleanup.UseCollectionInterfaces` not making changes on local variable

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1703]
Input : 

```java

import java.util.ArrayList;

public class TestClass {

	public void hello() {
		ArrayList<String> a = new ArrayList<>();
		a.add("Hello");
		System.out.println(a);
	}

}

```

Expected : 

```java

import java.util.ArrayList;

public class TestClass {

	public void hello() {
		List<String> a = new ArrayList<>();
		a.add("Hello");
		System.out.println(a);
	}

}

```

Actual : 

No changes

I am running it with 

`mvn rewrite:run -Drewrite.activeRecipes=org.openrewrite.java.cleanup.UseCollectionInterfaces`

Versions : 

```xml
<rewrite-maven-plugin.version>4.22.2</rewrite-maven-plugin.version>
<rewrite-logging-frameworks.version>1.5.2</rewrite-logging-frameworks.version>
<rewrite-testing-frameworks.version>1.20.2</rewrite-testing-frameworks.version>
<rewrite-migrate-java.version>1.4.3</rewrite-migrate-java.version>

```

**Comment by yeikel** [comment]
It seems that I misinterpreted the coverage of that recipe. Is it only for method return types?

**Comment by traceyyoshima** [comment]
Hi @yeikel, yes, it's scoped to return types on methods, but could be expanded to variable declarations with assignments.

**Comment by traceyyoshima** [comment]
@yeikel I misremembered - the recipe transforms both methods and variables, but was scoped to `public` modifiers since the RSPEC specifies public. `private` and `no modifiers` seem pretty reasonable, so I added those in as well.
