### ISSUE TITLE
Scope defined in dependency management defeats ChangeDependencyGroupIdAndArtifactId

### ISSUE THREAD

**Issue by gsmet** [openrewrite/rewrite#1717]
I created https://github.com/openrewrite/rewrite/pull/1716 to show exactly what the issue is with a test.

The problem is here:
https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java#L100

The `scope` is the one from the dependency management whereas the dependency doesn't have anything defined thus it defaults to the `compile` scope and it doesn't match.

I wasn't exactly sure how this one should be fixed given it is widely used in the codebase so I thought it would be better to show you the issue first.

**Comment by tkvangorder** [comment]
@gsmet

I finally got a little time to look at this and thank you for the reproducible use case! It was pretty easy to track down thanks to your work.
