### ISSUE TITLE
Remove jackson-module-kotlin as a required dependency

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#1722]
We want to support the serialization and deserialization of kotlin recipes.
We do not want rewrite to have an opinion about which version of kotlin its consumers use, if they use kotlin at all.

So we shall remove our dependency on jackson-module-kotlin and use reflection to apply it at runtime if it is present. Build plugins will be correspondingly updated to include jackson-module-kotlin by default, so users will have to make no changes.

**Comment by nmck257** [comment]
Unfortunately, `jackson-module-kotlin` itself has an opinion about kotlin version. The latest `jackson-module-kotlin` has a compile dependency on `kotlin-reflect:1.5.30`, which transitively pulls in `kotlin-stdlib:1.5.30`, whereas latest Kotlin is currently 1.8.10.

There might be a fix on the Jackson side: https://github.com/FasterXML/jackson-module-kotlin/issues/566#issuecomment-1445497275
...but in the interim:

This effectively pins recipes run via Maven plugin (haven't checked Gradle) to Kotlin 1.5.30. I wonder if it might be better to 1) dependency-manage kotlin-bom in the maven plugin, assuming that a pinned current version is better than a pinned stale version 2) remove `jackson-module-kotlin` from the plugin and move that dependency declaration responsibility to kotlin recipe authors 3) idk ?

**Comment by cowtowncoder** [comment]
Aside from the issue on Jackson-module-kotlin side which hopefully gets addressed, module itself does work against kotlin-core versions 1.4 - 1.8, doesn't it? At least that is my understanding, based on CI checking against different versions of `kotlin-core`.

**Comment by nmck257** [comment]
I'm not aware of any compatibility issues between the code of `jackson-module-kotlin` and newer versions of the Kotlin APIs, and anecdotally, I haven't experienced issues with apps which bring a newer Kotlin version + `jackson-module-kotlin`.

**Comment by cowtowncoder** [comment]
@nmck257 Ok yes that is my understanding as well. The issue linked-to needs to be resolved regardless, of course.
