### ISSUE TITLE
Maven - ChangeDependencyGroupIdAndArtifactId should allow adding a version tag

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#1723]
Currently, if you use the optional newVersion parameter, but the existing dependency in the pom does not include a version tag already (ie it is managed), then the newVersion value is effectively ignored.

It would be useful if this scenario instead added a version tag with the requested value.

**Comment by tkvangorder** [comment]
@nmck257 Thanks for reporting the issue, this recipe now has an optional flag `overrideManagedVersion` which can be set to `true` to force the version to be added to the dependency even if there is a managed version for the new dependency.

Conversely, if the old dependency is not managed but the new artifact is managed (and the override is set to `false`), this recipe will remove the version from the dependency.

**Comment by tkvangorder** [comment]
Let me know if this helps with your use cases and feel free to also reach out to the team on our slack org.

**Comment by nmck257** [comment]
Nice changes! Thank you,

**Comment by nmck257** [comment]
> @nmck257 Thanks for reporting the issue, this recipe now has an optional flag `overrideManagedVersion` which can be set to `true` to force the version to be added to the dependency even if there is a managed version for the new dependency.
> 
> Conversely, if the old dependency is not managed but the new artifact is managed (and the override is set to `false`), this recipe will remove the version from the dependency.

@tkvangorder do you think similar logic could be ported into `AddDependency`? As far as I can tell, that one currently requires the client to configure a version, and the recipe has no cleverness for checking if the new dependency has a managed version
