### ISSUE TITLE
Replace `Charset.forName` with `StandardCharsets` 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1724]
Examples  : 

| String | Constant |
|---|---|
| Charset.forName("US-ASCII")  |  StandardCharsets.US_ASCII |   
| Charset.forName("ISO-8859-1")  |   StandardCharsets.ISO_8859_1|   
| Charset.forName("ISO-8859-1")  |   StandardCharsets.ISO_8859_1|   
| Charset.forName("UTF-8")  |   StandardCharsets.UTF_8|   

Full list : 

```java

    /**
     * Seven-bit ASCII, a.k.a. ISO646-US, a.k.a. the Basic Latin block of the
     * Unicode character set
     */
    public static final Charset US_ASCII = Charset.forName("US-ASCII");
    /**
     * ISO Latin Alphabet No. 1, a.k.a. ISO-LATIN-1
     */
    public static final Charset ISO_8859_1 = Charset.forName("ISO-8859-1");
    /**
     * Eight-bit UCS Transformation Format
     */
    public static final Charset UTF_8 = Charset.forName("UTF-8");
    /**
     * Sixteen-bit UCS Transformation Format, big-endian byte order
     */
    public static final Charset UTF_16BE = Charset.forName("UTF-16BE");
    /**
     * Sixteen-bit UCS Transformation Format, little-endian byte order
     */
    public static final Charset UTF_16LE = Charset.forName("UTF-16LE");
    /**
     * Sixteen-bit UCS Transformation Format, byte order identified by an
     * optional byte-order mark
     */
    public static final Charset UTF_16 = Charset.forName("UTF-16");

```

Other example(for unit tests) : 

```java
String name =   Charset.forName("UTF-8").name();

```

**Note** : This recipe should only run in Java 7+

**Comment by yeikel** [comment]
@traceyyoshima will your changes also cover this case? Just wanted to make sure

`String name =   Charset.forName("UTF-8").name();`

**Comment by traceyyoshima** [comment]
> String name = Charset.forName("UTF-8").name();

Hi @yeikel, great question! Yes, a general description of the transformation looks like this:

```java
J.Assignment: String name =              Charset.forName("UTF-8").name();
              |           |              |                       |
              Variable    assignment     Method Invocation       Method Invocation
                                         |
                                         Change to `StandardCharset.CONSTANT`
```

The change happens on the matched method invocation `Charset.forName("UTF-8")` and the rest of the AST is left in place.
Does that help?

**Comment by yeikel** [comment]
> > will your changes also cover this case? Just wanted to make sure as I don't see any tests about the same
> 
> Hi @yeikel, great question! Yes, a general description of the transformation looks like this:
> 
> ```java
> J.VariableDecl: String name =              Charset.forName("UTF-8").name();
>                 |           |              |                       |
>                 Variable    assignment     Method Invocation       Method Invocation
>                                            |
>                                            Change to `StandardCharset.CONSTANT`
> ```
> 
> The change happens on the matched method invocation `Charset.forName("UTF-8")` and the rest of the AST is left in place.
> Does that help?

It does. Thank you for explaining
