### ISSUE TITLE
Yaml - DeleteKey does not handle entries with single-line dot-separated keys

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#1729]
See the following test cases:

```kotlin
class DeleteKeyTest: YamlRecipeTest {
    override val recipe get() = DeleteKey("$.a.b.c", null)

    @Test
    fun `hierachical property with scalar value`() = assertChanged(
        before = """
            a:
              b:
                c: qwe
        """.trimIndent(), after = "") // success

    @Test
    fun `single line property with scalar value`() = assertChanged(
        before = """
            a.b.c: qwe
        """.trimIndent(), after = "") // failure ("the recipe must make changes")

    @Test
    fun `hierachical property with mapping value`() = assertChanged(
        before = """
            a:
              b:
                c:
                  d: qwe
        """.trimIndent(), after = "") // success

    @Test
    fun `single line property with mapping value`() = assertChanged(
        before = """
            a.b.c:
              d: qwe
        """.trimIndent(), after = "") // failure ("the recipe must make changes")
}
```

**Comment by traceyyoshima** [comment]
Hi @nmck257, thanks for the report - taking a look!

**Comment by traceyyoshima** [comment]
Hi @nmck257, I took a look at the `a.b.c` is being treated as a Scalar by the YamlParser.

I think [DeleteProperty](https://github.com/openrewrite/rewrite/blob/main/rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java) may fit what you're looking for:

```kotlin
    @Test
    fun `single line property with mapping value`() = assertChanged(
        recipe = DeleteProperty("a.b.c", false, false, null),
        before = """
            a.b.c:
              d: qwe
        """.trimIndent(), after = "")

    @Test
    fun `single line property with scalar value`() = assertChanged(
        recipe = DeleteProperty("a.b.c", false, false, null),
        before = """
            a.b.c: qwe
        """.trimIndent(), after = "")
```

**Comment by nmck257** [comment]
@traceyyoshima - yep, `DeleteProperty` catches this case, and making that substitution in my own code accomplishes my goal. Thank you!

At that point, I guess this pivots from "bug/question" to "documentation feedback". These two recipes feel pretty similar, and on first attempt, I had apparently misinterpreted this line from `DeleteProperty`:
> Delete a YAML property. Nested YAML mappings are interpreted as dot separated property names, i.e. as Spring Boot interprets application.yml files.

In short, I expected it to only work if my provided key has a scalar value. That is, I had guessed that:
```yml
a.b.c:
  d: qwe
```
...would be interpreted as one property key, `a.b.c.d`, which does not equal `a.b.c`, and therefore nothing would get deleted.

I feel like if `DeleteProperty` were extended to support JsonPathMatcher syntax, then `DeleteKey` would be fully redundant?

But, I'm certainly not a power user here :)

**Comment by traceyyoshima** [comment]
> yep, `DeleteProperty` catches this case, and making that substitution in my own code accomplishes my goal. Thank you!

Great, I'm glad it works for you!

> Nested YAML mappings are interpreted as dot separated property names, i.e. as Spring Boot interprets application.yml files.

Ah, I appreciate your feedback, your interpretation makes sense. I added the detail to the description [here](https://github.com/openrewrite/rewrite/commit/dcf0130da997c5186e27a1819351bf4db5e1023f).

> I feel like if `DeleteProperty` were extended to support JsonPathMatcher syntax, then `DeleteKey` would be fully redundant?

That is a fair observation, and I understand why it may appear that way, but unfortunately, it's a little more complicated.

I had mentioned `a.b.c` is being treated as a `Yaml.Scalar`, but hadn't explained much about what that means. Essentially, yaml considers `a.b.c` as a key to the mapping `d: qwe`. So, the `DeleteProperty` recipe checks for `.` separators and splits the mapping entry to find a match. There is also some code in `DeleteProperty` that checks for naming conventions specific to property matching. Hopefully, that helps clarify the differences a bit!

Thanks again for opening the issue and providing your feedback, it's really appreciated!

**Comment by traceyyoshima** [comment]
Closing the issue, since it's been resolved

**Comment by nmck257** [comment]
Thanks for taking the time here! Agree w/ closure.

Though, this language:
> Essentially, yaml considers `a.b.c` as a key to the mapping `d: qwe`

...does make me think that the following test case *should* be valid for `DeleteKey`, as well:
```kotlin
    @Test
    fun `single line property with mapping value`() = assertChanged(
        before = """
            a.b.c:
              d: qwe
        """.trimIndent(), after = "") // failure ("the recipe must make changes")
```
But, I've got a solution, and I can study these semantics more on my own time

**Comment by nmck257** [comment]
Ahh - yeah, that connects the dots. Thanks again!
