### ISSUE TITLE
Add a parser that will create SourceFile place holders for any file that is not formally parsed by one of rewrite's other parsers.

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#1734]
Currently, the only source files that are included when processing a project are those that are created by one of Rewrite's parsers.

Any file type that is not handled by one of these parsers will be "invisible" during recipe execution. There is a plain-text parser available but this cannot be used on files that have binary content and there are a large number of file patterns that may/may not contain text.

This issue will introduce a `QuarkParser`: 

A parser that is used to record files known to exist in the project but not formally parsed by one of Rewrite's other parsers.

The underlying source file instance `Quark` is therefore known to exist (It will have a SourcePath) but it will not have its
content formally represented in the framework.

This task will also introduce `visitSourceFile(SourceFile sourceFile)` to `TreeVisitor` and each visitor implementation will call this method in `accept`
 
This will allow for a class of recipes to detect the presence of a file, rename a file, or delete the file.

**Comment by pway99** [comment]
Use case renaming a file which was not parsed due to its type and unavailable to the recipe
https://github.com/openrewrite/rewrite-maven-plugin/issues/183

Use case where the existence of a file affects the action of a recipe
https://github.com/openrewrite/rewrite-spring/issues/131

**Comment by jkschneider** [comment]
Resolved with #1737
