### ISSUE TITLE
ReplaceDuplicateStringLiterals should probably not be applied on test source code

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1740]
Different rules apply to test vs main source code.
Duplication is less an issue, and might even be desired, in tests code.

I checked with SonarLint: it doesn't report RSPEC-1192 as an issue in test code.

So I suggest that `org.openrewrite.java.cleanup.ReplaceDuplicateStringLiterals` being enhanced to not be applied on code that is identified as test code.

**Comment by traceyyoshima** [comment]
@murdos thanks again, I'm taking a look!
