### ISSUE TITLE
RemoveUnusedLocalVariables keeps assignement of unused variable, but removes its declaration

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1743]
```java
String foo;
Long.parseLong(foo = "123");
```

is changed to the following code that doesn't compile anymore:
```java
Long.parseLong(foo = "123");
```

**Comment by traceyyoshima** [comment]
`foo = "123"` isn't removed since it's not visited by `DeleteStatement`.
A separate issue is `Long.parseLong("123")` is not detected as unused.

**Comment by traceyyoshima** [comment]
Unassigning myself, upon closer investigation this will be much easier with data-flow analysis.
