### ISSUE TITLE
Style formatting for rewrite-yaml

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#175]
(As the title implies. Logging this issue just as an idea. Feel free to close. Issue body can be expanded further.)

e.g., there are style differences as inspired by the redhat-yaml vscode-plugin which formats as such:

```yml
---
foo:
- a
- b
- c
```

vs.

```yml
---
foo:
  - a
  - b
  - c
```

etc.

**Comment by sambsnyd** [comment]
This is a good idea and I'm sure we'll do it at some point but probably not for a while
