### ISSUE TITLE
ChangeDependencyGroupIdAndArtifactId should allow the `newVersion` to be expressed as a semver selector.

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite#1751]
Good morning,

It would be very useful if in the "newVersion" field, as it already exists in other recipes, you could indicate an exact version, or node-style semver selector used to select the version number.

Thank you very much for the excellent support you provide

Thanks & regards

**Comment by tkvangorder** [comment]
This is a good idea, currently `newVersion` only allows an exact version. I agree we really should be supporting a semver selector.
