### ISSUE TITLE
`==` and `!=` should not be used when `equals` is overridden.`RSPEC-1698`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#1756]
Similar spec : https://rules.sonarsource.com/java/RSPEC-1698

**Comment by yeikel** [comment]
I think that this is the same as https://github.com/openrewrite/rewrite/pull/769/files

It just missing the tag? https://app.moderne.io/search?q=tags%3ARSPEC-1698

**Comment by pway99** [comment]
Hi @yeikel,  made a few fixes to the `StringLiteralEquality` recipe.

>One more thing that is not clear from the tests in that PR is if it covers streams as well

I added a streams example to the test

>It just missing the tag? https://app.moderne.io/search?q=tags%3ARSPEC-1698

Thats a good question, [RSPEC-1698](https://rules.sonarsource.com/java/RSPEC-1698) and [RSPEC-4973](https://rules.sonarsource.com/java/RSPEC-1698) are similar although RSPEC-4973 is specific to `String` types.

I am thinking we should add a new recipe for RSPEC-4973 which is more general than `StringLiteralEquality`
