### ISSUE TITLE
Recipe AddOrUpdateAnnotationAttribute. Don't overwrite if attribute exists.

### ISSUE THREAD

**Issue by dianamaesan** [openrewrite/rewrite#1760]
Hello,

I would recommend setting one more condition for this recipe, as sometimes you don't want to overwrite an attribute if it is already defined, what do you think?

Thanks in advance!

**Comment by pway99** [comment]
Thanks @dianamaesan, Adding an option to not update existing attributes is a good recommendation, I will add this to the backlog.

**Comment by pway99** [comment]
Fixed by https://github.com/openrewrite/rewrite/issues/1761
