### ISSUE TITLE
Yaml - DeleteProperty - if a property with mapping value is left with one entry, then it gets collapsed inappropriately

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#1769]
See test case below.

```kotlin
@Test
fun `DeleteProperty preserves original indent structure of existing hierarchy`() = rewriteRun(
    { spec -> spec.recipe(DeleteProperty("my.old.key", false, null, null)) },
    yaml(
        """
        my:
          old:
            key:
              color: blue
              style: retro
          other:
            key: qwe
    """.trimIndent(),
        """
        my:
          other:
            key: qwe
    """.trimIndent()
    ) /* Failure;
        Actual value:
        my:other:
            key: qwe
    */
)
```

Two quirks in the actual output:
* The `other` key gets folded into its parent line, but keeps the colon separator instead of a dot
* The keys underneath `other` keep their original indent, effectively creating a double-indent

They're a bit cosmetic, but if we're dealing with a Spring Boot `application.yml`, then the first quirk prevents Spring from recognizing the affected config, so it seems bug-worthy.

If the parent key (eg `my`) still has 2+ children after the delete, then all whitespace is preserved as expected.

**Comment by traceyyoshima** [comment]
Hi @nmck257, thanks for reporting the issue! I'll take a look as soon as I can
