### ISSUE TITLE
In specific circumstances TypeUtils.isOverride() can return a false-positive result

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#1782]
`TypeUtils.isOverride()` can return a false-positive `true` if a method declaration has these properties:

- Method is not an overload of any superclass or interface method
- Method is declared on a class which accepts type parameters
- Method arguments include at least one type parameter
- Method shares its name and number of arguments with a method that _is_ an overload

So if you have an interface or superclass like this:
```java
interface Interface <T, Y> {
        void foo(Y y, T t);
}
```
Then both "foo" methods on this class will be reported as an override by TypeUtils.isOverride(), when only one actually is:
```java
class Clazz implements Interface<Integer, String> {
    
    void foo(Integer t, String y) { }
    
    @Override
    void foo(String y, Integer t) { }
}
```

The `JavaType.Method` for either `foo()` knows that it has type parameters `T` and `Y` . But `JavaType.Parameterized` records only the _types_ of any type parameters, not the _names_ of those type parameters. So there's no way for TypeUtils.isOverride() to know for sure if the type parameter name `Y` is supposed to correspond to `String` or to `Integer`.
To fix this, we have to adjust the parser and our type mapping to include type parameter names on `JavaType.Class`. Ideally in a backwards-compatible way so old ASTs don't become un-loadable.
![image](https://user-images.githubusercontent.com/8549033/167948168-8703094d-b3de-48cb-937b-8d96ef2d25fe.png)

**Comment by traceyyoshima** [comment]
I don't see a simple solution and am hoping Sam has an idea that will work. [🙏](https://emojipedia.org/folded-hands/)
