### ISSUE TITLE
Remove a user's home directory as a valid place to discover Recipes, still allow Styles

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#18]
Recipes are currently called "profiles" until #13 is complete

We've decided that the user home is a valid place to store style information, like preferred import ordering, but defining any recipes/visitors there should not be allowed. 

At the time of writing this issue I'm not actually sure if we are actively checking a user's home directory for anything or if that was just the plan. If we don't currently actively check the home directory for recipes, then this issue can be closed for now and we'll revisit later when we have a somewhat more rigorous concept of what a "Style" is.

**Comment by jkschneider** [comment]
It is permitted now through [this method](https://github.com/openrewrite/rewrite/blob/master/rewrite-core/src/main/java/org/openrewrite/RefactorPlan.java#L108). I don't think we need to ban scanning recipes from user home, just that nobody would likely define them there. But there is a good reason for them to define styles there. So let the YAML parser read rewrite YAML files in `~/.rewrite ` as normal?
