### ISSUE TITLE
No way to determine the declaring type on type `J.FieldAccess`

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite#1813]
Currently, there's a way to determine the declaring type for `J.MethodInvocation` but there's no way to determine the declaring type for `J.FieldAccess`. The implications being, I can't determine if `File.separatorChar` is accessing the `separatorChar` on the field/variable `File` or if it's the field `separatorChar` on the class `java.io.File`.

This is an even bigger issue when `seperatorChar` is statically imported.

**Comment by traceyyoshima** [comment]
@JLLeitschuh would you add an example of what you're attempting to do?

I looked at `J.FieldAccess` and the `type` is available through the `target`. `File` should be a `J.Identifier` and the `type` should have a `fullyQualifiedName`.

Example:
```java
import java.io.File;
            
class Test {
    void method() {
        char s = File.separatorChar;
    }
}
```

```java
    public J.FieldAccess visitFieldAccess(J.FieldAccess fieldAccess, ExecutionContext p) {
        J.FieldAccess f = super.visitFieldAccess(fieldAccess, p);
        J parent = getCursor().dropParentUntil(is -> is instanceof J.ClassDeclaration || is instanceof J.CompilationUnit).getValue();
        if (parent instanceof J.ClassDeclaration) {
            JavaType.FullyQualified currentClass = TypeUtils.asFullyQualified(((J.ClassDeclaration) parent).getType());
            if (currentClass != null && !"java.io.File".equals(currentClass.getFullyQualifiedName())) {
                if (f.getTarget() instanceof J.Identifier) {
                    JavaType.FullyQualified type = TypeUtils.asFullyQualified(f.getTarget().getType());
                    if (type != null && "File".equals(((J.Identifier) f.getTarget()).getSimpleName()) &&
                            "separatorChar".equals(f.getName().getSimpleName())) {
                        String fqn = type.getFullyQualifiedName();
                        if ("java.io.File".equals(fqn)) {
                            // do something
                        }
                    }
                }
            }
        }
        return f;
    }
```

**Comment by pway99** [comment]
Thanks @traceyyoshima, @JLLeitschuh  and I had a good discussion on this one and have decided it's an unnecessary enhancement given that the declaring type for any J.FieldAccess can be determined by inspecting the target.
