### ISSUE TITLE
Handling java module-info files

### ISSUE THREAD

**Issue by georgeVasiliu** [openrewrite/rewrite#1895]
**Steps to recreate the scenario**:

- Create a minimal Spring Boot application from initiliazr that uses Java and Gradle Groovy for the build system and only contains the following single class. (ignore resources/app port or other configurations)

```
 @SpringBootApplication
public class ExampleApplication{
	public static void main(String[] args) {
		ExampleApplication.run(ExampleApplication.class, args);
	}

	@RestController
	static class BootController {
		@GetMapping("/")
		public ResponseEntity<String> askQuestion() {
			return ResponseEntity.ok("Hello! ");
		}
	}
}
```

- Configure the openrewrite plugin to activate the "org.openrewrite.java.format.AutoFormat" recipe in order to automate the formatting of the source code
```
rewrite {
    activeRecipe("org.openrewrite.java.format.AutoFormat")
}
```

- Create a module-info.java for the application that contains and exposes everything required by the application

```
module com.example.application{
	requires spring.boot;
	requires spring.boot.autoconfigure;
	requires spring.web;

	opens com.example.application to spring.core;
	
	exports com.example.application;
}
```

- Run the rewriteDryRun task and then you will see this output (slimmed down from the whole output to the relevant part):

```
Validating active recipes
Parsing sources from project com.example.app;ication
All sources parsed, running active recipes: org.openrewrite.java.format.AutoFormat
These recipes would make results to src/main/java/module-info.java:
    org.openrewrite.java.format.AutoFormat
```

- Run the rewriteRun task and you will see that the module-info.java has been emptied and the task output mentions the changes:

![image](https://user-images.githubusercontent.com/26601265/171563758-acb840f6-4255-4a28-9e56-3e3f0da33a90.png)

```
All sources parsed, running active recipes: org.openrewrite.java.format.AutoFormat
Changes have been made to src/main/java/module-info.java by:
    org.openrewrite.java.format.AutoFormat
```

**Question**: Is it possible to ignore the module-info.java file? By using the "exclusion" feature from the plugin, it does not work (I have tried all possible combinations until I realized the phrasing used for the "exclusion" feature (in which it mentioned it ignores NON-Java sources, whiles the module-info does end indeed in .java). I would love either to have the plugin do this automatically (I can look over the source code and maybe fork it and try a fix) or have some sort of parameter or be able to include in the "exclusion" also Java source files. If you need anymore info, please let me know.

**Note**:  The same seems to be true for package-info.java files.

**Comment by pway99** [comment]
Hello @georgeVasiliu,
As it turns out the latest release 4.25.2 adds support for exclusions, here is an example of excluding the module-info.java file.
```xml
<plugin>
	<groupId>org.openrewrite.maven</groupId>
	<artifactId>rewrite-maven-plugin</artifactId>
	<version>4.26.0-SNAPSHOT</version>
	<configuration>
		<activeRecipes>
			<recipe>org.openrewrite.java.format.AutoFormat</recipe>
		</activeRecipes>
		<exclusions>
			<exclusion>**/module-info.java</exclusion>
		</exclusions>
	</configuration>
</plugin>
```
There is an effort going on to update the Java 11+ Parsers with support module-info source files which will provide the ability to refactor them via rewrite recipes.

Again thanks for the detailed and informative issue and please accept my apology for overlooking your question on the possibility of excluding source files and offering to help.

**Comment by georgeVasiliu** [comment]
Hello @pway99,

Thank you very much! I was using the gradle-plugin, not the maven-plugin, but on the latest version the exclusion works for the module-info.java files. Glad to see it's working now, so thank you! 

Wish you good luck in your endeavours. You can close the issue in my opinion (I am not sure whether I should do it or not).

**Comment by pway99** [comment]
Thanks @georgeVasiliu, 
Glad to hear exclusions are working for you :)
How about we keep this one open while #1925 is in progress.

**Comment by timtebeek** [comment]
Turns out there's a `com.sun.tools.javac.code.Type.ModuleType` we are not yet using in our `TypeMapping`:
https://github.com/openrewrite/rewrite/blob/0fffdf6dff2525fc0dd4a19a412de65621fd5429/rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java#L48-L79

Might be relatively straightforward to support from there by updating the relevant parsers to handle this additional type.

/cc @knutwannheden & @OlegDokuka

**Comment by commonquail** [comment]
Here's another data point from

```sh
mvn org.openrewrite.maven:rewrite-maven-plugin:5.33.0:dryRun \
  -Drewrite.activeRecipes=org.openrewrite.java.RemoveUnusedImports
```

```diff
diff --git a/src/main/java/module-info.java b/src/main/java/module-info.java
index 89d943e..2cfefa6 100644
--- a/src/main/java/module-info.java
+++ b/src/main/java/module-info.java
@@ -1,4 +1,4 @@ org.openrewrite.config.CompositeRecipe
-import org.jspecify.annotations.NullMarked;
+
 
 @NullMarked
 module example {

diff --git a/src/test/java/module-info.java b/src/test/java/module-info.java
index c29301d..b900d2a 100644
--- a/src/test/java/module-info.java
+++ b/src/test/java/module-info.java
@@ -1,4 +1,4 @@ org.openrewrite.config.CompositeRecipe
-import org.jspecify.annotations.NullMarked;
+
 
 @NullMarked
 open module example.t {

```

**Comment by timtebeek** [comment]
Let's continue to track this in the more detailed discussion in the below issue, and close this older less detailed duplicate
 - #4054
