### ISSUE TITLE
Migrate from Apache Commons Lang to Commons Lang3

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite#1909]
Teams often are using `org.apache.commons.lang.StringUtils` instead of `org.apache.commons.lang3.StringUtils` so I would like a recipe that migrates to commons-lang3.

I see the recipe as:

* `org.apache.commons.lang` -> `org.apache.commons.lang3`
* If `commons-lang` is present in the pom file, remove it.
* If `commons-lang3` is *NOT* present in the pom and/or dependency tree add it.

**Comment by pway99** [comment]
Hi @rdifrango,  Thanks for the suggestion, similar issue [#106](https://github.com/openrewrite/rewrite-migrate-java/issues/106) exits.
I hope you don't mind me copying some of your info to that one and closing this one.
