### ISSUE TITLE
Recipe idea: remove annotations used before introduction of @Repeatable

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#1921]
This could be used to clean pre-java8 legacy code.

Example with Mapstruct `@ValueMappings`/`@ValueMapping`:
```java
   @ValueMappings({
        @ValueMapping(source = "UNKNOWN", target = MappingConstants.NULL),
        @ValueMapping(source = "UNRECOGNIZED", target = MappingConstants.NULL)
    })
    public abstract FooEnum toEnum(BarEnum bar);
```
could be simplified to: 
```java
   
    @ValueMapping(source = "UNKNOWN", target = MappingConstants.NULL),
    @ValueMapping(source = "UNRECOGNIZED", target = MappingConstants.NULL)
    public abstract FooEnum toEnum(BarEnum bar);
```

I don't know if a generic recipe could be done (by inspecting annotations that have `@Repeatable` annotation), or if this this should be a recipe that take both involved annotation as parameters.

**Comment by jkschneider** [comment]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1697736/181383362-e65002a9-1ea3-4e1d-9de4-b93c6183d67c.png">
