### ISSUE TITLE
API to create a new local-variable identifier that won't conflict with an existing scope

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite#1937]
I'd like an API to come up with a new local-variable identifier that won't conflict with an API in any higher/lower scope.

For example:

```java
class Test {
    void test(String base, String fileName) {
        String path = base + "/" + fileName;
        // does something with 'path'
    }
}
```

Let's say I want to add the following below the declaration of `path`: `File file = new File(path);`. I need an API that allows me to generate a new variable name that won't conflict with any lower scope and any method declaration scope.

For the first implementation, this **does not** need to work outside the scope of a method body.

Here are some examples of cases and what name might be generated:

1. Case 1
```java
class Test {
    void test(String base, String fileName) {
        String path = base + "/" + fileName;
        // does something with 'path'
    }
}
```

Would generate a variable named `file`.

2. Case 2
```java
class Test {
    void test(String base, String fileName) {
        String file = base + "/" + fileName;
        // does something with file
    }
}
```

Would generate a variable named `file1`.

2. Case 3
```java
class Test {
    void test(String base, String fileName) {
        String path = base + "/" + fileName;
        // Need to inject new file name here
        if (true) {
            String file = System.getenv("user.home") + "/" + path;
        }
    }
}
```

Would generate a variable named `file1`.

**Comment by traceyyoshima** [comment]
@JLLeitschuh I think recipes need to be responsible to generate new variable names to produce reliable results.

Primarily, because visitors may visit any AST element, and the root of the cursor is based on the visited element.
So, there might be identifiers in the name scope that aren't visible due to the cursor position.

We have an example of what you are asking for in `RenameExceptionInEmptyCatch`. [link](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenameExceptionInEmptyCatch.java#L123).

**Comment by JLLeitschuh** [comment]
You can theoretically look down the tree, and look up the tree can't you? Or are you concerned that up the tree may have been modified already by another visitor?

In that case, take the cursor, and the current AST element as an argument, and if the cursor value != the current AST element, thrown an illegal argument exception

**Comment by traceyyoshima** [comment]
It's not about modification.
Yes, the `recipe` may guarantee the tree may be traversed up and down, but a utility can't do that.

Example:
```java
public class Example extends Recipe {

    @Override
    public String getDisplayName() {
        return "";
    }

    @Override
    protected TreeVisitor<?, ExecutionContext> getVisitor() {
        return new JavaIsoVisitor<ExecutionContext>() {
            @Override
            public J.ClassDeclaration visitClassDeclaration(J.ClassDeclaration classDecl, ExecutionContext executionContext) {
                J.ClassDeclaration cd = super.visitClassDeclaration(classDecl, executionContext);
                // The cursor root will be `cd`
                cd = new ExampleVisitor().visitClassDeclaration(cd, executionContext);
                return cd;
            }

            @Override
            public J.VariableDeclarations visitVariableDeclarations(J.VariableDeclarations multiVariable, ExecutionContext executionContext) {
                J.VariableDeclarations mv = super.visitVariableDeclarations(multiVariable, executionContext);
                // The cursor root will be `mv`
                mv = new ExampleVisitor().visitVariableDeclarations(mv, executionContext);
                return mv;
            }
        };
    }

    private static class ExampleVisitor extends JavaIsoVisitor<ExecutionContext> {
        @Override
        public J.ClassDeclaration visitClassDeclaration(J.ClassDeclaration classDecl, ExecutionContext executionContext) {
            // Root of the cursor will be the `classDecl`.
            return classDecl;
        }

        @Override
        public J.VariableDeclarations visitVariableDeclarations(J.VariableDeclarations multiVariable, ExecutionContext executionContext) {
            // Root of the cursor will be the `multiVariable`.
            return multiVariable;
        }
    }
}
```

The `Cursor` root is based on the AST element that is visited, so we may look down from the root, but not up.

**Comment by JLLeitschuh** [comment]
That sounds like a bug in the following lines:
```java
cd = new ExampleVisitor().visitClassDeclaration(cd, executionContext);
```
```java
mv = new ExampleVisitor().visitVariableDeclarations(mv, executionContext);
```

They were called without passing the cursor correctly. They should have been called like this:
```java
cd = new ExampleVisitor().visitClassDeclaration(cd, executionContext, getCursor());
```
```java
mv = new ExampleVisitor().visitVariableDeclarations(mv, executionContext, getCursor());
```

I understand that you may not have used the API like this always, but I think that you should be able to safely assume that you will have the entire cursor tree, and if you don't blow up with a requisite exception. The tests should catch that you're not passing the correct cursor to the `visit....` call quickly.

**Comment by traceyyoshima** [comment]
I'll check in with the team tomorrow and get back to you afterward.
