### ISSUE TITLE
The method findSinks() in ForwardFlow.java can crash the program by dereferencing a null-pointer

### ISSUE THREAD

**Issue by topdonn** [openrewrite/rewrite#1939]
We have a vulnerability related to the findSinks() method. Please see details below

Category: Code Quality - Null Dereference
CWE: 476
Severity: High
Title:
Location: org/openrewrite/java/dataflow/analysis/ForwardFlow.java : 65
Summary: The method findSinks() in ForwardFlow.java can crash the program by dereferencing a null-pointer on line 65.The program can potentially dereference a null-pointer, thereby causing a null-pointer exception.
Explanation: Null-pointer exceptions usually occur when one or more of the programmer's assumptions is violated. A dereference-after-store error occurs when a program explicitly sets an object to null and dereferences it later. This error is often the result of a programmer initializing a variable to null when it is declared.

**Comment by tkvangorder** [comment]
@topdonn can you please try your use case again against the latest release? And if this is still an issue provide a stack trace and which version you are encountering the issue?

**Comment by tkvangorder** [comment]
@topdonn I am going to close this issue, there have been a lot of fixes around the control flow logic. Can you try using the latest release? 

Thanks for reporting
