### ISSUE TITLE
Search/Replace text within a `PlainText` source file

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#1967]
Add a search/replace recipe that can be used on generic text source files. This will be an easy task when files are parsed as `PlainText`, this may become more complicated if the search and replace should span to other source file types.

It can be potentially dangerous to do generic text search/replace without semantic awareness when doing these types of operations on Java, XML, YAML, etc.

**Comment by sambsnyd** [comment]
We have this now. And supports running on other text-based ASTs as of https://github.com/openrewrite/rewrite/commit/741d5b39b38b3a68fa5102bc72a3a0833bf1dda7 will be going out in 7.36.0
