### ISSUE TITLE
missing import for annotation param

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#1976]
Hi,

I want to import the given param for the annotation `@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)`

My visitor has to do the following action:

- Remove @Singleton: OK
- Add @Scope annotation with ConfigurableBeanFactory.SCOPE_SINGLETON param :OK but the import for `ConfigurableBeanFactory.SCOPE_SINGLETON` is missing

This is my visitor

```java
public class ReplaceAnnotationVisitor extends JavaIsoVisitor<ExecutionContext> {
    private final JavaTemplate componentAnnotationTemplate;


    private static final char at = '@';

    private static final String SINGLETON_ANNOTATION_TO_REMOVE_NAME = "javax.inject.Singleton";

    public ReplaceAnnotationVisitor() {
        componentAnnotationTemplate = JavaTemplate.builder(this::getCursor, at + "Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)")
                .imports("org.springframework.context.annotation.Scope", "org.springframework.beans.factory.config.ConfigurableBeanFactor").javaParser(() -> JavaParser.fromJavaVersion()
                        .dependsOn("package org.springframework.context.annotation; public @interface " + "Scope" + " {}",
                                "package org.springframework.beans.factory.config; public interface ConfigurableBeanFactory {}"
                                ).build()).build();
    }

    @Override
    public J.ClassDeclaration visitClassDeclaration(J.ClassDeclaration classDecl, ExecutionContext ctx) {
        J.ClassDeclaration cd = super.visitClassDeclaration(classDecl, ctx);


        Optional<J.Annotation> requiredAnnotation = getAnnotationToRemove(cd);
        if (requiredAnnotation.isPresent()) {

            maybeRemoveImport("javax.inject.Singleton");


            maybeAddImport("org.springframework.context.annotation.Scope");
            maybeAddImport("org.springframework.beans.factory.config.ConfigurableBeanFactory");


            //cd = (J.ClassDeclaration) new ChangeType(SINGLETON_ANNOTATION_TO_REMOVE_NAME, "org.springframework.context.annotation.Scope", false).getVisitor().impvisit(cd, ctx, getCursor());
            cd = (J.ClassDeclaration) new RemoveAnnotation(SINGLETON_ANNOTATION_TO_REMOVE_NAME).getVisitor().visit(cd, ctx, getCursor());

            cd = cd.withTemplate(componentAnnotationTemplate,
                    cd.getCoordinates().addAnnotation(Comparator.comparing(J.Annotation::getSimpleName)));

        }
        return cd;
    }


    private Optional<J.Annotation> getAnnotationToRemove(J.ClassDeclaration cd) {
        return FindAnnotations.find(cd, at + SINGLETON_ANNOTATION_TO_REMOVE_NAME).stream().findFirst();
    }
}
```

Before:
```java
import javax.inject.Singleton;

@Singleton
public class FakeSingleton {


    public void sayWhoAmI() {
        System.out.println("I am a Singleton");
    }
}
```

After (the import org.springframework.beans.factory.config.ConfigurableBeanFactory is missing):
```java
import org.springframework.context.annotation.Scope;

@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
public class FakeSingleton {


    public void sayWhoAmI() {
        System.out.println("I am a Singleton");
    }
}
```

**Comment by traceyyoshima** [comment]
Hi @jdelobel, just a friendly FYI - adding the language after ``` like ```java will add syntax to the snippets. :)

**Comment by jdelobel** [comment]
> Hi @jdelobel, just a friendly FYI - adding the language after `like`java will add syntax to the snippets. :)
> 
> `maybeAddImport` will check if the type is in use prior to adding the import. I suspect there is missing type information related to `org.springframework.beans.factory.config.ConfigurableBeanFactory`. I'd start by adding `SCOPE_SINGLETON` to the stub of `ConfigurableBeanFactory` in the template.

Hi @traceyyoshima. ok for the language snippets. I will add it for the next.

For my missing import I have to add explicitly this code:

````java
     AddImport<ExecutionContext> addSConfigurableBeanFactorImport = new AddImport<>(
                    "org.springframework.beans.factory.config.ConfigurableBeanFactory",
                    null,
                    false);
````

But i dont think its a good practice.

Thanks,

**Comment by traceyyoshima** [comment]
Hi @jdelobel,
> But i dont think its a good practice.

You're right 👍

Ideally, the import will be added with `maybeAddImport`, but the import is not added due to missing type information.

The code in `dependsOn` needs to be modified so that `@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)` is compilable.

The code snippet in the template contains:
```java
@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
```

Before:
```java
package org.springframework.context.annotation;
public @interface Scope {}
```
```java
package org.springframework.beans.factory.config;
public interface ConfigurableBeanFactory {}
```

After:
```java
package org.springframework.context.annotation;
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Scope {
    String value() default "";
}
```
```java
package org.springframework.beans.factory.config;
public interface ConfigurableBeanFactory {
    String SCOPE_SINGLETON = "singleton";
}
```

Hopefully, this helps, please reach out on [Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) if you have any questions!

**Comment by eddumelendez** [comment]
imports said `"org.springframework.beans.factory.config.ConfigurableBeanFactor"` instead of `"org.springframework.beans.factory.config.ConfigurableBeanFactory"`

**Comment by jdelobel** [comment]
> imports said `"org.springframework.beans.factory.config.ConfigurableBeanFactor"` instead of `"org.springframework.beans.factory.config.ConfigurableBeanFactory"`

Hi @eddumelendez,

Thanks its working! 

The problem was me with the copy/paste.

**Comment by jdelobel** [comment]
Hi,

Thanks to keep the issue open.

I try to use the Recipe org.openrewrite.maven.UpgradeDependencyVersion

``xml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.socgen.digital.spm.migrate.UpgradeJavaxServletApiVersion
recipeList:
  - org.openrewrite.maven.UpgradeDependencyVersion:
      groupId: javax.servlet
      artifactId: javax.servlet-api
      newVersion: 4.0.1
      overrideManagedVersion: true
``
But the version declared in the dependancies mangaement is not uploaded in the pom.xml. Its working for other dependancies. Do you have any idea please?

I have another question:

When i user org.openrewrite.maven.AddManagedDependency, I have to create a new root recipe for each one for it to work. Is it possible to add multiple dependancies in one root recipe?

I donèt have slack but i will create ASAP to join your community.

Thanks

**Comment by traceyyoshima** [comment]
> But the version declared in the dependancies mangaement is not uploaded in the pom.xml. Its working for others dependancies. Do you have any idea please?

The `com.socgen.digital.spm.migrate.UpgradeJavaxServletApiVersion` recipe looks valid.
Providing feedback without seeing the pom and/or the `XML` for the plugin configuration is challenging.
But I'd double-check the recipe is activated in the configuration.



> When i use the recipe `org.openrewrite.maven.AddManagedDependency`, I have to create a new root recipe for each one for it to work. Is it possible to add multiple dependancies in one root recipe?

Yes, you may define multiple recipes in the `recipeList` for example [here](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/resources/META-INF/rewrite/apache-commons-io.yml#L44)!

```
---
type: specs.openrewrite.org/v1beta/recipe
name: my.example.Recipe
recipeList:
  - org.openrewrite.maven.AddManagedDependency:
      ... params
  - org.foo.Recipe2
      ... params
  - org.foo.Recipe3
      ... params
```

Other References:

- [Java lang API migrations](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/resources/META-INF/rewrite/java-lang-apis.yml#L17).
- [SpringBoot 2 version upgrades](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/resources/META-INF/rewrite/spring-boot2-upgrade-version.yml#L19).



> I donèt have slack but i will create ASAP to join your community.

Sounds good, sometimes we lose track of comments in GitHub, but the team and community are very responsive in slack since it's easier to track. Looking forward to seeing you in Slack!

**Comment by traceyyoshima** [comment]
Hi @jdelobel, I plan to close this issue in a couple of days due to inactivity. Just making sure you're all set.

**Comment by tkvangorder** [comment]
I am going to close this issue if there are still outstanding items, please feel free to re-open
