### ISSUE TITLE
Fill in properties in Maven dependency <scope>

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#198]
We didn't anticipate that the scope of a dependency would be filled in based on Maven properties. But we have found an example of that being the case.

```
[DEBUG] Downloading parent POM com.desjardins.infra.n3:n3-dependances:3.4.0 with relativePath: null
[DEBUG] Downloading parent POM com.desjardins.infra.commun:infra-commun:2.1.1 with relativePath: null
[DEBUG] Downloading parent POM org.slf4j:slf4j-parent:1.7.6 with relativePath: null
[DEBUG] Downloading parent POM org.slf4j:slf4j-parent:1.7.6 with relativePath: null
[DEBUG] Downloading parent POM org.slf4j:slf4j-parent:1.7.6 with relativePath: null
[DEBUG] Downloading parent POM ch.qos.logback:logback-parent:1.1.1 with relativePath: null
[DEBUG] Downloading parent POM ch.qos.logback:logback-parent:1.1.1 with relativePath: null
[DEBUG] Downloading parent POM com.desjardins.infra.n3:n3-dependances:3.4.0 with relativePath: null
[DEBUG] Downloading parent POM com.desjardins.infra.commun:infra-commun:2.1.1 with relativePath: null
[WARNING] Unable to parse Maven AST
java.lang.IllegalArgumentException: unsupported scope '${spring.scope.dependencyManagement}'
```
This variable is either coming from the n3-dependances-spring pom that contains this:
                               <spring.scope.dependencyManagement>provided</spring.scope.dependencyManagement>

Or from the n3-dependances-spring-nosharedlib pom that contains this:
                               <spring.scope.dependencyManagement>compile</spring.scope.dependencyManagement>

**Comment by jkschneider** [comment]
Seems working now based on https://github.com/openrewrite/rewrite/blob/master/rewrite-maven/src/test/kotlin/org/openrewrite/maven/MavenParserTest.kt#L118
