### ISSUE TITLE
Recipe to remove dead repositories like  `maven.glassfish.org`

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite#2029]
As noted in this comment https://github.com/jenkinsci/core-annotation-processors/pull/3#issuecomment-1179304090 `maven.glassfish.org` no longer responds. Instead of upgrading it to HTTPS we should just remove it completely.

**Comment by tkvangorder** [comment]
It would be simple enough to create a recipe that will remove a repository and use recipe configuration to support glob expressions in the URL...and possible also allow a repo to be removed by ID.
