### ISSUE TITLE
Rewrite command not building jar/war in multimodule project

### ISSUE THREAD

**Issue by visakini** [openrewrite/rewrite#2044]
Hi we are able to build jar/war file in our multimodule project with normal maven commands (mvn clean install ).

But while using rewrite along with maven command the jar/war is not getting created for the modules(mvn clean install rewrite:dryRun).

Since there is dependency on the modules we were getting error.

Please advise how to run rewrite command in case of multimodule project.

Note:Added the plugin in the parent pom.xml

**Comment by tkvangorder** [comment]
@visakini  A few questions for you: 

- What version of the maven-rewrite-plugin are you using? 
- Are you running this from the top-level project or from a submodule? 
- What specific error are you encountering? Do you have a stack trace?

**Comment by visakini** [comment]
I am using 4.26.0 version.
I am running at the top level Project.
It doesnt show  any error but it says No sources to compile and the jar/war is not built

**Comment by tkvangorder** [comment]
Also, can you run with debug and `-e` ?

**Comment by visakini** [comment]
It is working if i use mvn rewrite:dryRunNoFork .
