### ISSUE TITLE
`rewrite-test` kotlin tests are no longer able to be compiled on Windows

### ISSUE THREAD

**Issue by shanman190** [openrewrite/rewrite#2070]
When using the backtick method names, these are transformed into subclass definitions. As a result, great care has to be taken to make sure that the method names remain OS-agnositic. At present, there are some in the `org.openrewrite.java.cleanup.RemoveMethodCallVisitorTest` that will need to be resolved to re-allow the project to be able to be compiled on Windows.

**Comment by jkschneider** [comment]
Fixed by #2068

**Comment by JLLeitschuh** [comment]
Sorry about that. That's my mistake
