### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by changgengli** [openrewrite/rewrite#21]
Is there any plan to add support to kotlin method usage search and refactor?

**Comment by jkschneider** [comment]
@changgengli Yes there is! To be honest, we plan to do Groovy first to quickly get Gradle remediation (because dependency updates are so important). But now that Kotlin has a new compiler AST, it is more approachable than it was a few years ago.

**Comment by sambsnyd** [comment]
Will be tracking adding kotlin support on our longer-term roadmap, here: https://github.com/openrewrite/rewrite-roadmap/issues/12

**Comment by sschuberth** [comment]
>  To be honest, we plan to do Groovy first to quickly get Gradle remediation

Who needs Groovy if you can do Kotlin DSL with Gradle? 😉

**Comment by timtebeek** [comment]
> Will be tracking adding kotlin support on our longer-term roadmap, here: https://github.com/openrewrite/rewrite-roadmap/issues/12

That link has either gone bad, or links to a non-public repository. Also could not find any [mention of Kotlin on the project board](https://github.com/orgs/openrewrite/projects/4/views/10?filterQuery=kotlin). Is there another place where progress is tracked? Just curious, no pressure. :)

**Comment by Sineaggi** [comment]
@sambsnyd Can we get this issue reopened? There is currently no kotlin support in rewrite, nor any public issue tracking it.

**Comment by siblznbitz** [comment]
Hey @Sineaggi , better late than never but this has shipped :)
