### ISSUE TITLE
Delete `TreePrinter`?

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#214]
Now that `JavaPrinter` is designed for extension, is there any need for the lifecycle methods made available by `TreePrinter`?

**Comment by gadams00** [comment]
TreePrinter provides useful segregation of concerns for components that wish to influence printing, and is also a nice way for rewrite-core components to influence printing in a consistent way that is equally applicable to all printers (SearchResult.PRINTER is a good example). Discussed with @jkschneider, closing this as "won't do" for now.
