### ISSUE TITLE
IllegalStateException thrown from UnneccessaryExplicitTypeArguments

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#2142]
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/1878529/184919109-6578c49d-227f-4a2b-9d78-5274d299f626.png">

**Comment by jkschneider** [comment]
Believe this will be fixed by a change made in af7ee39b1f2e5f1951894f40a68d38e74a5bebd6
