### ISSUE TITLE
org.openrewrite.maven.AddProperty: Take parent into account and add optional flag for overriding

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#2188]
Hi,

the recipe `org.openrewrite.maven.AddProperty` does not check if the property is set by a parent pom, in which case it should not be set in the module. A optional parameter like `trustParent` to override this behavior would be useful.

Thanks and kind regards
Thomas

**Comment by hetzijzo** [comment]
In my situation the value also gets set even if the value from the parent is (effectively) the same as the value that will be set by the `org.openrewrite.maven.AddProperty`

**Comment by jkschneider** [comment]
Good suggestion. In addition to the basic ask, also added `trustParent` to both `AddProperty` and `ChangePropertyValue`. Since `ChangePropertyValue` sometimes uses `AddProperty`, this also improves its behavior.
