### ISSUE TITLE
grpc dependency issue: "Illegal character in path"

### ISSUE THREAD

**Issue by ashakirin** [openrewrite/rewrite#2205]
Trying to parse [thingsboard](https://github.com/thingsboard/thingsboard) open source project produces exception: "Caused by: java.net.URISyntaxException: Illegal character in path at index 55: file:/Users/ashakirin/.m2/repository/io/grpc/grpc-core/[1.42.1]/grpc-core-[1.42.1].pom"

Test to reproduce the problem:
`    @Test
    public void testParser() {

        MavenParser
                .builder()
                .build()
                .parse(
                List.of(
                        Path.of("grpc-issue/pom.xml"),
                        Path.of("grpc-issue/application/pom.xml")
                        ),
                Path.of("grpc-issue"),
                new InMemoryExecutionContext())
                .forEach(p -> p.getMarkers().findFirst(MavenResolutionResult.class).get());
    }`

Simplified project structure is attached.
The project can be build with maven without any problems

**Comment by ashakirin** [comment]
[grpc-issue.zip](https://github.com/openrewrite/rewrite/files/9550191/grpc-issue.zip)

**Comment by tkvangorder** [comment]
Hi @ashakirin ,

Thanks for taking the time to put together an example, this was very helpful. This issue was fixed in rewrite 7.29.0 and I have confirmed this by running your example against the latest snapshot version 7.30.0-SNAPSHOT. I think this is just a matter of upgrading to the latest release.
