### ISSUE TITLE
Error in rewrite when a maven project includes checkstyle configuration

### ISSUE THREAD

**Issue by bmageshvec** [openrewrite/rewrite#2221]
Hi Team, We are facing  below issue we have customized checkstyle configuration for multi module maven project  we integrated the maven rewrite plugin and executed the rewrite:run goal its failing with below Error: 
NoWhitespaceBefore: "," is preceded with whitespace
We have also tried with fail never option -fn but still it fails for the customized rules
Any help is much appreciated
Maven rewrite plugin Version: 4.33.0
Error: 
NoWhitespaceBefore: "," is preceded with whitespace

**Comment by tkvangorder** [comment]
@bmageshvec do you have a Java stack trace that can be included with this issue?

**Comment by tkvangorder** [comment]
@bmageshvec I believe this error is being generated by Checkstyle's maven plugin rather than by OpenRewrite. Checkstyle is reporting a violation (in the source code) for one of the rules you have defined.
