### ISSUE TITLE
NewStringBuilderBufferWithCharArgument throws ClassCastException

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#2225]
### Problem
Issue discovered with `org.restlet/src/main/java/org/restlet/representation/AppendableRepresentation.java`
  
  ### Expected behavior
  > Describe what you expected to see.
  
  ### Example diff
  
  
  ```diff
   
     public Appendable append(char c) throws IOException {
         if (this.appendableText == null) {
-            this.appendableText = new StringBuilder(c);
+            this.appendableText = /*~~(java.lang.ClassCastException: class org.openrewrite.java.tree.J$Identifier cannot be cast to class org.openrewrite.java.tree.J$Literal (org.openrewrite.java.tree.J$Identifier and org.openrewrite.java.tree.J$Literal are in unnamed module of loader 'app')
+  org.openrewrite.java.cleanup.NewStringBuilderBufferWithCharArgument$2.lambda$visitNewClass$0(NewStringBuilderBufferWithCharArgument.java:76)
+  org.openrewrite.internal.ListUtils.mapFirst(ListUtils.java:102)
+  org.openrewrite.java.cleanup.NewStringBuilderBufferWithCharArgument$2.visitNewClass(NewStringBuilderBufferWithCharArgument.java:75)
+  org.openrewrite.java.cleanup.NewStringBuilderBufferWithCharArgument$2.visitNewClass(NewStringBuilderBufferWithCharArgument.java:67)
+  org.openrewrite.java.tree.J$NewClass.acceptJava(J.java:3954)
+  org.openrewrite.java.tree.J.accept(J.java:60)
+  org.openrewrite.TreeVisitor.visit(TreeVisitor.java:206)
+  org.openrewrite.TreeVisitor.visitAndCast(TreeVisitor.java:285)
+  ...)~~>*/new StringBuilder(c);
         } else {
             this.appendableText.append(c);
         }
  ```
  
  
  #### Recipes in example diff:
  - org.openrewrite.java.cleanup.NewStringBuilderBufferWithCharArgument
  
  ### References:
  - Recipe ID: `undefined`
  - Recipe Name: "Common static analysis issues"
  - Repository: restlet/restlet-framework/master
  - Created at Wed Sep 14 2022 09:49:22 GMT-0700 (Pacific Daylight Time)

**Comment by mccartney** [comment]
For anyone looking at the example, the current code of `AppendableRepresentation` seems already fixed. I guess the report pertains to old code before this commit: https://github.com/restlet/restlet-framework-java/commit/adcd73b819fb77b08f3c3dfc7d6a7dff07f244df#diff-3dc133cf9e147a7d3f72864e0e528998f9c913541b2f8e6cc31af699c746ff7aR125

**Comment by pway99** [comment]
Thanks @mccartney

**Comment by tkvangorder** [comment]
This was fixed with https://github.com/openrewrite/rewrite/commit/bc3339dd0d4fd650b0f19956f38ab34b83cbcdf5
