### ISSUE TITLE
Change XML Attribute accuracy

### ISSUE THREAD

**Issue by zieka** [openrewrite/rewrite#2228]
### Problem
 tried to change an `until` attribute on a `suppress` tag
  
  ### Expected behavior
got my new value repeated many times
  
  ### Example diff

new value:  `2022-10-01Z`

```diff
-    <suppress until= "2022-10-07Z">
+    <suppress until="2022-10-01Z22022-10-01Z02022-10-01Z22022-10-01Z22022-10-01Z-2022-10-01Z12022-10-01Z02022-10-01Z-2022-10-01Z02022-10-01Z72022-10-01ZZ2022-10-01Z">
```
    
new value:  `"2022-10-01Z"`
  ```diff
-    <suppress until= "2022-10-07Z">
+    <suppress until=""2022-10-01Z"2"2022-10-01Z"0"2022-10-01Z"2"2022-10-01Z"2"2022-10-01Z"-"2022-10-01Z"1"2022-10-01Z"0"2022-10-01Z"-"2022-10-01Z"0"2022-10-01Z"7"2022-10-01Z"Z"2022-10-01Z"">
  ```

  
  #### Recipes in example diff:
  - org.openrewrite.xml.ChangeTagAttribute
  
  ### References:
  - Recipe ID: `undefined`
  - Recipe Name: "Change XML Attribute"
  - Created at Wed Sep 14 2022 11:40:50 GMT-0700 (Pacific Daylight Time)

**Comment by mccartney** [comment]
I think this bug report requires a bit more attention in providing what exactly was the input. Otherwise it's hard to guess what has triggered the duplication of values in the output.

**Comment by traceyyoshima** [comment]
@mccartney is right, there isn't enough information to reproduce the problem.
Closing the issue
