### ISSUE TITLE
Wrong encoding for Java source files with ISO-8859-1

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#2230]
Hi,

we have a massive problem with source file encoding. A lot of projects are encoded in ISO-8859-1. It seems that the encoding is not determined by e.g. a maven property but derived with `org.openrewrite.internal.EncodingDetectingInputStream`. This leads to wrong file changes. See as a example the project:
https://github.com/thomaszub/rewrite-encoding-bug

I would suggest to derive the encoding from the build system like Maven's `project.build.sourceEncoding` and only use heuristics if no encoding can be derived.

Thanks and kind regards
Thomas

**Comment by pway99** [comment]
Hi @thomaszub,

Thanks for the demo project, I can appreciate the scale of this problem and was able to confirm that a JavaParser configured with the ISO-8859-1 charset correctly prints `Zurück`.  Looking at the [docs](https://maven.apache.org/plugins/maven-resources-plugin/examples/encoding.html), we may need to consider both sources and resources.

**Comment by thomaszub** [comment]
Hi @pway99,

I made a PR which extends `Parser`, `Parser.Input` and `EncodingDetectingInputStream` with the possibility to set a `Charset`. This works with the maven-plugin if changed accordingly (I can make a PR for the maven-plugin). As I'm not familiar enough with the gradle-plugin or the non-Java parsers I would currently consider this PR as incomplete.

**Comment by pway99** [comment]
Hi Thomas,
Thanks for the PR,  Check out the [JavaParser.Builder#charset](https://github.com/openrewrite/rewrite/blob/48b4aa829b349ffde18cc28e273343943bd75f62/rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java#L229) it might simplify things a bit.  I'm still unsure how to handle the `EncodingDetectingInputStream` when the charset is intentionally set, and I will be looking at this also.  Perhaps we can team up on this one.

**Comment by pway99** [comment]
Hi Thomas, I have put up a rewrite-maven [PR](https://github.com/openrewrite/rewrite-maven-plugin/pull/421/files) for setting the charset from mavens `sourceEncoding` property, and working on a rewrite-java solution that will use the maven-plugin charset when its specified.

**Comment by thomaszub** [comment]
Hi Patrick, if I correctly remind this is not enough as the `JavaParser` will not pass the encoding to the `Input` and `EncodingDetectingInputStream`. Maybe we should team up and look together at the code.

**Comment by thomaszub** [comment]
Fixed by #2249
