### ISSUE TITLE
Remove Javadocs parameters without a description

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2246]
I often see Javadocs like: 

```java

/**
     * @param a
     * @param b
     * @param b
     * @param c
     * @return
     * @throws c
     */

```

Where the javadoc simply list the parameters without any description. 

As this does not add any value to the code, I'd prefer to simply remove all of them in bulk

**Comment by mccartney** [comment]
Related to #2247 (working in opposite directions).
