### ISSUE TITLE
Update TreeVisitor lifecycle hooks, where visitEach -> preVisit, add postVisit

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#228]
In order to enable performing operations _post_-visiting an element during tree traversal, the TreeVisitor lifecycle hooks should be updated to include a `postVisit` operation before the visit element's `return`. Additionally, `visitEach` should be renamed to `preVisit` for clarity.

This enables visitors to inject a lifecycle hook for situations where we'd like to see any messages/results of elements in a `postVisit` after an element has made it's breadth-first traversal calls outward. This is conceptually similar to how `visitEach` (to be renamed to `preVisit`) works, except for "`post`"-visiting.

inspired from work associated w/ https://github.com/openrewrite/rewrite/pull/224

**Comment by aegershman** [comment]
Work laid out as per commit (https://github.com/openrewrite/rewrite/commit/e8f3f0b62130c1627f6ef471f0400b37a409671d), but will keep this open for just a smidge longer to let things "settle" before outright closing the issue, just to have it as a tracking

**Comment by jkschneider** [comment]
> Example being to do something like call maybeAutoFormat.

I think in this practical example, we'll be choosing to auto format based on a cursor message passed up from a descendent. So no need to determine this. Might need to add an overload for `autoFormat` that doesn't do the check?
