### ISSUE TITLE
`ReplaceDuplicateStringLiterals` is not making changes to source files it should

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#2312]
The design partner reported 20 examples where they feel the recipe should have replaced the same string literal. 

"The description of the recipe, I understand that if a string has 5 or more characters and is repeated 3 times or more, the recipe should create a final string."

**Comment by tkvangorder** [comment]
@traceyyoshima I saw this behavior on the tenant SaaS and this was not in a test class.

**Comment by traceyyoshima** [comment]
Closing the issue, because we confirmed the problem was not in the Recipe, but related to classloading else where.
