### ISSUE TITLE
org.openrewrite.java.ChangePackage emits wrong content when target package only has 1 segment

### ISSUE THREAD

**Issue by ericbottard** [openrewrite/rewrite#2328]
It seems the recipe omits the `package <x>;` directive when the target package to rename to (`x`) doesn't contain a dot.

This was working fine at least in 7.24.0, not sure exactly when the issue appeared.

**Comment by pway99** [comment]
Thanks for identifying this one @ericbottard,
 it looks like the bug was introduced by #1951 which was in the 7.24.2 release.
