### ISSUE TITLE
ResolvedDependency.isDirect() return true when dependency is in parent

### ISSUE THREAD

**Issue by luisrodval** [openrewrite/rewrite#2356]
Hi,
The public method in ResolvedDependency.java:
`    public boolean isDirect() {
        return depth == 0;
    }`
Return true when the dependency is in **parent pom** but it is not in **project pom**. 

I thinks that **depth** should be 1 instead of 0. This behaviour is correct?

Thank you.

**Comment by tkvangorder** [comment]
Hi @luisrodval , Any dependency defined in a parent pom will be merged into the effective model of the child pom. 

parent: 
```xml
<groupId>com.example</groupId>
<artifactId>parent</artifactId>
<version>1.0.0</version>
...
<dependencies>
  <dependency>
    <groupId>com.example</groupId>
    <artifactId>example-a</artifactId>
    <version>1.0.0</version>
  </dependency>
</dependencies>
  
```

child:
 
```xml
<parent>
 <groupId>com.example</groupId>
 <artifactId>child</artifactId>
 <version>1.0.0</version>
</parent>
<groupId>com.example</groupId>
<artifactId>parent</artifactId>
<version>1.0.0</version>
...
<dependencies>
  <dependency>
    <groupId>com.example</groupId>
    <artifactId>example-b</artifactId>
    <version>1.0.0</version>
  </dependency>
</dependencies>
```

effective dependencies of the child: 
```xml
<dependencies>
  <dependency>
    <groupId>com.example</groupId>
    <artifactId>example-a</artifactId>
    <version>1.0.0</version>
  </dependency>
  <dependency>
    <groupId>com.example</groupId>
    <artifactId>example-b</artifactId>
    <version>1.0.0</version>
  </dependency>
</dependencies>
```

Where both dependencies will be first-order dependencies of the pom. If there are additional grandparents, any dependencies in those will also be merged as first-order dependencies.

Is this consistent with your use case? If not, can you provide an example?

**Comment by tkvangorder** [comment]
I am going to go ahead and close this issue, if you are still experiencing issues, please feel free to reopen.
