### ISSUE TITLE
Category tree loses recipes in certain cases

### ISSUE THREAD

**Issue by kmccarp** [openrewrite/rewrite#2358]
steps to reproduce category tree loading issue:

1. load rewrite-testing-frameworks -&gt; total catalog count: 871 recipes
2. load rewrite-spring -&gt; total catalog count: 871 recipes
3. load rewrite-java -&gt; total catalog count: 475 recipes

[Slack Message](https://moderneinc.slack.com/archives/C01S4M53THT/p1666708475867559)

**Comment by tkvangorder** [comment]
This has been fixed
