### ISSUE TITLE
Serialization and invalid surrogate pairs

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite#2374]
J.Literal has a treatment to handle invalid utf-16 surrogate pairs, which Jackson does not support in string values. This treatment needs to be applied to Json.Literal, and every other Literal tree class.

**Comment by tkvangorder** [comment]
Closing as duplicate

**Comment by timtebeek** [comment]
Depending on what files tripped up this issue, https://github.com/openrewrite/rewrite/issues/2062 might be a better duplicate, in the case of Yaml. Linked here in case anyone else stumbles across this issue.
