### ISSUE TITLE
org.openrewrite.java.cleanup.Cleanup rewrites build.gradle into invalid state 

### ISSUE THREAD

**Issue by mattthebig** [openrewrite/rewrite#2385]
As discussed in Discord two days ago with pway PFA a demo gradle build file that corrupts itself when invoking ./gradlew rewriteRun 
[build.gradle.demo.txt](https://github.com/openrewrite/rewrite/files/9934809/build.gradle.demo.txt)
This file shows the corruption in two places in the file - the string containing newlines has been broken (the same occurs with escaped double quotes I believe) and the * in the encoding setting is has duplicate text and question marks added.
[build.gradle.corrupt.txt](https://github.com/openrewrite/rewrite/files/9934814/build.gradle.corrupt.txt)

**Comment by pway99** [comment]
Thanks @mattthebig

**Comment by tkvangorder** [comment]
This has likely been fixed, can you please try this with the latest release?

**Comment by mattthebig** [comment]
Nope not even slightly fixed - still rewrites unwanted files - still breaks build.gradle
I'd focus on just getting the files to work on correct - the groovy parser is probably hard to fix but theres no way it should be being called at all from a java cleanup.
