### ISSUE TITLE
Java 15+ Replace String Format by Formatted

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2390]
See : https://jsparrow.github.io/rules/replace-string-format-by-formatted.html#description

```java

String output = String.format("Name: %s, Phone: %s, Address: %s, Salary: $%.2f", name, phone, address, salary);


```

```java

String output = "Name: %s, Phone: %s, Address: %s, Salary: $%.2f" .formatted(name, phone, address, salary);


```

Related but seems different: https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/cleanup/FixStringFormatExpressions.java

**Comment by timtebeek** [comment]
This was [implemented in a different module](https://github.com/openrewrite/rewrite-migrate-java/blob/main/src/main/java/org/openrewrite/java/migrate/lang/StringFormatted.java), as a particular version of Java is required.

**Comment by yeikel** [comment]
That's strange. I could not find it while searching. Github search is clearly not great :( 

As a side note, the recipe requires Java 17, but Java 15 should be enough
