### ISSUE TITLE
`stream().forEach()` can be replaced with `forEach()` (may change semantics) 

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2393]
I am not sure if we have a recipe for this. If we do, apologies in advance (and feel free to close it)

```java

List<String> elements = List.of("a","b","C");

Set<String> elementsSet= Set.of("a","b","C");


elements.stream().forEach(System.out::println);

elementsSet.stream().forEach(System.out::println);

```

```java

elements.forEach(System.out::println);
```

**Comment by yeikel** [comment]
Considering some of the considerations: https://stackoverflow.com/questions/23218874/what-is-difference-between-collection-stream-foreach-and-collection-foreach

And our motto, this can be potentially dangerous if implemented incorrectly

**Comment by timtebeek** [comment]
From reading the link it seems there's likely no guaranteed safe way to implement this recipe, so best then to close the issue.
