### ISSUE TITLE
AddOrUpdateAnnotationAttribute must indicate if another cycle is needed

### ISSUE THREAD

**Issue by bottemav** [openrewrite/rewrite#2415]
If AddOrUpdateAnnotationAttribute is applied to a annotation with only a value, then it needs another cycle to add the wanted attribute.

See the existing test `AddOrUpdateAnnotationAttributeTest.implicitValueToExplicitValue` where `AddOrUpdateAnnotationAttribute("org.junit.Test", "other", "1", null)` is executed

Before
```
import org.junit.Test;

class SomeTestClass {

    @Test("foo")
    void foo() {
    }
}
```
After the first cycle, the annotation is changed to:
```
import org.junit.Test;

class SomeTestClass {

    @Test(value = "foo")
    void foo() {
    }
}
``` 

In order to add the attribute "other", we need to run another cycle, but that is not done automatically. We explicitly need to indicate that at least 2 cycles are needed to get the desired result.
It would be helpful if AddOrUpdateAnnotationAttribute can indicate automatically that another cycle is needed or deliver the expected result after the first cycle.

This issue causes https://github.com/spring-projects-experimental/spring-boot-migrator/issues/528

**Comment by pway99** [comment]
@bottemav @fabapp2 looks like you resolved this issue in the spring-boot-migrator.  Closing this issue given that rewrite recipe execution is designed to continue processing until either no changes are detected, or the max number of cycles is exceeded.
