### ISSUE TITLE
Maven - Improve capabilities for scenario where an upgraded parent stops managing a given dependency's version

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#2418]
Consider a Maven project using some parent project for transitive dependency management. Suppose that the project has one or more dependencies declared without versions (ie relying on dependency management). Then, suppose that we use `UpgradeParentVersion` to move to a newer version of the parent project which **no longer provides dependency management** for one of those dependencies.

Sample test case:
```kotlin
@Test
fun foo() = rewriteRun(
    { spec -> spec.recipe(UpgradeParentVersion("org.springframework.cloud", "spring-cloud-config-dependencies", "3.1.4", null)) },
    pomXml("""
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
          <modelVersion>4.0.0</modelVersion>
          <groupId>org.sample</groupId>
          <artifactId>sample</artifactId>
          <version>1.0.0</version>
          
          <parent>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-config-dependencies</artifactId>
            <version>3.1.2</version>
          </parent>
          
          <dependencies>
            <dependency>
              <groupId>com.jcraft</groupId>
              <artifactId>jsch</artifactId>
            </dependency>
          </dependencies>
        </project>
    """.trimIndent())
)
```

This yields:

```
java.lang.AssertionError: Failed to parse sources or run recipe
[...]
Caused by: org.openrewrite.RecipeRunException: org.openrewrite.maven.internal.MavenParsingException: No version provided for dependency com.jcraft:jsch
[...]
```

Or, if you encounter this behavior as one sub-recipe in a full recipe execution, then you might get a log like this, but recipe execution continues:
```
[WARNING] org.openrewrite.maven.internal.MavenParsingException: No version provided for dependency com.jcraft:jsch
```

In isolation, this behavior feels reasonable. But as part of a larger recipe, this behavior starts to cause pain.

A user might respond to this message by adding an explicit version to the relevant dependency in their pom.xml. However, this gives the same result (you can verify by adapting the test case above), because `ChangeParentVersion` calls `RemoveRedundantDependencyVersions` both before and after `UpdateMavenModel`. The explicit version in the pom will be removed before applying the new parent version, and applying the new parent version will fail in UpdateMavenModel because there is no (explicit) version. The user does not have any (obvious) solution to update their pom.xml such that the recipe can succeed.

I see a few solution options to **help avoid OpenRewrite creating a project with missing versions**:
1. Remove the invocation `RemoveRedundantDependencyVersions` prior to `UpdateMavenModel` in `ChangeParentVersion`. This lets recipe authors use `ChangeDependencyGroupIdAndArtifactId` with `overrideManagedVersion=true` prior to `ChangeParentVersion` for any known dependencies which will lose dependency management in the new version, but, without this invocation of `RemoveRedundantDependencyVersions`, projects with many redundant versions will be more likely to keep stale, pinned versions
2. Add logic to `UpdateMavenModel` to "recover" from these exceptions globally by identifying the old maven model's managed version and adding it as an explicit version to the pom.xml. This is robust, but complex, and, may not be the right choice in every case (eg the parent project's maintainers may have stopped managing a given dependency for good reason, and "smoothing over" the removal may not be desirable)
3. Add a config option like `restoreDependencyVersions` to `UpgradeParentVersion`, which allows recipe authors to declare any GAVs which are known to lose dependency management with the new parent version. Then, the `ChangeParentVersion` implementation can inject these provided versions after the first `RemoveRedundantDependencyVersions` but before `UpdateMavenModel`. This provides recipe authors a direct opt-in solution for this scenario. But, dependencies which unexpectedly lose dependency management will still trigger the old behavior, which the user would still not have a clear solution to

Personally, I'm leaning towards option 3 above.

Meanwhile, there are also options for **what OpenRewrite should do when it does encounter a missing version**:
1. (Current behavior) fail the individual recipe and keep going. If this exception occurs during `UpdateMavenModel` as a post-visit for some recipe, then the exception is caught and logged in the `RecipeScheduler`, and execution continues with the next recipe using the same `before` sourcefiles (changes from the problematic recipe are discarded)
2. Fail and halt. Do not run any additional recipes, and either discard or apply the changes made thus far
3. Keep the changes from the problematic recipe and keep going (ie, accept the incomplete Maven model)
4. Find a new version somehow (ie the above solutions)

We could also consider implementing those options as different configurable "modes" for recipe execution (eg strict mode)

In my opinion, the current behavior might be a bad compromise between "fail and halt" and "keep the changes and keep going". We kinda fail fast, and we avoid running recipes with invalid inputs in the form of a bad maven model, but, we still run recipes with invalid inputs in the sense that the changes from the previous recipe in the list are not present. If we're running a recipe like `UpgradeSpringBoot`, and the `recipeList` is ordered intentionally by the recipe author, then essentially skipping a subrecipe and proceeding with the next can lead to unexpected behaviors. I think either option 2 or 3 would be better than 1, and I'd love to get more opinions on option 3.

There's also room to improve the log messaging, as the current message does not convey the consequences of the exception. Example:

```
(current) [WARNING] org.openrewrite.maven.internal.MavenParsingException: No version provided for dependency com.jcraft:jsch
(proposed) [WARNING] org.openrewrite.RecipeExecutionException: Discarding changes from recipe UpgradeParentVersion{args args args}. Nested exception is org.openrewrite.maven.internal.MavenParsingException: No version provided for dependency com.jcraft:jsch
```

**Comment by nmck257** [comment]
recapping side chat w/ @jkschneider 

We're picturing a solution option 4, which blends options 2 and 3: we add the logic to `ChangeParentVersion` to "recover" from newly-unmanaged dependencies, but use the old `MavenResolutionResult` as the source of versions instead of an explicitly-configured list. This gives us global recovery, but it's implemented on `ChangeParentVersion` instead of `UpdateMavenModel`.

We also considered adding an option to `ChangeParentPom` to select between 1) add error markers or 2) fix the versions automatically in this scenario.

So, broadly, we're pretty settled on the mechanics of the solution (logic in ChangeParentVersion), but still deciding on how we should control the scope of dependencies which the solution would run against (eg what recipe option(s) to add). For that, we're mainly thinking about the desired/typical experience for running framework version update recipes at scale for a large enterprise.

(and we agree that error reporting for scenarios like this could be improved)

**Comment by albertocavalcante** [comment]
Thanks for the detailed explanation @nmck257 ! It sounded very clear even not being familiar with OpenRewrite mechanics.

> We could also consider implementing those options as different configurable "modes" for recipe execution (eg strict mode)

I do like this idea and think it could be left either to the recipe developer or the end user opt-in for a "fail and halt" behavior by specifying some argument/flag in the plugin configuration (maven/gradle). 

> There's also room to improve the log messaging, as the current message does not convey the consequences of the exception.

In the meantime, while a strategic solution combining approaches 2 and 3 is being thought, having this implemented upfront would be a significant quick win and allow end users to fully understand what's happening and perhaps make a manual intervention as a tactical workaround for now. 
Having the log level as a WARNING also led to the conclusion of simply ignore it, shouldn't it be catch as an ERROR but safely continue? 
While I think the proposed message is clear and achieves the goal, I would like to hear your thoughts about prefixing the log message with the recipe name instead, personally if feels more natural to read, but not sure if it's feasible technically or other considerations that may emerge such as truncate the recipe name if the length is too long, Idk:

```java
[ERROR] org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_7: Cannot apply recipe. Reason: org.openrewrite.maven.internal.MavenParsingException: No version provided for dependency com.jcraft:jsch
...
```

**Comment by nmck257** [comment]
@albertocavalcante - putting the recipe name upfront on the log message does feel intuitive, though it's worth noting that in many cases, the failing recipe would be some nested subrecipe with a name which might be unfamiliar or unexpected to the user.

For example, the user might have requested to run `org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_7`, but the failing recipe might be `org.openrewrite.maven.UpgradeDependencyVersion` -- and because the "parent" recipe may call the `UpgradeDependencyVersion` recipe many times with different arguments, it's useful to include those arguments (eg `GAV = org.mockito:mockito:1.2.3`)

**Comment by nmck257** [comment]
Closed with https://github.com/openrewrite/rewrite/commit/e461dcf4f466a6d74af7ae6ec85181b9835453c5
