### ISSUE TITLE
CommonStaticAnalysis renames method incorrectly

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#2424]
Given the input:
```java
                class Test {
                    public String getFoo_bar() {
                        return "foobar";
                    }
                }
```

the method `getFoo_bar()` should be renamed to `getFooBar()`, but instead it is renamed to `getfooBar()`

I'm also a bit surprised to see a `public` method being renamed. Looking over common static analysis it looks like only private methods and fields should be renamed. Worth double-checking whether that is intentional.

**Comment by pway99** [comment]
I am fixing the recipe to rename `getFoo_bar()` -> `getFooBar()` is a simple fix.

Sonar rule [RSPEC-100](https://rules.sonarsource.com/java/RSPEC-100) does not exclude public methods from the method name casing check.  

Given the risk of renaming public methods, I will add a `renamePublicMethods` option to the recipe.  This will allow the recipe to remain a member of `common-static-analysis` while providing users with an opportunity to rename `public` methods as a separate task.
