### ISSUE TITLE
Recipes which alter method signatures should attempt to update JavaDoc as well

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#2425]
Recipes which alter method signatures should try to update their JavaDoc comments accordingly. The primary text of the comment, being unstructured natural language, limits what we can confidently achieve programmatically. But with JavaDoc elements like `@link` and `@param` we can do a bit more

A non-exhaustive list of recipes this may be applicable to:

- `ChangeMethodName` - References to property referenced by bean-style getter/setter may be renamed. Other JavaDoc comments with `@link` could potentially be renamed, but that is more expensive
- `ReorderMethodArguments` - Order of `@param`
- `DeleteMethodArgument` - low priority, don't know that anything uses this recipe

**Comment by tkvangorder** [comment]
Closing this issue, Sam said that we addressed some of the issues outlined here.
