### ISSUE TITLE
Bug in ChangePackage: a static import of an enum value in the same package disappears, causing a compilation error

### ISSUE THREAD

**Issue by ge0ffrey** [openrewrite/rewrite#2439]
Given
```
            package foo;
            public enum EnumA {
                A1,
                A2
            }
```
```
            package foo;
            import static foo.EnumA.A1;
            import static foo.EnumA.A2;
            public class App {...}
```

with a change package of `foo` to `bar`, the first part is ok:

```
            package bar;
            public enum EnumA {
                A1,
                A2
            }
```

but the second part ends up like this:

**Actual**:

```
            package bar;
            public class App {...}
```
Notice how the import statics of the enum disappeared, causing compilation errors later on.

**Expected**:
```
            package bar;
            import static bar.EnumA.A1;
            import static bar.EnumA.A2;
            public class App {...}
```

**Comment by traceyyoshima** [comment]
Hi @ge0ffrey, thanks for reporting the issue!

I took a look at https://github.com/openrewrite/rewrite/pull/2438/files and found the tests require a few changes:
the package for `EnumB` should be updated to `enumb` in the before, after, and afterConditions.

The test passed after making the changes.

Would you mind sharing the code that exists in `public class App {...}` or is it the same code from the example?

**Comment by traceyyoshima** [comment]
Closing the issue per discussion on https://github.com/openrewrite/rewrite/pull/2438. The issue appears to be fixed on the main branch.

**Comment by ge0ffrey** [comment]
I found the extra condition to reproduce: the statically important enums must be in the same package.
I'll create a new PR and a new issue for clarity.

**Comment by ge0ffrey** [comment]
@traceyyoshima Here's a clear, reproducer PR that fails as excepted: https://github.com/openrewrite/rewrite/pull/2470
