### ISSUE TITLE
WrappingAndBracesStyle$IfStatement NPE

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#2463]
![image](https://user-images.githubusercontent.com/22326988/204592949-09ea77a5-afdb-49b6-a5fd-42ba27c7ef5f.png)

**Comment by traceyyoshima** [comment]
@pway99 I don't see enough information on the screenshot. It may have been an old AST and the new `IfStatement.` I covered the possibility with this commit: https://github.com/openrewrite/rewrite/commit/357c49247d8a6de0a40ae80c35bc56b1ad34c642.

Can you confirm?

**Comment by pway99** [comment]
@traceyyoshima this was reported by a user, I do not have any additional information.

**Comment by traceyyoshima** [comment]
Closing the issue, this was confirmed to be fixed by https://github.com/openrewrite/rewrite/commit/357c49247d8a6de0a40ae80c35bc56b1ad34c642
