### ISSUE TITLE
PropertyParser does not correctly handle line continuations and whitespace

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#2471]
The Property file format allows for line continuations at any point by suffixes the end of a line with a `\`.  On the next line, any leading whitespace is ignored. 

```
fred=123, \
         567
```

Is equivalent to:
fred=123, 567

To make things more fun, you can put continuations at any point in the file.

```
fr\
ed=123, 567
```

Not that any sane person would do such a thing...but it is allowed

**Comment by traceyyoshima** [comment]
fixed by [5726b59](https://github.com/openrewrite/rewrite/commit/5726b59c9368969743454dfa8cfec2d119588a77)

**Comment by tkvangorder** [comment]
The initial fix is better, but we are going to lose all continuations (and whitespace) when attempting to print out the properties file.

**Comment by tkvangorder** [comment]
Closing this, as the additional work will be covered by #2473
