### ISSUE TITLE
Add support for continuations in properties.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#2473]
```kotlin
    @Suppress("WrongPropertyKeyValueDelimiter", "TrailingSpacesInProperty")
    @Issue("https://github.com/openrewrite/rewrite/issues/2473")
    @Test
    fun escapedNewLines() {
        val source = """
                \
                
                k\
                 e\
                
                  y \
                   = \
                
                    v\
                
                     al\
                      ue\
                       
            """.trimIndent()
        val props = PropertiesParser().parse(source)[0] as Properties.File

        assertThat(props.content.map { it as Properties.Entry }.map { it.key })
            .hasSize(1)
            .containsExactly("key")
        assertThat(props.content.map { it as Properties.Entry }.map { it.value.text })
            .hasSize(1)
            .containsExactly("value")

        val outputCapture = PrintOutputCapture(InMemoryExecutionContext())
        val printer = PropertiesPrinter<InMemoryExecutionContext>()
        printer.visitFile(props, outputCapture)
        assertThat(outputCapture.out.toString()).isEqualTo(source)
    }
```

**Comment by traceyyoshima** [comment]
Unassigning myself until this is a higher priority.
I've opened a branch with most of the necessary changes [here](https://github.com/openrewrite/rewrite/tree/preserve_source_code_of_properties_with_continuations) and plan to come back to this work later.

The remaining changes are fairly simple to add, but this isn't high-priority work yet.

TODOs:
- Read through the Properties documentation and apply all the parsing rules.
    - I.E. treat all spaces as a delimiter between a key and value.
- Add support for comments in the whitespace of continued lines.
- Add support for comments delimited by `!` character.
- Add with(X) in Entry to update continuations automatically.
- Update the continuation models to support key, `beforeEquals`, and value.
- Add printing for search markers for continuations for `beforeSyntax`.

**Comment by tkvangorder** [comment]
![image](https://user-images.githubusercontent.com/1878529/205137906-74bd7010-9ccf-46d0-89ac-660f2fb96838.png)

**Comment by gsmet** [comment]
@traceyyoshima hey. I just stumbled upon this issue after having opened https://github.com/openrewrite/rewrite/issues/2960 .

I see you have done some work related to that in a branch and from what I can see it looks like excellent progress. I wonder if we could at least get the first bits in, even if there is some later polishing remaining for corner cases after that.

I understand it looks like a not so critical issue but preserving the original formatting is IMHO one of the strength of OpenRewrite and I'm a bit reluctant pushing update rules that will change the user files in some unexpected way.

**Comment by kbrockhoff** [comment]
Would you accept additions to the PR to get this over the finish line? The Rewrite Maven plugin fails a property change where the key value pair are correct but the formatting has changed (continuation lines merged into one). This is cause headaches for us.

**Comment by traceyyoshima** [comment]
Hi @gsmet @kbrockhoff! I'm sorry it's taken so long for us to fix this issue. I've started working on a solution and should have something done soon!
