### ISSUE TITLE
Maven AddDependency adds dependencies that are transitive already

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#2476]
While upgrading **spring-petclinic** app (available here: https://github.com/spring-projects/spring-petclinic) we've noticed that a few dependencies are added to the pom but are coming from transitive dependencies anyway.

Lets have a look at **jakarta.persistence-api**. M2E shows dependency hierarchy for this dependency as follows:
![Screenshot 2022-11-30 at 19 18 42](https://user-images.githubusercontent.com/6433390/204935809-7ecda102-c830-48e7-b2cb-e75a1ef4d9a7.png)
In other words spring-data-jpa starter -> hiberbate-core -> persistence-api. All are *compile* scope dependencies. Removing the added persistence-api direct dependency doesn't have any effect. The code still compiles fine because available via *compile* scope transitive dependency I think. The culprit for the dependency to be added is: https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java#L202 Thus, all transitive dependencies are added.

Lets consider **jakarta.xml.bind-api**. M2E shows dependency hierarchy for this dependency as follows:
![Screenshot 2022-11-30 at 19 26 38](https://user-images.githubusercontent.com/6433390/204936662-6d24df33-87bf-414a-b216-132b18d5a1f6.png)
Besides *compile* scope dependency at the root level it only comes as *runtime* or *test* scope transitive dependency and probably this is the reason for this direct dependency to be necessary.

Now if I lift the restriction of checking direct dependencies only in `AddDependency` recipe class then **jakarta.persistence-api** direct dependency is not added because available via transitive dependency on *compile* scope. However, **jakarta.xml.bind-api** is not added either while it should be. It is not added because `getResolutionResult().getDependencies().get(Scope.Compile)` call includes **jakarta.xml.bind-api** while it seems to me that it should not be in the list of transitive dependencies on `compile` scope as it is a non-direct *runtime* and/or *test* scope dependency.

I have noticed that there is a test https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java#L579 pointing at issue #1443. I'd say that jackson-core dependency isn't needed in this case... seems like this is either similar or the same as **jakarta.persistence-api** case where we would not add the dependency.

Curious what your thoughts are on this.

**Comment by timtebeek** [comment]
I'm going to close this issue given the amount of changes to the underlying recipes since this was opened, assuming this is no longer an issue.
