### ISSUE TITLE
Result of JavaTemplate inserting statements in `before` coordinates of first method decl statement fails to render

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#251]
borne out of https://github.com/openrewrite/rewrite/pull/244 specifically https://github.com/openrewrite/rewrite/pull/244#discussion_r573141959

We should be able to use the following template in `CovariantEquals` inserted _before_ the first `Statement` of a `MethodDeclaration` using Coordinates, e.g.

```java

                "if (#{} == this) return true;\n" +
                "if (#{} == null || getClass() != #{}.getClass()) return false;\n" +
                "#{} #{} = (#{}) #{};"
```

with the insertion point being `m.getbody().getStatements().get(0).getCoordinates().before()`

However the resultant template is not inserted back into the method body, e.g.

```txt
----Template After Substitutions----
if (obj == this) return true;
if (obj == null || getClass() != obj.getClass()) return false;
A other = (A) obj;
------Generated Synthetic Class-----
class A {
    String id;
    @SuppressWarnings("all")
    public boolean equals(A other) {
    }
}
```

>After adding that, you can see the template is correctly populated with parameters...but not being inserted into the synthetic class.

**Comment by tkvangorder** [comment]
This issue is fixed with this commit : 19b99faaa5a0055375cc563a659e5c2b044e79e8
