### ISSUE TITLE
Error during recipe run: The contents of a quark are unknown, so the charset is unknown.

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#2513]
Hi,
I have this error with the following versions:

OPEN_REWRITE_MAVEN_PLUGIN_VERSION="4.36.0"
OPEN_REWRITE_JAVA_VERSION="1.15.0"
OPEN_REWRITE_TESTING_VERSION="1.32.0"

17:06:30,764 [INFO] org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
17:06:30,765 [ERROR] org.apache.maven.cli.MavenCli - Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.36.0:run (default-cli) on project wsserver: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.36.0:run failed: The contents of a quark are unknown, so the charset is unknown. -> [Help 1]
17:06:30,765 [ERROR] org.apache.maven.cli.MavenCli - 

FYI, 

- I dont use Quarkus into my project
- No problem with OPEN_REWRITE_JAVA_VERSION="1.13.0"

**Comment by traceyyoshima** [comment]
Hi @jdelobel, thank you for reporting the issue! We'll take a look.

So that you know, a `Quark` ([link](https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/main/java/org/openrewrite/quark/Quark.java)) is a type of unidentified source file.

**Comment by jdelobel** [comment]
[](url)

> Hi @jdelobel, thank you for reporting the issue! We'll take a look.
> 
> So that you know, a `Quark` ([link](https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/main/java/org/openrewrite/quark/Quark.java)) is a type of unidentified source file.

OK thanks for this information. Now i know what is a Quark :)

Waiting your response

**Comment by traceyyoshima** [comment]
> OK thanks for this information. Now i know what is a Quark :)
You're welcome :)

Generally, I'd agree, but I think it depends on how the error occurred. I don't expect a Quark to be visited by the standard visitors. So, it may be worth investigating.

Would you mind sharing which recipe was run and any information possible on what file caused the issue?

**Comment by traceyyoshima** [comment]
Hi @jdelobel, I plan to close this due to inactivity. The error implies a file is visited unexpectedly, which I suspect is related to using `visit`. Are you still encountering this issue?

**Comment by jdelobel** [comment]
> any information possible on what file caused the issue?

Hi @traceyyoshima ,

I thinks its one of my custom visitor but i dont have this problem with OPEN_REWRITE_JAVA_VERSION="1.13.0" its works fine. So i think its regression. 

When i have a time I will try to execute my visitor one by one

**Comment by jdelobel** [comment]
Hi @traceyyoshima ,

I don't already have this problem with 1.14.0. Its good for me!

**Comment by okundzich** [comment]
Thanks for letting us know!
