### ISSUE TITLE
Recipe to remove a Maven profile?

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#2514]
Is there any recipe to remove a maven profile? if not can you share me an example please?

**Comment by tkvangorder** [comment]
@jdelobel This will be very easy to implement, do you want to give it a shot?

1) You could implement a recipe that returns a MavenVisitor from it's `getVisitor()` method.

2) In that recipe/visitor define an XPath matcher for finding a tag that represents a profile: 

 `static final XPathMatcher PROFILE_MATCHER = new XPathMatcher("/project/profiles/profile");`

3) Override `visitTag()` in your visitor

```
     public Xml visitTag(Xml.Tag tag, P p) {
        t = super.visitTag(tag, p);
        if (PROFILE_MATCHER.matches(getCursor()) {
          //you can then make a decision to remove the profile by looking at the child content of the tag.

          //Use tag.getChildValue("id") or if you want to do something more specific, you can use tag.getChild()
          //if predicate is true....just return null. (this will remove the entire <profile></profile> from the file)
          
        }
        return t;
     }

```

**Comment by jdelobel** [comment]
Hi @tkvangorder ,

I have implemented it! Thanks a lot for your help. Its just easy :)

**Comment by tkvangorder** [comment]
Glad to hear that. If you feel like your solution is generic enough for general use, we would happily accept a PR.
