### ISSUE TITLE
401 Error when connecting to private nexus repository

### ISSUE THREAD

**Issue by natalia-pokrovskaya** [openrewrite/rewrite#2515]
Hello, 

I have detected a small regression with 4.37.0 version. We are using private nexus repository (private repos + mirror of central maven repo) protected by username and password.
Everything works fine with 4.36.0 version of plugin and in 4.37.0 it generates me the following error:
`]`

Maven Version : 3.5.0

Thank you in advance for your help!

Regards,
Natalia

**Comment by tkvangorder** [comment]
@natalia-pokrovskaya This is now available in the `4.38.1` version of rewrite-maven-plugin
