### ISSUE TITLE
Add ChangePropertyEntryDelimiter recipe

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#2533]
The recipe will normalize property entry delimiters.

**Comment by coiouhkc** [comment]
What is meant by "normalizing" - eliminating unnecessary spaces around the `=` sign?

**Comment by TheMarvelFan** [comment]
Hi can someone provide details on this issue? I would like to take it up, but I require some guidance.

**Comment by timtebeek** [comment]
Closing this issue as insufficiently specified ; likely this was meant to switch between spaces around ` = ` and no spaces around `=`, or even `: ` and `=`, but the details are lost for now.
