### ISSUE TITLE
Annotations positioned after modifiers or type parameters

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#254]
All of these positions are possible:

![image](https://user-images.githubusercontent.com/1697736/107821927-23b83800-6d32-11eb-849a-9bc7eea4510f.png)

- [ ] Add `Annotation.Position` enum to identify the position.
- [ ] Update `JavaPrinter`.
- [ ] Update `MinimumViableSpacing`
- [ ] Update `WrappingAndBraces` to not add newlines after annotations that come after modifiers.
- [ ] Update modifier removal to change the position of annotations to `FRONT` that are otherwise `AFTER_MODIFIER` if no modifiers remain.

**Comment by jkschneider** [comment]
Started work on 0d7846f95c733ca879610da120c7373a1d8a7390.

**Comment by jkschneider** [comment]
Some things that are tricky about this:

* `ModifiersTree` (the compiler representation of modifiers) lacks start positions on modifiers. The modifiers in the compiler internal AST are also not in order of the way they appear in the source code. Currently, `sortedFlags` looks at a substring at the before/after position of the entire modifier set and extracts modifiers and their prefixes one at a time. But now annotations could be in the middle of this. So `sortedFlags` needs to know how to skip annotations as it encounters them.
* The position of the first annotation before a modifier will be the start position of the `ModifiersTree`. So you can't compare these two positions to know whether any annotations occur before modifiers.
* The basic assumption that we can map all annotaitons, then modifiers, then type parameters is no longer true.
