### ISSUE TITLE
 Recipe validation error in org.openrewrite.maven.AddDependency

### ISSUE THREAD

**Issue by marcgemis** [openrewrite/rewrite#2547]
I've added

`			<plugin>
				<groupId>org.openrewrite.maven</groupId>
				<artifactId>rewrite-maven-plugin</artifactId>
				<version>4.38.0</version>
				<configuration>
					<activeRecipes>
                                                 <recipe>org.openrewrite.java.migrate.jakarta.JavaxAnnotationMigrationToJakartaAnnotation</recipe>
						<recipe>org.openrewrite.java.migrate.jakarta.JavaxValidationMigrationToJakartaValidation</recipe>
					</activeRecipes>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.openrewrite.recipe</groupId>
						<artifactId>rewrite-spring</artifactId>
						<version>4.31.0</version>
					</dependency>
					<dependency>
						<groupId>org.openrewrite.recipe</groupId>
						<artifactId>rewrite-migrate-java</artifactId>
						<version>1.15.0</version>
					</dependency>
				</dependencies>
			</plugin>
`

to. my pom.xml

when I run ./mvnw rewrite:run I get the following error

`[INFO] Using active recipe(s) [org.openrewrite.java.migrate.jakarta.JavaxAnnotationMigrationToJakartaAnnotation, org.openrewrite.java.migrate.jakarta.JavaxValidationMigrationToJakartaValidation]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[ERROR] Recipe validation error in org.openrewrite.maven.AddDependency: Unable to load Recipe: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.openrewrite.maven.AddDependency["onlyIfUsing"])
[ERROR] Recipe validation error in org.openrewrite.maven.AddDependency: Unable to load Recipe: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.openrewrite.maven.AddDependency["onlyIfUsing"])
[ERROR] Recipe validation error in org.openrewrite.maven.AddDependency: Unable to load Recipe: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.openrewrite.maven.AddDependency["onlyIfUsing"])
[ERROR] Recipe validation errors detected as part of one or more activeRecipe(s). Execution will continue regardless.
[INFO] Project [BlueCloud API Gateway] Resolving Poms...
`

**Comment by traceyyoshima** [comment]
Hi @marcgemis, thank you for reporting the issue. I see that you're using the maven plugin version `4.38.0`.
We did a point release that includes fixes from rewrite `7.34.1` could you please try running the recipe with `4.38.1`?

**Comment by marcgemis** [comment]
Hello @traceyyoshima , running it with 4.38.1 makes no difference, still the same IllegalArgumentException.

**Comment by thomaszub** [comment]
Hi, this is a bug in the `JavaxValidationMigrationToJakartaValidation`. See https://github.com/openrewrite/rewrite-migrate-java/issues/170

**Comment by sambsnyd** [comment]
I believe this is fixed with this commit: https://github.com/openrewrite/rewrite-migrate-java/pull/171
Let us know if the problem persists despite that fix
