### ISSUE TITLE
Add Recipe to Change An Enum Value

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#255]
It might be useful to have a core recipe that will change an enum value: 

Given: 

```
public enum Example {
   METHOD_DECL
}


public class A {
   private final Example example;
   
   A() {
     example = METHOD_DECL;
   }
}
```

This recipe could be used to change the above to this: 

```
public enum Example {
   METHOD_DECLARATION
}


public class A {
   private final Example example;
   
   A() {
     example = METHOD_DECLARATION;
   }
}
```

**Comment by sambsnyd** [comment]
Agreed that it may well be useful. Closing for now. Once we have a use-case or request for it we will naturally create it at that time.
