### ISSUE TITLE
Print semicolons on non-block switch expression cases.

### ISSUE THREAD

**Issue by lars06** [openrewrite/rewrite#2550]
When the ChangePackage recipe is run by itself, there is some strange behaviour where semicolons are removed from [new switch statement](https://www.baeldung.com/java-switch#switch-expressions) cases that return an enum. I have created a new project to run this in isolation and get the same result. When the semicolons are removed by the recipe, the code no longer compiles as this is not valid Java syntax. The issue does not occur when returning non-enum values, or when using the older style switch statements.

I set up the project in the same way as the [getting started guide](https://docs.openrewrite.org/running-recipes/getting-started#step-5-run-a-recipe-with-yaml-configuration) (except I am not using the AutoFormat recipe). Why does openrewrite modify code like this when a recipe is only to change the package? In the meantime I have switched to the older style switch statements (which is not ideal). Does anyone have ideas to fix this bug? Thanks!

To reproduce:
- Create a new switch statement (-> syntax) that returns an enum. NOTE: I have validated the bug does not occur when returning integers or strings
- Run ChangePackage recipe with `./mvnw rewrite:run` (should succeed)
- Check file to see semicolons removed from switch cases and code no longer compiles

---
Maven plugin:
```
<plugin>
   <groupId>org.openrewrite.maven</groupId>
   <artifactId>rewrite-maven-plugin</artifactId>
   <version>4.38.1</version>
   <configuration>
      <activeRecipes>
         <recipe>com.example.ChangePackageName</recipe>
      </activeRecipes>
   </configuration>
</plugin>
```
---
rewrite.yaml:
```type: specs.openrewrite.org/v1beta/recipe
name: com.example.ChangePackageName
displayName: Rename package name
recipeList:
  - org.openrewrite.java.ChangePackage:
      oldPackageName: test.api
      newPackageName: test.myapi
      recursive: true
```
---
Sample test code before rewrite (after rewrite, semicolons are removed at the end of case lines):
```
private Enum run(String test) {
    return switch (test) {
        case "test1" -> Enum.NO;
	case "test2" -> Enum.YES;
	default -> Enum.MAYBE;
    };
}
```

**Comment by jkschneider** [comment]
Thanks @lars06, able to reproduce with a parser test.
