### ISSUE TITLE
`org.openrewrite.java.cleanup.MethodNameCasing` renames public interface methods despite `renamePublicMethods` is false

### ISSUE THREAD

**Issue by hetzijzo** [openrewrite/rewrite#2557]
When I have a public interface with a method (which is public by default) the Recipe `org.openrewrite.java.cleanup.MethodNameCasing` will rename the method, even if the property `renamePublicMethods` of the recipe is set to false (this is the default).

```java
public interface MyPublicInterface {
  String my_Public_Method();
}
```

NB. For Spring Data JPA methods with an underscore in the naming is very common. See https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-property-expressions

I don't expect the recipe to change this method at all.

**Comment by jkschneider** [comment]
Thanks for reporting @hetzijzo !

**Comment by hetzijzo** [comment]
I am already working on a small suggestion. I'll try to push it to my fork today.

**Comment by jkschneider** [comment]
@hetzijzo Sorry about the extra effort -- I hadn't noticed the PR. I looked at it, and I think we've got these cases covered with dd3d1fbd5e4fbd84f5df4cad035dae5b4014e5c4 and also the case of method declarations on annotation definitions, so I think we can safely close #2564 .
