### ISSUE TITLE
Add source paths to assertion description

### ISSUE THREAD

**Issue by shanman190** [openrewrite/rewrite#2600]
As part of fixing multi module `AddDependency` (https://github.com/openrewrite/rewrite/pull/2587), I found it difficult to know which file the assertion failures was for as the `build.gradle` files are so simple.

I think it could be helpful to add some more information to the assertion description, such as the source paths, which would make it easier for users to know which file the failure was for in cases such as mine.

**Comment by tkvangorder** [comment]
Good suggestion, thank you!
