### ISSUE TITLE
Add recipe to add `final` modifier to private fields

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#2611]
There is currently a `FinalizeLocalVariables` recipe but nothing for private fields. I think that would be nice to have, as currently the `RenamePrivateFieldsToCamelCase` will otherwise end up renaming corresponding `SCREAMING_SNAKE_CASE` fields (probably intended as final fields) to camel case. Many such examples can be found in the [Netflix/astyanax](https://public.moderne.io/organizations/Netflix/astyanax/master) repository. So this recipe should be added to `org.openrewrite.java.cleanup.CommonStaticAnalysis` before the `RenamePrivateFieldsToCamelCase` recipe.

Maybe it would also make sense with an option to rename the fields to SCREAMING_SNAKE_CASE.

**Comment by knutwannheden** [comment]
@kunli2 Thanks a lot for the fix! I tested the recipe and found one false positive case, where the `final` modifier is added although it shouldn't. If the field is reassigned from some context using the `this` keyword:

```java
    @Test
    void fieldReassignedByAMethodUsingThis() {
        rewriteRun(
          java(
            """
              class A {
                  private String name = "ABC";

                  void func() {
                      this.name = "XYZ";
                  }

                  String getName() {
                      return name;
                  }
              }
              """
          )
        );
    }
```

One small improvement would also be to check if all constructors (directly or indirectly via `this()`) assign a given private field and in that case also add the `final` modifier. Here a few tests for that (probably overlapping with some of the existing tests):

```java
    @Test
    void fieldAssignedInConstructorViaThis() {
        rewriteRun(
          java(
            """
              class A {
                  private String name;

                  A() {
                    this.name = "XYZ";
                  }
              }
              """,
            """
              class A {
                  private final String name;

                  A() {
                    this.name = "XYZ";
                  }
              }
              """
          )
        );
    }

    @Test
    void fieldAssignedInAllAlternateConstructors() {
        rewriteRun(
          java(
            """
              class A {
                  private String name;

                  A() {
                    name = "XYZ";
                  }
                  A(String n) {
                    name = n;
                  }
              }
              """,
            """
              class A {
                  private final String name;

                  A() {
                    name = "XYZ";
                  }
                  A(String n) {
                    name = n;
                  }
              }
              """
          )
        );
    }

    @Test
    void fieldAssignedIndirectlyInAllAlternateConstructors() {
        rewriteRun(
          java(
            """
              class A {
                  private String name;

                  A() {
                    this(name);
                  }
                  A(String name) {
                    this.name = name;
                  }
              }
              """,
            """
              class A {
                  private final String name;

                  A() {
                    this(name);
                  }
                  A(String name) {
                    this.name = name;
                  }
              }
              """
          )
        );
    }
```

Let me know if you would like me to create a separate enhancement issue for this.

Finally, I think it would be very nice if this recipe could be added to `org.openrewrite.java.cleanup.CommonStaticAnalysis` (in `rewrite-java/src/main/resources/META-INF/rewrite/static-analysis-cleanup.yml`) somewhere before `RenamePrivateFieldsToCamelCase`, so that this new recipe gets a chance to add the `final` modifier to private static fields which were intended as final, before `RenamePrivateFieldsToCamelCase` converts them to camel case.

**Comment by kunli2** [comment]
Hi @knutwannheden, great findings.
I will make a fix to the case of an assignment using the `this` keyword.
I will also try to make an enhancement to cover multi-constructor cases, the last test case you provide would be a challenge, will think about it.

**Comment by knutwannheden** [comment]
Sounds great! Not having any false positives is of course the primary concern, so covering multiple constructors could then maybe be addressed with a separate issue. The `this` logic should also cover the qualified `this` like in `A.this.x`, if possible.

**Comment by knutwannheden** [comment]
@kunli2 I thought of one more false positive in the new recipe. Real code would certainly never look exactly like this (but I think it makes the point clear) and I suspect there would indeed not be many real world cases where this problem would actually crop up. Anyway, here it goes:
```java
    @Test
    void fieldAssignedInLambdaInsideConstructor() {
        rewriteRun(
          java(
            """
                class A {
                    private int x;
                    A() {
                        Runnable r = () -> x = 2;
                    }
                }
              """
          )
        );
    }
```
This test currently fails, as the recipe makes `x` final.

**Comment by knutwannheden** [comment]
@kunli2 I tried to test the two recipes together in the public SaaS, but it looked to me like it didn't work as I was expecting. I haven't analyzed this any further and possibly I did something wrong: https://public.moderne.io/results/794D5/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+TmV0ZmxpeC9hc3R5YW5heH5+bWFzdGVyIiwib3JpZ2luIjoiZ2l0aHViLmNvbSIsInBhdGgiOiJOZXRmbGl4L2FzdHlhbmF4IiwiYnJhbmNoIjoibWFzdGVyIiwib3JnYW5pemF0aW9uIjoiTmV0ZmxpeCIsIm5hbWUiOiJhc3R5YW5heCJ9?referrer=%2Fresults%2F794D5

![Screenshot_20230124-052915](https://user-images.githubusercontent.com/408765/214213448-fe36f3e0-4941-4699-9bf5-99ccc3cf274b.png)

Let me know if you want me to look into this.

**Comment by kunli2** [comment]
Hi @knutwannheden, thanks for testing them together, let me look into this next.

**Comment by kunli2** [comment]
hi @knutwannheden, I think we have done everything, can we close this ticket? thanks

**Comment by knutwannheden** [comment]
Yes, very nice, thank you!
