### ISSUE TITLE
Upgrade Gradle Wrapper recipe does not update gradlew shell scripts

### ISSUE THREAD

**Issue by alextu** [openrewrite/rewrite#2618]
### Problem
When upgrading Gradle wrapper with Gradle task `gradlew wrapper --gradle-version=7.6`, you might get updated `gradlew` and/or `gradlew.bat` scripts. Those are generated by the Gradle execution.
Currently the current Openrewrite recipe does not update those scripts as no Gradle build happens. Only a fixed script part of the recipe is copied.

### Mitigation
Since those scripts are generated by Gradle from templates, they cannot be downloaded from the Gradle distribution.
One mitigation could consist in embedding the various different generated scripts per Gradle version(s). The big downside would be maintaining this recipe, adding scripts to it whenever a new Gradle version is out with a changed generated script.

**Comment by jkschneider** [comment]
> Since those scripts are generated by Gradle from templates

Can you isolate the part of Gradle code that substitutes this template?

**Comment by sambsnyd** [comment]
It would be very helpful if Gradle wrappers - shell scripts, jar, properties file - were published independently of the Gradle distribution itself. Would really simplify automating this if there were GAV coordinates we could target

**Comment by alextu** [comment]
@sambsnyd Yep but I think it would cause a security issue: currently the distribution is validated with a checksum, if some files are pulled externally from the distribution, this validation done by Gradle is "useless".
I asked the Gradle team if at least the scripts could be part of the distribution instead of being generated, it might be possible but a complex refactoring for them because of chicken and egg problem when building Gradle with Gradle (if I understood correctly)

@jkschneider Here's the code https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/StartScriptGenerator.java#L108-L113 called by the Gradle wrapper task to generate scripts, scripts templates are in there as well. Eventually it ends up packaged in `lib/plugins/gradle-plugins-7.6.jar`.

**Comment by sambsnyd** [comment]
If we pre-generate wrapper scripts per-version and pack them inside a recipe jar, that's us hosting pre-generated wrapper scripts instead of Gradle. If it's a security issue for Gradle to provide pre-generated wrapper scripts, wouldn't it also be a security issue for us to provide them?

**Comment by alextu** [comment]
Yes, totally you're right, since it's already the case with the current embedded script, my suggestion is more a quick fix than a general long term solution.
Although one could say it's mitigated by PR reviews where users should spot diffs in Gradle scripts. It's also the general mitigation afaik for "manual" PR upgrading the Gradle wrapper, scripts diff have to be checked by a human (the wrapper jar can be automatically validated via https://github.com/gradle/wrapper-validation-action).
