### ISSUE TITLE
Gradle - Recipe to add checksums verification to existing wrapper

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2648]
Given an existing wrapper such as 

> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists

Create a new recipe to add the `distributionSha256Sum` to the configuration. Example: 

> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> distributionSha256Sum=7ba68c54029790ab444b39d7e293d3236b2632631fb5f2e012bb28b4ff669e4b
> 

This checksum is distributed by Gradle with each release. Example: https://services.gradle.org/distributions/gradle-7.6-bin.zip.sha256

It can also be added by adding the argument `--gradle-distribution-sha256-sum` to the wrapper generation

See: https://docs.gradle.org/current/userguide/gradle_wrapper.html#configuring_checksum_verification

**Comment by shanman190** [comment]
This is mostly handled by the `UpdateGradleWrapper` recipe as long as the Gradle version changes, then the checksum is added for all versions. There is an edge case for adding to the current version though.

https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java#L183

**Comment by timtebeek** [comment]
I think this is indeed best handled by upgrading to the next version of Gradle, or allow to "upgrade" to the current version of Gradle, as opposed to a dedicated way to add a distribution for a particular version.

**Comment by yeikel** [comment]
It seems that my issue was misunderstood. My ask was about adding the verification to an existing wrapper regardless of its version

It is possible to be running using the latest version and not have the verification turned on due to misconfiguration

**Comment by timtebeek** [comment]
Apologies! Looks like that's picked up in
- https://github.com/openrewrite/rewrite/pull/4491
