### ISSUE TITLE
`AddGradleWrapper` should support custom distributions urls

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2651]
The [AddGradleWrapper ](https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/AddGradleWrapper.java) recipe should allow users to customize the `distributionUrl` 

> --gradle-distribution-url
> 
> The full URL pointing to Gradle distribution ZIP file. Using this option makes --gradle-version and --distribution-type obsolete as the URL already contains this information. This option is extremely valuable if you want to host the Gradle distribution inside your company’s network.

This is critical for Enterprise environments where `https\://services.gradle.org/distributions` is usually blocked

As stated in the official documentation, If given, the `version` and `distribution` parameters are not needed/ignored as `--gradle-distribution-url` is an absolute url (they are currently mandatory in our recipe)

**Comment by timtebeek** [comment]
I like this suggestion; particularly because it would offer a clear path for organizations that do not yet use a custom distribution url internally to adopt one with ease. It's on the backlog for now, but it seems manageable for a community contribution at first glance.

**Comment by shanman190** [comment]
It should be noted that the behavior here should act in the same manner as that of the `gradle wrapper` command. If `distributionUrl` is present, then it should be taken as is with all other options being ignored.

**Comment by shanman190** [comment]
@timtebeek, I'm not sure that I agree with this one being a good first issue. The initial change is relatively straight forward, but it's going to leak into the `GradleWrapper` utility class for validating the distribution and has some side effects that the requested `distributionUrl` must be reachable and valid. It's unfortunate, but the gradle wrapper jar only exists within another jar that exists within the full Gradle distribution. You can see some of this madness happening in the `GradleWrapperJar` utility class.

I'd appreciate your feedback as well if you think that scope creep kind of pulls it out of the good first issue category.

**Comment by yeikel** [comment]
One more thing that I noticed is that we call `https://services.gradle.org/versions` to discover versions.  While this endpoint is very convenient for us,  this is probably not available in an Enterprise environment and we should consider parsing the raw output of `https://services.gradle.org/distributions/`  instead

**Comment by shanman190** [comment]
@yeikel, I think the json data format is a lot more consumable for usage. While it's possible to use the HTML data format, we also haven't had any reports of that particular issue. 

The short of it is that I think once this feature has been implemented as described, it'll satisfy those strictest of enterprise environments anyway. It's probably more likely the case that in those environments they are packaging their own private distributions. With the handling of an exact `distributionUrl`, it should completely bypass all version resolution logic and just add the exact Gradle wrapper specified. So in this case, no parsing would be necessary, but the user will have to always specify the exact full url to their desired distribution. This is the same behavior as what Gradle expects for end users to have to deal with.

**Comment by yeikel** [comment]
> @yeikel, I think the json data format is a lot more consumable for usage. While it's possible to use the HTML data format, we also haven't had any reports of that particular issue.
> 
> The short of it is that I think once this feature has been implemented as described, it'll satisfy those strictest of enterprise environments anyway. It's probably more likely the case that in those environments they are packaging their own private distributions. With the handling of an exact `distributionUrl`, it should completely bypass all version resolution logic and just add the exact Gradle wrapper specified. So in this case, no parsing would be necessary, but the user will have to always specify the exact full url to their desired distribution. This is the same behavior as what Gradle expects for end users to have to deal with.

I agree that users could hardcode the full URL as you mentioned for the initial generation, but the Update feature discussed in #2650 would not be available under that condition. In that sense, the update feature will also need to also take a full URL

**Comment by shanman190** [comment]
@yeikel, yes, you are correct. The `UpdateGradleWrapper` would need a very similar mechanism to what we've discussed here.

**Comment by sambsnyd** [comment]
I've addressed this issue in this commit:
https://github.com/openrewrite/rewrite/commit/07685db42c5476cba8a146ae7c2fab662e806d38
