### ISSUE TITLE
Gradle wrapper recipes should allow wrappers to come from places other than services.gradle.org

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#2666]
Currently the gradle wrapper update recipes operate under the assumption that all gradle distributions will come from serivces.gradle.org. Some organizations instead host gradle distributions within their internal artifact repository. Self-hosted gradle distributions may or may not be customized in some way.

**Comment by timtebeek** [comment]
Isn't this a duplicate of https://github.com/openrewrite/rewrite/issues/2651 ?

**Comment by sambsnyd** [comment]
It is! Thanks tim
