### ISSUE TITLE
Variable names within variable declarations have the type of their parent declaration, which can differ from the variable name itself

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite#2672]
By given  source code
```
class A {
    private int a, b;

    A() {
        a = 0;
        b = 1;
    }
}
```

Found this bug, debug in the method `visitClassDeclaration()`.
the varible `((Identifier)((NamedVariable)((JRightPadded)((ArrayList)((VariableDeclarations)classDecl.body.statements.get(0).element).variables).get(1)).element).name).fieldType.name` is `a`, but it should be `b`. see attached picture here.
 

![Screen Shot 2023-01-18 at 8 26 10 AM](https://user-images.githubusercontent.com/122563761/213274956-0aadf2fa-4f22-4eee-97f9-f2e38acd12cf.png)

**Comment by sambsnyd** [comment]
I believe the source of this issue is here:
https://github.com/openrewrite/rewrite/blob/fd4785170bd550d2b0b02715f6df4a529ac76b68/rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java#L1482
