### ISSUE TITLE
Cleanup should remove trailing spaces

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#2681]
Should remove excess white-space between method name and argument list, and between last argument and closing parenthesis:
```java
foo    ("foo"      );
```
becomes:
```java
foo("foo");
```

I haven't checked as to whether `AutoFormat` will do this. It should, but it isn't part of the cleanup recipes since we generally don't want to reformat _everything_ as part of cleanup. So maybe a dedicated visitor for trailing whitespace. Which should, of course, respect any relevant styles attached to the LST

**Comment by kunli2** [comment]
do we want a dedicated recipe for this white space cleaning up?

**Comment by kunli2** [comment]
For the argument list, there is a space style [methodDeclarationParentheses](https://github.com/openrewrite/rewrite/blob/19df599e6612b1f2dfbe5cf57704eab7f4ee66ff/rewrite-java/src/main/java/org/openrewrite/java/style/SpacesStyle.java#L109), an example is [here](https://github.com/openrewrite/rewrite/blob/c98e8a12cf41ec29536e3c65c6eacbe2c91cece5/rewrite-java-test/src/test/java/org/openrewrite/java/format/SpacesTest.java#L2372).  
However, it can not cover this case well.
```java
    @Test
    void withinMethodDeclarationParenthesesTrue2() {
        rewriteRun(
          spaces(style -> style.withWithin(style.getWithin().withMethodDeclarationParentheses(true))),
          java(
            """
              class Test {
                  public void foo(int x, int y    ) {
                  }
              }
              """,
            """
              class Test {
                  public void foo( int x, int y ) {
                  }
              }
              """
          )
        );
    }
```

expected
```java
  class Test {
      public void foo( int x, int y ) {
      }
  }
```
 but was:
```java
  class Test {
      public void foo( int x, int y    ) {
      }
  }
```
I think this is something we want to improve.

**Comment by sambsnyd** [comment]
I _believe_ that method declaration parenthesis is about there being a space before the parenthesis. We might need a new style setting for whitespace trailing arguments.

**Comment by okundzich** [comment]
should this be in progress?

**Comment by kunli2** [comment]
> should this be in progress?

Yes, we can close it after https://github.com/openrewrite/rewrite/pull/2741 merged.
