### ISSUE TITLE
Create RemovePluginRepository recipe

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2709]
This should be very similar to the [RemoveRepository](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRepository.java) recipe

Sample: 

```xml

    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2//</url>
        </pluginRepository>

          <pluginRepository>
            <id>atlassian</id>
            <url>https://packages.atlassian.com/mvn/maven-external/</url>
        </pluginRepository>
    </pluginRepositories>

```

**Comment by yeikel** [comment]
@timtebeek Can you assign this to me? I am willing to give it a try/reserve it for me although I can't promise any timeline :)

**Comment by timtebeek** [comment]
Absolutely! Appreciate you diving in; let me know if you need any help! :)

**Comment by timtebeek** [comment]
Quickly looking it over it appears [`REPOS_MATCHER` is only used on line 96 of RemoveRepository](https://github.com/openrewrite/rewrite/blob/v7.35.0/rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRepository.java#L96) ; the rest seems similar and generic enough that you could maybe plug it in there indeed.
