### ISSUE TITLE
Replace `org.apache.commons.lang3.Validate.notNull` with `Objects.requireNonNull`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2724]
> Validate.notNull(myObject, "The object must not be null");
> 
>     Type Parameters:
>         T - the object type
>     Parameters:
>         object - the object to check
>         message - the [String.format(String, Object...)](http://download.oracle.com/javase/6/docs/api/java/lang/String.html?is-external=true#format(java.lang.String,%20java.lang.Object...)) exception message if invalid, not null
>         values - the optional values for the formatted exception message 
>     Returns:
>         the validated object (never null for method chaining) 
>     Throws:
>         [NullPointerException](http://download.oracle.com/javase/6/docs/api/java/lang/NullPointerException.html?is-external=true) - if the object is null

See : https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/Validate.html#notNull(T,%20java.lang.String,%20java.lang.Object...)

https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#requireNonNull-T-

**Comment by timtebeek** [comment]
At first glance it seems we can convert a good deal of these with [Change method name](https://docs.openrewrite.org/reference/recipes/java/changemethodname), as a yaml-only recipe, provided we use an explicit two arguments [Method pattern](https://docs.openrewrite.org/reference/method-patterns).

Cases using more than two arguments for the `values` then might need a dedicated Java visitor that introduces `String.format(message, values..)` for the second argument, although that does eagerly create the String before it's needed (undesirable). I would leave this case out initially, given that I expect a yaml-only `ChangeMethodName` already covers a lot of cases.

**Comment by srmalkan** [comment]
Hi, Could you assign it to me, I would like to work on it.

**Comment by timtebeek** [comment]
Sure! Glad to see you're looking to contribute. Let me know if you need any help!
