### ISSUE TITLE
Coordinates for J.Modifier locations

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#274]
In order to more conveniently `add` or `replace` `J.Modifier`'s on VariableDeclarations, MethodDeclarations, ClassDeclarations, etc., it'd be convenient to have access to make changes to J.Modifier's using Coordinates (similar to being able to `addAnnotation`)

EDIT including more specific examples

---

We can't use `mv.getModifiers().get(0).getCoordinates().before()` in this case because if the list of Modifiers is empty, we get an exception-- and "VariableDeclarations" doesn't have an accessor to add/replace the coordinates of modifiers outright.

Specific example from https://github.com/openrewrite/rewrite/pull/298. 

```java
mv = mv.withModifiers(
    ListUtils.concat(mv.getModifiers(), new J.Modifier(Tree.randomId(), Space.EMPTY, Markers.EMPTY, J.Modifier.Type.Final))
);
```

Additionally, from https://github.com/openrewrite/rewrite/blob/71c6e2541387bbc031640adb0708e41902239cdf/rewrite-java/src/main/java/org/openrewrite/java/cleanup/HideUtilityClassConstructorVisitor.java#L125-L135

**Comment by sambsnyd** [comment]
I agree this would be an improvement. But I suspect there just isn't that much more of interest to do with modifiers than what we already have. We already have recipes that reorder and change modifiers. Their implementations could be simplified if we had this functionality but I don't see that alone as sufficient argument to prioritize it.
