### ISSUE TITLE
ReplaceLambdaWithMethodReference operates on groovy.lang.Closures.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#2745]
Issue discovered on Netflix/astyanax.

**Comment by knutwannheden** [comment]
@traceyyoshima Is this a regression caused by my recent work on this recipe? I wasn't actually aware that the Java recipes would also get applied to Groovy code. So it looks like the Groovy LST model extends the Java one?

**Comment by traceyyoshima** [comment]
> @traceyyoshima Is this a regression caused by my recent work on this recipe? I wasn't actually aware that the Java recipes would also get applied to Groovy code. So it looks like the Groovy LST model extends the Java one?

Ya, the Groovy LST extends J so that common java recipes may be applied to Groovy as well.
Groovy types have a super type of GroovyObject and a GroovyObject has a super type of java.lang.Object.
So, there are a lot of shared types between the two languages.
