### ISSUE TITLE
Replace manual building of elements with JavaTemplate

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#277]
In order to exercise/consolidate the usage of `JavaTemplate`, evaluate and replace locations of `new`ing/building elements "manually" with `JavaTemplate`. 

Example:
https://github.com/openrewrite/rewrite/blob/a8f820b363ff6ebda19e81f387d044c0324284b2/rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java#L46-L52

---

note: posted this as a discussion (if for no other reason than to exercise github discussions https://github.com/openrewrite/rewrite/discussions/275). Feel free to close this. Just wanting to externalize it as a potential issue.

**Comment by sambsnyd** [comment]
I'd say we've pretty much done this by now

**Comment by aegershman** [comment]
I think there are still elements we build manually, just picking some random files within rewrite-java and such:
 https://github.com/openrewrite/rewrite/blob/55dcef080a72ca881061f8f42b3d5b7f6b7f3124/rewrite-java/src/main/java/org/openrewrite/java/DeleteStatement.java#L96-L102

https://github.com/openrewrite/rewrite/blob/55dcef080a72ca881061f8f42b3d5b7f6b7f3124/rewrite-java/src/main/java/org/openrewrite/java/AddImport.java#L98-L101

https://github.com/openrewrite/rewrite/blob/55dcef080a72ca881061f8f42b3d5b7f6b7f3124/rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java#L46-L52

Maybe these aren't candidates for using JavaTemplate, or maybe it doesn't matter that much, so, that's fine. We can close if desired 👍
