### ISSUE TITLE
Replace manual prefix formatting of elements with maybeAutoFormat

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#278]
In order to get out of the business of manually setting whitespace (e.g. when building elements using something like `Space.format(" ")`), and to exercise our `autoFormat`'ing logic, evaluate visitors which do prefix setting and replace it with autoFormat.

Example:

https://github.com/openrewrite/rewrite/blob/a8f820b363ff6ebda19e81f387d044c0324284b2/rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java#L46-L52

Feel free to close this. Just wanting to externalize it as a potential issue.

**Comment by sambsnyd** [comment]
I'd say we've done this now

**Comment by aegershman** [comment]
https://github.com/openrewrite/rewrite/blob/55dcef080a72ca881061f8f42b3d5b7f6b7f3124/rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java#L57

Looks like we're still doing manual prefix formatting? Maybe not a big deal, though.
