### ISSUE TITLE
MethodMatcher treats array arguments as if they were non-array arguments

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#28]
When applying a [MethodMatcher](https://github.com/openrewrite/rewrite/blob/2251195316c6e5c7282a2f8c059b400f2f37ba0f/rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java#L42) like `new MethodMatcher("a.A foo(int[])")` to methods like these:
```java
package a;

class A {
    // Should match this, but does not
    void foo(int[] arg) { }
    // Should not match this, but does
    void foo(int arg)
}
```
It does not match the `foo` with argument of type `int[]`, which it should.
And it does match the `foo` with argument of type `int`, which it should not.

To reproduce this issue, un-`@Disable` [MethodMatcherTest.matchesPrimitiveArgument()](https://github.com/openrewrite/rewrite/blob/007d47ab247fb77c43a65a3e8aeb66ffdedb6ced/rewrite-test/src/main/kotlin/org/openrewrite/java/MethodMatcherTest.kt#L104) test.

**Comment by traceyyoshima** [comment]
Fixed on latest, removed the disabled annotation.
