### ISSUE TITLE
Maven ignores dependencyManagement dependencies with unresolvable property references

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#281]
The POM `org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec-parent:2.0.0.Final` (depended on in several places by Quarkus) has a `dependencyManagement` section with a single dependency on `javax.activation-api` referring to a property `${activation.version}` which is not defined in either it or its parent.

Properties do _not_ propagate up from children to their parents, only down in Maven.

Maven fails to resolve a POM attempting to use this parent and `javax.activation-api` even when the POM defines the property `activation.api`.

```xml
<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.jboss.spec.javax.xml.bind</groupId>
        <artifactId>jboss-jaxb-api_2.3_spec-parent</artifactId>
        <version>2.0.0.Final</version>
        <relativePath/>
    </parent>

    <groupId>com.mycompany.app</groupId>
    <artifactId>my-app</artifactId>
    <version>1</version>

    <properties>
        <activation.version>2.0.0</activation.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jarkarta.activation-api</artifactId>
        </dependency>
    </dependencies>
</project>
```

Maven just seems to silently ignore these kind of `dependencyManagement` dependencies. I think in these scenarios we can also ignore them, but maybe after we're fully confident that normal property resolution is solid.

**Comment by tkvangorder** [comment]
This is now working in 7.0.0
