### ISSUE TITLE
Replacing method parameters does not update parameter types within the method body

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#2819]
Consider a template invocation like this one, being applied to a method declaration which changes a parameter from type `List` to type `Chunk` (a spring-batch type). 

```java
                m = m.withTemplate(
                        JavaTemplate.builder(
                                () -> getCursor().getParentTreeCursor(),"Chunk<#{}> #{}")
                                .javaParser(() -> JavaParser.fromJavaVersion()
                                        .classpath("spring-batch-core", "spring-batch-infrastructure")
                                        .build())
                                .imports("org.springframework.batch.item.Chunk")
                                .build(),
                        m.getCoordinates().replaceParameters(),
                        chunkTypeParameter,
                        paramName);
```

This will successfully replace the method invocation's parameters, but any references to those parameters within the method body will still have type attribution indicating the previous parameter type. So removing imports for those types will fail, because they will still appear to be in use. 

In this example `JavaTemplate` is used, but any mechanism for updating method parameters will face similar challenges keeping LST elements and type metadata in sync.

**Comment by knutwannheden** [comment]
@sambsnyd I assume the same would apply when using `JavaTemplate` to change the type of other declarations, right?

What do you propose should be done about this? Maybe provide a dedicated visitor, which also knows how to fixup the type attribution of any references? Client recipes could then use this rather than make an attempt with `JavaTemplate`.

**Comment by sambsnyd** [comment]
I'm not entirely sure what to do about it. It is a somewhat pervasive problem that making changes to one part of your LST does not automatically propagate to metadata it would logically affect.

While the more general problem is hard to grapple with, in this specific case it would work pretty well to have a visitor which would update the type of a particular symbol. Like `ChangeType` but constrained to only affect a particular symbol. We could override `J.MethodDeclaration.withParameters()` to automatically apply it to the method body. Then regardless of whether the change was made by java template or directly the method body would be kept up to date.

But even with all that, subclasses would not automatically be accounted for. It is quite challenging to keep metadata consistent in the face of changes to type definitions...

**Comment by knutwannheden** [comment]
> But even with all that, subclasses would not automatically be accounted for. It is quite challenging to keep metadata consistent in the face of changes to type definitions...

Yes, there is other cascading effects like this. For example when changing the type of a parameter some of the method invocations on that parameter may become invalid, if the new type doesn't declare corresponding methods or fields. And even if it does, the method invocation (and field accesses) would also have to be updated accordingly to reference the new method. This issue may also be present in your use case.

My gut feeling is that `JavaTemplate` shouldn't try to do anything smart here and that client recipes should for such use cases instead use a fine-grained `ChangeType` visitor provided by OpenRewrite.

For some use cases it might be interesting to offer a sledgehammer complement: Serialize the source file's entire LST (or possibly just a given subtree) and reparse it into a fresh, properly type-attributed LST (provided that at least the LST modifications were all correct). Client recipes / visitors could then schedule this as a post action before the LST is processed by the next visitor.

**Comment by timtebeek** [comment]
For the specific case of Spring Batch here we already have a dedicated visitor that changes the underlying method usage, as seen here: https://github.com/openrewrite/rewrite-spring/commit/912d49d20171b8215c39133596c486fab2f64b10

Sounds like that approach should be followed for any such changes, as it's hard to generalize when there might not be a one to one replacement. I think instead relying on detection of compilation issues might be best for any cases missed here.
