### ISSUE TITLE
ChangeMethodName doesn't refactor method references

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#283]
If I modify the test `ChangeMethodNameTest#changeMethodNameForMethodWithSingleArgDeclarative()` as follows it fails, because the recipe didn't refactor the method reference as expected.

```java
    @Test
    fun changeMethodNameForMethodWithSingleArgDeclarative(jp: JavaParser) = assertChanged(
        jp,
        dependsOn = arrayOf(b),
        recipe = ChangeMethodName("com.abc.B singleArg(String)", "bar"),
        before = """
            package com.abc;
            class A {
                public void test() {
                    new B().singleArg("boo");
                    new java.util.ArrayList<String>().forEach(new B()::singleArg);
                }
            }
        """,
        after = """
            package com.abc;
            class A {
               public void test() {
                   new B().bar("boo");
                   new java.util.ArrayList<String>().forEach(new B()::bar);
               }
            }
        """
    )
```

Note: I tested this against the latest master of the repo.

**Comment by knutwannheden** [comment]
By the way, it might be nice to have a Java-specific `RecipeTest` type, where the method parameters are annotated with `@org.intellij.lang.annotations.Language("java")` so that in the tests the Java-code is properly syntax highlighted and the editor will do code completion etc.

**Comment by jkschneider** [comment]
> By the way...

@knutwannheden That's a huge "btw" :). Done in #285.
