### ISSUE TITLE
Add language-specific RecipeTest with IntelliJ @Language annotation on before/after to syntax highlight tests.

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#285]
See https://github.com/openrewrite/rewrite/issues/283#issuecomment-779226889.

Also add the `@Language` annotation to language-specific parser implementations on the `parse` method that takes in a vararg string of sources.

**Comment by jkschneider** [comment]
cc / @knutwannheden

**Comment by jkschneider** [comment]
In projects that depend on rewrite, syntax highlighting inside test strings don't work well yet because of https://youtrack.jetbrains.com/issue/IDEA-262136 unless you bring rewrite itself into your IntelliJ workspace and form a gradle composite with your project and rewrite.

**Comment by knutwannheden** [comment]
What should always work, but isn't quite as convenient is that you can also use a multi-line comment like `/* language=java */` on the invocation side (i.e. in the test).
