### ISSUE TITLE
FinalizePrivateFields: Causes variables to not be initalized correctly

### ISSUE THREAD

**Issue by SplotyCode** [openrewrite/rewrite#2865]
Given the following example:
```
public class Reproducer {
  private String potentiallyFinal;

  public Reproducer(String potentiallyFinal) {
    this.potentiallyFinal = potentiallyFinal;
  }

  public Reproducer() {
  }
}
```
FinalizePrivateFields adds the final modifier to the field `potentiallyFinal` witch does not compile.  The Field only has one mutator with is in the constructor, but the class has different constructors witch do not set the Field. I would expect one of the following:
- rewrite does NOT apply the FinalizePrivateFields at all
- rewrite initializes the Field with its default value (in this case null, but diffrent for primitive types) in all other contructors
- rewrite calls the main contructor with its default value (i believe this would be quite hard to detect: a) main constructor might have other side effects b) other Parameters might influence this)

**Comment by timtebeek** [comment]
Thank you for reporting this here as well! A bit [more context available on Slack](https://rewriteoss.slack.com/archives/C01AB6L98TC/p1676891449393299).

First step in resolving this is likely a new unit test in [FinalizePrivateFieldsTest.java](https://github.com/openrewrite/rewrite/blob/main/rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java),
after which the [debugger](https://docs.openrewrite.org/concepts-and-explanations/lst-examples#using-the-debugger-to-detect-lsts) can be used to explore current and desired behaviour.

**Comment by jbessels** [comment]
Started using Open Rewrite at work, promoting it. I've noticed the exact same bug/behavior myself. Hopefully this one can be squashed soon as we have quite a few classes which are affected by it.

**Comment by timtebeek** [comment]
Thank you for confirming @jbessels ; I've moved it up to "Up Next", to hopefully see it resolved soon.

**Comment by timtebeek** [comment]
Added a [reproduction PR](https://github.com/openrewrite/rewrite/pull/2869) already; that'll likely also contain the fix once merged, which should then close this issue.

**Comment by jbessels** [comment]
New to OpenRewrite. What is the release schedule wrt bugs??

**Comment by timtebeek** [comment]
Typically we release every two to three weeks; at most four. But there was only a [couple days between 7.36.0 & 7.36.1](https://github.com/openrewrite/rewrite/releases) just this week. Not sure where this fix would fall, but as [FinalizePrivateFields is included with our often used clean up recipes](https://github.com/openrewrite/rewrite/blob/v7.36.1/rewrite-java/src/main/resources/META-INF/rewrite/cleanup.yml#L26), this might warrant another point release.

**Comment by timtebeek** [comment]
Thanks for the quick fix @kunli2 !

For @SplotyCode and @jbessels you can test the new behavior [using our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions). Hope this solves the most pressing issue. Of confirmed we look forward to the next release.

**Comment by SplotyCode** [comment]
Seems to solve the issue!

**Comment by timtebeek** [comment]
Thanks for confirming on such short notice! Happy to hear this has helped.
Are you able to continue with the snapshot versions until the next release?

**Comment by SplotyCode** [comment]
For me this would be completely fine

**Comment by jbessels** [comment]
Just found out about the fix in snapshot. Hopefully I can try it out this evening but as my issue was the same as mentioned in the OP I think all will be fine.
