### ISSUE TITLE
ChangePropertyKey - Remove node, sub structure is not embedded into existing node

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#2881]
Hi,

I' trying to write a recipe which removes a node `d` from a YAML keeping the sub structure (`e` in the test case, in my real use case this can be more complex and is unknown). I tried the `ChangePropertyKey` recipe:

```java
@Test
void indentedPropertyEmbedIntoExisting() {
    rewriteRun(
      spec -> spec.recipe(new ChangePropertyKey("a.b.d", "a.b", null, null, null)),
      yaml(
        """
          a:
            b:
              c: false
              d:
                e: true
          """,
        """
          a:
            b:
              c: false
              e: true
          """
      )
    );
}
```

The test result is
```
expected:
a:
  b:
    c: false
    e: true
but was: 
a:
  b:
    c: false
  b:
    e: true
```

It essentially works but the a second `b` node is created leading to an invalid YAML.

Thanks and kind regards
Thomas

**Comment by timtebeek** [comment]
Hi @thomaszub Thanks for providing such a quick reproduction test, very helpful! Should fit in well to our existing [ChangePropertyKeyTest](https://github.com/openrewrite/rewrite/blob/main/rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangePropertyKeyTest.java), to fix the issue with [ChangePropertyKey](https://github.com/openrewrite/rewrite/blob/main/rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java). Are you looking to potentially contribute a fix as well, or merely want to see this fixed?

**Comment by thomaszub** [comment]
Hi @timtebeek, sorry for the late response. I made a PR which fixes the issue.
Kind regards Thomas

**Comment by timtebeek** [comment]
Thanks a lot for contributing a fix once again; will have a look!
