### ISSUE TITLE
Method-related recipes consider override dimension

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#289]
A recipe like `ChangeMethodName` should also rename any matching override declaration and references to these override declarations. The same idea applies to other recipes changing the signature of a method declaration.

In a first step it probably makes sense to require the input to identify method declarations which are not overrides.

**Comment by jkschneider** [comment]
> In a first step it probably makes sense to require the input to identify method declarations which are not overrides.

I'd like to understand this a bit better. Would not a match on an overridden method only influence that method and any descendent overrides of it? I'm not clear why it matters whether a method is an override or not. Perhaps an example would help?

**Comment by knutwannheden** [comment]
> I'd like to understand this a bit better. Would not a match on an overridden method only influence that method and any descendent overrides of it? I'm not clear why it matters whether a method is an override or not. Perhaps an example would help?

I was thinking it is possibly it will be more difficult to implement. Here an example:

```java
class A {
  void m() {}
}
class B extends A {
  @Override void m() {}
}
class C extends B {
}
```

Let's assume I now want to rename `B#m()` to `m1` while *not* renaming `A#m()`:

```java
class Test {
  void foo() {
    new A().m();
    new B().m();
    new C().m();
    A a = new C();
    a.m();
  }
}
```

The result should be

```java
class Test {
  void foo() {
    new A().m();
    new B().m1();
    new C().m1();
    A a = new C();
    a.m();
  }
}
```

Thinking about it, it is probably not really more difficult to implement :-)

I assume it would be the user's responsibility to remove the `@Override` annotation on `B#m` (or `B#m1`) in a separate step or should the recipe (optionally) do that then?

**Comment by sambsnyd** [comment]
If you have an example of `ChangeMethodName` or similar making an incorrect change I'd welcome a pull request adding a disabled test demonstrating the issue.
