### ISSUE TITLE
Time estimates for composite recipes are inflated

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#2924]
Screenshot from running Java 17 upgrade on 10,000 repos.
Showing 300,000 hours saved is still quite inflated.

![image](https://user-images.githubusercontent.com/8549033/222874622-e1795f76-4244-4435-9881-ba97809a8ab9.png)

I wonder if any piece of a composite recipe making a change results in the time savings estimate for the _entire_ composite being recorded?

**Comment by nmck257** [comment]
semi-related: https://github.com/openrewrite/rewrite-maven-plugin/issues/486#issuecomment-1414379638

**Comment by kunli2** [comment]
I did some tests on SAAS to run recipe upgradeJava17, I didn't see any problem, here are some data I got.
BTW, currently, the timesaving is undercounted if there are multiple changes in a file, and it's just counted once (this is another topic not related to this question).

### Group 1: Jenkins CI
![Migrate to Java 17](https://user-images.githubusercontent.com/122563761/223485466-cb5dea8a-6b5e-4502-b72d-de493c7795a1.png)
![Screen Shot 2023-03-07 at 12 48 48 AM](https://user-images.githubusercontent.com/122563761/223485510-a9bd1619-f396-4a66-b17c-710513586c69.png)


### Group 2: Apache 
![Migrate to Java 17](https://user-images.githubusercontent.com/122563761/223485541-6a8b2572-4cb6-4a64-8883-1bba2bb32c38.png)
![Screen Shot 2023-03-07 at 1 01 47 AM](https://user-images.githubusercontent.com/122563761/223485565-1afd5e5e-dc18-4a92-a4b4-f066b701f3cf.png)

### Group 3: Default 
![Migrate to Java 17](https://user-images.githubusercontent.com/122563761/223485864-3b35084e-8136-4c6a-acbe-5d0f7ff3a540.png)
![Screen Shot 2023-03-07 at 1 19 29 AM](https://user-images.githubusercontent.com/122563761/223485888-de356b32-8d1a-40d4-8257-37b2677074ea.png)

Summary:

Group | Repo Searched | Repo Changed | Fille searched | Total results (files) | Time savings | Total files changed | Average time saving per result/file (unit : minutes) | Average results count per file
-- | -- | -- | -- | -- | -- | -- | -- | --
Jenkins CI | 953 | 869 | 82556 | 82438 | PT6908H36M | 3526 | 5.02 | 23.3800340328985
Appach 2 | 702 | 650 | 207104 | 199241 | PT16650H36M | 11187 | 5.014 | 17.8100473764191
Default | 93 | 80 | 27453 | 12785 | PT991H22M | 3493 | 4.65 | 3.66017749785285


We can see that the average time saving per result/file is about 5 minutes, which is reasonable.
I am not able to run ~10,000 repos on SAAS (not response somehow), but if we estimate it from the data we tested above, 
compare to group Apache, ~700 repos saved 16,650 hours (16,650 / 700 ~= 23.78), if this data is correct, it's ~237,800 hours to run ~100,000 repos. it's on the same scale of ~300,000 hours (assume other repos have larger sizes maybe).
 
So I think the number is reasonable from the current analysis so far. unless the changed places are overcounted, if that's the case, it should be another issue related to recipe execution but not time savings.

<img width="1114" alt="Screen Shot 2023-03-07 at 8 21 47 AM" src="https://user-images.githubusercontent.com/122563761/223484766-0991d24f-8ebb-4d76-b796-451571dd0698.png">

**Comment by sambsnyd** [comment]
Let's add some of this information to the recipe performance data table and we can use that to further investigate

**Comment by kunli2** [comment]
added time savings by this [commit](https://github.com/openrewrite/rewrite/pull/2975/files)
