### ISSUE TITLE
`JavaTemplate` can't type-attribute references to types from the same project 

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#2927]
When `JavaTemplate` is used to modify a piece of code and the template contains expressions, where the types are derived from template parameters, which in turn as their type have some other top-level type in the same compilation unit, then the type attribution is missing after the replacement.

Here a test case which could be added to `JavaTemplateTest`, which demonstrates the problem. After the replacement the `Collections.singletonList()` method invocation has no type (`J.MethodInvocation#methodType` is `null`) because the stub generated by `BlockStatementTemplateGenerator` didn't contain the `T2` type.

```java
    void replaceWithReferenceToOtherTopLevelType() {
        rewriteRun(
          spec -> spec.recipe(toRecipe(() -> new JavaVisitor<>() {
              @Override
              public J visitMethodInvocation(J.MethodInvocation method, ExecutionContext executionContext) {
                  if (method.getSimpleName().equals("asList")) {
                      method = method.withTemplate(JavaTemplate.builder(this::getCursor, "Collections.singletonList(#{any()})")
                          .imports("java.util.Collections").build(),
                        method.getCoordinates().replace(), method.getArguments().get(0));
                      maybeAddImport("java.util.Collections");
                      maybeRemoveImport("java.util.Arrays");
                  }
                  return method;
              }
          })),
          java(
            """
              import java.util.Arrays;

              class T {
                  void m() {
                      Object l = Arrays.asList(new T2());
                  }
              }
              class T2 {
              }
              """,
            """
              import java.util.Collections;

              class T {
                  void m() {
                      Object l = Collections.singletonList(new T2());
                  }
              }
              class T2 {
              }
              """
          )
        );
    }
```

**Comment by jkschneider** [comment]
this is why you basically shouldn’t ever use `#{any()}` but rather always specify a type

**Comment by timtebeek** [comment]
I believe this has been addressed with
 - https://github.com/openrewrite/rewrite/pull/3285
 - https://github.com/openrewrite/rewrite/commit/4a2e1908d1d443e7bc7262ae9a8bff7174a8cf9f

We can reopen if I misunderstood, but given the timelines those seemed to have aligned.
