### ISSUE TITLE
JavaTemplate import collisions

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite#295]
When using JavaTemplate to add/replace code with an import, your additional import may collide with an existing import, resulting in compilation errors like this:

```
parse warn: ExampleJunitTestClass.java:11: error: a type with the same simple name is already defined by the single-type-import of Timeout
parse warn: import org.junit.rules.Timeout;
parse warn: ^
parse warn: ExampleJunitTestClass.java:54: error: reference to Timeout is ambiguous
parse warn:     /*<<<<START>>>>*/@Timeout(500)/*<<<<END>>>>*/@Test
parse warn:                       ^
parse warn:   both class org.junit.jupiter.api.Timeout in org.junit.jupiter.api and class org.junit.rules.Timeout in org.junit.rules match
parse warn: ExampleJunitTestClass.java:11: error: a type with the same simple name is already defined by the single-type-import of Timeout
```

You don't see this issue anywhere; to get the output shown above you currently have to modify the JavaTemplate builder to place a listener on the JavaParser it uses. What happens under normal usage is that the JavaTemplate synthetic compilation fails, and the template replacement continues without type attribution. The typical pattern after doing such a JavaTemplate call is to use maybeAddImport, which will fail because the import is not referenced due to the failed compilation and type attribution.

It's impossible to know when this is going to happen to a given visitor, since it depends on the contents of the parsed source.

**Comment by sambsnyd** [comment]
We've gone through several major revisions of JavaTemplate since this issue was created, considering this to be obsolete until we find a current example of such a problem.
