### ISSUE TITLE
FinalClass does not take into account inner subclasses when constructor is final

### ISSUE THREAD

**Issue by arthurvl** [openrewrite/rewrite#2954]
One way of implementing sum types for ADT's in Java is to make a class with a private constructor and public constructor methods that will return instances of inner subclasses extending the class (see e.g. https://softwareengineering.stackexchange.com/questions/159804/how-do-you-encode-algebraic-data-types-in-a-c-or-java-like-language). The FinalClass cleanup breaks code that does this, as it does not take into account inner classes when checking for extending classes; and inner classes can access private constructors...

Failing test for java.org.openrewrite.java.cleanup.FinalClass.java:

```java
    @Test
    void innerClassExtending() {
        rewriteRun(
          java(
            """
              class A {
                  private A() {}
                            
                  private static class B extends A {
                      public B() {
                          super();
                      }
                  }
              }
              """
          )
        );
    }
```

**Comment by jkschneider** [comment]
Interesting, thanks for the solid example!
