### ISSUE TITLE
All visit methods other than visit() itself should be protected so that they can't be called directly, bypassing cursor-management code.

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#299]
I tried running AutoFormat on spring-petclinic via the maven plugin. It didn't work because the cursor used by the sub visitors (e.g.: BlankLinesVisitor) didn't include the compilation unit.
You'd get a cursor like J.Import -> root, when it should be J.Import -> J.CompilationUnit -> root.
That cursor was messed up because `AutoFormatVisitor.visitCompilationUnit()` was calling `JavaVisitor.visitCompilationUnit()` directly on the sub-visitors, bypassing the cursor setting code which lives exclusively in `TreeVisitor.visit()`.

It is almost certainly a bug to directly call any visit method other than `visit()` itself on any visitor which uses cursoring (most visitors),
I've fixed this particular instance. This leads me to believe we need to make all of the other visit methods `protected` to avoid this extremely easy to make mistake.

**Comment by jkschneider** [comment]
Cannot be done because `accept` needs public access to visit methods.
