### ISSUE TITLE
Gradle ChangeDependencyGroupId and ChangeDependencyArtifactId cannot be combined

### ISSUE THREAD

**Issue by ge0ffrey** [openrewrite/rewrite#2994]
To reproduce this bug, build a recipe to change a gradle dependency `org.foo:foo` to `org.bar:bar`.

Something like this:

```
  doNext(new ChangeDependencyGroupId("org.foo", "foo", "org.bar", null));
  doNext(new ChangeDependencyArtifactId("org.bar", "foo", "bar", null)); // Does nothing
  // doNext(new ChangeDependencyArtifactId("org.foo", "foo", "bar", null)); does nothing either
```

The second recipe always does nothing, regardless if the groupId or artifactId is changed first, regardless if the second recipe starts from the old or the new name.

**Proposals**

Proposal A) Add ChangeDependencyGroupIdAndArtifactId (like in Maven recipes)

Proposal B) Update model gradle model between recipe runs

**Comment by shanman190** [comment]
@ge0ffrey, just wanted to share a sample of where these two recipes combined do work as desired.
https://github.com/shanman190/rewrite/commit/e00f6310d3d302e04f432535fddd5562d29eb6dd

If you've got a reproducible sample with which you can recreate your issue, I'd be more than happy to take a look at it.

**Comment by timtebeek** [comment]
I'm going to close this one as not reproducible; if you do find a way to reproduce do let us know!
