### ISSUE TITLE
Maven wrapper 3.2.0+  : Add checksum verification

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#2996]
Starting with the Maven wrapper 3.2.0, they added checksum verification

This recipe should add this verification. 

See

https://issues.apache.org/jira/browse/MWRAPPER-75
https://github.com/apache/maven-wrapper/blob/master/src/site/markdown/index.md#checksum-verification-of-downloaded-binaries

**Comment by coiouhkc** [comment]
Could you please assign it to me? I would attempt it in coming weeks...
