### ISSUE TITLE
YamlParser not working as expected

### ISSUE THREAD

**Issue by dunningdan** [openrewrite/rewrite#2998]
Release 7.34.3 and prior the YamlParser was working as expected. With release 7.35.0 the YamlParser is returning an empty object. 
```
  @Test
  void test_yaml_creation() {
    String yaml =
            "version: 1\n"
                    + "rules:\n"
                    + "  default: disabled\n"
                    + "  exceptions:";
    List<org.openrewrite.yaml.tree.Yaml.Documents> parsedYamlFile =
            new YamlParser().parse(yaml);

    assertNotNull(parsedYamlFile);
    assertThat(parsedYamlFile.size(), equalTo(1));
  }
```

Once I upgrade it to 7.35.0 - the size is returning 0. Is this expected?

**Comment by kunli2** [comment]
Hi @dunningdan, I verified the latest version 7.38.0 with the test case above, and it works for me. 
Can you please try 7.38.0? thanks.

**Comment by timtebeek** [comment]
We've come a long way since this issue was opened; tried it again just now with the following test, which passes, so I'm closing this issue. If you continue to have an issue with the latest versions feel free to report back here!

```java

    @Test
    void test_yaml_creation() {
        String yaml = """
          version: 1
          rules:
            default: disabled
            exceptions:
          """;
        List<SourceFile> sourceFiles = YamlParser.builder().build().parse(yaml).toList();
        assertThat(sourceFiles).singleElement()
          .extracting(SourceFile::printAll)
          .isEqualTo(yaml);
    }
```
