### ISSUE TITLE
SimplifyBooleanExpression does not finish executing in a reasonable amount of time

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#300]
https://github.com/openrewrite/rewrite/blob/master/rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpression.java

When running `SimplifyBooleanExpression` using `RewriteOnDisk` against the `cleanup` package, the recipe takes an inordinately long amount of time to execute. So long, that after 30 minutes of letting it run locally, it didn't complete execution at all (or crash, so, hey, I suppose that's... good? not really). 

Logging this as a reminder to go back to evaluate why. (This may be a good opportunity to take notes on anything related to debugging recipes, if any).

**Comment by sambsnyd** [comment]
I may have indirectly fixed this as part of my fix for #389
If we notice this crop up again feel free to reopen
