### ISSUE TITLE
Calling `VariableDeclarations.NamedVar.isField(Cursor)` from within `visitVariableDeclarations` may be surprising

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#301]
see: https://github.com/openrewrite/rewrite/pull/298
Forgive the clickbait-inspired title 😉 

Calling `VariableDeclarations.NamedVar.isField(Cursor)` from within `visitVariableDeclarations` yields inaccurate results due to the cursor from `getCursor()` being a tree-level too high. This makes sense from a technical point of view, but may be surprising to someone calling `multiVar.getVariables()... v -> v.isField(getCursor())` from within `visitVariableDeclarations`.

## longer explanation

In `FinalizeLocalVariablesVisitor`, we wanted to see whether a `VariableDeclarations.NamedVar` within a `VariableDeclarations` is a `field` (e.g. a class variable). (We make this call from `visitVariableDeclarations` rather than `visitVariables`, because we want to add a `private` `J.Modifier`, which is on the `VariableDeclaration`, not the `VariableDeclaration.NamedVariable`.) `VariableDeclarations.NamedVar` has a built-in convenience method, `boolean isField(Cursor)`:

https://github.com/openrewrite/rewrite/blob/ce47cd39dcf4a142e0ff96749325b234d0a1b0ae/rewrite-java/src/main/java/org/openrewrite/java/tree/J.java#L4546-L4554

In `J` on `VariableDeclarations.NamedVar` we can see the definition of `isField(Cursor)` traverses up starting from where the `NamedVar` would be located assuming your cursor is at the location of the `NamedVar` (this makes sense).

However, we're starting from `visitVariableDeclarations`-- the immediate parent of what would be `visitVariable`. So when we end up calling `isField` on the list of `variables`, it means we start one "parent" layer higher than what the `isField(..)` method is assuming. This means the cursor resultant from `getCursor()` will not be accurate for `isField(Cursor)` to function, and getting a cursor "down" at the layer of the variables is not straightforward (at least to me). Therefore, in this case, we end up copying the `VariableDeclarations.NamedVariable.isField(..)` method and pasting it with the extra `JRightPadded` and `J.VariableDeclarations` removed:

https://github.com/openrewrite/rewrite/blob/ce47cd39dcf4a142e0ff96749325b234d0a1b0ae/rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariablesVisitor.java#L115-L123

_All this to say_, I wanted to document this as an issue to consider, because I imagine others will eventually run into something similar. Just putting it out there. Feel free to close whenever.

**Comment by sambsnyd** [comment]
Yes, agreed this is a good idea. Feel free to go ahead and make that change if you feel like. Closing this issue due to low priority in the meantime.
