### ISSUE TITLE
FinalizeLocalVariables should identify multiple possible initializers in conditional branching

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#302]
see: https://github.com/openrewrite/rewrite/pull/298
see: https://github.com/openrewrite/rewrite/issues/197

FinalizeLocalVariables should be able to identify uninitialized local variables with multiple possible initializers conditional on branching pathways. See the following unit test as an example: https://github.com/openrewrite/rewrite/blob/4e9a3cae39f95e7a7ff1ec0d689ec4c748bc91ed/rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/FinalizeLocalVariablesTest.kt#L155-L185

Note, this may be a case for `isInSameNameScope` https://github.com/openrewrite/rewrite/blob/ce47cd39dcf4a142e0ff96749325b234d0a1b0ae/rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java#L873

## background

Currently, 
- If the variable declaration has an initializer, and we find any writes to the variable again, then it’s not a “final” candidate.
- if the variable declaration does NOT have an initializer, then at-least-one write to the variable is acceptable, since that’s us initializing it. But any writes after that would make it a re-assignment, and thus not a “final” candidate.

But there's a missing bit. `FinalizeLocalVariables` should be able to identify multiple initializer candidates within conditional branches, and not see them as multiple reassignment statements. For example, right now, when the visitor sees this...

https://github.com/openrewrite/rewrite/blob/4e9a3cae39f95e7a7ff1ec0d689ec4c748bc91ed/rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/FinalizeLocalVariablesTest.kt#L160-L171

...it sees two assignment operations to `a` as being reassignments, thus “not a final candidate”. `FinalizeLocalVariables` needs to realize the assignments at the ends of the `if` conditional branches are not in the same possible pathways, thus not “reassignments”-- there's only one initialization possible.

**Comment by sambsnyd** [comment]
This would be a nice improvement. But I don't think we have any demand, at the moment, to prioritize this.
