### ISSUE TITLE
Profile Activation by SDK Version can not handle empty version ranges.

### ISSUE THREAD

**Issue by AlexanderSkrock** [openrewrite/rewrite#3025]
I wanted to execute the rewrite-maven-plugin on our codebase to have a first impression and play around with rewrite's capabilities. Sadly, I was not able to run it successfully because there was some weird profile definition throughout our pom hierarchy. I was able to identify the following dependency to be problematic, when evaluating the poms:
```
<dependency>
    <groupId>org.camunda.spin</groupId>
    <artifactId>camunda-spin-dataformat-json-jackson</artifactId>
    <version>1.14.0</version>
</dependency>
```
This project defines a profile which activates by sdk version using an empty range "(,)" (see [pom.xml#L193](https://github.com/camunda/camunda-spin/blob/master/dataformat-json-jackson/pom.xml#L193)). I am not totally sure if this notation is valid following the maven version specification. Still, I would be happy if you could support that one.

For reference, I approached the following exception:
```
java.lang.NullPointerException: Cannot invoke "org.antlr.v4.runtime.tree.TerminalNode.getText()" because "version" is null

	at org.openrewrite.maven.internal.VersionRequirement$VersionSpec$1.toVersion(VersionRequirement.java:132)
	at org.openrewrite.maven.internal.VersionRequirement$VersionSpec$1.lambda$visitVersionRequirement$0(VersionRequirement.java:117)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openrewrite.maven.internal.VersionRequirement$VersionSpec$1.visitVersionRequirement(VersionRequirement.java:127)
	at org.openrewrite.maven.internal.VersionRequirement$VersionSpec$1.visitVersionRequirement(VersionRequirement.java:105)
	at org.openrewrite.maven.internal.grammar.VersionRangeParser$VersionRequirementContext.accept(VersionRangeParser.java:138)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.openrewrite.maven.internal.VersionRequirement$VersionSpec.build(VersionRequirement.java:134)
	at org.openrewrite.maven.internal.VersionRequirement.fromVersion(VersionRequirement.java:65)
	at org.openrewrite.maven.tree.ProfileActivation.isActiveByJdk(ProfileActivation.java:82)
	at org.openrewrite.maven.tree.ProfileActivation.isActive(ProfileActivation.java:67)
```

**Current behaviour**
```
    @Test
    void shouldThrowWhenApproachingEmptyRangeSpecification() {
        ProfileActivation activation = new ProfileActivation(false, "(,)", null);
        assertThrows(NullPointerException.class, activation::isActive);
    }
```
Also, I wrote a small test case to reproduce the issue where it occurred in my case:
```
    @Test
    void shouldThrowOnPomWithProfileActivationWithEmptySdkRange(@TempDir Path cacheDir) throws IOException {
        Pom pom = RawPom.parse(new URL("https://raw.githubusercontent.com/camunda/camunda-spin/master/dataformat-json-jackson/pom.xml").openStream(), null).toPom(null, null);

        RocksdbMavenPomCache cache = new RocksdbMavenPomCache(cacheDir);
        assertThrows(IllegalArgumentException.class,  () -> cache.putPom(pom.getGav(), pom));
        RocksdbMavenPomCache.closeCache(cacheDir.resolve(".rewrite-cache").toString());
    }
```

**Expected behaviour**
```
    @Test
    void shouldDetectNoJdkRestrictionWhenApproachingEmptyRangeSpecification() {
        ProfileActivation activation = new ProfileActivation(false, "(,)", null);
        assertTrue(activation.isActive());
    }
```

Kind regards,
Alexander Skrock

**Comment by timtebeek** [comment]
Hi @AlexanderSkrock ; thanks for the detailed report! Can confirm I get the same results here locally. I've not looked into a fix yet, but hope a colleague is able to help you out with that soon.

You could consider converting the desired state unit test that you have into a [JUnit Pioneer `@ExpectedToFail` ](https://junit-pioneer.org/docs/expected-to-fail-tests/) annotated test, with an `@Issue("https://github.com/openrewrite/rewrite/issues/3025")` to link it here. That way there's a hook to update this ticket if it gets resolved as part of other work.

That profile activation `<jdk>(,)</jdk>` certainly is interesting. I'm only [finding outdated docs on those ranges](https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution), and nothing to suggest `(,)` would be something to expect often. Are there any alternatives for you to use there?

**Comment by timtebeek** [comment]
I've found https://github.com/camunda/camunda-commons works; trying to pull that up into the platform, but it's getting late here and that might take a while. If you bump the Maven wrappers I can automate these steps and don't have to run them locally on my machine.

**Comment by AlexanderSkrock** [comment]
Hi @timtebeek ,

thank you for the quick response!
I did not know about that annotation `@ExpectedToFail`, I will definitely have a look into it, sounds useful.

Just for clarification, I am not a developer of the project `camunda-spin-dataformat-json-jackson`. So I won't be able to update the used maven version. On my own project using that dependency we run Maven 3.6.3, but that one is not publicly available, so you could not use it for automated testing.

Towards the defined version range of `(,)`, sadly I also was not able to find documentation on it. The profile was introduced with this [commit](https://github.com/camunda/camunda-spin/commit/bd446541524c5f1b44ba7094eb3e480226f641e8), sadly without any hint on the version range.

Kind regards
Alexander Skrock

**Comment by timtebeek** [comment]
More than welcome to attempt a fix yourself! Should help that you already have a small reproduction test case to iterate & test quickly. Let us know if you need any further guidance, or welcome to join our Slack if you'd like to discuss in more detail without delay.

**Comment by AlexanderSkrock** [comment]
Hi @timtebeek ,

honestly this is my first time opening a pull request. It seems I openend a separate issue accidently: #3028 
Is there a possibility to clean up this duplicate. I am sorry for any inconvience in advance.

Kind regards
Alexander Skrock

**Comment by timtebeek** [comment]
No worries at all; you've done everything right so far! So this is an issue, whereas #3028 is a pull request; they can look very similar, but only a pull request has code changes. When your pull request gets merged that will also close this issue, as I've [linked the pull request to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
