### ISSUE TITLE
Using hasSize() instead of size().isEqualTo()

### ISSUE THREAD

**Issue by khmarbaise** [openrewrite/rewrite#3032]

**Comment by timtebeek** [comment]
Well this is embarrassing; we actually have [a recipe to do exactly this](https://docs.openrewrite.org/reference/recipes/java/testing/assertj/useexplicitsize).
[Example test](https://github.com/openrewrite/rewrite-testing-frameworks/blob/a6829b2b5792599eee188e8d12d363690f77e473/src/test/java/org/openrewrite/java/testing/assertj/UseExplicitSizeTest.java#L38-L80) on the rewrite-testing-framework project.

I'll see about running this on all our projects through the platform, thanks!
