### ISSUE TITLE
Recipe AddManagedDependency invalid regex verification of group/artifact IDs in onlyIfUsing parameter

### ISSUE THREAD

**Issue by jonaslindmark** [openrewrite/rewrite#3063]
I'm trying to make AddManagedDependency work adding a dependency only if usage of an artifact that contains a few dashes is found. The class complains about the validity of the onlyIfUsing parameter.

I haven't been able to find a clear definition of what characters are allowed in a maven group or artifact ID. [Guide to naming conventions on groupId, artifactId, and version](https://maven.apache.org/guides/mini/guide-naming-conventions.html) doesn't offer a clear guidance and refers to [Java spec 7.7 Unique Package Names](https://docs.oracle.com/javase/specs/jls/se6/html/packages.html#7.7).

It is clearly stated that Maven does not enforce these "rules", can we make the regex more lenient? has there been any discussion on this topic before?

Example test showing the behavior https://github.com/openrewrite/rewrite/commit/17208d56d2df86dd86d3d53caedfe1ff2cc3598c

Regex in question is over here https://github.com/openrewrite/rewrite/blob/75799135767a686ea55495eb00c0da4d96b12006/rewrite-maven/src/main/java/org/openrewrite/maven/AddManagedDependency.java#L120

Happy to submit a patch if we can figure out what identifiers we want to allow here.

**Comment by timtebeek** [comment]
Hi @jonaslindmark ; That looks like an oversight indeed; from you test it seems you're a good way towards a fix as well, would you want to open that up as a contribution? It seems like the regex would only need a minimal change to also allow for dashes.

**Comment by timtebeek** [comment]
I think we can keep it fairly minimal at `[\w\.-]+` for both the `groupId` and `artifactId`, unless you have other edge cases in mind that we might want to support already now. Looking at it in more detail now the `groupId` matcher might be a bit too wide with the unescaped dot there. 🤔

**Comment by jonaslindmark** [comment]
TIL: 

> Note that a different set of metacharacters are in effect inside a character class than outside a character class. For instance, the regular expression . loses its special meaning inside a character class, while the expression - becomes a range forming metacharacter.

From [Character Classes](https://docs.oracle.com/javase/tutorial/essential/regex/char_classes.html)

So no need to escape that dot, verified with a small test.

**Comment by timtebeek** [comment]
Appreciate the detailed look there! Meanwhile I've fixed the ingestion of some of the public Spotify repositories into https://public.moderne.io , such that you can run and verify the fix there if it helps.

You can [create a repository group](https://public.moderne.io/settings/repo-groups) containing ~40 Spotify repositories, and then execute either [known recipes such as Common static analysis](https://public.moderne.io/recipes/org.openrewrite.java.cleanup.CommonStaticAnalysis), or compose new recipes to [tryout through the builder](https://public.moderne.io/recipes/builder). Each should run in a few seconds there, as we prebuild the lossless semantic trees daily.

Here's an example run for the Common static analysis results: https://public.moderne.io/results/rkIZj
Temporary link, as the results are only kept in memory on our workers, but can be recreated if needed.

Feel free to have a look, and contribute back if you want; it's free for OSS as our way of giving back.

**Comment by timtebeek** [comment]
Just merged your PR, thanks again! We expect to do a release within a week or so; until then you can [use our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions).
The platform typically gets these updates within a day as well.

Hope this works well for you and come again if you have any further suggestions for improvement! :)
