### ISSUE TITLE
Code cleanup recipe for using Java imports to reduce usage of FQNs

### ISSUE THREAD

**Issue by wabrit** [openrewrite/rewrite#3094]
It would be useful to have a recipe which transforms Java source by simplifying references to fully-qualified e.g. classes based on imports present.

e.g. transform this:

```java
import some.long.package.name.Foo

@some.long.package.name.Foo
public class Bar { ... }
```

to

```java
import some.long.package.name.Foo

@Foo
public class Bar { ... }
```

**Comment by sambsnyd** [comment]
Good idea. Shouldn't be too difficult.
