### ISSUE TITLE
RewriteTest + YamlResourceLoader - recipe validation should be recursive, or perhaps disabled?

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#3096]
Suppose you have a recipe project using `rewrite-spring`, and you're doing something like this:

```java
@Test
void foo() {
    rewriteRun(spec -> spec.recipe(
                Environment.builder()
                        .load(new YamlResourceLoader(this.getClass().getResourceAsStream("/META-INF/rewrite/spring-boot-24.yml"),
                                URI.create("rewrite.yml"), new Properties()))
                        .load(new YamlResourceLoader(this.getClass().getResourceAsStream("/META-INF/rewrite/junit5.yml"),
                                URI.create("rewrite.yml"), new Properties()))
                        .build()
                        .activateRecipes("org.openrewrite.java.spring.boot2.SpringBoot2JUnit4to5Migration"))
    // ...
```

The recipe happily instantiates, succeeds on the validation assertions in `rewriteRun`, and runs.

But, suppose you instead activate `org.openrewrite.java.testing.junit5.JUnit4to5Migration` -- aka, the first recipe listed in `SpringBoot2JUnit4to5Migration`. Then, the validation assertion fails, as it cannot find the rewrite-testing-frameworks Hamcrest recipes (declared in `hamcrest.yml`).

It seems that `YamlResourceLoader` does not recursively check for recipe existence; it only checks the recipes which are directly referenced in the activated recipe's `recipeList`.

But, a step further: the recipe described above *does* run. It does *not* encounter some runtime issue from lack of Hamcrest recipes. This implies that the relevant recipes are indeed available; the `YamlResourceLoader` just doesn't know about them when it applies its validations. The validation therefore seems inaccurate.

Should those validations be rewritten or bypassed somehow when used from `RewriteTest`?
This would also make the `RecipeSpec::recipeFromResources` method more useful, as currently it gets stuck in cases where additional yamls must be loaded to pass validation (and therefore you have to use code like above).

**Comment by sambsnyd** [comment]
Definitely worth looking into

**Comment by nmck257** [comment]
It seems like we do have the recursive checking now, perhaps after #3389.

But, that now obligates the test author to name and load every yaml from the classpath which is referenced throughout the recipe chain, which is a bit of a nuisance. Would be lovely if we could harvest ymls from the classpath automatically.
