### ISSUE TITLE
org.openrewrite.java.cleanup.EmptyBlock remove the finally{} from try-finally

### ISSUE THREAD

**Issue by PongPong** [openrewrite/rewrite#3108]
the org.openrewrite.java.cleanup.EmptyBlock recipe removes the empty finally block from try-finally statements.

Before

```
try( AutoCloseable closeable = f.open() ) {
// do something
} finally {}
```
After (compilation error)

```
try( AutoCloseable closeable = f.open() ) {
// do something
}
```

**Comment by timtebeek** [comment]
Hi @PongPong! Can you confirm it only removes empty finally blocks? Or are you seeing something different? Is there a reason you would like the recipe to retain empty finally blocks?

In any case; we have a test specifically to match the case that you've highlighted above:
https://github.com/openrewrite/rewrite/blob/57b4fd6f29cb112def09a003a2160e98df1441b7/rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/EmptyBlockTest.java#L152-L187

If you'd like the recipe to do something else we'd love to hear your rationale behind that change, preferably as a similar unit test PR if you're looking to highlight an issue; that way we can get started on a possible fix quickly.

**Comment by PongPong** [comment]
In Java, when working with resources that need to be closed after they have been used, the Autocloseable interface can be implemented by the class to ensure that the close() method is called automatically when the resource is no longer needed.

When the try block completes, the close() method of the closeable resource is automatically called, even if an exception is thrown within the try block. This is handled by the try-with-resources statement, which ensures that the close() method is always called, even in the event of an exception.

Since I am not interested in handling any exceptions that may be thrown by the close() method, I can leave the finally block empty.

**Comment by timtebeek** [comment]
Hi @PongPong ; what kind of compilation error are you seeing without `finally {}` that you were not seeing before? Because the following works fine in my reproduction samples.
```java
try( AutoCloseable closeable = f.open() ) {
// do something
}
```

Perhaps a complete class example would work best here; that way it's easier to convert into a unit test.

**Comment by knutwannheden** [comment]
I think it is a regular `try` statement not a try-with-resources statement. E.g.
```java
        try {
            return null;
        } finally {
        }
```
Here the `catch` or `finally` is indeed required.

**Comment by PongPong** [comment]
@timtebeek ah, my fault , after checking , your case is valid, thanks for your clarification

**Comment by knutwannheden** [comment]
While the issue mentions try-with-resources I can confirm that the recipe behaves incorrectly with a regular `try` statement without `catch` blocks and an empty `finally` block (as per my previous comment).

**Comment by knutwannheden** [comment]
@PongPong Please let us know if we missed something with respect to the try-with-resources statement or any other edge case. The issue I reported with a try-finally block (without catch block) has been fixed.

**Comment by PongPong** [comment]
yes, I generated the API client from the OpenAPI schema, but the code generation process produced a try-finally block due to a conditional statement in the template which do not generate the catch block. However, when I ran the EmptyBlock recipe, it removed the finally block entirely, leaving only the try block. This caused a complication error, as the finally block is necessary to ensure that certain operations are always executed, regardless of whether an exception is thrown in the try block.

not sure if there are any recipe that can remove the wrapping  try-catch  completely

```
try {
//do something
} finally {}
```

to 
```
// do something
```

**Comment by knutwannheden** [comment]
@PongPong There is the `RemoveUnneededBlock` for this purpose. We could look into enhancing it as you propose. It would however have to respect that a try-finally block where the try contains variable declarations cannot be inlined this way without further analysis, since the block declares a new lexical scope for variables and when inlined the variable could conflict with variables declared in later statements.

**Comment by knutwannheden** [comment]
`RemoveUnneededBlock` will now also inline the body of a try-finally block with empty finally, if it doesn't contain any variable declarations.
