### ISSUE TITLE
Direct support for Refaster templates

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#3110]
### Background ###
Refaster is a part of Google Errorprone (see [docs](https://errorprone.info/docs/refaster)) and allows code refactorings to be defined declaratively in Java using before and after templates (see below for a simple example taken directly from the documentation). These templates then get picked up and applied in-place by the Errorprone annotation processor (similarly to how OpenRewrite recipes get applied in-place).

Expressing simple refactoring using declarative templates in Java is very convenient and is extremely easy to get started with, as there is no additional AST API the developer needs to learn and program against. Also, there are quite a few Refaster templates available as part of Errorprone itself, but also in [PicnicSupermarket/error-prone-support](https://github.com/PicnicSupermarket/error-prone-support) and other GitHub repos.

For these reasons it would be very interesting if OpenRewrite could directly support existing Refaster templates. Ideally a Refaster template should for the user (applying recipes) be indistinguishable from regular OpenRewrite recipes and to the recipe author feel like a normal Refaster template when being developed.

#### Refaster Example ####
Here is an example of a Refaster template which will replace expressions matching `str.equals("")` or `str.length() == 0` (where `str` is any expression of type String) with `str.isEmpty()`.

```java
public class StringIsEmpty {
  @BeforeTemplate
  boolean equalsEmptyString(String string) {
    return string.equals("");
  }

  @BeforeTemplate
  boolean lengthEquals0(String string) {
    return string.length() == 0;
  }

  @AfterTemplate
  @AlsoNegation
  boolean optimizedMethod(String string) {
    return string.isEmpty();
  }
}
```
### Acceptance Criteria
- There is a unit test that shows how java classes with rules **with a single `@BeforeTemplate` and a single `@AfterTemplate` are processed** using an annotation processor and can be executed as a recipe. We consider that the community can incrementally add more refaster annotations if needed.

Existing real examples are:
   * https://github.com/PicnicSupermarket/error-prone-support/blob/master/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PrimitiveRules.java
   * https://github.com/PicnicSupermarket/error-prone-support/blob/master/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JUnitRules.java
   * https://github.com/PicnicSupermarket/error-prone-support/blob/master/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MockitoRules.java

### Assumptions
- The annotation processor can copy relevant classpath jars to `META-INF/rewrite/classpath` and configures `JavaParser`

### Out of scope

- The template parameter DSL will at some point have to be extended for "named" parameters (if a Refaster template refers to the same method parameter multiple times)
- The template parameter DSL will also need to be extended for Java generics
- How to determine if the LST for a `JavaTemplate` is context-free or not (for Refaster templates they basically always should be), so that it can be cached?

**Comment by timtebeek** [comment]
We now support writing and running Refaster recipes through an annotation processor in [openrewrite/rewrite-templating](https://github.com/openrewrite/rewrite-templating). This is already [used in rewrite-migrate-java](https://github.com/openrewrite/rewrite-migrate-java/blob/v2.2.1/src/main/java/org/openrewrite/java/migrate/lang/StringRules.java) for the above example. We also added [documentation on writing refaster rules](https://docs.openrewrite.org/authoring-recipes/types-of-recipes#refaster-templates). That concludes this issue; further issues can go into [rewrite-templating/issues](https://github.com/openrewrite/rewrite-templating/issues).
