### ISSUE TITLE
org.openrewrite.java.cleanup.HideUtilityClassConstructor is missing ignore annotation for @NoArgsConstructor(access = AccessLevel.PRIVATE)

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite#3114]
(https://github.com/openrewrite/rewrite/blob/aaa06ff9f94b45f35263795dabf5d5dd665a9abf/rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java#L96) has 

```
    public static HideUtilityClassConstructorStyle hideUtilityClassConstructorStyle() {
        return new HideUtilityClassConstructorStyle(Arrays.asList(
                "@lombok.experimental.UtilityClass",
                "@lombok.Data"
        ));
    }
```

but doesn't ahve `@NoArgsConstructor(access = AccessLevel.PRIVATE)` so the compilation after transformation will fail with 

constructor Foo() is already defined in class Foo
@NoArgsConstructor(access = AccessLevel.PRIVATE)

**Comment by timtebeek** [comment]
Hi @blipper Thanks for pointing out this omission; do I correctly deduce that you want to add this additional annotation to prevent compilation errors?
```diff
    public static HideUtilityClassConstructorStyle hideUtilityClassConstructorStyle() {
        return new HideUtilityClassConstructorStyle(Arrays.asList(
                "@lombok.experimental.UtilityClass",
+               "@lombok.NoArgsConstructor",
                "@lombok.Data"
        ));
    }
```
While I don't think the code as it is right now would allow for adding the `access = AccessLevel.PRIVATE` at present, I don't think there's harm in detecting the mere presence of `@lombok.NoArgsConstructor` and backing off from adding an additional constructor. Would you agree there?

And is this a change you'd want to provide a pull request for, or is it merely something you'd like to see fixed whichever way soon?

**Comment by blipper** [comment]
I guess that makes sense to disable regardless.

I wonder if we need to deal with the other variations but I guess by definition a utility class doesn't have field level params.
https://projectlombok.org/features/constructor

Happy to do a pull or whatever.

**Comment by timtebeek** [comment]
Sure; happy to merge a quick pull request if you want to contribute this change; I think even the GitHub online editor would be enough to add this in here. https://github.com/openrewrite/rewrite/blob/aaa06ff9f94b45f35263795dabf5d5dd665a9abf/rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java#L96-L101
Otherwise I can make that change and close the issue that way; whatever you prefer.
