### ISSUE TITLE
`TypeValidation.none` not working in recipe test

### ISSUE THREAD

**Issue by JoseLora** [openrewrite/rewrite#3129]
This test does NOT pass because the `ChangeType` recipe is doing nothing:

```java
  @Test
  void sample() {
    this.rewriteRun(
        spec -> spec
            .recipe(new ChangeType("com.test.MyOldClass", "com.test.MyNewClass", true))
            .typeValidationOptions(TypeValidation.none()),
        java(
            """
                    package com.test.app;

                    import com.test.MyOldClass;

                    public class App {

                      public MyOldClass myClass() {
                        return new MyOldClass();
                      }

                    }
                """,
            """
                    package com.test.app;

                    import com.test.MyNewClass;

                    public class App {

                      public MyNewClass myClass() {
                        return new MyNewClass();
                      }

                    }
                """));
  }
```

In contrast, if we use stubs with `JavaParser.dependsOn()` to ensure external types are resolved, it works:

```java
  @Test
  void sample() {
    this.rewriteRun(
        spec -> spec
            .recipe(new ChangeType("com.test.MyOldClass", "com.test.MyNewClass", true))
            .parser(JavaParser.fromJavaVersion()
                .dependsOn(
                    """
                        package com.test;

                        public class MyOldClass {}
                        """)),
        // .typeValidationOptions(TypeValidation.none()),
        java(
            """
                    package com.test.app;

                    import com.test.MyOldClass;

                    public class App {

                      public MyOldClass myClass() {
                        return new MyOldClass();
                      }

                    }
                """,
            """
                    package com.test.app;

                    import com.test.MyNewClass;

                    public class App {

                      public MyNewClass myClass() {
                        return new MyNewClass();
                      }

                    }
                """));
  }
```

Is there any way to ignore type errors without having to declare stubs or include types in classpath?

We want to develop a recipe library for a large company framework and it seems weird having to include a lot of test dependencies in recipe library pom just because of this. We thought we could write recipe tests only considering initial LST and final LST without checking for types or compilation errors.

**Comment by timtebeek** [comment]
Hi @JoseLora ; I agree that stubs are not ideal when developing recipes; instead you'll likely want to look at using classpath dependencies instead, through `org.openrewrite.java.JavaParser.Builder#classpath(java.lang.String...)` ([link](https://github.com/openrewrite/rewrite/blob/0d3312d0eb5bbdee61b22047adcdbf3aed8ba0a8/rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java#L355)), such as for instance [seen here](https://github.com/openrewrite/rewrite-migrate-java/blob/713e52ae29069ee187ff8abf7d292de17448b31b/src/test/java/org/openrewrite/java/migrate/apache/commons/lang/IsNotEmptyToJdkTest.java#L28-L32).
```java
class IsNotEmptyToJdkTest implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        spec.parser(JavaParser.fromJavaVersion().classpath("commons-lang3", "plexus-utils", "maven-shared-utils"))
          .recipe(new IsNotEmptyToJdk());
    }
```
That way you only have to declare a dependency on your internal framework, rather than redeclare the classes your recipe might depend on.

OpenRewrite does require the full type before we're able to run recipes, as your `class MyOldClass` might extend a certain class that recipes might match on.

Does that help to provide some context and a workable solution for your case? Welcome to discuss your use case some more, especially if you're looking to roll this out at scale internally.

**Comment by timtebeek** [comment]
And specifically, the `TypeValidation` option that you referenced is to ignore missing types in the recipe output, not the recipe input. In rare cases it might not be practical to add the correct type attribution on the output in recipes; in such cases you can ignore a type check on the output in unit tests. This of course is not recommended; as missing types mean recipes won't chain easily anymore, as input types will be missing downstream.

**Comment by JoseLora** [comment]
Thanks @timtebeek 

I partially understand you, but first of all, what is `.typeValidationOptions(TypeValidation.none())` for then? I thought it was what I was looking for but it doesn't work in the example.

If I understand `JavaParser.classpath()` option, where I had to enumerate needed dependencies for my concrete test, but this forces me to declare each of them in our recipe library pom, right? That's what it seems weird to me. The pom for our recipes library jar will grow a lot. If my test is asserting initial source code and final source code... do we really need all this type checking and dependencies in our recipe library pom?

(Sorry for the lack of knowledge of the inner workings)

**Comment by timtebeek** [comment]
> I partially understand you, but first of all, what is `.typeValidationOptions(TypeValidation.none())` for then? I thought it was what I was looking for but it doesn't work in the example.

Did you notice [my follow up comment](https://github.com/openrewrite/rewrite/issues/3129#issuecomment-1511076713)? It allows imperfect recipes from producing a result that will compile, without having the correct type attribution on each output tree element.
 
> I understand `JavaParser.classpath()` option, where I had to enumerate needed dependencies for my concrete test, but this forces me to declare each of them in our recipe library pom, right? That's what it seems weird to me. The pom for our recipes library jar will grow a lot. If my test is asserting initial source code and final source code... do we really need all this type checking and dependencies in our recipe library pom?

Note that you can declare these dependencies as test-scoped(!) That might resolve any hesitation you have about a growing POM, as the dependencies do not make it into the recipe jar that you distribute, until you explicitly refer to those types in your custom imperative (Java) recipes.

> (Sorry for the lack of knowledge of the inner workings)

No problem at all! Here to help; and you're also welcome on our Slack and #questions channel there if GitHub issues proves to limiting.

**Comment by JoseLora** [comment]
Sorry, read your last reply too late. I understand `TypeValidation.none` now, it allows a not-checked recipe output.

Regarding input, I understand type checking is fully required for Openrewrite to work, resolve classes and so on.

Actually the only problem we saw is having to declare so many dependencies in our recipes library pom. We thought OpenRewrite worked in a more source (text) to source way.

It's clear now. Thank you!

**Comment by timtebeek** [comment]
Glad we could clear up your questions; feel free to reach out again if you have any more!
