### ISSUE TITLE
org.openrewrite.java.cleanup.FinalizeMethodArguments incorrectly applies final to params on an abstract method

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite#3135]
```
class Foo {
abstract void bar(String a);
}
```
transforms to

```
class Foo {
abstract void bar(final String a);
}
```

This is meaningess as per https://stackoverflow.com/questions/17719892/making-abstract-method-parameters-final-in-java
 and triggers https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/modifier/RedundantModifierCheck.html warning in Checkstyle

**Comment by kunli2** [comment]
Thanks @blipper for reporting, fixed.
