### ISSUE TITLE
Describe recipe utility

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite#315]
Put the functionality in rewrite core. This will be exposed in maven and gradle plugins as describe tasks with different options. One option would be to output this description in markdown that would be used it docs.

Display:
Name (fully qualified name)
Display name
Description
Tags
Parameters (required and optional)
Depends on (doNext). Tree view of dependencies:
- direct. Default for generating docs. Could be displayed as links to these recipes in docs.
- recursive (optional for maven and gradle describe tasks)

**Comment by jkschneider** [comment]
Depends on #315.

**Comment by okundzich** [comment]
https://github.com/openrewrite/rewrite/issues/314#issue-812951499

**Comment by gadams00** [comment]
Completed via https://github.com/openrewrite/rewrite-recipe-markdown-generator
