### ISSUE TITLE
Recipe dependency hygiene

### ISSUE THREAD

**Issue by okundzich** [openrewrite/rewrite#316]
Ensure this contract exists: No dependencies of what you are trying to migrate to in the migration recipes themselves.

For example, rewrite-srping cannot have a dependency on Spring Boot 2. rewrite-testing-frameworks cannot have a dependency on JUnit 5.

**Comment by gadams00** [comment]
Did a spot check on rewrite-testing-frameworks and rewrite-spring, and I believe this is already done.
