### ISSUE TITLE
Double-check how JavaType.Flag is a Set of same type of J.Modifier.Type (List) in J.java

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#318]
Feel free to close, probably need to rephrase this issue body. I'm just dumping this out of my head as I can since I'm seeing it and don't want to forget:

The enum of `Flag` appears the same as J.Modifier.Type (?)
https://github.com/openrewrite/rewrite/blob/ceee8084a8295cf97399673e4294015c2317368e/rewrite-java/src/main/java/org/openrewrite/java/tree/Flag.java#L20-L29

https://github.com/openrewrite/rewrite/blob/ceee8084a8295cf97399673e4294015c2317368e/rewrite-java/src/main/java/org/openrewrite/java/tree/J.java#L3058-L3091

and in `JavaType`, `Flags` (which appear same as J.Modifier.Type?) are of a `Set`, Whereas in J, `J.Modifier.Type` is often contained within a `List`. https://github.com/openrewrite/rewrite/blob/ceee8084a8295cf97399673e4294015c2317368e/rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java#L393

Wanted to point this out as something to double-check. Should Modifier Types be referenced as a Set more often rather than a List (considering you can't have multiple of the same modifier)? Should "flag" and "J.modifier.type" be collapsed into one? etc.

**Comment by jkschneider** [comment]
@aegershman They are a list in the AST because the preservation of order matters. In the type attribution, it doesn't matter.
