### ISSUE TITLE
Javadoc link to array not preserved 

### ISSUE THREAD

**Issue by mduerig** [openrewrite/rewrite#3198]
OpenRewrite does not properly preserve Javadoc links to arrays:

```
/**
 * Foo {@link javax.jcr.Value[] values} bar.
 */
```
is incorrectly converted to
```
/**
 * Foo {@link javax.jcr.Valuevaluesbar. bar.
 */
```
when running _mvn_ rewrite:run -Drewrite.activeRecipes=org.openrewrite.java.AddLicenseHeader_

**Comment by timtebeek** [comment]
Sorry to hear! That's a bug indeed, and annoying that it won't let you run recipes without producing such unwanted changes. Feel free to open a pull request to replicate the issue in a test, such that we can more easily pick this up when we have time.

**Comment by mduerig** [comment]
https://github.com/openrewrite/rewrite/pull/3213

**Comment by timtebeek** [comment]
Thank you for adding a test! As also noted in https://github.com/openrewrite/rewrite/pull/3213#issuecomment-1538033667 I've merge the test already, and briefly explored what might cause this issue. It's either a problem printing the results back out, or a problem with how we parse the `int[]` in the code snippet (or both). Either way having the test helps to pick this up once we have time, or notify you here if it's resolved as part of other work.
