### ISSUE TITLE
Recipe InlineVariable removes comment(s)

### ISSUE THREAD

**Issue by jbessels** [openrewrite/rewrite#3201]
PRE 
```
  Collections.sort(sortedList, new Comparator<Integer>() {
                    @Override
                    public int compare(Integer o1, Integer o2) {
                        int result = o1 - o2; // low-to-high
                        return result;
                    }
```

POST
```
Collections.sort(sortedList, new Comparator<Integer>() {
                    @Override
                    public int compare(Integer o1, Integer o2) { return o1 - o2;
                    }
```

You notice that the comment has been removed. As a comments can also be a much larger multiline /* .. */ or even a abused Javadoc /**..*/  I think its best to place the comment(s) right above the return code.

**Comment by knutwannheden** [comment]
@jbessels Thanks for the report. I have now changed the recipe so its behavior is consistent with that of IntelliJ IDEA. See https://github.com/openrewrite/rewrite-static-analysis/blob/6306b9d31cd0c2c92e3fc2d8234d218c64b5dbe4/src/test/java/org/openrewrite/staticanalysis/InlineVariableTest.java#L171-L195

**Comment by jbessels** [comment]
Thanks a lot guys for picking this one up so quickly. When will this fix finds its way to the SNAPSHOT version???

**Comment by rpau** [comment]
It should be automatically after any PR is merged.

**Comment by knutwannheden** [comment]
In this case unfortunately not. We are in the process of preparing the 8.0 release and decided to split out all static analysis issues into the new rewrite-static-analysis repo. Since the release should be ready soon, I decided to fix it there already. If you need the fix already earlier, I can also commit it to the rewrite repo, from which we build the current 7.x snapshot builds.

**Comment by jbessels** [comment]
Going that extra mile is very much appreciated but **NOT** needed as it would be prevent you from working on something else . As the 8.0 release will be ready soon as you said I can wait. I just make an extra comment by the <exclude> lines for the issue and recheck later when 8.0 is released. 8.0. Will this result in a new 4.46 or 4.45.1 release??

**Comment by rpau** [comment]
I believe that the answer is that it can be only available for the 8 release, but @knutwannheden should confirm

**Comment by knutwannheden** [comment]
> Will this result in a new 4.46 or 4.45.1 release??

I suspect this will be a 4.46.0 release or possibly a 5..0.0 release for the Maven plugin. I expect this will happen rather soon, if not we can always backport and make it available through our snapshot releases.

**Comment by jbessels** [comment]
Tim reminded me that this has been fixed. Retested it with 5.4.2. Comments are NO longer removed. Thanks.
**Ticket can be closed.**

![image](https://github.com/openrewrite/rewrite/assets/69236284/f691766d-d66d-443c-8df0-e16db8602ace)

**Comment by knutwannheden** [comment]
@jbessels Thanks for confirming!
