### ISSUE TITLE
Maven RemoveProperty - does not clean up empty properties tag

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite#3231]
When `RemoveProperty` removes the last/only property in a `pom.xml`, then it would be nice if it also removed the empty `<properties>` tag. The existing recipe logic is trivial and does not attempt to handle this case.

**Comment by timtebeek** [comment]
Ideally tackled by calling out to the dedicated recipe in https://github.com/openrewrite/rewrite/issues/2737

**Comment by nielsdebruin** [comment]
Am I correct in thinking 9fed57a465e7bd70f546bbb67c824abbd7ff4f69 resolves this issue?

**Comment by timtebeek** [comment]
Indeed that's tackled since! Thanks for helping clear out the backlog. 🙏
