### ISSUE TITLE
Gradle recipe which sets Java sourceCompatibility and targetCompatibility

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#3235]
Similar to what we have for maven. For inclusion in the java 8 -> 11 and java 11 -> 17 migrations

**Comment by shanman190** [comment]
A bit of the basis for this is already available. I think we could probably update `ChangeJavaCompatibility` (maybe rename to `UpdateJavaCompatibikity`) which by default would match the current declaration style and have an option to change to a desired declaration style. Then `UpdateJavaVersion` has some handling for the Gradle Java Toolchains functionality.

https://github.com/openrewrite/rewrite/blob/9a6879c7551ebfe783632ce4df7b137b879e3703/rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeJavaCompatibility.java

https://github.com/openrewrite/rewrite-migrate-java/blob/6f5d37e2ebfd24a115190e6a346ceee2b3c04a4f/src/main/java/org/openrewrite/java/migrate/UpgradeJavaVersion.java

**Comment by knutwannheden** [comment]
@kunli2 This recipe rename is another candidate for the 8.0 migration recipe.
