### ISSUE TITLE
Gradle UpdateJavaCompatibility recipe does not work with Micronaut's generated format.

### ISSUE THREAD

**Issue by jeremyg484** [openrewrite/rewrite#3255]
A Micronaut 3.x app generated by Micronaut Launch uses the following format in build.gradle for Java compatibility settings:

```
java {
    sourceCompatibility = JavaVersion.toVersion("1.8")
    targetCompatibility = JavaVersion.toVersion("1.8")
}
```

Using `JavaVersion.toVersion` as we do is not properly detected and updated by the UpdateJavaCompatibility recipe.

**Comment by shanman190** [comment]
Hi @jeremyg484 👋

I see a couple of possibilities here, so what would you ideally like to see?

I could see trying to attempt to keep the method invocation directly (`JavaVersion.toVersion("11")`) or convert it to the enum type by default (`JavaVersion.VERSION_11`).

**Comment by jeremyg484** [comment]
Hi @shanman190, thanks for the quick response!

I think either would ultimately be fine, but I would lean toward keeping the same format (unless the `declarationStyle` option is set differently) as it would be consistent with what we are also generating for new Micronaut 4 apps created with https://micronaut.io/launch
