### ISSUE TITLE
Should gradle RemoveDepenency be package private?

### ISSUE THREAD

**Issue by iparadiso** [openrewrite/rewrite#3259]
I was looking for a recipe to remove a gradle dependency when I noticed that [RemoveGradleDepenency](https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveGradleDependency.java#L24) was deprecated in favor for [RemoveDependency](https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveDependency.java#L41).  

However RemoveDependency is currently package private.  Is this intended?  Looking for clarity for how we should be be using this recipe.

Many Thanks!

**Comment by shanman190** [comment]
@iparadiso, nice catch! That was an accidental thing, it's public now and the snapshot should be available momentarily.

**Comment by iparadiso** [comment]
@shanman190 many thanks.  What's the current snapshot version I can try?  Will you have another release soon?

**Comment by shanman190** [comment]
@iparadiso, 7.41.0-SNAPSHOT is available on sonatype's snapshot repository. Some things are in flight, but we can cut a release if you are needing these changes in one?
