### ISSUE TITLE
Duplicate @Test annotation added to method

### ISSUE THREAD

**Issue by starksm64** [openrewrite/rewrite#3260]
I have created a simple recipe to add a Junit5 @Test annotation to a method that has a legacy @testName custom javadoc tag using the latest 7.40.8 openrewrite release. A simple `RewriteTest` shows the annotation being added twice. In debugging this, the reason is that the `AnnotationMatcher("@org.junit.jupiter.api.Test")` used to validate that a method does not already have an annotation fails to match the existing annotation because the `matchesAnnotationName` call to `TypeUtils.asFullyQualified(annotation.getType())` returns null and the `annotation.getType()` returns Unknown.

Full test repo is here:
https://github.com/starksm64/tck-rewrite-tools.git

Output of mvn test:
```bash
[INFO] Running tck.conversion.rewrite.ConvertTestNameTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Visting(someTestMethod)
Found unknown block tag: testName:
Added @Test annotation?
MethodDeclaration{test.somepkg.SomeTestClass{name=someTestMethod,return=void,parameters=[]}}
Visting(someTestMethod)
Found unknown block tag: testName:
Added @Test annotation?
MethodDeclaration{test.somepkg.SomeTestClass{name=someTestMethod,return=void,parameters=[]}}
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.735 s <<< FAILURE! - in tck.conversion.rewrite.ConvertTestNameTest
[ERROR] tck.conversion.rewrite.ConvertTestNameTest.addTestAnnotation  Time elapsed: 0.729 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[Expected recipe to complete in 1 cycle, but took at least one more cycle. Between the last two executed cycles there were changes to "test/somepkg/SomeTestClass.java"] 
expected: 
  "package test.somepkg;
  
  
  public class SomeTestClass {
  
      /**
      @testName: someTestMethod
      */
      @Test
      public void someTestMethod() {
      }
  }"
 but was: 
  "package test.somepkg;
  
  
  public class SomeTestClass {
  
      /**
      @testName: someTestMethod
      */
      @Test
      @Test
      public void someTestMethod() {
      }
  }"
        at org.openrewrite.test.RecipeSchedulerCheckingExpectedCycles.scheduleVisit(RecipeSchedulerCheckingExpectedCycles.java:69)
        at org.openrewrite.RecipeScheduler.scheduleRun(RecipeScheduler.java:106)
        at org.openrewrite.Recipe.run(Recipe.java:498)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:320)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:131)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:126)
        at tck.conversion.rewrite.ConvertTestNameTest.addTestAnnotation(ConvertTestNameTest.java:18)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ConvertTestNameTest.addTestAnnotation:18 [Expected recipe to complete in 1 cycle, but took at least one more cycle. Between the last two executed cycles there were changes to "test/somepkg/SomeTestClass.java"] 
expected: 
  "package test.somepkg;
  
  
  public class SomeTestClass {
  
      /**
      @testName: someTestMethod
      */
      @Test
      public void someTestMethod() {
      }
  }"
 but was: 
  "package test.somepkg;
  
  
  public class SomeTestClass {
  
      /**
      @testName: someTestMethod
      */
      @Test
      @Test
      public void someTestMethod() {
      }
  }"
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

Code for the JavaIsoVisitor that adds the annotation [ConvertJavaTestNameVisitor.java](https://github.com/starksm64/tck-rewrite-tools/blob/02c3b59867163c3bebc212f8eaa83ea871c19939/src/main/java/tck/jakarta/platform/rewrite/ConvertJavaTestNameVisitor.java):
```java
package tck.jakarta.platform.rewrite;

import org.openrewrite.java.AnnotationMatcher;
import org.openrewrite.java.JavaIsoVisitor;
import org.openrewrite.java.JavaTemplate;
import org.openrewrite.java.tree.Comment;
import org.openrewrite.java.tree.J;
import org.openrewrite.java.tree.Javadoc;

import java.util.Comparator;

/**
 * Find methods marked with a @testName javadoc comment and add a Junit5 @Test annotation
 * @param <ExecutionContext>
 */
public class ConvertJavaTestNameVisitor<ExecutionContext> extends JavaIsoVisitor<ExecutionContext> {
    private final AnnotationMatcher TEST_ANN_MATCH = new AnnotationMatcher("@org.junit.jupiter.api.Test");

    private final JavaTemplate testAnnotationTemplate =
            JavaTemplate.builder(this::getCursor, "@Test")
                    .imports("org.junit.jupiter.api.Test")
                    .build();


    public ConvertJavaTestNameVisitor() {
    }

    @Override
    public J.MethodDeclaration visitMethodDeclaration(J.MethodDeclaration method, ExecutionContext ec) {
        String methodName = method.getSimpleName();
        if(method.getAllAnnotations().stream().anyMatch(TEST_ANN_MATCH::matches)) {
            System.out.printf("Visting(%s) skipped due to @Test\n", methodName);
            return super.visitMethodDeclaration(method, ec);
        }
        System.out.printf("Visting(%s)\n", methodName);
        for(Comment c : method.getComments()) {
            if(c instanceof Javadoc.DocComment) {
                for(Javadoc jd : ((Javadoc.DocComment) c).getBody()) {
                    if(jd instanceof Javadoc.UnknownBlock) {
                        String name = ((Javadoc.UnknownBlock) jd).getName();
                        System.out.printf("Found unknown block tag: %s\n", name);
                        if(name.equals("testName:")) {
                            method = method.withTemplate(testAnnotationTemplate,
                                    method.getCoordinates().addAnnotation(Comparator.comparing(J.Annotation::getSimpleName)));
                            System.out.println("Added @Test annotation?\n"+method);
                        }
                    }
                }
            }
        }

        return super.visitMethodDeclaration(method, ec);
    }

}
```

**Comment by timtebeek** [comment]
hi @starksm64 ! Looks like you're very close, with an implementation that's indeed a good recipe candidate. I'll try to explore here as well, but looking briefly at your implementation I have a feeling the type returns null because the annotation template (and possibly also the unit tests) might be missing a classpath entry before it's able to resolve the test annotation. Here's two examples where we similarly add a missing annotation, while providing the appropriate classpath entries:

- https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/junit5/AddMissingNested.java#L110
- https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/test/java/org/openrewrite/java/testing/junit5/AddMissingNestedTest.java#L35

Hope that already helps you debug a bit, before I'm back to work tomorrow to explore this further myself

If this is a recipe you'd like to contribute we'd also gladly accept it into https://github.com/openrewrite/rewrite-testing-frameworks

**Comment by timtebeek** [comment]
Indeed resolved with these changes: https://github.com/openrewrite/rewrite/issues/3260
I'm guessing you might still want to work on your implementation; potentially

- [ ] potentially adding `@DisplayName("<original testname>")`
- [ ] Removing the print statements
- [ ] Removing the Javadoc tag

With the classpath issues resolved I imagine the above steps will be easier, especially when you step through with the debugger. Hope this helps!

**Comment by starksm64** [comment]
@timtebeek thanks so much for the feedback and especially the PR.

In going through the docs I had the impression that recipe code saw the runtime environment classpath. Does a recipe basically need to restate any build dependency needed to have the recipe code compile?

**Comment by timtebeek** [comment]
No problem at all; happy to help & see you develop recipes; Feel free to ask more questions here, or on [our public Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA).

We should make classpath usage more explicit; as right now [the page about JavaTemplate](https://docs.openrewrite.org/authoring-recipes/modifying-methods-with-javatemplate) does not mention classpath at all. I've [logged this as an improvement](https://github.com/openrewrite/rewrite-docs/issues/170).

We do have some documentation about using classpath dependencies, but that mostly goes in depth on [using multiple different versions](https://docs.openrewrite.org/authoring-recipes/multiple-versions) in a single project. Hope that's still of some use; happy to hear any feedback such that we can improve this area of the docs still.

**Comment by timtebeek** [comment]
Also had a quick look at running recipes at scale against some of the arquillian repositories, in case that interests you; Here's a quick recipe run of some static analysis fixes as an example: https://public.moderne.io/results/LwqI7

You can run recipes against these yourself as well by [creating a repository group](https://public.moderne.io/settings/repo-groups)
![image](https://github.com/openrewrite/rewrite/assets/1027334/31508066-2ecf-490f-a440-3e9ba848ac8a)

Happy to walk you through this as well; it's another reason why it might help to have your recipes available through OpenRewrite.
