### ISSUE TITLE
`RemoveUnusedImports` removes used imports and adds duplicated ones

### ISSUE THREAD

**Issue by pzygielo** [openrewrite/rewrite#3275]
## What version of OpenRewrite are you using?
I am using
- Maven plugin v4.46.0

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a single module project

## What is the smallest, simplest way to reproduce the problem?
https://github.com/pzrep/openrewrite-unused-import-record

## What did you expect to see?
I expected to see no changes.

## What did you see instead?
https://github.com/pzrep/openrewrite-unused-import-record/actions/runs/5100022041/jobs/9168054354

Depends on number of imports done with * I guess:

1. star-import is replaced with explicit imports, including duplicated [`Record`] one:
```diff
diff --git a/src/main/java/pzrep/p2/Client1.java b/src/main/java/pzrep/p2/Client1.java
index 2533533..edfecd5 100644
--- a/src/main/java/pzrep/p2/Client1.java
+++ b/src/main/java/pzrep/p2/Client1.java
@@ -1,7 +1,10 @@
 package pzrep.p2;
 
 import pzrep.p1.Record;
-import pzrep.p1.*;
+import pzrep.p1.A;
+import pzrep.p1.B0;
+import pzrep.p1.B1;
+import pzrep.p1.Record;
 
 class Client1 {
     void f(Record r) {
```
This is unfortunate but allows to compile modified class.

2. required import gets removed
```diff
diff --git a/src/main/java/pzrep/p2/Client2.java b/src/main/java/pzrep/p2/Client2.java
index 2bb52f5..50aea66 100644
--- a/src/main/java/pzrep/p2/Client2.java
+++ b/src/main/java/pzrep/p2/Client2.java
@@ -1,6 +1,5 @@
 package pzrep.p2;
 
-import pzrep.p1.Record;
 import pzrep.p1.*;
 
 class Client2 {
```
This makes modified source to be uncompilable. (That's the original issue I observed with https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Record.html)

**Comment by pzygielo** [comment]
I see that duplicated `Record` import (p. 1 above) is no longer inserted (looks that something in maven plugin [5.0.0->5.2.1](https://github.com/openrewrite/rewrite-maven-plugin/compare/v5.0.0...v5.2.1) helps :smile:)

**Comment by joanvr** [comment]
this was very kindly fixed by @tclayton-newr in #3397; you can already try this in our [snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions), or with the next release in a week or so

**Comment by pzygielo** [comment]
Still having my `Record` removed in
- https://github.com/pzrep/openrewrite-unused-import-record/pull/8

**Comment by pzygielo** [comment]
Still having my `Record` removed in
- https://github.com/pzrep/openrewrite-unused-import-record/pull/9

**Comment by pzygielo** [comment]
Could this be reopened (or cloned to new one if needed) by maintainers, please?
