### ISSUE TITLE
Missing space before extends/implements using ClassDeclaration#withExtends/withImplements

### ISSUE THREAD

**Issue by MBoegers** [openrewrite/rewrite#3289]
## What version of OpenRewrite are you using?
I am using https://github.com/openrewrite/rewrite Branch: main Commit: 9d567a3ba281285d8b20f942921f98e7fcc0ee35

## How are you running OpenRewrite?
I wrote a reproducing test.

## What is the smallest, simplest way to reproduce the problem?
Find a reproducer test here https://gist.github.com/MBoegers/072b1412e9fee01b4728a61e68f44562

## What did you expect to see?
Extending a class with java.util.ArrayList:
**Input:**
```java
class CustomList {}
```
**Result:**
```java
class CustomList extends java.util.ArrayList {}
```

A class implementing java.io.Serializable:
**Input:**
```java
class CustomList {}
```
**Result:**
```java
class CustomList implements java.io.Serializable {}
```

## What did you see instead?
Extending a class with java.util.ArrayList:
```java
class CustomListextends java.util.ArrayList {}
```

A class implementing java.io.Serializable:
```java
class CustomListimplements java.io.Serializable {}
```

## What is the full stack trace of any errors you encountered?
Extending a class with java.util.ArrayList:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

[Unexpected result in "de/example/CustomList.java"
diff --git a/de/example/CustomList.java b/de/example/CustomList.java
index e454a71..a71d73b 100644
--- a/de/example/CustomList.java
+++ b/de/example/CustomList.java
@@ -1,4 +1,4 @@ 
 package de.example;
 
-class CustomList extends java.util.ArrayList {
+class CustomListextends java.util.ArrayList {
 }
\ No newline at end of file
] 
expected: 
  "package de.example;
  
  class CustomList extends java.util.ArrayList {
  }"
 but was: 
  "package de.example;
  
  class CustomListextends java.util.ArrayList {
  }"
org.opentest4j.AssertionFailedError: [Unexpected result in "de/example/CustomList.java"
diff --git a/de/example/CustomList.java b/de/example/CustomList.java
index e454a71..a71d73b 100644
--- a/de/example/CustomList.java
+++ b/de/example/CustomList.java
@@ -1,4 +1,4 @@ 
 package de.example;
 
-class CustomList extends java.util.ArrayList {
+class CustomListextends java.util.ArrayList {
 }
\ No newline at end of file
] 
expected: 
  "package de.example;
  
  class CustomList extends java.util.ArrayList {
  }"
 but was: 
  "package de.example;
  
  class CustomListextends java.util.ArrayList {
  }"
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:446)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:125)
	at app//org.openrewrite.java.tree.WithMissPaddingReproducer$WithExtendsTest.triggerIt(WithMissPaddingReproducer.java:90)
```
A class implementing java.io.Serializable:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

[Unexpected result in "de/example/CustomList.java"
diff --git a/de/example/CustomList.java b/de/example/CustomList.java
index 5be0342..4514ef4 100644
--- a/de/example/CustomList.java
+++ b/de/example/CustomList.java
@@ -1,4 +1,4 @@ 
 package de.example;
 
-class CustomList implements java.io.Serializable {
+class CustomListimplements java.io.Serializable {
 }
\ No newline at end of file
] 
expected: 
  "package de.example;
  
  class CustomList implements java.io.Serializable {
  }"
 but was: 
  "package de.example;
  
  class CustomListimplements java.io.Serializable {
  }"
org.opentest4j.AssertionFailedError: [Unexpected result in "de/example/CustomList.java"
diff --git a/de/example/CustomList.java b/de/example/CustomList.java
index 5be0342..4514ef4 100644
--- a/de/example/CustomList.java
+++ b/de/example/CustomList.java
@@ -1,4 +1,4 @@ 
 package de.example;
 
-class CustomList implements java.io.Serializable {
+class CustomListimplements java.io.Serializable {
 }
\ No newline at end of file
] 
expected: 
  "package de.example;
  
  class CustomList implements java.io.Serializable {
  }"
 but was: 
  "package de.example;
  
  class CustomListimplements java.io.Serializable {
  }"
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:446)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:130)
	at app//org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:125)
	at app//org.openrewrite.java.tree.WithMissPaddingReproducer$WithImplementsTest.triggerIt(WithMissPaddingReproducer.java:119)
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Maybe after my current PR.

**Comment by timtebeek** [comment]
No need to reopen; I've just transferred the issue; thanks again for the detailed report! This is really helpful.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by timtebeek** [comment]
Appreciate the offer to help @tarunsamanta2k20 ! Feel free to start a draft pull request with the above replicating test early. That way you (and I) can step through with the debugger.

**Comment by tarunsamanta2k20** [comment]
@timtebeek could you please let me know in which file do i have to make changes?

**Comment by timtebeek** [comment]
You can add the tests that @MBoegers has provided in https://gist.github.com/MBoegers/072b1412e9fee01b4728a61e68f44562 to the bottom of [ClassDeclarationTest.java](https://github.com/openrewrite/rewrite/blob/main/rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ClassDeclarationTest.java) as a start. Then you can already open a draft pull request to replicate the issue here, and then we can start stepping through with the debugger to see what causes the issue. I'm suspecting a lack of padding or prefix to the initial `implents` or `extends`.

**Comment by timtebeek** [comment]
Having briefly explored the issue here I think we might need to make this change to fix the issue for `withImplements/withExtends`, but I'm uncertain if that will cause any other issues. We'll have to find out on your branch!

```diff
diff --git a/rewrite-java/src/main/java/org/openrewrite/java/tree/JContainer.java b/rewrite-java/src/main/java/org/openrewrite/java/tree/JContainer.java
index c0316ea16..0b5642727 100644
--- a/rewrite-java/src/main/java/org/openrewrite/java/tree/JContainer.java
+++ b/rewrite-java/src/main/java/org/openrewrite/java/tree/JContainer.java
@@ -158,7 +158,7 @@ public static <J2 extends J> JContainer<J2> withElementsNullable(@Nullable JCont
             if (elements == null || elements.isEmpty()) {
                 return null;
             }
-            return JContainer.build(Space.EMPTY, JRightPadded.withElements(emptyList(), elements), Markers.EMPTY);
+            return JContainer.build(Space.SINGLE_SPACE, JRightPadded.withElements(emptyList(), elements), Markers.EMPTY);
         }
         if (elements == null || elements.isEmpty()) {
             return null;
```

**Comment by AlexanderSkrock** [comment]
Hi together,

I approached this behaviour myself when implementing something and wanted this fixed. As there was some time since the last update, I decided to fix it myself. I hope you do not mind, @tarunsamanta2k20 .

Kind regards
Alexander Skrock

**Comment by knutwannheden** [comment]
@AlexanderSkrock After a discussion in the team we decided to revert [your PR](#3511) again. This in order to maintain a clear separation of concerns, well aware that this may end up surprising recipe authors when running into this particular issue. The LST model is intentionally kept "dumb" and the recipe is basically in full control.

To resolve this particular type of problem, the recipe should wrap the modification (here `ClassDeclaration#withwithImplements()`) in a call to `maybeAutoFormat()` to resolve the problem.

**Comment by AlexanderSkrock** [comment]
I understand the separation of concerns. This portion of code should not care about formatting. The LST model during runtime is valid. Still, I would expect any method provided by the java api to result in valid code, which is currently not the case. Could we possible delegate this issue to the `JavaPrinter` or would you still insist to leave this problem to the recipe implementer as rewrite itself does not want to care about formatting.

**Comment by knutwannheden** [comment]
Delegating to the printer was also discussed. In this particular case it may seem trivial, but whitespace can often be attached at different levels of the LST and it would be non-trivial for the printer to have to work out for each case when some additional whitespace would have to be added and when not. Therefore, for consistency, it currently remains the responsibility of the modifying recipe to add any required whitespace to the LST.

**Comment by knutwannheden** [comment]
I understand where you are coming from. Sometimes there is just no good compromise between conflicting concern. 🤷
