### ISSUE TITLE
Wrong value for document.getSourcePath().toFile().getAbsolutePath()

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#3297]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite bom v1.19.4
- Maven/Gradle plugin v4.46.0
- OPEN_REWRITE_MIGRATE_JAVA_VERSION="1.21.1"

## What is the smallest, simplest way to reproduce the problem?

```java
public class FakeRecipe extends Recipe {


    @Override
    public String getDisplayName() {
        return "FakeRecipe";
    }

    @JsonCreator
    public FakeRecipe() {

    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {

        return new MavenVisitor<ExecutionContext>() {
            @Override
            public Xml visitDocument(Xml.Document document, ExecutionContext ctx) {
                System.out.println("FakeRecipe document.getSourcePath():" + document.getSourcePath());
                System.out.println("FakeRecipe document.getSourcePath().toFile():" + document.getSourcePath().toFile());
                System.out.println("FakeRecipe document.getSourcePath().toFile().getAbsolutePath():" + document.getSourcePath().toFile().getAbsolutePath());
                return super.visitDocument(document, ctx);
            }


        };
    }
}
```

## What did you expect to see?

- First log: `FakeRecipe document.getSourcePath():modules\conf\pom.xml` => OK
- Second log: `FakeRecipe document.getSourcePath().toFile():modules\conf\pom.xml` => OK
- Third log: `FakeRecipe document.getSourcePath().toFile().getAbsolutePath():C:\Users\me\workspace\springboot-migration\src\main\workspace\modules\modules\conf\pom.xml` => KO (**modules** appears twice)

## What did you see instead?

FakeRecipe document.getSourcePath().toFile().getAbsolutePath():C:\Users\me\workspace\springboot-migration\src\main\workspace\modules\conf\pom.xml  (modules has to apears only one time because its really the place where my file is)

**Comment by timtebeek** [comment]
That's really weird how we can get that wrong. I wonder if it's the same on all platforms, as I don't have access to a windows machine. 🤔 I'll try it on Linux tomorrow, hopefully it replicates in a unit test.

**Comment by shanman190** [comment]
So to me this looks like a current working directory issue to me. It's only at the point where the invocation to `getAbsolutePath()` goes ahead and looks up the current working directory to resolve the fully qualified path from the relative path. All of that logic is going to be intrinsic to the Java language though and not specifically rewrite. In your test case, would you mind also printing out what `new File(".").getAbsolutePath()` shows as well?

**Comment by timtebeek** [comment]
Made a quick attempt to replicate this in a unit test on Ubuntu linux; no such issues yet unfortunately:
```java
package org.openrewrite.maven;

import org.junit.jupiter.api.Test;
import org.openrewrite.ExecutionContext;
import org.openrewrite.test.RewriteTest;
import org.openrewrite.xml.tree.Xml;

import java.io.File;

import static org.openrewrite.maven.Assertions.pomXml;

class SourcePathAbsolutePathTest implements RewriteTest {
    @Test
    void sourcePathAbsolutePath() {
        MavenVisitor<ExecutionContext> mavenVisitor = new MavenVisitor<>() {
            @Override
            public Xml visitDocument(Xml.Document document, ExecutionContext executionContext) {
                System.out.println("FakeRecipe document.getSourcePath(): " + document.getSourcePath());
                System.out.println("FakeRecipe document.getSourcePath().toFile(): " + document.getSourcePath().toFile());
                System.out.println("FakeRecipe document.getSourcePath().toFile().getAbsolutePath(): " + document.getSourcePath().toFile().getAbsolutePath());
                System.out.println("FakeRecipe new File(\".\").getAbsolutePath(): " + new File(".").getAbsolutePath());
                return super.visitDocument(document, executionContext);
            }
        };
        rewriteRun(spec -> spec.recipe(RewriteTest.toRecipe(() -> mavenVisitor)),
          pomXml("""
              <project>
                <groupId>com.mycompany.app</groupId>
                <artifactId>my-app</artifactId>
                <version>1</version>
              </project>
              """,
            sourceSpecs -> sourceSpecs.path("modules/conf/pom.xml")
          ));
    }
}
```
Does that show the issue for you still @jdelobel ?

**Comment by timtebeek** [comment]
Thanks for reporting back here @jdelobel ! Feel free to reopen or open an new issue if necessary in the future.
