### ISSUE TITLE
YAML encoding errors with Windows 

### ISSUE THREAD

**Issue by thomaszub** [openrewrite/rewrite#3312]
## What version of OpenRewrite are you using?
I am using

- OpenRewrite v8.0.0
- Maven plugin v5.0.0

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a single module project.

## What is the smallest, simplest way to reproduce the problem?
```yaml
some: # german umlaute äöü
    key: value
```

## What did you expect to see/What did you see instead?
After applying a YAML recipe, the encoding is broken.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Yes, I make a PR.

**Comment by timtebeek** [comment]
Appreciate you're looking to provide a fix!
 -- Timotheüs

**Comment by knutwannheden** [comment]
@thomaszub Just for clarification: Is this issue new with OpenRewrite 8.0? Did this work as expected with older versions?

**Comment by thomaszub** [comment]
@knutwannheden: I tested it with the maven-plugin 4.42.0 (rewrite 7.38.0) and the bug is present.
