### ISSUE TITLE
`AddDependencyTest` is broken on `main`

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite#3343]
It looks like the `AddDependencyTest` is broken on the `main` branch:

https://ge.openrewrite.org/scans/tests?search.timeZoneId=America/New_York&tests.container=org.openrewrite.gradle.AddDependencyTest&tests.test=addDependenciesWithoutVersionWithClassifierToExistingGrouping()

**Comment by JLLeitschuh** [comment]
It looks like following tests are also failing:
 - [AddGradleEnterpriseTest](https://ge.openrewrite.org/s/27v6d3z3wu32w/tests/:rewrite-gradle:test/org.openrewrite.gradle.plugins.AddGradleEnterpriseTest)
 - [AddSettingsPluginRepositoryTest](https://ge.openrewrite.org/s/27v6d3z3wu32w/tests/:rewrite-gradle:test/org.openrewrite.gradle.plugins.AddSettingsPluginRepositoryTest)
 - [AddBuildPluginTest](https://ge.openrewrite.org/s/27v6d3z3wu32w/tests/:rewrite-gradle:test/org.openrewrite.gradle.plugins.AddBuildPluginTest)
 - [AddSettingsPluginTest](https://ge.openrewrite.org/s/27v6d3z3wu32w/tests/:rewrite-gradle:test/org.openrewrite.gradle.plugins.AddSettingsPluginTest)
 - [GroovyVisitorTest](https://ge.openrewrite.org/s/27v6d3z3wu32w/tests/:rewrite-groovy:test/org.openrewrite.groovy.GroovyVisitorTest)

https://ge.openrewrite.org/s/27v6d3z3wu32w/tests/overview?outcome=failed&suite-outcome-details=:rewrite-gradle:test-1-org.openrewrite.gradle.plugins.addgradleenterprisetest-262

**Comment by JLLeitschuh** [comment]
And `MigrateJavaTemplateToRewrite8Test`

**Comment by JLLeitschuh** [comment]
Temporarily disabled the failing tests to unblock `main`: https://github.com/openrewrite/rewrite/commit/79cff476f2a04e8164af1b2d49752128160f8a41

**Comment by joanvr** [comment]
Could you check if they are still failing?

**Comment by JLLeitschuh** [comment]
Everything works now! Thanks!
