### ISSUE TITLE
NoSuchMethodError with MethodMatcher calls

### ISSUE THREAD

**Issue by maxxedev** [openrewrite/rewrite#3365]
## What version of OpenRewrite are you using?

I am using the latest version

## How are you running OpenRewrite?
```
mvn clean org.openrewrite.maven:rewrite-maven-plugin:5.2.3:run     \
 -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:2.0.0      \
 -Drewrite.activeRecipes=org.openrewrite.java.migrate.UpgradeToJava17  
```

## What did you see instead?
```
java.lang.NoSuchMethodError: 'boolean org.openrewrite.java.MethodMatcher.matches(org.openrewrite.java.tree.J$MethodInvocation)'
  org.openrewrite.java.migrate.lang.MigrateClassLoaderDefineClass$1.visitMethodInvocation(MigrateClassLoaderDefineClass.java:57)
  org.openrewrite.java.migrate.lang.MigrateClassLoaderDefineClass$1.visitMethodInvocation(MigrateClassLoaderDefineClass.java:48)
```

Please revert changes to MethodMatcher that deleted some public methods

v8.1.2
https://github.com/openrewrite/rewrite/blob/v8.1.2/rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java#L219-L228

v8.1.3
https://github.com/openrewrite/rewrite/blob/v8.1.3/rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java#L270

The method is called by several recipes:
[BigDecimalRoundingConstantsToEnums](https://github.com/openrewrite/rewrite-static-analysis/blob/a6e524cccef1417e2461fb33bfae25846c9166a2/src/main/java/org/openrewrite/staticanalysis/BigDecimalRoundingConstantsToEnums.java#L80), [MigrateClassLoaderDefineClass](https://github.com/openrewrite/rewrite-migrate-java/blob/927b01de8e8fd8f1ab68bc934a860043e0eba441/src/main/java/org/openrewrite/java/migrate/lang/MigrateClassLoaderDefineClass.java#L29)

**Comment by maxxedev** [comment]
See also pull request https://github.com/openrewrite/rewrite/pull/3342

**Comment by timtebeek** [comment]
Thanks fort he help in working through this! Quick recap of what was discussed on Slack: There's been a change to rewrite MethodMatcher that's merely source compatible, not binary compatible. As a result we're doing patch releases where we can to pick up this change. There's newer versions of the plugin, rewrite-static-analysis and rewrite-migrate-java already; will follow up with patch releases of rewrite-spring and rewrite-recipe-bom to resolve all of this.

**Comment by timtebeek** [comment]
Likely resolved through
https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v5.2.4
https://github.com/openrewrite/rewrite-static-analysis/releases/tag/v1.0.2
https://github.com/openrewrite/rewrite-migrate-java/releases/tag/v2.0.3
https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.0.3
