### ISSUE TITLE
Rewrite 8.x upgrade recipes should add/update dependencies

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#3371]
## What problem are you trying to solve?
As part of the 8.x release we've both automated and documented the migration steps, but these steps are incomplete:
https://github.com/openrewrite/rewrite/tree/main/rewrite-java/src/main/java/org/openrewrite/java/recipes
https://docs.openrewrite.org/changelog/8-1-2-release

The recipes do not yet update the version numbers of rewrite-recipe-bom, or rewrite modules themselves, which could be a fairly easy addition with the existing recipes we have for Maven and Gradle dependencies.

The `UpdateMovedRecipe` also currently does not add a dependency on rewrite-static-analysis, which is required when using any of those recipes.

To add / update dependencies, we can either use `rewrite-maven` or `rewrite-gradle` directly, or use `rewrite-java-dependencies`. Both options would require the rewrite recipes to move outside of `rewrite-java` (to prevent cycles), either into a separate sub module in openrewrite/rewrite, or into a separate repository under the openrewrite GitHub organization.

## What precondition(s) should be checked before applying this recipe?
An `onlyIfUsing` on `org.openrewrite.staticanalysis` before adding `rewrite-static-analysis`.

## Describe the situation before applying the recipe
Dependencies left on 7.x, with classes not found for `org.openrewrite.staticanalysis`.

## Describe the situation after applying the recipe
Dependencies upgraded to 8.x, or respective module or bom version.

## Have you considered any alternatives or workarounds?
We can not do any of the above, and merely document these changes.
But then we will have similar issues in the future when automating upgrades.

**Comment by timtebeek** [comment]
@kunli2 I'd be interested in your thoughts on this; not necessarily as something to pick up immediately, but mostly if the move and upgrades make sense.

**Comment by kunli2** [comment]
Since it's not widely used and the hardest part for users is to do code changes, so I would like to leave it as manual work for the user to update dependency as the last step. but adding recipes is also fine.

**Comment by timtebeek** [comment]
These recipes have since been removed, so we can close this issue that proposed to update them: https://github.com/openrewrite/rewrite/compare/36acdbb130d923a7231d26b8678d107f6f4202d7...ae17d87a37631d1c434d8b077b450a3389fdb3d2
