### ISSUE TITLE
Checkstyle automatic fix not working

### ISSUE THREAD

**Issue by k12dbrantley** [openrewrite/rewrite#3374]
I am following the instructions at 
https://docs.openrewrite.org/running-recipes/popular-recipe-guides/automatically-fix-checkstyle-violations

When I try to run the rewrite in gradle it fails with the following error

* What went wrong:
Execution failed for task ':rewriteRun'.
> org.openrewrite.RecipeException: Recipes not found: org.openrewrite.java.cleanup.Cleanup

I also have not been able to find a Cleanup.java in openrewrite repo. 
Are the instructions at the link above current?

**Comment by timtebeek** [comment]
Hi yes sorry about that! You're not the first today; we need to update our documentation, as noted in https://github.com/openrewrite/rewrite-docs/issues/190
I hope you don't mind me closing this issue; you can follow along to the other one that's already in the rewrite-docs repository where the fix will go.
