### ISSUE TITLE
Maven settings.xml file causes infinite loop when running maven plugin

### ISSUE THREAD

**Issue by fastCapybara** [openrewrite/rewrite#3376]
## What version of OpenRewrite are you using?

I am using

- Maven plugin v4.46.0

## Background

I'm looking into using OpenRewrite, but having an issue with the Maven plugin when trying to use the command 'mvn rewrite:run' causes the plugin to go into an infinite loop when it gets to a part where the command line outputs "Project [project name] Resolving Poms". This happens with every project I've tried running it on, including the sample petclinic project with sample recipes in the [getting started guide](https://docs.openrewrite.org/running-recipes/getting-started).

This seems to be happening because I'm using a custom settings.xml file that points to internal Maven repositories/mirrors for my organization and the main OpenRewrite library isn't handling that correctly.

Adding the skipMavenParsing option gets the rest of the plugin to run properly in my case, but I would like to have it update the pom files in the future.

## Details

From what I can tell, the root cause of the problem is that in the file 'rewrite-maven\src\main\java\org\openrewrite\maven\tree\\[MavenRepositoryMirror.java](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java)' line 56 should be
```java
        while (!next.equals(mapped)) {
```
instead of
```java
        while (next != mapped) {
```
Here's the full method this line is in:
```java
    public static MavenRepository apply(Collection<MavenRepositoryMirror> mirrors, MavenRepository repo) {
        MavenRepository mapped = repo;
        MavenRepository next = null;
        while (next != mapped) {
            next = mapped;
            for (MavenRepositoryMirror mirror : mirrors) {
                mapped = mirror.apply(mapped);
            }
        }
        return mapped;
    }
```
The mirror.apply(mapped) call on line 59 can return a new object, and if mapped gets set to a new object reference, the while loop will never stop. This is because it's comparing object references and not comparing by using the .equals method. Given what I have in my settings.xml file, the populated mirrors collection causes an infinite loop.

Here's the relevant part of the stack trace:
```
... later calls
matches:110, MavenRepositoryMirror (org.openrewrite.maven.tree)
apply:66, MavenRepositoryMirror (org.openrewrite.maven.tree)
apply:59, MavenRepositoryMirror (org.openrewrite.maven.tree) <- where the infinite loop is happening
applyMirrors:807, MavenPomDownloader (org.openrewrite.maven.internal)
normalizeRepository:654, MavenPomDownloader (org.openrewrite.maven.internal)
normalizeRepository:648, MavenPomDownloader (org.openrewrite.maven.internal)
distinctNormalizedRepositories:636, MavenPomDownloader (org.openrewrite.maven.internal)
download:476, MavenPomDownloader (org.openrewrite.maven.internal)
resolveParentPom:416, ResolvedPom$Resolver (org.openrewrite.maven.tree)
resolveParentPropertiesAndRepositoriesRecursively:356, ResolvedPom$Resolver (org.openrewrite.maven.tree)
resolveParentsRecursively:313, ResolvedPom$Resolver (org.openrewrite.maven.tree)
resolve:302, ResolvedPom$Resolver (org.openrewrite.maven.tree)
resolve:144, ResolvedPom (org.openrewrite.maven.tree)
resolve:104, Pom (org.openrewrite.maven.tree)
parseInputs:106, MavenParser (org.openrewrite.maven)
parse:41, Parser (org.openrewrite)
parseMaven:385, MavenMojoProjectParser (org.openrewrite.maven)
listResults:276, AbstractRewriteMojo (org.openrewrite.maven)
execute:54, AbstractRewriteRunMojo (org.openrewrite.maven)
executeMojo:134, DefaultBuildPluginManager (org.apache.maven.plugin)
... earlier calls
```
Heres a modified snippet of the mirrors configuration in my settings.xml:
```
<mirrors>
  <mirror>
    <id>org.snapshots.mirror</id>
    <name>Snapshots Repository</name>
    <url>http://maven.example.local:10001/maven/content/public-snapshots</url>
    <mirrorOf>public-snapshots</mirrorOf>
  </mirror>
  <mirror>
    <id>org.releases.mirror</id>
    <name>Maven Repository</name>
    <url>http://maven.example.local:10001/maven/content/public</url>
    <mirrorOf>*</mirrorOf>
  </mirror>
</mirrors>
```
I would submit a pull request to fix this, but I'm not certain what these calls to normalizeRepository and applyMirrors are supposed to do or if changing this line would have an impact on intended behavior. I'm also not certain that the issue isn't on my end, e.g. I need to change my settings.xml file.

**Comment by timtebeek** [comment]
Hi @fastCapybara ; thanks for the immediate detailed analysis! Welcome  to open up a draft pull request such that we similarly can have a look. Plus if you install and run that locally you can then immediately see if that resolves your issue.

**Comment by timtebeek** [comment]
Fixed in 
- #3545
