### ISSUE TITLE
Auto formatting breaks Groovy/Gradle files

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite#3388]
## What version of OpenRewrite are you using?

I am using
- OpenRewrite v8.1.5
- Gradle plugin v6.1.8

## How are you running OpenRewrite?

I am using the Gradle plugin, and my project is a single module project. I am doing a fresh checkout of the [Spring PetClinic Migration repository](https://github.com/openrewrite/spring-petclinic-migration) that is described in the OpenRewrite docs.

## What is the smallest, simplest way to reproduce the problem?

Here is the [build.gradle file](https://gist.github.com/mike-solomon/5d040e52948df545c31a9196ff1cc73f) after I added OpenRewrite and the AutoFormat recipe.

If you do a rewrite run at that point, the `build.gradle` file will be formatted in such a way that it completely breaks. 

[Here is what it looks like after rewrite has run](https://gist.github.com/mike-solomon/587a780e6538ad7f1410eea9d06b0b29). You can see that there are no spaces anymore between things like `id` and the name of the plugin or `implementation` and the link to the dependency.

## What did you expect to see?
I would have expected the AutoFormat recipe to not destroy the `build.gradle` file and, instead, format the code in a way that it still functions.

**Comment by sambsnyd** [comment]
Should be fixed by https://github.com/openrewrite/rewrite/commit/64a8c36c3d9f4aed7e4fa6442e7fd22a3cd66690
