### ISSUE TITLE
User properties in `.mvn/maven.settings` should be read

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite#3409]
## What version of OpenRewrite are you using?

I am using

- rewrite-maven:8.1.6

## What is the smallest, simplest way to reproduce the problem?
- Parse the pom in the [maven-config.zip](https://github.com/openrewrite/rewrite/files/12022259/maven-config.zip) project 
- the parser fails to retrieve the user properties 
- the dependency can't be resolved

[Here's](https://github.com/corona-warn-app/cwa-server/tree/v3.2.0) a real-world example using this feature.

## What did you expect to see?
The user properties should be read.

## Are you interested in [contributing a fix to OpenRewrite]
The Regex in `MavenParser:178` should be fixed to interpret "-D" or even -define (?) as user-property.
`Pattern.compile("(?:$|\\s)-P\\s+([^\\s]+)").matcher(mavenConfigText);`

````java
    @Test
    @DisplayName("Should Read .mvn/maven.config")
    void shouldReadMvnMavenConfig() {
        String mavenConfig = """
                -Drevision=42
                -Dvalidation-api.version=2.0.1.Final
                -Psome-profile,another-profile
                """;

        Stream<SourceFile> parse = MavenParser.builder().build().parse(List.of(Path.of("./testcode/maven-projects/maven-config").resolve("pom.xml")), null, new InMemoryExecutionContext(t -> {
            t.printStackTrace();
            fail("exception");
        }));

    }
}
````

**Comment by joanvr** [comment]
Hi @fabapp2, thanks for your time and opening this issue. Since you already provided some example in the "Are you interested in" section... Can I assume you interested in contributing and providing a fix for this issue? Shall I assign it to you?
Many thanks in advance :)

**Comment by fabapp2** [comment]
Hi @joanvr, sorry for my late reply. 
I would not dare to "improve" the existing regex and replace this approach.
In SBM I "borrowed" code from Maven, what about just using [this](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/spike/rewrite-maven-parser/sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/MavenConfigFileParser.java)?

**Comment by fabapp2** [comment]
Hi @joanvr. I fixed the link☝️

**Comment by fabapp2** [comment]
The properties cannot be set in MavenParser, like e.g. `activeProfiles`.
This would probably be a largeer change(?).
I discussed with @timtebeek that we close this for now as it is a corner case.
