### ISSUE TITLE
UpgradeDependencyVersion unnecessarily adds explicit version numbers that are fully specified by the parent pom 

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite#344]
Maven dependency version upgrades add versions to dependencies where they're not necessary when parent projects define dependency versions in dependency management. As an example, rewrite-spring contains UpgradeDependency version on groupId org.springframework.boot to 2.x as well as UpgradeParentVersion for spring-boot-starter-parent to 2.x. When upgrading spring-petclinic, it updates the spring-boot-parent version, which is correct, but it also adds versions to all spring-boot dependencies, which is unnecessary.

**Comment by okundzich** [comment]
See also #341

**Comment by sambsnyd** [comment]
While we now have a recipe/visitor to accomplish this kind of task, UpgradeDependencyVersion and UpgradeParentVersion doesn't yet use it.
