### ISSUE TITLE
Parsing error of annotation between array dimensions

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite#3453]
We found this parsing error from https://github.com/openrewrite/rewrite/issues/2911
to parse annotation between array dimensions

Here is a example failing test
``` java
    @Test
    void annotationBetweenDimensions() {
        rewriteRun(
          java(
            """
              import javax.annotation.Nonnull;

              class ArrayNotNull {
                  int[][] ints = new int[2][2];

                  public int   @Nonnull    [] @Nonnull [] getInts() {
                      return ints;
                  }
              }
              """
          )
        );
    }
```

I think the problem is currently we don't store annotations in `J.ArrayType#dimensions` [code](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/tree/J.java#L312)
a possible solution is to change dimensions data structure from
`List<JRightPadded<Space>> dimensions;` to `List<JRightPadded<Annotation>> dimensions;`  

[slack discussion](https://rewriteoss.slack.com/archives/C01A843MWG5/p1691016514187669)

**Comment by traceyyoshima** [comment]
@knutwannheden, an additional annotation position is not covered by the issue in `J.NewArray`. However, `J.NewArray` and `J.ArrayType` represent dimensions differently. The `J.NewArray#dimensions` is a `List<ArrayDimension>` instead of a `Space`. So, to solve `J.NewArray`, we could add a nullable list of annotations field.

A nullable field would affect `J.ArrayAccess`, which uses `ArrayDimension` and would always have a null annotation field since annotations are not permitted on array access.

```java
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

class ArrayNotNull {
    // J$ArrayType
    Integer @TypeUsePosAnn [] @TypeUsePosAnn [] ints =
    // J$NewArray
    new Integer @TypeUsePosAnn [2] @TypeUsePosAnn [2];
}

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE_USE})
@interface TypeUsePosAnn {}
```

**Comment by knutwannheden** [comment]
See also these earlier attempts at fixing this: #3464 and #2635. They were never completed but maybe contain something useful.

**Comment by knutwannheden** [comment]
I thought I had worked out a somewhat elegant solution at some point, but it looks like I never documented this anywhere. But using the `@JsonConstructor` approach we should also be able to change the API while remaining backward compatible, without too much of a hassle.

**Comment by traceyyoshima** [comment]
I've written a document with various considerations on resolving the parsing issues, along with details for backward compatibility. I'll update the issue after we've discussed the pros/cons of the various solutions.
