### ISSUE TITLE
Maven dependencyManagement is incorrectly taking precedence over listed dependency versions, does not match Maven's behavior 

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#346]
The managed version of a dependency is always taking precedence over a version that has been initially overridden in a child project. This does not match the behavior of Aether

**Comment by sambsnyd** [comment]
I've fixed a _piece_ of this issue in this commit: https://github.com/openrewrite/rewrite/commit/5c6f274d90bc89b83b845ee17f32143a0238d1d4

Now dependencyManagement _scope_ no longer takes precedence over an explicitly specified dependency scope. Other aspects of this issue remain to be fixed

**Comment by tkvangorder** [comment]
Rewrite's maven resolution has been substantially updated to match Maven's resolution model. 

The significant fixes include: 

14c58f5c1ad7aa9086f0906f338c78b25d11c0ec
942dc0620e042962aff91e2b8a204a633c2747bc
668a767fca6686858101383621ec0e726833ce50
b747c37c14ef391b2b23fd4949b8ed632ceaf5f3
db48251baeb3d24c3672f95d070640e029df549e
d70058f9f345050aafbc2c430d37aa56ec391c86
a1e56c5d252c7081e799bf89462f18d7abe509b0
74bde1f9bf3cafff454500b5d698ca60dbb297e8
073a7a57d101ffed66c92b05de737eff79da7b23
4b8e420fed9b45edbcd20cccb3cd0aa4c5b57ac3
