### ISSUE TITLE
[Feedback] Github Oauth2 Authorization requires access to private repos

### ISSUE THREAD

**Issue by FabianUntermoser** [openrewrite/rewrite#3461]
Hi !

I'm curious why you require to allow access to private repos as well.
With no explanation on this matter, me and I'm sure many others will abort trying out moderne.io

Thanks

**Comment by zieka** [comment]
Hi Fabian,
Thanks for reaching out.  With regards to moderne.io there is a doc site which includes explanation of the permissions here:
https://docs.moderne.io/references/github-permissions

Our application tenant is configured with this option currently, as you noted.   
This means that currently you do not need to grant these permissions to log in, browser, run recipes, etc.
You will be prompted for more permissions when viewing results or trying to issue commits in any form (forks, etc)

We can look into possible adjustments to make on our end to narrow when the permission request is made.

Hope this provides some clarity.

**Comment by FabianUntermoser** [comment]
Thanks @zieka for the quick response!

Good idea with the delay of the log in. Makes it frictionless to check out your tenant.

If the docs state access to private repos as optional, I'd like to suggest making this an opt-in feature.
That would increase the plattforms trustworthyness.

With this suggestion out I'm fine with closing this issue.
