### ISSUE TITLE
Unexpected return type when adding constructor method by Java template

### ISSUE THREAD

**Issue by i059917** [openrewrite/rewrite#3500]
When I try to simply add a empty constructor method to a test class by using Java template in my customized recipe, after code refactoring, the constructor is generated but with a returned type 'Template' which is not expected there:

Here is my code snippet of my recipe:
```java
final JavaTemplate template = JavaTemplate.builder("public TestClass() {\n" +
                    "        \n" +
                    "    }").build();
classDeclaration = classDeclaration.withBody(template.apply(new Cursor(getCursor(), classDeclaration.getBody()),
            classDeclaration.getBody().getCoordinates().firstStatement()));
System.out.println(TreeVisitingPrinter.printTree(getCursor()));
return classDeclaration;
```

And the output is like this:
![image](https://github.com/openrewrite/rewrite/assets/9570835/c70b2a4e-f7cb-407d-bea5-f8abc46680f0)

I tried to add a merbership method to a class, it works good. Not sure is this an issue when adding contructor method? Or probably I didn't handle it correctly...

Btw, my case is trying to add some constructors definition for some code refactoring requirement. e.g. add protected access constructor instead of leave it with a default public constructor to some classes.

**Comment by knutwannheden** [comment]
Thank you for reaching out. I suspect that your template may work properly if you call the `contextSensitive()` method on `JavaTemplate.Builder`. This is always required when your template references variables or types which aren't part of the template themselves or one of the template parameters. Let me know if this doesn't help.

**Comment by i059917** [comment]
@knutwannheden it works after add contextSensitive(). thank you!
