### ISSUE TITLE
Maven recipe: Migrate usage of `${artifactId}` to `${project.artifactId}`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#3510]
## What problem are you trying to solve?

Handle the following Maven deprecation warning

```

[WARNING] 
[WARNING] Some problems were encountered while building the effective model for xxx
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```

## Describe the solution you'd like

Instances of `${artifactId}` should be replaced with `${project.artifactId}` 

## Additional context

This properly can be used in many places within a maven build. For example, besides the `pom.xml` file, it is possible to define this in `assembly.xml` and possibly other files 

Examples : 

`pom.xml`

```xml

<build>
        <finalName>${artifactId}</finalName>
</build>
```

`assembly.xml` 

```xml
 <file>
            <source>target/${artifactId}.jar</source>
            <outputDirectory>output</outputDirectory>
            <destName>${artifactId}.jar</destName>
        </file>
```

**Comment by knutwannheden** [comment]
AFAIK the same applies to `$version` unless we already have a recipe for that.

**Comment by yeikel** [comment]
> AFAIK the same applies to `$version` unless we already have a recipe for that.

Should that be a separate recipe or the same?

**Comment by knutwannheden** [comment]
IMHO it should be part of the same recipe. I doubt anyone wants to keep either on these on purpose.

**Comment by timtebeek** [comment]
Isn't this a duplicate of https://github.com/openrewrite/rewrite/issues/1621 ?

**Comment by yeikel** [comment]
> Isn't this a duplicate of #1621 ?
Yeah. Closing

Thanks for pointing it out

**Comment by timtebeek** [comment]
No worries; thanks for helping keep the backlog free from duplicates by closing this one. :)

I think it should be relatively straightforward to implement https://github.com/openrewrite/rewrite/issues/1621 , if that's something you'd like to take on. Even just having some tests would help. Or else perhaps @AlekSimpson can help out.
