### ISSUE TITLE
Maven - Add `groupId ` if missing for maven plugins

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite#3529]
## What problem are you trying to solve?

In Maven, it is possible to omit the `groupId ` of a Maven plugin as maven defaults to `org.apache.maven.plugins` when the `groupId ` is not provided

## What precondition(s) should be checked before applying this recipe?

- It is a maven build
- It is a plugin definition
- the `groupId ` is not present

## Describe the situation before applying the recipe

```xml

<build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
            </plugin>
        </plugins>
 </build>         
   
```

## Describe the situation after applying the recipe

```diff

<build>
        <plugins>
            <plugin>
++             <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
            </plugin>
        </plugins>
 </build>         
   
```

## Any additional context

Schema : https://maven.apache.org/xsd/maven-4.0.0.xsd

In particualr this section

```xml

<xs:all>
<xs:element minOccurs="0" name="groupId" type="xs:string" default="org.apache.maven.plugins">
<xs:annotation>
<xs:documentation source="version">4.0.0+</xs:documentation>
<xs:documentation source="description">
The group ID of the reporting plugin in the repository.
</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element minOccurs="0" name="artifactId" type="xs:string">

```

**Comment by timtebeek** [comment]
Thanks for the clear description and link to the xsd; what's your motivation to override the default with the same value? Clarity?

Seems like an relatively straightforward (custom) recipe; would you be willing to take that on?

**Comment by timtebeek** [comment]
Agree with you there; we can add this to a Maven best practices recipe, along with setting an explicit version:
- https://github.com/openrewrite/rewrite/issues/2735

**Comment by timtebeek** [comment]
Implemented in 
- https://github.com/openrewrite/rewrite/pull/3591
