### ISSUE TITLE
Recipe that add a parameter for an object création

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#3551]
## What problem are you trying to solve?
I want to add a parameter to an object (as first param but we can define a position if needed)

## What precondition(s) should be checked before applying this recipe?
The number of parameter is < as required

## Describe the situation before applying the recipe

```java
class A {
    void foo() {
        Object myObject =new Object("myString", "myString")
    }
}
```

## Describe the situation after applying the recipe

```java
class A {
      void foo() {
        Object myObject =new Object(myCustomObject, "myString", "myString")
    }
}
```

**Comment by timtebeek** [comment]
Hi @jdelobel ; thanks for the suggestion! We've discussed similar approaches in the past, but it's hard to implement this as a generic configurable recipe, as the new to insert argument would often depend on what's available in the surrounding context, with little guarantees about particularly named variables being available.

We would only be able to insert new arguments safely when those are for instance literals including null, static method invocations, field references, ternary operators using such inputs, etc.. I'm not sure if we'd want to support anything beyond that generically, such as a a variable you're suggesting above, as that will highly depend on the context, and has a good chance of [doing harm](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices#do-no-harm) if the context is only ever so slightly different.

Given the above, do you then still think there's value in producing some kind of recipe that inserts for instance `null` when the number of arguments to a method changes? I could see that being a common enough case.

Alternatively we can also provide a visitor that you can use in your own custom recipes if you need anything more, while wanting to keep the complexity of your custom recipe low.

**Comment by jdelobel** [comment]
Hi @timtebeek ,

Thanks for your anwser.

I dont need to add null parameter to a method change. 
If I understand correctly it is not possible to have a generic method. However how can I create something specific for my particular case (based on the example above)?

**Comment by timtebeek** [comment]
> If I understand correctly it is not possible to have a generic method. However how can I create something specific for my particular case (based on the example above) or can you provide me an example that acts on the object's instanciation?

Perhaps the best place to start is write a recipe that uses a MethodMatcher, with a `<constructor>` method pattern, as seen here in the docs: https://docs.openrewrite.org/reference/method-patterns
From there you should be able to add an argument to the method invocation. Things might be slightly more interesting when you want to refer to variables in the surrounding context, but if you start a gist, or reach out on Slack we might be able to help you out. This recipe might come closest in the sense of altering method arguments: https://github.com/openrewrite/rewrite/blob/v8.5.2/rewrite-java/src/main/java/org/openrewrite/java/ReorderMethodArguments.java
Hope that helps!

**Comment by timtebeek** [comment]
Given the added context above this is likely not a recipe we can pick up generically, as the argument needs to be taken from surrounding context, which will differ from case to case. As such its probably best picked up with guidance through Slack if possible. Feel free to share any progress here though if you feel that might help others!
