### ISSUE TITLE
`UseMavenCompilerPluginReleaseConfiguration` does not match when `groupId` is implied

### ISSUE THREAD

**Issue by jbessels** [openrewrite/rewrite#3562]
I am using

        <rewrite-maven-plugin.version>5.5.2</rewrite-maven-plugin.version>
        <rewrite-migrate-java.version>2.1.0</rewrite-migrate-java.version>
        <rewrite-testing-frameworks.version>2.0.11</rewrite-testing-frameworks.version>
        <rewrite-static-analysis.version>1.0.7</rewrite-static-analysis.version>

Maven multi-project 
command: mvn rewrite:run
Private repo

When using the recipe some ` <source> and <target>` are transformed into one `<release>` tag but there are 12+ ones which are not transformed. The OK and FAIL situations seem to have the exact same layout. The following does NOT transform

```
 <build>
      <plugins>
      ....
             <plugin>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>${maven-compiler-plugin.version}</version>
              <configuration>
                  <source>${java.version}</source>
                  <target>${java.version}</target>
              </configuration>
          </plugin>
     ....
    </plugins>
</build>
```
It should be 
```
 <build>
      <plugins>
      ....
             <plugin>
              <artifactId>maven-compiler-plugin</artifactId>
              <version>${maven-compiler-plugin.version}</version>
              <configuration>
                  <release>${java.version}</release>
              </configuration>
          </plugin>
     ....
    </plugins>
</build>
```
Note: A second issue is that instead of `<release>$j{ava.version} ></release>` its actually transformed into <release>17</release>. For the latter I've created a Moderne ticket. 

I hope you can investigate this.

**Comment by timtebeek** [comment]
This will be because of the implied groupId not being matched. See also:
- https://github.com/openrewrite/rewrite/issues/3529

**Comment by jbessels** [comment]
Nice to know that the reason is known. Thanks for the info.
I noticed the missing GroupId this morning and I did add the groupId where it was missing.

**Comment by timtebeek** [comment]
That should help; as seen above we're planning a recipe to add those, but we could also expand the recipe here to match when absent; both should help to resolve your issue.
