### ISSUE TITLE
gradle kotlin script version number not ugpraded while in maven pom.xml depencies version also upgraded

### ISSUE THREAD

**Issue by nagkumar** [openrewrite/rewrite#3594]
`  testImplementation("org.mockito:mockito-core:1.10.19")`

after rewrite run it is stil the same while i expevt it to be

`  testImplementation("org.mockito:mockito-core:3.12.4")`

this bug is not in pom.xml while observed with gradle 8.3 and kotlin .kts file

**Comment by timtebeek** [comment]
Hi @nagkumar! Thanks for your report. We don't support Gradle Kotlin scrips just yet (only Groovy), but are getting close. We're tracking progress on that in this issue
- https://github.com/openrewrite/rewrite/issues/3291

You can subscribe to the above issue to be notified when support is finished, or watch out for upcoming OpenRewrite releases and their release notes.

Hope that helps! And I hope you don't mind me closing this issue in favor of the earlier issue. Your reminder is appreciated!
