### ISSUE TITLE
`TypeUtils.findOverriddenMethod` misidentifies package scoped method from class in different package

### ISSUE THREAD

**Issue by AlejandroBertolo** [openrewrite/rewrite#3599]
Greetings. 

We've found a problem in the [MissingOverrideAnnotation ](org.openrewrite.staticanalysis.MissingOverrideAnnotation)recipe, by which in very specific circunstances, a method will be wrongly annotated, generating compilation issues in processed projects. 

The error can be observed whenever:

- A class extends/implements from a supertype.
- The supertype contains a method which is not exposed externally (that is, with package/default visibility)
- The extending class declares a new method with the same signature.
- The recipe will wrongly consider this copycat method an override and assign the annotation, resulting in compilation failures.

## What version of OpenRewrite are you using?
staticAnalysis 1.0.8
RecipeBom 2.3.0
RewriteMavenPlugin 5.7.1

## How are you running OpenRewrite?

Through maven plugin in multimodule projects.

## What is the smallest, simplest way to reproduce the problem?

Given the following example superclass:

```java
package org.example;

public class A {

    public void accessible() {
       // Open for overriding
    }

    void notAccessible() {
        // This method is not visible from subclass due to default access and different package.
    }
}
```

And the following extending class:

```java
package org.example.impl;

import org.example.A;

class B extends A {

    public void accessible() {
        super.accessible();
    }

    void notAccessible() {
        // Same signature than super method but not an override.
    }
}
```

## What did you expect to see?
The recipe should add the override annotation to the accesible method.

```java
package org.example.impl;

import org.example.A;

class B extends A {

    @Override
    public void accessible() {
        super.accessible();
    }

    void notAccessible() {
        // Same signature than super method but not an override.
    }

}
```

## What did you see instead?

The notAccessible() method is considered an override and is annotated.
This results in compilation failure as notAccesible() can't override the supertype.

```java
package org.example.impl;

import org.example.A;

class B extends A {

    @Override
    public void accessible() {
        super.accessible();
    }

    @Override
    void notAccessible() {
        // Same signature than super method but not an override.
    }

}
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Yes, we can contribute a fix to skip override annotations for these specific cases.

**Comment by timtebeek** [comment]
Hi @AlejandroBertolo , thanks yet again! Must say I really appreciate your thorough reports and willingness to help fix the issues you find.

I've moved the issue and renamed it to better reflect your latest insights; I reckon we can verify it here, and then the fix should automatically cascade to rewrite-static-analysis without the need for additional tests there. Any fix in this repository would result in [fixes across multiple recipes](https://github.com/search?q=org%3Aopenrewrite+findoverriddenmethod&type=code), so no need to test those individually.
