### ISSUE TITLE
support  JDK21 JVM and Migration

### ISSUE THREAD

**Issue by nagkumar** [openrewrite/rewrite#3601]
JDK 21 support as it currently supports only JDK 17
<img width="585" alt="image" src="https://github.com/openrewrite/rewrite/assets/332234/ceb7bdc1-9e46-4348-85e4-1f3a3854d504">

**Comment by nagkumar** [comment]
My Observation is it is not accepting JDK 21 as runtime used to run the gradle task rewriteRun

**Comment by timtebeek** [comment]
Correct; as pointed out in that other issue we're waiting for these blockers to be cleared before we can continue:

- https://github.com/gradle/gradle/issues/25574
- https://docs.gradle.org/8.4-rc-1/release-notes.html

Only then can we get started on a Java 21 specific parser, similar to [the Java 8, 11 and 17 parsers in OpenRewrite/rewrite](https://github.com/openrewrite/rewrite), which will then unlock support for running on Java 21 as well.
