### ISSUE TITLE
`RemoveUnusedImports` removes used import of `xxx.Record`

### ISSUE THREAD

**Issue by pzygielo** [openrewrite/rewrite#3607]
## What version of OpenRewrite are you using?
I am using
- Maven plugin v5.8.1

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a single module project.

## What is the smallest, simplest way to reproduce the problem?
https://github.com/pzrep/openrewrite-record

## What did you expect to see?
I expected to see no changes.

## What did you see instead?
https://github.com/pzrep/openrewrite-record/actions/runs/6445928658/job/17500499199#step:6:24:

required import gets removed:
```diff
diff --git a/src/main/java/pzrep/p2/Client2.java b/src/main/java/pzrep/p2/Client2.java
index 2bb52f5..50aea66 100644
--- a/src/main/java/pzrep/p2/Client2.java
+++ b/src/main/java/pzrep/p2/Client2.java
@@ -1,6 +1,5 @@
 package pzrep.p2;
 
-import pzrep.p1.Record;
 import pzrep.p1.*;
 
 class Client2 {
```
This makes modified source to be uncompilable:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] .../src/main/java/pzrep/p2/Client2.java:[6,12] reference to Record is ambiguous
  both class pzrep.p1.Record in pzrep.p1 and class java.lang.Record in java.lang match
```

-----
- originally reported in #3275

**Comment by knutwannheden** [comment]
@pzygielo Thanks for the detailed report and reproducer. Very much appreciated!

Star folded imports are indeed tricky to handle correctly. On first sight it indeed looks like the import can be removed. But due to the clash with `java.lang.Record` that is an issue.

**Comment by timtebeek** [comment]
Thanks for the reproduction repository; I've used that to create this unit test that shows the same issue:
- https://github.com/openrewrite/rewrite/pull/3629
