### ISSUE TITLE
ResolvedDependency.hashCode() causes StackOverflowError with circular dependencies

### ISSUE THREAD

**Issue by edudar** [openrewrite/rewrite#3626]
## What version of OpenRewrite are you using?
I am using

- OpenRewrite v8.7.4
- Gradle plugin v6.3.19
- rewrite-maven v8.7.4

`org.openrewrite.maven.tree.ResolvedDependency` uses Lombok-generated `hashCode` that calls for hash codes of transitive dependencies. This leads to StackOverflowError when dependencies are "circular". 

For example, [io/grpc/grpc-core/1.58.0](https://repo1.maven.org/maven2/io/grpc/grpc-core/1.58.0/grpc-core-1.58.0.pom) depends on `grpc-util` and [io/grpc/grpc-util/1.58.0](https://repo1.maven.org/maven2/io/grpc/grpc-util/1.58.0/grpc-util-1.58.0.pom) depends on `grpc-core`. The scopes are different (`compile` vs. `runtime`), so Gradle resolves this just fine.

**Comment by knutwannheden** [comment]
@edudar Thanks for reporting this issue. Can you tell us exactly where you encountered this `StackOverflowError`?

**Comment by edudar** [comment]
Nothing special to report here; I was simply running `gradle rewriteRun` on the project. The active recipe does not matter as this error happens on any of them. I first encountered it with `guava` and managed to resolve it on my own to then stumble upon `grpc` case. We don't define these explicitly and get them transitively via one of `gcp` dependencies for logging.

**Comment by knutwannheden** [comment]
Makes sense. If you could tell me what recipe you ran, I may be able to reproduce the problem.

**Comment by edudar** [comment]
`org.openrewrite.java.RemoveObjectsIsNull`

**Comment by knutwannheden** [comment]
Thanks. I was expecting a Maven recipe here. But I will try to reproduce using this.

**Comment by edudar** [comment]
I believe the maven part runs regardless of whether the recipe is maven-related or not. I tried multiple recipes: as simple as `RemoveObjectsIsNull` to junit migrations to spring boot migrations. They all were failing with the same error pointing to rewrite-maven.

**Comment by knutwannheden** [comment]
We detected a few more situations where these dependency cycles were problematic. Should be fixed now with #3678
