### ISSUE TITLE
Duplicate cursor while working with Java visitors

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#3641]
The change in `TreeVisitor`:

```java
            setCursor(cursor.getParent());

            if (topLevel) {
                sample.stop(Timer.builder("rewrite.visitor.visit").tag("visitor.class", getClass().getName()).register(Metrics.globalRegistry));
                visitCountSummary.record(visitCount);

                if (t != null && afterVisit != null) {
                    for (TreeVisitor<?, P> v : afterVisit) {
                        if (v != null) {
                             v.setCursor(new Cursor(cursor, tree)); // <---- This change
                            //noinspection unchecked
                            t = (T) v.visit(t, p);
                        }
                    }
                }

                sample.stop(Timer.builder("rewrite.visitor.visit.cumulative").tag("visitor.class", getClass().getName()).register(Metrics.globalRegistry));
                afterVisit = null;
                visitCount = 0;
            }
```

seems problematic and may lead to the creation of two cursors (child and parent) pointing to the same AST node.
The following call `t = (T) v.visit(t, p);` would create another cursor with the same `tree` element it seems:

```java
    @Nullable
    public T visit(@Nullable Tree tree, P p) {
        if (tree == null) {
            return defaultValue(null, p);
        }

        Timer.Sample sample = null;
        boolean topLevel = false;
        if (visitCount == 0) {
            topLevel = true;
            sample = Timer.start();
        }

        visitCount++;
        setCursor(new Cursor(cursor, tree));
```

Having a duplicate cursor leads to problems with indents in the auto formatting visitor.

**Comment by BoykoAlex** [comment]
I propose to switch the cursor creation to call:

from

```java
v.setCursor(new Cursor(cursor, tree));
```

to

```java
v.setCursor(cursor == null ? null : cursor.fork());
```

**Comment by knutwannheden** [comment]
@BoykoAlex Thanks for reporting. This seems to be about commit https://github.com/openrewrite/rewrite/commit/3086e52b47c774ac3b6dd1ebea90e07225d09455. It indeed looks like the after visitor's cursor will end up with a parent with the same value.

@sambsnyd If I understand your commit correctly, you made a change to fix `TreeVisitorTest#scheduleAfterOnVisitWithCursor()`. But I think that what that test is doing is somewhat dangerous: Its visitor overrides `visit(Tree, P)`. This is of course possible, but that method (in `TreeVisitor`) is the one which contains all the "important" bits about setting up the cursor etc. So I think a visitor doing that can't expect the cursor to point to the element being visited. In that way I think this test is wrong. What are your thoughts on this?

**Comment by knutwannheden** [comment]
@BoykoAlex Rather than calling `Cursor#fork()` I would like to propose to switch back to using the original cursor, as we had it before. I will update your PR accordingly.

**Comment by knutwannheden** [comment]
Using `Cursor#fork()` could also make sense in a second step to avoid any "pollution" between visitors.

**Comment by BoykoAlex** [comment]
@knutwannheden reverting the commit or switching to `fork()` either should fix the issue for me. thanks very much for looking into this!-)
