### ISSUE TITLE
Java Parser gives parser error for syntax `java.lang.@NonNull String test`

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#3683]
Coming from https://github.com/spring-projects/sts4/issues/1142#issuecomment-1804239926

Looks like this is a valid syntax.

I've created a unit test for this syntax:
```java
              public class A {
                java.lang.@Deprecated String a;
              }
```

**Comment by timtebeek** [comment]
Oh wow, didn't know that was an option; although after seeing all the ways you can declare and annotate arrays I'm not surprised. As soon as we add support I want a recipe that moves away from that style. ;) Thanks for bringing it to our attention!

**Comment by traceyyoshima** [comment]
Note: I think annotations in FQNs may be supported now that we have an annotations field in `J.Identifier`.

**Comment by timtebeek** [comment]
Just rebased this one to check
- https://github.com/openrewrite/rewrite/pull/3684

**Comment by timtebeek** [comment]
Thanks for the report @BoykoAlex ! Should be fixed in the latests snapshots, with a release to follow soon.
