### ISSUE TITLE
WARNING AT COMPILE TIME on javax.annotation.meta.When.MAYBE

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite#3703]
Hi,

When i compile my project, i have this warning (I use @Nullable annotation). FYI my target source is java 8 but i use java 17. 

[WARNING] COMPILATION WARNING :                                           
[INFO] -------------------------------------------------------------      
[WARNING] unknown enum constant javax.annotation.meta.When.MAYBE          
  reason: class file for javax.annotation.meta.When not found             
[WARNING] unknown enum constant javax.annotation.meta.When.MAYBE          
  reason: class file for javax.annotation.meta.When not found             
[WARNING] unknown enum constant javax.annotation.meta.When.MAYBE          
  reason: class file for javax.annotation.meta.When not found             
[WARNING] unknown enum constant javax.annotation.meta.When.MAYBE          
  reason: class file for javax.annotation.meta.When not found             
[WARNING] unknown enum constant javax.annotation.meta.When.MAYBE          
  reason: class file for javax.annotation.meta.When not found             

Maybe you don't have to use `javax.annotation.meta.When.MAYBE ` https://github.com/openrewrite/rewrite/blob/eee01ddc30f343f98c355a8c9344081c228c692e/rewrite-core/src/main/java/org/openrewrite/internal/lang/Nullable.java#L39

**Comment by timtebeek** [comment]
Does your project have a dependency on https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305/3.0.2 ?
That contains the `javax.annotation.meta.When` for as much as I can tell, and could resolve your issue.

**Comment by Bananeweizen** [comment]
I see the same warning just running "gradlew test" on the HEAD of the rewrite project itself, with no local changes. 
![grafik](https://github.com/openrewrite/rewrite/assets/406876/9b49c0c3-c297-4d63-8516-a539d5a17f2c)

**Comment by jdelobel** [comment]
> Does your project have a dependency on https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305/3.0.2 ? That contains the `javax.annotation.meta.When` for as much as I can tell, and could resolve your issue.

OK for me after added this deps

**Comment by timtebeek** [comment]
- Continued in https://github.com/openrewrite/rewrite/issues/7421
