### ISSUE TITLE
UseStaticImport fails on <Generic>calls()

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite#3705]
`Collections.<Object>emptyList()` and similar explicitly typed generic methods are not handled correctly in `UseStaticImport`.

## What is the smallest, simplest way to reproduce the problem?

```java
    @Test
    void ecplicitGenerics() {
        rewriteRun(
          spec -> spec.recipe(new UseStaticImport("java.util.Collections emptyList()")),
          java(
            """
            import java.util.Collections;
            import java.util.List;

            public class Reproducer {
                public void reproduce() {
                    List<Object> list = Collections.emptyList();
                    List<Object> list = Collections.<Object>emptyList();
                }
            }
            """,
            """
            import java.util.List;

            import static java.util.Collections.emptyList;

            public class Reproducer {
                public void reproduce() {
                    List<Object> list = emptyList();
                    List<Object> list = emptyList();
                }
            }
            """
          )
        );
    }
```

## What did you expect to see?
The second call either being shortened to just the method name or not changed at all.

## What did you see instead?

The second line with the generic becomes this non compiling code:
```java
List<Object> list = <Object>emptyList();
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Maybe, but I haven't been able to fix the other ones I raised for the same class, yet.

**Comment by knutwannheden** [comment]
I think we should simply not replace any calls with generic type parameters. Figuring out if these are required is really tricky (e.g. when lambdas are involved) and we haven't implemented a type inference engine yet.

Fixing this issue should then be quite straight-forward.
