### ISSUE TITLE
Fully remove PartProvider and last remaining references

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#3754]
## What problem are you trying to solve?
PartProvider has been deprecated for a while now; with the [JavaTemplate as suggested replacement](https://docs.openrewrite.org/concepts-explanations/javatemplate).
https://github.com/openrewrite/rewrite/blob/d0704ac91c0fc618542838fa3f1edaf04c8089ef/rewrite-java/src/main/java/org/openrewrite/java/PartProvider.java#L35

## Describe the solution you'd like

- [ ] Fully remove PartProvider in this repository
- [ ] Remove from [rewrite-spring AddRouteTrailingSlash](https://github.com/openrewrite/rewrite-spring/blob/de623f1470a5f6417aa8a88f98b50ed220620273/src/main/java/org/openrewrite/java/spring/boot3/AddRouteTrailingSlash.java#L23)
- [ ] Remove from [rewrite-spring ReplaceGlobalMethodSecurityWithMethodSecurity](https://github.com/openrewrite/rewrite-spring/blob/de623f1470a5f6417aa8a88f98b50ed220620273/src/main/java/org/openrewrite/java/spring/security5/ReplaceGlobalMethodSecurityWithMethodSecurity.java#L105)
- [ ] Remove from [rewrite-migrate-java MigrateCollectionsSingletonList](https://github.com/openrewrite/rewrite-migrate-java/blob/7c18d9401ecde2cfd23c0e9e18135cdc9226a5fd/src/main/java/org/openrewrite/java/migrate/util/MigrateCollectionsSingletonList.java#L26)
- [ ] Remove from [rewrite-static-analysis ReplaceStringBuilderWithString](https://github.com/openrewrite/rewrite-static-analysis/blob/060911975cb058c20d00fa1e54e98f5773e4bc85/src/main/java/org/openrewrite/staticanalysis/ReplaceStringBuilderWithString.java#L21)
- [x] Remove from [rewrite-testing-frameworks AnyStringToNullable](https://github.com/openrewrite/rewrite-testing-frameworks/blob/0e44bf7791432d356552b495266f202b3d91b0d4/src/main/java/org/openrewrite/java/testing/mockito/AnyStringToNullable.java#L24)

## Additional context
- https://docs.openrewrite.org/concepts-explanations/javatemplate

**Comment by Mgonzalez-droid** [comment]
I am open to working this issue if needed.

**Comment by timtebeek** [comment]
That would be much appreciated! Feel free to open a pull request against any of those projects and I'll see them through. Do you need any further assistance beyond what's covered in [the docs about JavaTemplate](https://docs.openrewrite.org/concepts-explanations/javatemplate)?

**Comment by Mgonzalez-droid** [comment]
I'll give it a read over and let you know. Thank you!

**Comment by Mgonzalez-droid** [comment]
Is there any branch you would prefer I branch off of? I looked through the documents and did not find a preferred branch.

**Comment by timtebeek** [comment]
Just forking the main branch, and starting a branch on your end would work fine. Thanks again!

**Comment by Mgonzalez-droid** [comment]
Sounds great, thank you!

**Comment by Mgonzalez-droid** [comment]
I was able to start some work on your changes and the template documentation is mostly straightforward. However, I wanted to know how the code snippet fits in the new template. I have an example here of what I have so far:

![rewrite-migrate-java_MigrateCollectionsSingletonList-java](https://github.com/openrewrite/rewrite/assets/67339220/acdee7f4-41fa-43a3-b55b-5be805468b7e)

Let me know how I should format the code snippet into the new template. Thank you!

**Comment by timtebeek** [comment]
Quick first reaction: you can drop lines 75, 76 & 77 when not using any dependencies such as here! :)

**Comment by timtebeek** [comment]
Figured pick up one of these just now to have an example: here's one of the five required changes above in https://github.com/openrewrite/rewrite-testing-frameworks/commit/e383281491aa96ed00a689233e4af41b2f80b34b

**Comment by Mgonzalez-droid** [comment]
Thank you, the example helps a lot. I am resuming work on these changes.

**Comment by timtebeek** [comment]
Thanks a lot! Would be good to see this through, and thankful for the help!
