### ISSUE TITLE
Replace `UUID.randomUUID()` with `Tree.randomId()` as part of recipe best practices

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite#3757]
## What problem are you trying to solve?
Convention says to use `Tree.randomId()` for consistency, yes sometimes folks use `UUID.randomUUID()`.
We want to convert those cases where `randomUUID` is used to create LST elements to use `randomId`.

## What precondition(s) should be checked before applying this recipe?
- Used as id for an LST element

## Describe the situation before and after applying the recipe
```diff
- new J.Literal(UUID.randomUUID(), Space.SINGLE_SPACE, Markers.EMPTY, defaultValue, defaultValue, null, JavaType.Primitive.Boolean);
+ new J.Literal(Tree.randomId(), Space.SINGLE_SPACE, Markers.EMPTY, defaultValue, defaultValue, null, JavaType.Primitive.Boolean);
```

## Any additional context
We have a broader collection of best practices; Likely we want to bundle and enforce those together.
- https://docs.openrewrite.org/recipes/java/recipes
- https://github.com/openrewrite/gh-automation/issues/45

**Comment by TheMarvelFan** [comment]
Hi,
Do I have to write a recipe for replacing references to UUID.randomUUID(), or do I have to modify these references in existing recipes?

**Comment by timtebeek** [comment]
Ideally I had thought to write a recipe that matches any LST element constructor, and replace the first argument if that's a call to `UUID.randomUUID()`. That recipe we can then run once across all projects through the Moderne paltform, and add to a pull request check to ensure it's not reintroduced on community contributions.

**Comment by TheMarvelFan** [comment]
Ok I will open a PR with the recipe asap.

**Comment by timtebeek** [comment]
Looking forward to it, thanks!

**Comment by TheMarvelFan** [comment]
Hi
Please review the changes made, and suggest if more changes are required.
