### ISSUE TITLE
dependencyManagement needs to propagate to dependencies

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#376]
In this diagram:
Solid arrows going up represent a "parent" relationship
Solid arrows going down represent a "dependency" relationship
Dotted arrows going down represent a "managed dependency" relationship

![image](https://user-images.githubusercontent.com/8549033/111014722-f2934d80-8359-11eb-8f9a-be6988b3a87f.png)

So: "A" depends on "C" depends on "D"
The version of "D" should come from "A"'s dependency management.
So in this example 0.1.0-SNAPSHOT should win.
Currently 0.2.0-SNAPSHOT is winning. 

[MavenParserTest.dependencyManagementPropagatesToDependencies()](https://github.com/openrewrite/rewrite/blob/3c13fd3514c3016f3efe2867d9016147f1ea50be/rewrite-maven/src/test/kotlin/org/openrewrite/maven/MavenParserTest.kt#L728) reproduces this issue

**Comment by tkvangorder** [comment]
This has been resolved as part of the work on https://github.com/openrewrite/rewrite/issues/346
