### ISSUE TITLE
Default wildcard import aggregation gobbles up inner types.

### ISSUE THREAD

**Issue by abassouk** [openrewrite/rewrite#381]
Example (extracted from a `mvn rewrite:diff` result): 

```
-import org.glassfish.jersey.server.monitoring.ApplicationEvent;
-import org.glassfish.jersey.server.monitoring.ApplicationEventListener;
-import org.glassfish.jersey.server.monitoring.RequestEvent;
-import org.glassfish.jersey.server.monitoring.RequestEvent.Type;
-import org.glassfish.jersey.server.monitoring.RequestEventListener;
+import org.glassfish.jersey.server.monitoring.*;
```

In this case, the `RequestEvent.Type` should _not_ be considered a candidate for collection into that wildcard; the import is effectively lost and the resulting source doesn't compile. 

Tested on rewrite-maven-plugin 3.0.0-rc.6

**Comment by jkschneider** [comment]
Hi @abassouk. Thanks for the report! This was fixed in https://github.com/openrewrite/rewrite/issues/352, and is currently buildable from snapshot.
