### ISSUE TITLE
UpdateMavenModel does not handle valid XML properly

### ISSUE THREAD

**Issue by smurf667** [openrewrite/rewrite#3811]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.11.1
- rewrite-maven_ v8.11.1

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a multi-module project. However, the issue occurs also with single module projects and is demonstrated in a simple unit test below.

For reasons outside my control I have Maven `pom.xml` files that use XML-escaped characters in Maven coordinates. This leads to the stacktrace documented below ("Dependency must have artifactId").

## What is the smallest, simplest way to reproduce the problem?

```java
package demo;

import static org.openrewrite.maven.Assertions.pomXml;

import org.junit.jupiter.api.Test;
import org.openrewrite.maven.AddManagedDependency;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

class ExampleTest implements RewriteTest {

  @Override
  public void defaults(final RecipeSpec spec) {
    spec.recipe(new AddManagedDependency("ch.qos.logback", "logback-classic", "1.4.14", null, null, null, null, null, null, null));
  }

  @Test
  void shouldNotFailWithValidMavenXml() {
    rewriteRun(pomXml("""
      <project>
        <groupId>com.mycompany.app</groupId>
        <artifactId>my-app</artifactId>
        <version>1</version>
        <dependencies>
          <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-&#0097;pi</artifactId>
            <version>2.0.9</version>
          </dependency>
        </dependencies>
      </project>
      """,
      """
      <project>
        <groupId>com.mycompany.app</groupId>
        <artifactId>my-app</artifactId>
        <version>1</version>
        <dependencyManagement>
          <dependencies>
            <dependency>
              <groupId>ch.qos.logback</groupId>
              <artifactId>logback-classic</artifactId>
              <version>1.4.14</version>
            </dependency>
          </dependencies>
        </dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-&#0097;pi</artifactId>
            <version>2.0.9</version>
          </dependency>
        </dependencies>
      </project>
      """
      ));
  }

}
```

## What did you expect to see?

A successful modification.

## What did you see instead? What is the full stack trace of any errors you encountered?

```
Caused by: java.lang.IllegalStateException: Dependency must have artifactId
  at org.openrewrite.maven.UpdateMavenModel.lambda$visitDocument$1(UpdateMavenModel.java:70)
  at java.base/java.util.Optional.orElseThrow(Optional.java:403)
  at org.openrewrite.maven.UpdateMavenModel.visitDocument(UpdateMavenModel.java:70)
  at org.openrewrite.xml.tree.Xml$Document.acceptXml(Xml.java:151)
  at org.openrewrite.xml.tree.Xml.accept(Xml.java:50)
  at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:278)
  ... 88 more
```

The reason for this is the (naive?) use of `Xml.Tag.getChildValue()` which at its core determines the expected text content [here](https://github.com/openrewrite/rewrite/blob/v8.11.1/rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java#L357-L368); I did not check, but there seem to many such places, for example [here](https://github.com/openrewrite/rewrite/blob/v8.11.1/rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java#L54).

The problem with XML-escaped characters is now that this is no longer a list of size one, but a list of text fragments.
For example for `<artifactId>slf4j-&#0097;pi</artifactId>` this is a list of `slf4j-`, `&#0097;` and `pi` - still valid XML, but it won't be properly processed.

I am unsure what a proper "fix" might be. Should the `Xml.Tag` have an additional method `getInnerText()` (similar as in HTML DOM elements)? Should `UpdateMavenModel` get the strings for Maven coordinates in a more robust manner itself with some helper method?

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I'd rather not, as I have trouble getting everything to compile on my private setup. Additionally, I am too unfamiliar with the code to make the "right" changes, I expect.

**Comment by timtebeek** [comment]
Thanks for providing context to the issue; indeed unfortunate that you have to deal with such escapes, and we have to handle that better.

**Comment by timtebeek** [comment]
Exploring the issue here for a bit; your test indeed fails; this passes, despite the escape
```
@Test
void escapedAinArtifactId() {
    rewriteRun(
      pomXml(
        """
          <project>
            <groupId>com.mycompany.app</groupId>
            <artifactId>my-app</artifactId>
            <version>1</version>
            <dependencies>
              <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-&#0097;pi</artifactId>
                <version>2.0.9</version>
              </dependency>
            </dependencies>
          </project>
          """,
        spec -> spec.afterRecipe(pomXml -> {
            assertThat(pomXml.getMarkers().findFirst(MavenResolutionResult.class).orElseThrow()
              .getDependencies().get(Scope.Compile))
              .singleElement()
              .satisfies(dep -> assertThat(dep.getArtifactId()).isEqualTo("slf4j-api"));
        })
      )
    );
}
```

**Comment by timtebeek** [comment]
And this indeed shows what you also found, that the artifactId contains an ArrayList instead of a regular value
```java
@Test
void escapedAinArtifactIdVisited() {
    rewriteRun(
      spec -> spec.recipe(RewriteTest.toRecipe(() -> new XmlVisitor<>() {
          @Override
          public Xml visitTag(Xml.Tag tag, ExecutionContext ctx) {
              if (new XPathMatcher("/project/dependencies/dependency").matches(getCursor())) {
                  var child = tag.getChild("artifactId");
                  var childValue = tag.getChildValue("artifactId");
                  var children = tag.getChildren("artifactId");
                  System.out.println();
              }
              return super.visitTag(tag, ctx);
          }
      })),
      pomXml(
        """
          <project>
            <groupId>com.mycompany.app</groupId>
            <artifactId>my-app</artifactId>
            <version>1</version>
            <dependencies>
              <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-&#0097;pi</artifactId>
                <version>2.0.9</version>
              </dependency>
            </dependencies>
          </project>
          """
      )
    );
}
```

**Comment by knutwannheden** [comment]
@traceyyoshima It seems like the XML entity fix you made doesn't also extend to XML character references and needs a separate fix.

**Comment by timtebeek** [comment]
I think I have a fix in
- https://github.com/openrewrite/rewrite/pull/3813

**Comment by timtebeek** [comment]
Thanks again for the report @smurf667 ; you can try it out through [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions), before we release somewhere in the next two weeks.

**Comment by timtebeek** [comment]
Glad to hear that works and thanks for confirming here!
