### ISSUE TITLE
Consider gradle dependency locking

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#386]
Logging this for the icebox for consideration at some point.

Consider using gradle dependency-locking to occasionally (could be nightly, why not) pin dynamically-resolved dependency versions to a lockfile for reproducible versions. Would want to check how other projects are using this.

https://docs.gradle.org/current/userguide/dependency_locking.html

**Comment by sambsnyd** [comment]
We will probably adopt dependency locks, at least in certain places, at some point.
