### ISSUE TITLE
ShortenFullyQualifiedTypeReferences adds superfluous annotations 

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite#3873]
## What version of OpenRewrite are you using?

8.13.0-SNAPSHOT

I do not have a minimal example yet, however, it fails as follows.

I suspect the issue might be because `org.openrewrite.java.JavaVisitor#usedTypes` does not account for type annotations, however, I am not sure.

Input file: https://github.com/pgjdbc/pgjdbc/blob/0b0f4ce6ed89c6acd73ecb8c8ca416b850e45454/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java

Execution log

```
Changes have been made to pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java by:
    org.openrewrite.staticanalysis.MissingOverrideAnnotation
        io.github.pgjdbc.staticanalysis.CodeCleanup
            org.openrewrite.java.format.MethodParamPad
            org.openrewrite.staticanalysis.EqualsAvoidsNull
            org.openrewrite.staticanalysis.ExplicitInitialization
            org.openrewrite.java.ShortenFullyQualifiedTypeReferences
```

If I exclude `ShortenFullyQualifiedTypeReferences` from my configuration, then duplicate `@Nullable` annotations are not added (in fact, none of them added, and only `@Override` is added as it was missing)

Problematic diff:

```diff
@@ -488,6 +499,9 @@ public class PgConnection implements BaseConnection {
   private final TimestampUtils timestampUtils;

   @Deprecated
+  @Nullable
+  @Nullable
+  @Override
   public TimestampUtils getTimestampUtils() {
     return timestampUtils;
   }
@@ -534,10 +548,16 @@ public class PgConnection implements BaseConnection {
     return typemap;
   }

+  @Nullable
+  @Nullable
+  @Override
   public QueryExecutor getQueryExecutor() {
     return queryExecutor;
   }

+  @Nullable
+  @Nullable
+  @Override
   public ReplicationProtocol getReplicationProtocol() {
     return queryExecutor.getReplicationProtocol();
   }
@@ -1012,10 +1041,16 @@ public class PgConnection implements BaseConnection {
     }
   }

+  @Nullable
+  @Nullable
+  @Override
   public TransactionState getTransactionState() {
     return queryExecutor.getTransactionState();
   }

+  @Nullable
+  @Nullable
+  @Override
   public int getTransactionIsolation() throws SQLException {
     checkClosed();
+  @Nullable
+  @Nullable
+  @Override
   public void setTransactionIsolation(int level) throws SQLException {
     checkClosed();

@@ -1084,11 +1122,17 @@ public class PgConnection implements BaseConnection {
     }
   }

+  @Nullable
+  @Nullable
+  @Override
   public void setCatalog(String catalog) throws SQLException {
     checkClosed();
     // no-op
   }

+  @Nullable
+  @Nullable
+  @Override
   public String getCatalog() throws SQLException {
     checkClosed();
     return queryExecutor.getDatabase();
```

**Comment by traceyyoshima** [comment]
@vlsi Thank you for reporting the issue -- it would greatly appreciate to have a test that reproduces the issue. Sometimes the community links us to the branch of project where the issue occurs, which is also fine. I can quickly identify the source of the problem if I know what to run that will recreate the problem.

**Comment by vlsi** [comment]
The code is at https://github.com/pgjdbc/pgjdbc/pull/2979
To reproduce it you need to un-comment both rules https://github.com/vlsi/pgjdbc/blob/1c1100988fa5fc6d3a428b19b5430eaef811ee06/config/openrewrite/rewrite.yml#L62-L65

and execute `./gradlew --refresh-dependencies rewriteRun`.

However, I just tried rerunning it, and it does **NOT** reproduce the issue of unexpected `@Nullable` annotations.
Maybe the recent fixes in snapshot somehow healed this issue.

However, https://github.com/openrewrite/rewrite/issues/3870 still reproduces.

```diff
@@ -1174,7 +1196,7 @@ public class PgConnection implements BaseConnection {
   }

   // This is a cache of the DatabaseMetaData instance for this connection
-  protected java.sql.@Nullable DatabaseMetaData metadata;
+  protected @NullableDatabaseMetaData metadata;
```

**Comment by vlsi** [comment]
Closing as the issue does not reproduce with the latest snapshot.

**Comment by knutwannheden** [comment]
Thanks for retesting.
