### ISSUE TITLE
evaluate simple aggregation of commits and issues for changelog in release  notes

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#388]
Just logging this for the backlog, not dire or immediately pressing.

In order to save time or better recall the delta of changes made from version to version, evaluate what can be done for a simple aggregation of changes made in commits, issues, and PRs for releases. Consider what others are doing. Preferably simple, non-fiddly, and easy to maintain configuration for it. Or not require especially complex git commit message rules. Bleh. If nothing else, it'd be valuable for jogging memory of total changes.

Just for consideration.

**Comment by sambsnyd** [comment]
This is a good idea. We don't need a github issue for it.
