### ISSUE TITLE
Provide a way to integrate/configure googleapis/code-suggester so openrewrite diff is displayed as GitHub PR suggestions

### ISSUE THREAD

**Issue by vlsi** [openrewrite/rewrite#3891]
## What problem are you trying to solve?

It would be nice if OpenRewrite suggestions could be displayed as PR suggestions in GitHub UI.

## Describe the solution you'd like

* "check style workflow" executes OpenRewrite, produces a diff/patch/whatever file as workflow artifact
* A separate `on: workflow_run: types: completed` workflow picks up the attached patch artifact and calls https://github.com/googleapis/code-suggester to create code suggestions

A dedicated `on: workflow_run` workflow would be able to access secrets, so it would be relatively secure, and it would not allow PR builds to access secrets.

Unfortunately, the current `googleapis/code-suggester` does not support comments for suggestions. In other words, it creates only ` ```suggestion ... ``` ` comment, and it would probably be great to pass extra information like the rule name to the message.

For instance, ErrorProne's messages include a link with detailed explanation and the summary:

```
ERROR: example/myproject/BUILD:29:1: Java compilation in rule '//example/myproject:hello'
ShortSet.java:6: error: [CollectionIncompatibleType] Argument 'i - 1' should not be passed to this method;
its type int is not compatible with its collection's type argument Short
      s.remove(i - 1);
              ^
    (see http://errorprone.info/bugpattern/CollectionIncompatibleType)
```

OpenRewrite could probably add a link to the rule documentation so the users could know the intention behind the rule.

## Additional context

* https://github.com/timtebeek/code-suggester-action-reproducer/pull/1 
* https://github.com/openrewrite/rewrite-gradle-plugin/issues/255
* https://docs.github.com/en/rest/pulls/reviews?apiVersion=2022-11-28#create-a-review-for-a-pull-request
* [INFRA-25352: Provide user / personal access token for a user that could add PR suggestions for automatic code reviews](https://issues.apache.org/jira/browse/INFRA-25352)

**Comment by vlsi** [comment]
It looks like `pull requests=read and write` should be enough for the action to create suggestions.
Unfortunately, it would imply the commenter user would have permission to merge PRs.

<img width="790" alt="GitHub provides no access, read-only, and read-write access for personal access tokens" src="https://github.com/openrewrite/rewrite/assets/213894/6e3aa8e3-9bc1-4143-bc79-7b42a25ab75f">

**Comment by koppor** [comment]
As far as I understand [reviewdog](https://github.com/reviewdog/reviewdog#--reviewdog---a-code-review-dog-who-keeps-your-codebase-healthy), it supports [diff as input](https://github.com/reviewdog/reviewdog#diff), which should be enough to send the patch file to the API and then one has the suggestions?

It can even made be more simpler - if the diff is existing in the working tree: https://github.com/reviewdog/action-suggester

(I put that as TODO on my list; I wanted to share fast, because we made good experiences in the context of checkstyle with reviewdog)

**Comment by timtebeek** [comment]
Thanks for the helpful link @koppor; hadn't come across reviewdog before, and seems a convenient option for other platforms than GitHub indeed. For now I'd started to work with code-suggester in these two PRs, and will expand that with recipe runs:
- https://github.com/openrewrite/gh-automation/pull/48
- https://github.com/openrewrite/rewrite-migrate-java/pull/402

That approach helpfully hides the implementation details in a shared workflow, such that we can always switch as needed. I'd for now considered this something to use on the OpenRewrite repositories itself, but we can look at opening that up as an action ourselves in the future as well. Input & help welcome. :)

**Comment by timtebeek** [comment]
As part of https://github.com/openrewrite/gh-automation/issues/45 we now have two new workflows that together review PRs:
The first one receives a PR and runs recipes, while the second comments any changes found as code suggestions.

- https://github.com/openrewrite/gh-automation/blob/main/.github/workflows/receive-pr.yml
- https://github.com/openrewrite/gh-automation/blob/main/.github/workflows/comment-pr.yml

An example of such automated review comments can be seen here https://github.com/openrewrite/rewrite-testing-frameworks/pull/343#pullrequestreview-1862541678

We're likely to refine and expand this approach still, but I believe this is a good first step to show how this can be achieved. We don't yet insert accompanying comments, and that's perhaps indeed not supported by code-suggester, but good enough for use on our own PRs for now.

Further input and suggestions welcome, but I think we've achieved enough to close this issue already; I'll monitor any comments that arrive still, and can reopen if needed.
