### ISSUE TITLE
org.openrewrite.maven.AddProperty addToRootPom flag

### ISSUE THREAD

**Issue by jpraet** [openrewrite/rewrite#3895]
## What problem are you trying to solve?

I want to add a maven property to the root pom only.
org.openrewrite.maven.AddProperty adds the property to all poms.

## Describe the solution you'd like

addToRootPom flag, like for [org.openrewrite.maven.AddManagedDependency](https://docs.openrewrite.org/recipes/maven/addmanageddependency).

## Have you considered any alternatives or workarounds?

trustParent=true doesn't work for my use case.

**Comment by timtebeek** [comment]
Thanks for the suggestion @jpraet ! I guess the best way forward here is to use preconditions, with a recipe that detects whether or not it's applied to the root pom. That way we don't have to add options to various Maven recipes, but can reuse that precondition across recipes instead.

**Comment by sambsnyd** [comment]
That feels like a reasonable improvement to make, I will look into it
