### ISSUE TITLE
Maven repositories in settings.xml override repositories of the same id in pom.xml, including the default maven central repository

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#3908]
With a maven settings.xml like:
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <profiles>
    <profile>
        <id>central</id>
        <repositories>
            <repository>
                <id>central</id>
                <url>https://artifactory.moderne.ninja/artifactory/moderne-cache-3/</url>
                <releases><enabled>true</enabled></releases>
                <snapshots><enabled>false</enabled></snapshots>
            </repository>
        </repositories>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>central</activeProfile>
  </activeProfiles>
</settings>
```

`mvn help:effective-pom` will show that the default maven central does not appear in the effective repository list. This is very similar to the behavior of a mirror.

Settings.xml repository id wins over pom.xml repository with the same id.
Two repositories with the same id in a pom.xml is an error.
Two repositories with the same id in settings.xml is not an error, last wins.

**Comment by NiasSt90** [comment]
[From the documentation:](https://maven.apache.org/guides/mini/guide-multiple-repositories.html#repository-ids) 

> Each repository must have a unique ID. Clashing repository IDs within either effective settings or effective POMs lead to build failures. However, repositories from POM get overwritten by repositories with the same ID from effective settings. Repository IDs are also used in the [local repository metadata](https://maven.apache.org/ref/3-LATEST/maven-repository-metadata/).

Sounds like the opposite, the settings.xml overwrite repositories with same ID.
