### ISSUE TITLE
RemoveObjectsIsNull also rewrites boxed ints

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite#3915]
We have an issue in the code, where we have `Objects.isNull(i)`, where `i` is an `int`.

Then, Java boxes the integer. when `i != null`  is written, the auto boxing does not work and leads to a compile error:

    operand types for binary operator '!='

Wish: when the method parameter type is not an object, do not rewrite.

See https://github.com/JabRef/jabref/pull/10788

**Comment by timtebeek** [comment]
Picked up in 
- https://github.com/openrewrite/rewrite/pull/3918
