### ISSUE TITLE
Support for XML Namespaces

### ISSUE THREAD

**Issue by ammachado** [openrewrite/rewrite#3919]
## What problem are you trying to solve?
Change namespaced tags without being required to know the namespace prefix. For example, on the following XML, I want to replace the `schemaLocation` attribute on the `beans` tag.

```xml
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd
                           http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-2.0.xsd">
</bean>
```

There are situations where the namespace URI remains the same, but the prefix changes. I can try change the attribute `xsi:schemaLocation`, but for that the prefix should match.

## Describe the solution you'd like
- Add regex support to `ChangeTagAttribute` (~~I already have this working, I will contribute a PR~~ #3920);
- Add support to [`name`](https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/name), ~~[`namespace-uri`](https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/namespace-uri) and [`local-name`](https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/local-name)~~ on `XPathMatcher`; #3925 and #4287 
- ~~Add a `namespaces` field on `Xml.Document` and `Xml.Tag`, mapping the declared prefixes and namespaces;~~ #3925 and
- ~~Add a `namespace` or a `namespacePrefix` field on `Xml.Tag` and `Xml.Attribute`, identifying the namespace of that particular tag/attribute.~~ #3925 
- Move tags/attributes between namespaces

## Have you considered any alternatives or workarounds?
No.

**Comment by timtebeek** [comment]
Seems reasonable, thanks! Might tie into some of the [`schemaLocation` changes we do in rewrite-migrate-java](https://github.com/search?q=repo%3Aopenrewrite%2Frewrite-migrate-java%20schemaLocation&type=code).

**Comment by ammachado** [comment]
Probably a few of the existing Java EE9/10 recipes could be improved with this, also create new ones, specially new recipes to refactor `schemaLocation` for Spring XML files.

**Comment by knutwannheden** [comment]
With that PR merged, I think this ticket can now be closed. What fo you guys think, @ammachado and @timtebeek ?

**Comment by timtebeek** [comment]
We had added a disabled tests previously; think we can reevaluate the `@Disabled` on that tests before we close
https://github.com/openrewrite/rewrite/blob/22ac272d0a37fe1023af153ec68aef3ab7926849/rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java#L223-L226

**Comment by ammachado** [comment]
#3925 does not consider namespaces on `org.openrewrite.xml.SemanticallyEqual`.

**Comment by evie-lau** [comment]
Also need to finish support for `name` and `namespace-uri` functions in XPathMatcher. The latter function may potentially require a refactor or rewrite.

**Comment by timtebeek** [comment]
I feel this has been handled and then last refined in
- https://github.com/openrewrite/rewrite/commit/cda2cfb7d6fed2d870c44073ca04a555708ea41b

Let's pick up any remaining work separately as the context has shifted quite a bit since this was opened. Thanks all!
