### ISSUE TITLE
`UpgradeSpringBoot_3_2` changes `build.gradle` `sourceCompatibility` and `targetCompatibility` from 21 back to 17

### ISSUE THREAD

**Issue by aholland** [openrewrite/rewrite#3938]
Title says it all - sorry for the brief report! Also I think they should ideally be JavaVersion.21 in Gradle 8.5 (to be fair you might already be detecting which convention to use - I had a plain `21` before I ran the script).

**Comment by timtebeek** [comment]
Picked up in
- https://github.com/openrewrite/rewrite/pull/3939
