### ISSUE TITLE
Maven Recipe to sort pom.xml contents

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#397]
For ease of code review and consistency across many projects, it would be convenient to have a Recipe which sorted the contents of pom.xml files similarly to how this existing Maven plugin does:

```
mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort -Dsort.sortDependencies=scope,groupId,artifactId -Dsort.sortPlugins=groupId,artifactId -Dsort.sortModules=true -Dsort.nrOfIndentSpace=4
```

**Comment by pway99** [comment]
closed by https://github.com/openrewrite/rewrite/pull/992
