### ISSUE TITLE
UpdateMavenWrapper inconsistent when the wrapper is in a nested directory

### ISSUE THREAD

**Issue by gsmet** [openrewrite/rewrite#3982]
## What version of OpenRewrite are you using?

I am using the latest version of the OpenRewrite Maven plugin: 5.22.0.

## How are you running OpenRewrite?

Using the Maven plugin.

## What is the smallest, simplest way to reproduce the problem?

```
git clone git@github.com:hibernate/hibernate-demos.git
cd hibernate-demos
git switch -d f4dd176ea3a128f5c308f4fef86b9e5cdecb1f36
cd hibernate-search/hsearch-feature-examples/base

cat <<\EOF > rewrite.yml
---
type: specs.openrewrite.org/v1beta/recipe
name: io.quarkus.updates.core.quarkus37.UpdateMavenWrapper
recipeList:
  - org.openrewrite.maven.UpdateMavenWrapper:
      distributionVersion: 3.9.x
      addIfMissing: false
EOF

mvn -U org.openrewrite.maven:rewrite-maven-plugin:run  -Drewrite.activeRecipes=io.quarkus.updates.core.quarkus37.UpdateMavenWrapper
```

## What did you expect to see?

The Maven wrapper properly updated in this subdirectory.

## What did you see instead?

The property file is updated in place but the `maven-wrapper.jar` file is moved to/updated in a parent directory (`../../../.mvn/`):

```
$ git status

HEAD detached at f4dd176
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    .mvn/wrapper/maven-wrapper.jar
	modified:   .mvn/wrapper/maven-wrapper.properties

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../../../.mvn/ <---- maven-wrapper.jar is here
	rewrite.yml

no changes added to commit (use "git add" and/or "git commit -a")
```

## What is the full stack trace of any errors you encountered?

This is the output, we can see that the files have been moved:

```
[INFO] Running recipe(s)...
[WARNING] File has been moved from hibernate-search/hsearch-feature-examples/base/.mvn/wrapper/maven-wrapper.jar to .mvn/wrapper/maven-wrapper.jar by:
[WARNING]     io.quarkus.updates.core.quarkus37.UpdateMavenWrapper
[WARNING]         org.openrewrite.maven.UpdateMavenWrapper: {distributionVersion=3.9.x, addIfMissing=false}
[WARNING] Changes have been made to hibernate-search/hsearch-feature-examples/base/.mvn/wrapper/maven-wrapper.properties by:
[WARNING]     io.quarkus.updates.core.quarkus37.UpdateMavenWrapper
[WARNING]         org.openrewrite.maven.UpdateMavenWrapper: {distributionVersion=3.9.x, addIfMissing=false}
[WARNING] Please review and commit the results.
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

My wild guess would be that the original sourceFile should be passed to `MavenWrapper#wrapperJar()` but that's a wild guess :).

I wasn't sure how to add a test that would mimick this setup.

**Comment by timtebeek** [comment]
Thanks for the report and clear steps to replicate; had a brief look already. Looks like we create a new Remote source file here:
https://github.com/openrewrite/rewrite/blob/1fa4b4e96d5557758127d57a2d09203cdaa078a3/rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenWrapper.java#L166-L170

And we do copy the id and any markers to that Remote file (to signify it's an update to the same file), but fail to call `.withSourcePath(sourcefile.getSourcePath())`, which effectively moves the file to the default location.
https://github.com/openrewrite/rewrite/blob/1fa4b4e96d5557758127d57a2d09203cdaa078a3/rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenWrapper.java#L392

Adding that `withSourcePath` might be all that's needed to get this fixed; in addition to some testing of course.

**Comment by gsmet** [comment]
Yeah I was thinking more about using `Remote#builder(SourceFile before, URI uri)` so that we make sure we don't forget about setting an important attribute.

That would mean duplicating `MavenWrapper#wrapperJar()` and friends with a `SourceFile before` variant when needed but I think it would be safer. WDYT?

If you can point me to how I could add a test with this type of setup, I would gladly open a PR, I wasn't entirely sure how to create a nested hierarchy with a Maven wrapper in the subdirectory.

**Comment by timtebeek** [comment]
That's likely safer indeed; might even replace the existing no-args methods if applicable (haven't checked).

As for testing: RewiteTest extends SourceSpecs, which has [methods to setup directories](https://github.com/openrewrite/rewrite/blob/1fa4b4e96d5557758127d57a2d09203cdaa078a3/rewrite-test/src/main/java/org/openrewrite/test/SourceSpecs.java#L29-L36). You might need to be sure the correct markers are present, but I expect the existing tests have that already.

And much appreciated that you're looking to provide a fix if possible; note that even a rough draft is already welcome, if you can't get it to work all the way.

**Comment by shanman190** [comment]
Also the same bug exists within the `MavenWrapperDownloader.java` side and in the Gradle wrapper recipe as well from what it looks like.

So you could hand in the before `SourceFile`, but that would mean that you'd have to have a nullable variation for creating a Maven wrapper where there wasn't one (right now this can only be done at the root of the repository). Given that, it might just be easier to copy the `sourcePath` over from the before files just within the edit phase steps (one of which Tim linked to).

The other place would be here:
https://github.com/openrewrite/rewrite/blob/1fa4b4e96d5557758127d57a2d09203cdaa078a3/rewrite-maven%2Fsrc%2Fmain%2Fjava%2Forg%2Fopenrewrite%2Fmaven%2FUpdateMavenWrapper.java#L400


And if you're feeling up for the Gradle version (nearly identical recipe) that's here:
https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle%2Fsrc%2Fmain%2Fjava%2Forg%2Fopenrewrite%2Fgradle%2FUpdateGradleWrapper.java#L332

If you don't happen to feel up to it, I can grab both of these updates sometime in the afternoon for me.

**Comment by gsmet** [comment]
I have a small patch for it already and I'm working on some other fixes in this area due to other feedback.

I still have to figure out how to write the tests though.

**Comment by timtebeek** [comment]
Feel free to push up a draft PR without tests if you'd like me to have a look; I'm out this afternoon, but back this evening.

**Comment by gsmet** [comment]
I pushed my initial work here: https://github.com/openrewrite/rewrite/pull/3989

**Comment by shanman190** [comment]
@gsmet you might check out the latest snapshots when you have a minute, but otherwise I think this issue is now resolved.

**Comment by timtebeek** [comment]
Proactively closing this issue; if needed we can reopen and investigate again. Thanks all!

**Comment by gsmet** [comment]
Ah yes, thanks, I forgot to reference the issue in the PR.
