### ISSUE TITLE
AddDependency.onlyIfUsing does not work as advertised

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#401]
The description for `AddDependency.onlyIfUsing` states: 
"Add the dependency only if using one of the supplied types. Types should be identified by fully qualified class name or a glob expression"

There are two major inaccuracies in this description.

1 - Glob expressions are not supported, only a literal fully qualified name is accepted.
Note the lack of glob support in this snippet from [AddDependencyVisitor](https://github.com/openrewrite/rewrite/blob/c201c2589b57df15544dd2545c3081bc89915935/rewrite-maven/src/main/java/org/openrewrite/maven/AddDependencyVisitor.java#L86) where `onlyIfUsing` is implemented:
```java
        if (onlyIfUsing != null) {
            Set<JavaType> found = ctx.getMessage(JavaType.FOUND_TYPE_CONTEXT_KEY, emptySet());
            if (onlyIfUsing.stream().noneMatch(t -> found.contains(JavaType.Class.build(t)))) {
                return maven;
            }
        }
```
Only being contained in that set on the `ExecutionContext` counts as being "used", which no glob pattern ever will be.

2 - The type wont be found unless some _other_ recipe has found the type _and_ added a specific entry into the `ExecutionContext`. The only visitors which will currently add this key to the execution context are `FindMethods`, `FindTypes` or `AddImport`.
![image](https://user-images.githubusercontent.com/8549033/112524770-70ddef80-8d5d-11eb-80ba-9ba31f6e7397.png)

**Comment by pway99** [comment]
Fixed by: #432
