### ISSUE TITLE
UpgradeDependencyVersion should support forcing exact version

### ISSUE THREAD

**Issue by jpraet** [openrewrite/rewrite#4166]
## What problem are you trying to solve?

As historic legacy, at my workplace internal maven artifact versions are in the format `major.minor-buildnumber`.
I'm trying to use [UpgradeDependencyVersion](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java) to upgrade to an exact specific version `2.0-3`.
But this does not work because it is interpreted as a [hyphenated range](https://docs.openrewrite.org/reference/dependency-version-selectors#hyphenated-range) semver selector. 

## Describe the solution you'd like

A way to force the version to be interpreted as an exact version.

## Have you considered any alternatives or workarounds?

Currently using [ChangeDependencyGroupIdAndArtifactId](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java) as a workaround.
That works, but is not intended for this purpose and results in a recipe validation error "newGroupId OR newArtifactId must be different from before".

**Comment by timtebeek** [comment]
Ah that's unexpected and unfortunate; We use those version selectors in a lot of different places, so I'd hope to solve this without any additional options having to be passed in. Perhaps we could do a quick experiment with an exact version selector? For instance something like `(2.0-3)` or an alternative if you have any other suggestions; this is just a quick thought up to now. :)

**Comment by shanman190** [comment]
What if we used node's exact version syntax? 

`=2.0-3`

Alternatively, we could make the hyphen range more specific as node requires a space on either side of the hyphen (ex `2.0 - 3`). I'm not sure how prevalently the shorter notation is used, but I've not seen it used much, so this may not be too much of a breaking change.

**Comment by jpraet** [comment]
Both `(2.0-3)` and `=2.0-3` seem fine to me. Or `[2.0-3]` which is how it would be represented in a [maven version range](https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html).

**Comment by timtebeek** [comment]
I think I like the exact version option best `=2.0-3`; that has the least potential to confuse users, and would be a new selector such that there's no chance of conflicts with existing use. Would you be open to adding that to [the semver package](https://github.com/openrewrite/rewrite/tree/main/rewrite-core/src/main/java/org/openrewrite/semver) @jpraet ?

**Comment by jpraet** [comment]
> Would you be open to adding that to [the semver package](https://github.com/openrewrite/rewrite/tree/main/rewrite-core/src/main/java/org/openrewrite/semver) @jpraet ?

Yes
