### ISSUE TITLE
Issue with .env extension in migrations

### ISSUE THREAD

**Issue by javidomjim** [openrewrite/rewrite#4175]
## What version of OpenRewrite are you using?
I am using the following

- OpenRewrite v5.26.0
- Maven/Gradle plugin v8.17.1
- rewrite-_module_ v 2.7.1
Using the recipe: org.openrewrite.text.FindAndReplace located in org.openrewrite.rewrite.core:8.17.1

And I have also tested with: 

- OpenRewrite v5.29.0
- Maven/Gradle plugin v8.23.1
- rewrite-_module_ v 2.9.0
Using the recipe: org.openrewrite.text.FindAndReplace located in org.openrewrite.rewrite-core:8.23.1

## How are you running OpenRewrite?
I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
  <version>5.26.0</version>
      <activeRecipes>
	 <recipe>com.project.UpgradeToJava21</recipe>
     </activeRecipes>
</plugin>
```
I am using a recipe that mainly uses the text recipe FindAndReplace to modify some text in both a Dockerfile and a Properties.env file with the idea of changing its version from Java 17 to Java 21. While the Dockerfile migrates its version without any issue, the Properties.env file is not migrating in any case. The recipe that I am using is the following: 

```xml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.project.UpgradeToJava21
displayName: Upgrade to Java 21
description: 'This recipe will apply changes commonly needed when migrating to Java 21, including intermediate versions.'
recipeList:

  # Upgrade to Java 21
  - org.openrewrite.java.migrate.UpgradeToJava21

  # Recipes to change dockerfile to Java 21
  - org.openrewrite.text.FindAndReplace:
      find: "FROM repo/javase-17-ubi8:[0-9]+\\.[0-9]+\\.[0-9]+\\.RELEASE"
      replace: "FROM repo/javase-21-ubi8:1.0.0.RELEASE"
      regex: true
      caseSensitive : true
      filePattern: "**/Dockerfile"

  #TODO: This recipe is currently not working
  # Recipes to change properties.env to Java 21
  - org.openrewrite.text.FindAndReplace:
      find: "adoptopenjdk-17(\\.\\d+\\.\\d+\\+\\d+)"
      replace: adoptopenjdk-21.0.2
      regex: true
      filePattern: "**/envs/properties.env"

---
```
I have also tested a few different scenarios:
 - I have changed the name of the file to props.env and run the recipe, but it did not change to the new version requested in the recipe.
 - I have manually changed the extension of the file from properties.env to properties.txt and in this case, it did work as intended
 - I have tried to change the extension using another recipe, but the content was not change either.
 - I have tried to execute the recipes with dryRun, and it does not look like the recipes are being applied to properties.env
 - I have tried to used another recipe: org.openrewrite.properties.ChangePropertyValue, but it did not change the content.

After all these test, I believe **there must be some kind of issue with the .env extension**, that somehow, it is not being detected by the recipes. 

## What is the smallest, simplest way to reproduce the problem?
By running mvn rewrite:run with the recipe showed above on the Properties.env file that contains the following information: 
```java
# Sonar parameters
SONAR_PROJECT_KEY=""

# Fortify parameters
FORTIFY_PROJECT=""

JAVA_VERSION="adoptopenjdk-17.0.8+7"
```

## What did you expect to see?
```java
# Sonar parameters
SONAR_PROJECT_KEY=""

# Fortify parameters
FORTIFY_PROJECT=""

JAVA_VERSION="adoptopenjdk-21.0.2"
```

## What did you see instead?
```java
# Sonar parameters
SONAR_PROJECT_KEY=""

# Fortify parameters
FORTIFY_PROJECT=""

JAVA_VERSION="adoptopenjdk-17.0.8+7"
```

## What is the full stack trace of any errors you encountered?
In this case, there is no stack trace with any errors. The migration runs succesfully but the properties.env file content remains the same. I have attached an image where you can see the different tests performed with the outputs that they gave in each case:

![Properties env failing](https://github.com/openrewrite/rewrite/assets/51230438/c442eefd-3c81-44c7-9933-d649dba8dfe9)

Thank you very much for your time and for your effort!

**Comment by timtebeek** [comment]
Thanks for bringing this to our attention! The problem you're facing here is that we only parse particular files as text, as specified in the Maven and Gradle plugins. You can override which files to parse as plain text with the mask options on the plugins, such as for instance seen here: https://openrewrite.github.io/rewrite-maven-plugin/run-mojo.html#plainTextMasks

In this specific case I think it makes sense to support those formats by default, so I've gone ahead and added them to the plugins.
- https://github.com/openrewrite/rewrite-maven-plugin/commit/b81b5cdb29c5d7c5c5fad25ea7fc78bcdcfa8f3a
- https://github.com/openrewrite/rewrite-gradle-plugin/commit/672d7cb33292aa3c9384ad02b63a95179cc95f86

The next release should contain this code change; until then you can use [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions). Hope that helps!

**Comment by javidomjim** [comment]
Great! I have just applied the mask options and that did the trick! 

Thank you very much for your help!
