### ISSUE TITLE
YAML: Unable to parse lists of lists 

### ISSUE THREAD

**Issue by pdulich** [openrewrite/rewrite#4176]
## The Problem
In YAML documents it is allowed to define lists of lists.
```yaml
listOfLists:
  - - a
    - b
```

**OpenRewrite is unable to parse this type of lists correctly.**

---

To better understand the meaning of this document, here is the same document described in JSON:
```json
{
  "listOfLists": [
    ["a", "b"]
  ]
}
```

## What version of OpenRewrite are you using?
I am using the OpenRewrite Gradle Plugin v6.12.0

## How are you running OpenRewrite?
I'm using the Gradle Plugin within a single module project.

## What is the smallest, simplest way to reproduce the problem?
To reproduce the problem, create a yaml file containing the following snippet and run the plugin.
```yaml
listOfLists:
  - - a
    - b
```

Another option is to use the unit tests in the rewrite-yaml module e.g. in the `YamlParserTest.java`.
Add the following test and execute it.

```java
@Test
void listOfLists() {
    rewriteRun(
      yaml(
        """
          listOfLists:
            - - a
            - b
          """
      )
    );
}
```

## What did you expect to see?
The yaml should be parseable. Or: the test should succeed.

## What did you see instead?
Parsing of the yaml fails due to:
`When parsing and printing the source code back to text without modifications, the printed source didn't match the original source code. This means there is a bug in the parser implementation itself.`

(This is because, the produced source code contains additional `-` signs.)

## What is the full stack trace of any errors you encountered?
```
org.opentest4j.AssertionFailedError: [When parsing and printing the source code back to text without modifications, the printed source didn't match the original source code. This means there is a bug in the parser implementation itself. Please open an issue to report this, providing a sample of the code that generated this error for "file.yaml":
diff --git a/file.yaml b/file.yaml
index edb1cf7..8cc0b6c 100644
--- a/file.yaml
+++ b/file.yaml
@@ -1,4 +1,4 @@ 
 root:
     listOfLists:
-      - - a
+      - - - a
         - b
\ No newline at end of file
] 
expected: 
  "root:
      listOfLists:
        - - a
          - b"
 but was: 
  "root:
      listOfLists:
        - - - a
          - b"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at org.openrewrite.test.RewriteTest.assertContentEquals(RewriteTest.java:617)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:312)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:133)
	at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:128)
	at org.openrewrite.yaml.YamlParserTest.listOfLists(YamlParserTest.java:70)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
I've already identified the root cause and will create a PR containing the fix later today.

**Comment by timtebeek** [comment]
Thanks a lot for the detailed report and offer to help resolve! Hadn't ever seen those nested lists, but good to know and definitely something we should support then. The error you're seeing is part of our test framework to ensure we faithfully reproduce files whenever there are no changes.

**Comment by pdulich** [comment]
I've found some other problems related to this. My change fixes only lists of lists of scalars. But if it is e.g. a list of list of mappings, the problem still persists.

I'll take care of these bugs. Could you reopen this issue please, @timtebeek?
Or should I open a new issue?
