### ISSUE TITLE
org.openrewrite.java.ChangePackage precise match

### ISSUE THREAD

**Issue by selfyguy** [openrewrite/rewrite#4188]
https://docs.openrewrite.org/recipes/java/changepackage

When I use the above recipe to move/rename/change the types in package `com.test.model.staff` to `com.test.model.data.staff`, it picks up the types in package `com.test.model.staffdetails` too.

How can I restrict it to pick up only files from package `.staff` and **not** from `.staffdetails` ?

**Comment by timtebeek** [comment]
Hi! Thanks for the report; I think this might be a bug we hadn't encountered before. Looking at the implementation quickly it might just be this line that causes trouble:
https://github.com/openrewrite/rewrite/blob/212296420cd490706a23e1b11ee6c85a2813df61/rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java#L94

Slightly further down we don't use `startsWith` but `equals` for package comparison:
https://github.com/openrewrite/rewrite/blob/212296420cd490706a23e1b11ee6c85a2813df61/rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java#L102

The best way to rule this out would be to add a unit test to ChangePackageTest similar to this one
https://github.com/openrewrite/rewrite/blob/212296420cd490706a23e1b11ee6c85a2813df61/rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java#L114-L147

That unit test should then contain two `java()` source specifications; one using package `com.test.model.staff` and one using com.test.model.staffdetails`. Only the source spec using `com.test.model.staff` should have a second text block to indicate the desired change. The other source spec should only have a single text block.

Is this something you'd want to help resolve?

**Comment by shanman190** [comment]
@timtebeek, I think it's a little more complicated than just swapping to equals as it looks like nested packages should be moved as well. 
https://github.com/openrewrite/rewrite/blob/212296420cd490706a23e1b11ee6c85a2813df61/rewrite-java-test%2Fsrc%2Ftest%2Fjava%2Forg%2Fopenrewrite%2Fjava%2FChangePackageTest.java#L364-L400

I suspect that these all should be equals exact and then starts with the package name followed by a dot. That should handle the case of exact package and all subpackages.

**Comment by Dinozavvvr** [comment]
Hi everyone! I'm a user of your project and I'm interested in contributing to it. Can I try to help you in this and maybe some other issues if you don't mind?

**Comment by timtebeek** [comment]
Thanks for your sharp eye as always @shanman190 , and thanks for the offer to help @Dinozavvvr .

> I'm a user of your project and I'm interested in contributing to it. Can I try to help you in this and maybe some other issues if you don't mind?

All help is welcome! Best to start with a draft pull request that just adds tests to replicate the issue at hand here, and then from there we can see what changes would make the test pass to fix the issue.

**Comment by Dinozavvvr** [comment]
Is something need from me now? I wrote tests and fixed issue @timtebeek

**Comment by timtebeek** [comment]
Thanks a lot! Hadn't seen your PR pop up just yet as drafts don't trigger a notification for me yet. I see it now though:
- https://github.com/openrewrite/rewrite/pull/4189

I'm traveling right now, but will be back Thursday for a closer look; great to see you picked this up and worked out how to make the tests pass.

**Comment by timtebeek** [comment]
Thanks a lot @Dinozavvvr ; Change should make it into our next release, and can already be tried out from the latest [snapshot version](https://docs.openrewrite.org/reference/snapshot-instructions).
