### ISSUE TITLE
Java 17 upgrade recipe is not updating Gradle wrapper to 7.3+

### ISSUE THREAD

**Issue by aakash-pinc** [openrewrite/rewrite#4195]
## How are you running OpenRewrite?
Moderne.io

## Problem Statement
Java 17 Migration recipe is not upgrade Gradle wrapper to supported version as per [Gradle-Java-Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html)

## What is the smallest, simplest way to reproduce the problem?
Create a Gradle (4.x) project with JDK 8.  Now run the Java 17 migration recipe and you will notice Gradle wrapper is not upgraded to 7.3+.

## Are you interested in [contributing a fix to OpenRewrite]
No

**Comment by timtebeek** [comment]
Thanks for the suggestion @aakash-pinc ! Picked up in https://github.com/openrewrite/rewrite-migrate-java/commit/907ac1c1c6b99d9e4b2a8ff4875c1d8e7e15b1a3 , which is available after a redeploy of the recipes.
