### ISSUE TITLE
GitProvenance is very slow getting committers on a large Git history

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite#4210]
## What version of OpenRewrite are you using?

I am using
- Maven plugin 5.32.0

## What did you see instead?
After the following line of output
```
[INFO] Validating active recipes...
```
there is a delay of several minutes when I run locally. When I noticed this, I attached a profiler. The GitProvenance calculation of the committers takes forever. In the following screenshot that consumes around 7 minutes (after I noticed the delay, so add some minutes).
![grafik](https://github.com/openrewrite/rewrite/assets/406876/b30a4def-0960-4989-b939-6b7e06cbe1ba)
The git repo has 67K commits and 63K committed files (currently). I'm on Windows.

Maybe that information is useful when running on moderne.io infrastructure, but for local execution of most recipes that's probably not useful and should be improved.

**Comment by timtebeek** [comment]
Oh wow; picture really speaks volumes here; thanks for including that! The `getCommitters(Repository)` was added last year
- https://github.com/openrewrite/rewrite/pull/3654

And is called from this group of methods. 
https://github.com/openrewrite/rewrite/blob/58156584fa98e03cb9201b8f44739519f4e6f15e/rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java#L146-L218

I agree with you that we should do something to improve performance here, or add a cut off past which we stop looking at committers; say a couple months. Either way thanks for calling this out!

**Comment by timtebeek** [comment]
Figured provide some more context: both [the Maven plugin](https://github.com/openrewrite/rewrite-maven-plugin/blob/56cc48b0c0faefb37812578a3d247c40599c99e8/src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java#L777-L785) and [Gradle plugin](https://github.com/openrewrite/rewrite-gradle-plugin/blob/6121f79f122f69f09457734ee9fd28a5888493db/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L152-L160) call the same method in openrewrite/rewrite to determine the GitProvenance. We're considering adding a 90 day committer history look back cut off to limit how many commits are evaluated while still having some committer history available to recipes. Not yet saying we'll definitely land on that, but figured give you that update such that you know we're working on it.

**Comment by timtebeek** [comment]
Thanks again @Bananeweizen ! Sam's had another look at it turns out that we're not just calling `getCommitters(Repository)` once, but once for each submodule(!). That then greatly inflates the time necessary, especially when there are a large number of modules. Sam will pick this up.

**Comment by timtebeek** [comment]
Likely fixed, or at least much improved in
- https://github.com/openrewrite/rewrite-maven-plugin/commit/6abcb02653b101723b6ec4d454bd78be03ffc23d
- https://github.com/openrewrite/rewrite-gradle-plugin/commit/a12a4403ebb0e668e37ff3fbe44b7ef328d33f9b

Thanks again for the reporting this issue; I hope you see similar improvements there, or else let us know!

**Comment by Bananeweizen** [comment]
@timtebeek much, much faster now. Haven't profiled, but the previous long pause surely isn't that long anymore.
