### ISSUE TITLE
Merge Yaml to a specific File

### ISSUE THREAD

**Issue by Sid532001** [openrewrite/rewrite#4225]
Hi @Openrewrite i want to write a recipe which inserts a snippet inside a key in a specific yaml file  in my case application.yaml

# Current scenario
i have a field 
animals:
# End result 
I want my result to look like this 
animals:
	dog:
	   pet:
		labrador
		
![image](https://github.com/openrewrite/rewrite/assets/57298688/84ae4824-c96a-4842-9f03-3538469811af)

Do we have any recipe to perform this operation on a specific file
@timtebeek

**Comment by timtebeek** [comment]
Sure, you can use our merge yaml recipe and combine that with a precondition that limits the recipe to files matching a particular path, as seen here: https://docs.openrewrite.org/reference/yaml-format-reference#preconditions

Hope that helps!
