### ISSUE TITLE
Yaml parser support for flow style mappings

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite#423]
The current yaml parser (and printer) makes the assumption that parsed yaml documents contain only block style elements. Add support for Yaml flow style sequences and mappings, and any other flow style yaml document elements.

example flow style sequence:
```
a: [foo bar, baz]
```

example flow style mapping:
```
b: {c: 3, d: 4}
```

**Comment by sambsnyd** [comment]
flow-styled sequences are now handled as of #573.
flow-styled mappings are, as of yet, unsupported.
