### ISSUE TITLE
`CatchClauseOnlyRethrows` should not remove empty catch if the exception then gets caught by another catch block

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite#4235]
### Problem
As can be seen in the example, a catch block is removed that was added for a specific subtype of an exception to just have it rethrown. Now, that the catch block is removed, the exception will get handled by a different catch block, which is the wrong thing to do.

### Expected behavior
In this case the recipe should not remove the catch block. Checking for any following catch blocks is the easy fix here.

### Example diff

**From:** `spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/serializer/ByteArraySingleTerminatorSerializer.java`

```diff
 			}
return copyToSizedArray(buffer, n);
}
-		catch (SoftEndOfStreamException e) { // NOSONAR catch and throw
-			throw e; // it's an IO exception and we don't want an event for this
-		}
catch (IOException | RuntimeException ex) {
publishEvent(ex, buffer, n);
throw ex;
```

#### Recipes in example diff:
- `org.openrewrite.staticanalysis.CatchClauseOnlyRethrows`

### References:
- [View original result](https://app.moderne.io/results/XzAhP6YZa/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoic3ByaW5nLXByb2plY3RzL3NwcmluZy1pbnRlZ3JhdGlvbiIsImJyYW5jaCI6Im1haW4ifQ==?referrer=https%3A%2F%2Fapp.moderne.io%2Fresults%2FXzAhP6YZa)
- Recipe ID: `org.openrewrite.staticanalysis.CatchClauseOnlyRethrows`
- Recipe Name: `Catch clause should do more than just rethrow`
- Repository: `spring-projects/spring-integration/main`
- Created at Fri Jun 07 2024 16:24:12 GMT+0200 (Central European Summer Time)

**Comment by nielsdebruin** [comment]
Should be resolved with merging https://github.com/openrewrite/rewrite-static-analysis/pull/348
