### ISSUE TITLE
add clang-format style

### ISSUE THREAD

**Issue by samuelfac** [openrewrite/rewrite#4251]
## What problem are you trying to solve?
Format the code with [clang-format](https://github.com/autostyle/clang-format) style

## Describe the solution you'd like
create a new style that will use ".clang-format" file from source project to format the code.

**Comment by timtebeek** [comment]
Hi @samuelfac ; I'm not too familiar with clang-format; would you mind explaining in some more detail exactly what you're after? Perhaps with some examples of a configuration file to take in and apply to projects?

You might know we already support various named styles, and even allow you to customize styles to your needs.
https://docs.openrewrite.org/concepts-explanations/styles
Could this be used to achieve what you're after already?

I'm not sure how widely used [clang-format](https://clang.llvm.org/docs/ClangFormat.html) is, but it's a high bar for us to add two ways to do one thing; in this case to define how you want to define your project style.

There's also other competing standards like checkstyle and .editorconfig that on the surface seem similar, as are tools like spotless and Google Java format that do not allow customization. I'd be hesitant to add support for each of these and have to support all going forward. 

What's the context behind your specific request for clang support?

**Comment by timtebeek** [comment]
For now this feature is not planned; We can revisit this if there's renewed interest in the future.
