### ISSUE TITLE
Incompatible types error in ReloadableJava21Parser

### ISSUE THREAD

**Issue by protocol7** [openrewrite/rewrite#4301]
## What version of OpenRewrite are you using?
* org.openrewrite:rewrite-core:jar:8.29.0

## What is the smallest, simplest way to reproduce the problem?
ReloadableJava21Parser fails to parse the following snippet:

```java
import static org.hamcrest.Matchers.allOf;
import static org.hamcrest.Matchers.hasProperty;
import static org.hamcrest.core.Is.isA;
import static org.hamcrest.core.IsEqual.equalTo;

import org.hamcrest.Matcher;

public class Foo {
  public static Matcher<Throwable> bar() {
    return allOf(
        isA(Exception.class),
        hasProperty("message", equalTo("foo")));
  }
}
```

Generates the following error:
```
11:20:24.320 [main] WARN  o.o.j.i.ReloadableJava21Parser -- Foo.java:12: error: incompatible types: inference variable T#1 has incompatible bounds
11:20:24.320 [main] WARN  o.o.j.i.ReloadableJava21Parser --     return allOf(
11:20:24.320 [main] WARN  o.o.j.i.ReloadableJava21Parser --                 ^
11:20:24.320 [main] WARN  o.o.j.i.ReloadableJava21Parser --     equality constraints: Throwable
11:20:24.321 [main] WARN  o.o.j.i.ReloadableJava21Parser --     upper bounds: T#2,T#3,Exception,Object
11:20:24.321 [main] WARN  o.o.j.i.ReloadableJava21Parser --   where T#1,T#2,T#3 are type-variables:
11:20:24.321 [main] WARN  o.o.j.i.ReloadableJava21Parser --     T#1 extends Object declared in method <T#1>allOf(Matcher<? super T#1>,Matcher<? super T#1>)
11:20:24.321 [main] WARN  o.o.j.i.ReloadableJava21Parser --     T#2 extends Object declared in method <T#2>hasProperty(String,Matcher<?>)
11:20:24.321 [main] WARN  o.o.j.i.ReloadableJava21Parser --     T#3 extends Object declared in method <T#3>isA(Class<T#3>)
```

This then causes some recipes to fail, presumably because they lack the full LST.

## Are you interested in contributing a fix to OpenRewrite

I suspect this is beyond my understanding of OpenRewrite :)

**Comment by protocol7** [comment]
This can be further reduced to:

```java
import static org.hamcrest.core.Is.isA;

import org.hamcrest.Matcher;

public class Foo {
  public static Matcher<Throwable> bar() {
    return isA(Exception.class);
  }
}```

Giving the error:
```
12:07:07.891 [main] WARN  o.o.j.i.ReloadableJava21Parser -- Foo.java:10: error: incompatible types: inference variable T has incompatible equality constraints Throwable,Exception
12:07:07.892 [main] WARN  o.o.j.i.ReloadableJava21Parser --     return isA(Exception.class);
12:07:07.892 [main] WARN  o.o.j.i.ReloadableJava21Parser --               ^
12:07:07.892 [main] WARN  o.o.j.i.ReloadableJava21Parser --   where T is a type-variable:
12:07:07.892 [main] WARN  o.o.j.i.ReloadableJava21Parser --     T extends Object declared in method <T>isA(Class<T>)
```

Note that this compiles with `javac`

(Don't trust the line numbers as I've done some editing of the code before posting here).

**Comment by timtebeek** [comment]
Thanks for the detailed report again! I'm trying to replicate the issue here, but so far my unit test isn't turning up any issue just yet.

```java
import org.junit.jupiter.api.Test;
import org.openrewrite.Recipe;
import org.openrewrite.java.JavaParser;
import org.openrewrite.test.RecipeSpec;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.java.Assertions.java;

class HamcrestParserTest implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        spec.parser(JavaParser.fromJavaVersion().classpath("hamcrest"))
          .recipe(Recipe.noop());
    }

    @Test
    void foo() {
        rewriteRun(
          //language=java
          java(
            """
              import static org.hamcrest.core.Is.isA;

              import org.hamcrest.Matcher;

              public class Foo {
                public static Matcher<Throwable> bar() {
                  return isA(Exception.class);
                }
              }
              """
          )
        );
    }
}
```

**Comment by timtebeek** [comment]
No issue either when I place this class into an empty project.

```java
import org.hamcrest.Matcher;
import static org.hamcrest.core.Is.isA;
import org.hamcrest.Matcher;

public class Foo {
  public static Matcher<Throwable> bar() {
    return isA(Exception.class);
  }
}
```

And then run: `mvn org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=org.openrewrite.java.OrderImports`
Note the deliberate double import such that the recipe makes changes.

**Comment by protocol7** [comment]
Thanks for turning it into a proper test. Just to confirm that I'm also not seeing the issue when running the test above, including when swapping in the original code in our code base that triggered this. I'll continue debugging what is different between how we run OpenRewrite in our regular job vs in this test.

**Comment by timtebeek** [comment]
Sure! Let me know what you find there; and note that you can skip past building the LST model and jump straight to a breakpoint in your debugger when [executing recipes with the Moderne CLI](https://www.moderne.io/moderne-ide-plugin-signup). Perhaps that helps you there, as it's a nice time-saver here.

**Comment by protocol7** [comment]
Was able to figure this out. We got an old 1.3 version of hamcrest-core as a transitive dependency through org.openrewrite.recipe:rewrite-testing-frameworks -> junit:junit -> org.hamcrest:hamcrest-core, which has different type for the relevant method:
```java
public static <T> Matcher<T> isA(Class<T> type)
```

2.x has:
```java
public static <T> Matcher<T> isA(Class<?> type)
```

Excluding `junit:junit` as a transitive dependency fixes this. Sorry for the noise here, OpenRewrite is working as intended :)

**Comment by timtebeek** [comment]
Ah thanks for confirming! All the best there.
