### ISSUE TITLE
UseStaticImport should rewrite if method already exists

### ISSUE THREAD

**Issue by protocol7** [openrewrite/rewrite#4304]
## What version of OpenRewrite are you using?
* org.openrewrite:rewrite-core:jar:8.29.0

## What is the smallest, simplest way to reproduce the problem?

UseStaticImport should not rewrite with an import static when there is a method in the scope with the same name (and maybe signature).

The second case below I'm not sure how to best deal with, perhaps don't rewrite the `String.valueOf`, or do what the test here does.

```java
  @Test
  void testUseStaticImport() {
    rewriteRun(
        spec -> spec.recipe(new UseStaticImport("java.util.List of(..)")),
        // language=java
        java(
            """
                    package com.helloworld;

                    import java.util.List;

                    public class Foo {

                        void of() {}

                        void foo() {
                          List.of();
                        }
                    }
            """));
  }

  @Test
  void testUseStaticImport2() {
    rewriteRun(
        spec ->
            spec.recipe(
                new CompositeRecipe(
                    List.of(
                        new UseStaticImport("java.lang.String valueOf(..)"),
                        new UseStaticImport("java.lang.Integer valueOf(..)")))),
        // language=java
        java(
            """
                    package com.helloworld;

                    public class Foo {
                        void foo() {
                          String.valueOf("1");
                          Integer.valueOf("1");
                        }
                    }
            """,
            """
                    package com.helloworld;

                    import static java.lang.String.valueOf;
        
                    public class Foo {
                        void foo() {
                          valueOf("1");
                          Integer.valueOf("1");
                        }
                    }
            """
        ));
  }
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Happy to give it a try with some pointers, as usual not sure where to start.

**Comment by timtebeek** [comment]
Thanks for the report! In this case I think extending the preconditions with a separate visitor that looks at static imports used might be best. We already have a check on not declaring any similarly named methods. This would be a similar check but then looking at not having any similarly named static imports already.

https://github.com/openrewrite/rewrite/blob/c97c7f214634c78b257e6a7eb6705727f3d46900/rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java#L62

Welcome to add just those two unit tests to a draft pull request to kick this off; then we can see if you work it out from there, or tag team to get this through.

**Comment by protocol7** [comment]
> We already have a check on not declaring any similarly named methods

Is that intended to inhibit the behaviour in the first test I included? I happened to notice that the buggy behaviour there seems to require the class being in a package, so perhaps something is broken with the precondition.

**Comment by timtebeek** [comment]
Hmm; Yes thanks for calling that out! Shows again why I love runnable bug reports. Makes troubleshooting much easier.

**Comment by protocol7** [comment]
Here's a start: https://github.com/openrewrite/rewrite/pull/4307. This fixes the bug with not taking the package name into account, but does not add a precondition for already imported methods yet.
