### ISSUE TITLE
`JavaTemplate` leaves behind temporary directory `java-templateXXXX` after execution

### ISSUE THREAD

**Issue by pzygielo** [openrewrite/rewrite#4369]
Temporary directory created at
https://github.com/openrewrite/rewrite/blob/65fb0cf71643037d1c472348317fa88a2f32bb3b/rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java#L49 is left in file system with
```
java-template9656347799495757644
└── org
    └── openrewrite
        └── java
            └── internal
                └── template
                    ├── __M__.class
                    └── __P__.class
```

**Comment by timtebeek** [comment]
Oh wow, thanks for calling that out! Would you want to add a small change to delete that file on exit? That should help I suppose.
