### ISSUE TITLE
Migrate nullness annotations to JSpecify

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite#4419]
## What problem are you trying to solve?
Standardized nullness annotations across code bases

## Describe the solution you'd like
Convert all existing nullness annoations  https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use to https://jspecify.dev/docs/start-here/ standard ones.

Should create one recipe for nullable and another for nonnull.  This are different due to Lombok's runtime NonNull behaviour.  Also create a NullMarked if provablly nonnull or all nonnul.

## Have you considered any alternatives or workarounds?
- Maybe https://github.com/jspecify/jspecify/issues/553

**Comment by timtebeek** [comment]
With that I think we have two good options for you already: either adapt the above declarative recipes if you want to have something today, or subscribe to that open PR for a larger effort to standardize as outlined above. Hope that helps!

**Comment by timtebeek** [comment]
I'll close this one as a duplicate for now; we can continue to track in the above PR or this issue.
- https://github.com/openrewrite/rewrite/issues/2838
