### ISSUE TITLE
newArtifactId changed to newArtifact in ChangePluginGroupIdAndArtifactId

### ISSUE THREAD

**Issue by gsmet** [openrewrite/rewrite#4420]
:wave:

`newArtifactId` was renamed to `newArtifact` in `ChangePluginGroupIdAndArtifactId`.

This is very odd as not consistent with the rest of the properties (you have `oldArtifactId` but `newArtifact`). Also it breaks compatibility for anyone using the recipe.

The change was made here: https://github.com/openrewrite/rewrite/pull/3843/files#diff-a3496299541c5119d2fd48e331f97b62173789f41a9ec4f5f25f9e8454ab7518R59

And you can see that there are already a few people complaining there.

I know the change is not exactly recent but for whatever reason, it just popped up in the Quarkus Updates test.

It looks odd to me. Could someone confirm that it was intended?

Thanks!

**Comment by timtebeek** [comment]
Indeed looks accidental; Let's restore the original. Would you want to push that up?

**Comment by gsmet** [comment]
Working on it but I have a hard time building now: 

```
> Failed to query the value of task ':rewrite-gradle:compileGroovy' property 'javaLauncher'.
   > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=8, vendor=any vendor, implementation=vendor-specific} for LINUX on x86_64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.
```

Is there a way to run things without having to install Java 8 somewhere?

**Comment by gsmet** [comment]
Well, I installed a good old Java 8 with SDKMAN! and I can go further.

**Comment by gsmet** [comment]
https://github.com/openrewrite/rewrite/pull/4421 should address it.
