### ISSUE TITLE
rewrite-maven error parse pom.xml

### ISSUE THREAD

**Issue by HelloDhero** [openrewrite/rewrite#4439]
rewrite-maven has error in ResolvedPom.resolveDependencies , it try download maven-core use the version properties ${project.prerequisites.maven}, but the transmitting dependencies has be exclude

**Comment by timtebeek** [comment]
Hi @HelloDhero ; it's unclear what you're asking. Please follow this structure when opening issues, and include enough details for us to reproduce the issue:
https://github.com/openrewrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
