### ISSUE TITLE
Xpath 'nodes from anywhere' + attribute selection does not work

### ISSUE THREAD

**Issue by crankydillo** [openrewrite/rewrite#4528]
## What version of OpenRewrite are you using?

`main` branch

## How are you running OpenRewrite?

The following test fails on the last `assertThat` when added to `XPathMatcherTest`

```java
    @Test
    void noMatterWhereAttributeSelection() {
        assertThat(match("/dependencies/dependency/artifactId[@scope='compile']", xmlDoc)).isTrue();
        assertThat(match("//artifactId[@scope='compile']", xmlDoc)).isTrue();
        assertThat(match("//dependency/artifactId[@scope='compile']", xmlDoc)).isTrue();
    }
```
## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I always want to, but time is short:(  #4269 is currently more concerning for us:)

**Comment by DidierLoiseau** [comment]
Now that #4532 was merged, these tests succeed :slightly_smiling_face:

**Comment by timtebeek** [comment]
Thanks again @DidierLoiseau !
