### ISSUE TITLE
Minor parsing issue; space after import, before semi-colon

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#4569]
## What version of OpenRewrite are you using?
- OpenRewrite. Latest: v8.37.x
- Maven/Gradle plugin: N/A -- noticed while reading parser code.

## How are you running OpenRewrite?
N/A

The issue is caused by IMPORT missing here, and applies to all languages: https://github.com/openrewrite/rewrite/blob/main/rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java

## What is the smallest, simplest way to reproduce the problem?
```java
    @Test
    void spaceBeforeSemiColon() {
        rewriteRun(
          java(
            """
              import java.util.List ;
              """
          )
        );
    }
```

## What did you expect to see?

```java
import java.util.List ;
```

## What did you see instead?

```java
import java.util.List; // <- space is removed
```

**Comment by timtebeek** [comment]
Thanks for the runnable report @traceyyoshima ! I imagine this breaks the print idempotence, and then blocks any changes to those files? Did you already explore any possible fix?

**Comment by traceyyoshima** [comment]
> IMPORT

Ya, the parsing bug will result in a parsing error which would prevent changes.

Ah, I didn't realize the link I provided didn't include the line number. `IMPORT` needs to be added here: https://github.com/openrewrite/rewrite/blob/main/rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java#L1769. The imports needs to be detected as a statement during parsing to handle space before the semicolon.

**Comment by timtebeek** [comment]
Ah that helps, thanks! Seems manageable, although I've logged off for today and I'm out all of tomorrow. Will try to have another look Sunday or Monday then. Thanks for clarifying!

**Comment by timtebeek** [comment]
Your suggestion indeed fixes the test you added; Could you double check I understood you correctly?
- https://github.com/openrewrite/rewrite/pull/4577

**Comment by traceyyoshima** [comment]
> Your suggestion indeed fixes the test you added; Could you double check I understood you correctly?
> 
> * [Detect whitespace before import semicolon #4577](https://github.com/openrewrite/rewrite/pull/4577)

The changes look good
