### ISSUE TITLE
org.openrewrite.java.style.CheckstyleConfigLoader isn't actually used 

### ISSUE THREAD

**Issue by blipper** [openrewrite/rewrite#4570]
I can't find any evidence that this is actually used?  It would be useful but there doesn't seem the machinery to actually use as part of the style or configure it?

**Comment by timtebeek** [comment]
Hi! That's used in both the Maven and Gradle plugins:
* https://github.com/openrewrite/rewrite-maven-plugin/blob/22bb78748d442a9f2c316978efc82bc487533b59/src/main/java/org/openrewrite/maven/ConfigurableRewriteMojo.java#L247-L282
* https://github.com/openrewrite/rewrite-gradle-plugin/blob/459570d8ec7cc874df8802bb3d326b3d3446047e/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L1340-L1353

Are you using either of those plugins? Or are you perhaps using something else still?

Either way I'll close the issue as it's not immediately actionable, but happy to answer any further questions.
