### ISSUE TITLE
Have time to help take a look at the jdk21 upgrade issue

### ISSUE THREAD

**Issue by stevenniu9527** [openrewrite/rewrite#4576]
1、I used UpgradeToJava21 and found that javax->jakarta was not being upgraded

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>5.42.0</version>
                <configuration>
                    <exportDatatables>true</exportDatatables>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.migrate.UpgradeToJava21</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-spring</artifactId>
                        <version>5.21.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-migrate-java</artifactId>
                        <version>2.23.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```
result：
![image](https://github.com/user-attachments/assets/9ea55f3f-2a88-4ebd-a527-6d86e7bb5834)

2、How to use the UpgradeSpringBoot_3_3 at the same time, remove junit4 upgrade junit5 recipe .
I only want to upgrade Springboot related, I don't want to upgrade the junit version.

3、After the swagger upgrade, the response type annotation was not converted, but was deleted directly
origin code：
```java
  @GET
  @Path("sync")
  @ApiOperation(value = "acquireSyncLeader", notes = "acquireSyncLeader", response = String.class, httpMethod = "GET")
  @ApiResponses(value = {
          @ApiResponse(code = 500, message = "inner error"),
          @ApiResponse(code = 404, message = "not found")
  })
```
updated code:
```java
  @GET
  @Path("sync")
  @Operation(summary = "acquireSyncLeader", description = "acquireSyncLeader", httpMethod = "GET")
  @ApiResponses(value = {
          @ApiResponse(responseCode = "500", description = "inner error"),
          @ApiResponse(responseCode = "404", description = "not found")
  })
```

I hope to get the code
```java
 @GET
    @Path("sync")
    @Operation(summary = "acquireSyncLeader", description = "acquireSyncLeader", responses = {@ApiResponse(responseCode = "200",
            content = @Content(schema = @Schema(implementation = String.class))),
            @ApiResponse(responseCode = "404", description = "not found"), @ApiResponse(responseCode = "500", description = "inner error")}, method = "GET")
```

**Comment by timtebeek** [comment]
hi! Please update the version of rewrite-migrate-java you're using for more predictable results:
- https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v5.42.2
- https://github.com/openrewrite/rewrite-migrate-java/releases/tag/v2.27.0

**Comment by stevenniu9527** [comment]
> hi! Please update the version of rewrite-migrate-java you're using for more predictable results:
> 
> * https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v5.42.2
> * https://github.com/openrewrite/rewrite-migrate-java/releases/tag/v2.27.0

Thanks, Please have a look other question:

2、How to use the UpgradeSpringBoot_3_3 at the same time, remove junit4 upgrade junit5 recipe .
I only want to upgrade Springboot related, I don't want to upgrade the junit version.

3、After the swagger upgrade, the response type annotation was not converted, but was deleted directly
origin code：

  @GET
  @Path("sync")
  @ApiOperation(value = "acquireSyncLeader", notes = "acquireSyncLeader", response = String.class, httpMethod = "GET")
  @ApiResponses(value = {
          @ApiResponse(code = 500, message = "inner error"),
          @ApiResponse(code = 404, message = "not found")
  })
updated code:

  @GET
  @Path("sync")
  @Operation(summary = "acquireSyncLeader", description = "acquireSyncLeader", httpMethod = "GET")
  @ApiResponses(value = {
          @ApiResponse(responseCode = "500", description = "inner error"),
          @ApiResponse(responseCode = "404", description = "not found")
  })
I hope to get the code

 @GET
    @Path("sync")
    @Operation(summary = "acquireSyncLeader", description = "acquireSyncLeader", responses = {@ApiResponse(responseCode = "200",
            content = @Content(schema = @Schema(implementation = String.class))),
            @ApiResponse(responseCode = "404", description = "not found"), @ApiResponse(responseCode = "500", description =

**Comment by timtebeek** [comment]
Spring Boot 3 requires JUnit Jupiter; which is why we include those changes when you upgrade Spring Boot.

For the swagger changes it sounds like you're proposing a change to these lines in [rewrite-openapi](https://github.com/openrewrite/rewrite-openapi/):
https://github.com/openrewrite/rewrite-openapi/blob/178666d08dd2b8b577f974be9ccee79f179c6ef8/src/main/resources/META-INF/rewrite/swagger-2.yml#L128-L130
Are you sure that's necessary? We hadn't had any earlier complaints. If so you can open an issue again rewrite-openapi.

With that I think we've answered all your questions; also feel free to join [our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) if you have any further questions, as GitHub Issues aren't ideal for quick fleeting questions.
