### ISSUE TITLE
MavenPomDownloader fails to download some dependencies

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite#461]
Dear Rewriters,

we add `org.springframework.boot:spring-boot-starter-data-jpa:runtime` and `com.h2database:h2:runtime` as dependencies and `MavenPomDownloader` fails to download `dbcp2` and `h2`, please see the test attached which explicitly tries to download `org.apache.commons:commons-dbcp2:2.8.0` and fails. These are the only problems we've seen so far.

[MavenPomDownloaderTest.java.txt](https://github.com/openrewrite/rewrite/files/6353280/MavenPomDownloaderTest.java.txt)

**Comment by traceyyoshima** [comment]
Thanks for reporting the issue @fabapp2!
I tested each of the mentioned dependencies and they're resolved with the latest maven resolution.

I'll be closing the issue, please let us know if you have any other issues!
