### ISSUE TITLE
Openrewrite marketplace should render empty string and space options in more obvious way

### ISSUE THREAD

**Issue by bmuschko** [openrewrite/rewrite#4619]
## What problem are you trying to solve?

Navigate to the recipe "Add a configuration option for the Maven runtime" via https://app.moderne.io/marketplace/org.openrewrite.maven.core. The empty string and space options seem to have no assigned textual representation, even though the value is an [empty string and space](https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/AddRuntimeConfig.java#L61-L65).

<img width="566" alt="image" src="https://github.com/user-attachments/assets/1f14a690-fd13-4981-9d8e-fb48d42e2439">

## Describe the solution you'd like

The options should be rendered in a more apparent way so that end users can identify then as an empty string and space.

## Have you considered any alternatives or workarounds?

There are no workarounds.

## Additional context

N/A

## Are you interested in [contributing this feature to OpenRewrite]

I am not sure I can contribute the UI. Is this a public Git repo?

**Comment by timtebeek** [comment]
hi @bmuschko ; Thanks for pointing this out; the UI is not a public Git repository, but I'll pass your issue along to the team, and ask them to report back here.

**Comment by zieka** [comment]
@bmuschko thanks for reporting this!
A fix will be deployed soon
<img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbmx3dTNjM3IzNmtxdnJlM291cG1lM3R1YnQ3MjU2ajE4ZDg3MXRoYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/mi6DsSSNKDbUY/giphy-downsized.gif" />
