### ISSUE TITLE
OpenRewrite fails with "Illegal state while comparing versions" when using internal dependencies with non-SemVer versions

### ISSUE THREAD

**Issue by kadirbekov** [openrewrite/rewrite#4654]
**Hello,**

I'm encountering an issue with OpenRewrite when attempting to upgrade to Spring Boot 3.3 using the UpgradeSpringBoot_3_3 recipe. Our project includes internal company dependencies that use version numbers not following Semantic Versioning (SemVer), such as **ORC-246-1-SNAPSHOT**. This causes OpenRewrite to fail with an exception when comparing versions.

**Environment:**
OpenRewrite Gradle Plugin Version: 6.26.0
OpenRewrite Spring Recipe Version: 5.22.0
Build Tool: Gradle
Gradle Version: gradle-7.6
Java Version: JDK 17
Operating System: (macOS Sequoia)

**Build Script Snippets:**
build.gradle file:
```

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.1'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'org.hibernate.orm' version '6.1.6.Final'
    id 'org.openrewrite.rewrite' version '6.26.0'
}

dependencies {
    // Other dependencies...

    implementation "com.veon.eurasia.oraculum:jira-api:ORC-246-1-SNAPSHOT"
    rewrite("org.openrewrite.recipe:rewrite-spring:5.22.0")
}

rewrite {
    activeRecipe("org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_3")
}
```

**Problem Description:**
When running the rewriteRun task, we receive the following error:

```

Caused by: java.lang.IllegalStateException: Illegal state while comparing versions: [ORC.0.0.0-246.0.0.0] and [9.0.0]. Metadata = [9.0.0]
    at org.openrewrite.semver.LatestRelease.compare(LatestRelease.java:164)
    at org.openrewrite.semver.VersionComparator.upgrade(VersionComparator.java:45)
    at org.openrewrite.gradle.DependencyVersionSelector.select(DependencyVersionSelector.java:142)
    at org.openrewrite.gradle.DependencyVersionSelector.select(DependencyVersionSelector.java:83)
    ...
Caused by: java.lang.IllegalStateException: No match found
```
[logs.txt](https://github.com/user-attachments/files/17660966/logs.txt)

**Analysis:**
It appears that OpenRewrite is attempting to compare our internal dependency version ORC-246-1-SNAPSHOT (parsed as ORC.0.0.0-246.0.0.0) with a standard SemVer version 9.0.0. This leads to an exception because the version format does not match the expected SemVer pattern.

**Steps to Reproduce:**
Include a dependency with a non-SemVer version format in the project, e.g., ORC-246-1-SNAPSHOT.
Configure OpenRewrite with the UpgradeSpringBoot_3_3 recipe.
Run the rewriteRun Gradle task:
bash
Copy code
./gradlew rewriteRun

**Expected Behavior:**
OpenRewrite should handle dependencies with non-SemVer version formats gracefully, perhaps by:

Skipping them during version comparison.
Providing a warning instead of throwing an exception.
Allowing configuration to exclude certain dependencies from version comparisons.
Attempted Workarounds:

Is there a recommended way to configure OpenRewrite **to handle dependencies with non-SemVer** version formats?

Thank you for your assistance!

**Comment by timtebeek** [comment]
- Fixed in https://github.com/openrewrite/rewrite/pull/4656

Thanks for the report @kadirbekov & thanks for the fix @Jenson3210 !
