### ISSUE TITLE
Illegal state while comparing versions with latest.release

### ISSUE THREAD

**Issue by asibross** [openrewrite/rewrite#4684]
This exception was thrown:
```
Caused by: java.lang.RuntimeException: Error while visiting build.gradle: java.lang.IllegalStateException: Illegal state while comparing versions : [latest.0.0.0.0.0.0] and [3.0.1]. Metadata = [3.0.1]
  org.openrewrite.semver.LatestRelease.compare(LatestRelease.java:164)
  org.openrewrite.semver.VersionComparator.upgrade(VersionComparator.java:45)
  org.openrewrite.gradle.DependencyVersionSelector.select(DependencyVersionSelector.java:142)
  org.openrewrite.gradle.DependencyVersionSelector.select(DependencyVersionSelector.java:83)
  org.openrewrite.gradle.UpgradeDependencyVersion$1.visitMethodInvocation(UpgradeDependencyVersion.java:227)
  org.openrewrite.gradle.UpgradeDependencyVersion$1.visitMethodInvocation(UpgradeDependencyVersion.java:148)
```

When using a gradle dependency with map notation and latest.release version.
For example:
```
implementation group: 'com.jayway.jsonpath', name: 'json-path', version: 'latest.release'
```

When using String notation things work as expected:
```
implementation 'com.jayway.jsonpath:json-path:latest.release'
```

## What version of OpenRewrite are you using?
`rewrite-core` version: 8.40.2

## How are you running OpenRewrite?

I am using the Gradle init script.

**Comment by timtebeek** [comment]
Thanks for the report @asibross ! Indeed seems like we're misinterpreting the version for that particular notation. Would you want to help resolve the issue by opening a draft PR that adds a unit test first? [UpgradeDependencyVersionTest.java](https://github.com/openrewrite/rewrite/blob/main/rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java) has a few examples already that should be easy to copy and adjust to match your case.

**Comment by timtebeek** [comment]
Hmm; I've briefly tried to replicate this issue by adding a test to 
https://github.com/openrewrite/rewrite/blob/372246cbdc55d39dc8507f1cc5c7dae7c84b8d2e/rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java#L37

So far this test passes; do you spot anything I might be doing differently that could make a similar test fail?
```java
@Issue("https://github.com/openrewrite/rewrite/issues/4684")
@Test
void mapNotationLiteralLatestRelease() {
    rewriteRun(
      buildGradle(
        """
          plugins {
            id 'java-library'
          }

          repositories {
            mavenCentral()
          }

          dependencies {
            implementation group: "com.google.guava", name: "guava", version: 'latest.release'
            testImplementation group: "com.google.guava", name: "guava", version: 'latest.integration'
          }
          """
      )
    );
}
```

**Comment by shanman190** [comment]
@timtebeek, I don't see anything in particular either. And looking back at the old version, the logic remains the same as today when scanning the source file to find the variable mappings (if they are present). So I wonder if @asibross may be able to try again with the latest versions of provide some more information about his setup.

**Comment by timtebeek** [comment]
Hmm; #4822 is not related here; but we can reopen this issue if new details emerge on how to trigger the issue with a test or reproducer.
