### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite#47]
I think we need a visitor that changes package name in classes, it's very useful and as I can see it's not implemented yet.

**Comment by jkschneider** [comment]
Absolutely could add something like this. This would be a very simple `JavaIsoRefactorVisitor` that just implements `visitPackage`:

```java
@Override
public J.Package visitPackage(J.Package pkg) {
  return pkg.withExpr(TreeBuilder.buildName(newPackage).withPrefix(pkg.getPrefix()));
}
```

**Comment by sambsnyd** [comment]
Done as part of #248
@Guseyn take a look and let me know if that works for you
