### ISSUE TITLE
Groovy parser does not correctly handle nested parenthesis

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#4703]
When we attempt to parse:
```groovy
def foo(Map map) {
    ((map.containsKey("foo"))
            && ((map.get("foo")).equals("bar")))
}

def timestamp(int hours, int minutes, int seconds) {
    (hours) * 60 * 60 + (minutes * 60) + seconds
}
```

What we actually get is an `IllegalStateException` out of the parser.

Reproduced in [BinaryTest.extraParensAroundInfixOperator()](https://github.com/openrewrite/rewrite/blob/652654e57c5387c93c0c7d844b957c29ced52871/rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java#L207)

**Comment by timtebeek** [comment]
Half of this has already been fixed through
- https://github.com/openrewrite/rewrite/pull/4751

**Comment by jevanlingen** [comment]
Other half has been fixed today: 
- https://github.com/openrewrite/rewrite/pull/4801
