### ISSUE TITLE
Question: Is there a way to Use something like Preconditions in getRecipeList-Method?

### ISSUE THREAD

**Issue by Botschap** [openrewrite/rewrite#4711]
I am using 

- OpenRewrite v8.38.2

I am trying to create a Recipe using Java-Code that adds Maven-Dependencies dependent on two conditions.
1. is a company specific config set in a config-file
2. is the dependency used in the current pom.xml

My Problem is that its not possible to use Preconditions in the 'getRecipeList()'-Method of a Recipe but in the 'getVisitors()'-Method where its not possible to return e.g. the 'AddDependency'-Recipe but only its Visitor. That means the Scanning-Logic is never applied and the Recipe is not beheaving as expected.

Is there a Solution to this Problem or is our approach just the wrong one?

this is how the 'getVisitor()'-Method works
```java
Preconditions.check(
                        Preconditions.and(
                                
                                Preconditions.not(
                                        new FindKey("$.my_config").getVisitor()),
                                // Prüfung auf Vorhandensein der notw. Dependency
                                new FindDependency(groupId, artifactId, null,"").getVisitor()
                        ),

                        new AddDependency(
                              ....
                        ).getVisitor());
```

this is how I would like to use it
```java
Preconditions.check(
                        Preconditions.and(
                                
                                Preconditions.not(
                                        new FindKey("$.my_config").getVisitor()),
                                // Prüfung auf Vorhandensein der notw. Dependency
                                new FindDependency(groupId, artifactId, null,"").getVisitor()
                        ),

                        new AddDependency(
                              ....
                        ));
```

**Comment by timtebeek** [comment]
hi @Botschap ; Indeed the `*RecipeList` methods are not expected to be used with ScanningRecipes; I'll look towards making that explicit.

As for how to still achieve your goals; here's two example of delegating to two other recipes from one scanning recipe:
- One case where the delegated recipes are regular Recipes
https://github.com/openrewrite/rewrite-java-dependencies/blob/bc96656e511a7d8d8c725e3965ca65b12cd81ed4/src/main/java/org/openrewrite/java/dependencies/RemoveDependency.java#L116-L140
- And another where the delegated recipes themselves are also ScanningRecipes
https://github.com/openrewrite/rewrite-java-dependencies/blob/bc96656e511a7d8d8c725e3965ca65b12cd81ed4/src/main/java/org/openrewrite/java/dependencies/AddDependency.java#L159-L180

I hope seeing those examples helps you there; with that I think we can close this issue, but I'll monitor for any replies.
