### ISSUE TITLE
Backwards-incompatible change to ListUtils.map() breaks gradle plugin

### ISSUE THREAD

**Issue by centic9** [openrewrite/rewrite#4730]
It seems the change to ListUtils.map() at https://github.com/openrewrite/rewrite/commit/f4ca98215b0ad660292e17ffb5af3e05cb89f8cd breaks the Gradle plugin.

When trying to apply JUnit4to5Migration it fails with an exception, see details below.

According to https://github.com/openrewrite/rewrite-gradle-plugin/blob/main/plugin/src/main/java/org/openrewrite/gradle/isolated/DefaultProjectParser.java#L1392 the Gradle plugin is still trying to use the old version of "map()".

## What version of OpenRewrite are you using?
Gradle-plugin:	id 'org.openrewrite.rewrite' version '6.27.1'
Dependency: rewrite("org.openrewrite.recipe:rewrite-testing-frameworks:2.23.0")
Gradle: 8.5

## How are you running OpenRewrite?
Via a simple Gradle project

## What is the smallest, simplest way to reproduce the problem?
The following Gradle file triggers the problem for me
```gradle

plugins {
	id 'org.openrewrite.rewrite' version '6.27.1'
}

apply plugin: 'java'

repositories {
	mavenCentral()
}

dependencies {
	testImplementation 'org.junit.vintage:junit-vintage-engine:5.11.3'
	testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.3'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.3'

	rewrite("org.openrewrite.recipe:rewrite-testing-frameworks:2.23.0")
}

rewrite {
	// https://docs.openrewrite.org/recipes/java/testing/junit5/junit4to5migration
	activeRecipe("org.openrewrite.java.testing.junit5.JUnit4to5Migration")
	setExportDatatables(true)
}
```

## What did you expect to see?
I expect Gradle task `rewriteRun` to be executed successfully

## What did you see instead?
Error: NoSuchMethodError: 'java.util.List org.openrewrite.internal.ListUtils.map(java.util.List, 

## What is the full stack trace of any errors you encountered?
```
Caused by: java.lang.NoSuchMethodError: 'java.util.List org.openrewrite.internal.ListUtils.map(java.util.List, java.util.function.UnaryOperator)'
        at org.openrewrite.gradle.isolated.DefaultProjectParser.listResults(DefaultProjectParser.java:1392)
        at org.openrewrite.gradle.isolated.DefaultProjectParser.run(DefaultProjectParser.java:420)
        at org.openrewrite.gradle.DelegatingProjectParser.lambda$run$2(DelegatingProjectParser.java:115)
        at org.openrewrite.gradle.DelegatingProjectParser.unwrapInvocationException(DelegatingProjectParser.java:164)
        at org.openrewrite.gradle.DelegatingProjectParser.run(DelegatingProjectParser.java:114)
        at org.openrewrite.gradle.RewriteRunTask.run(RewriteRunTask.java:36)
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
likely can't invest enough time here for now

**Comment by centic9** [comment]
Downgrading to `rewrite("org.openrewrite.recipe:rewrite-testing-frameworks:2.22.0")` makes it work again.

**Comment by timtebeek** [comment]
hi! Yes pinning back works, or recompiling your recipe jars. We're considering a roll back; you can follow along here:
- https://github.com/openrewrite/rewrite/pull/4729

**Comment by timtebeek** [comment]
Fixed in https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.23.1
Thanks again for the prompt warning!
