### ISSUE TITLE
Extend YAML CommentOutProperty with option to keep original property uncommented

### ISSUE THREAD

**Issue by ashakirin** [openrewrite/rewrite#4740]
Currently YAML CommentOutProperty adds the comment and always comments out original property.
To be consistent with property AddPropertyComment recipe, introduce the option to keep original property and just add a comment.
In the future, it would be nice to align the names and parameters for YAML CommentOutProperty and property AddPropertyComment recipes

**Comment by timtebeek** [comment]
- Fixed in https://github.com/openrewrite/rewrite/pull/4741
Thanks again!
