### ISSUE TITLE
Maven artifact cannot be download when `settings.xml` contains a `<repository>` URL that produces a HTTP 302 redirect

### ISSUE THREAD

**Issue by HelloDhero** [openrewrite/rewrite#4760]
When I set a URL in the repository node of settings. xml that returns 302, it doesn't work

**Comment by timtebeek** [comment]
Hi @HelloDhero ; I've adjusted the title to match what I think you're reporting; could you let me know if that's indeed the case?
What kind of error are you seeing?

We'd welcome a contribution to see this resolved, given that the lack of details makes this hard to pick up for anyone else.

**Comment by HelloDhero** [comment]
![Uploading image.png…]()

**Comment by HelloDhero** [comment]
![Uploading WechatIMG1143.jpg…]()

**Comment by HelloDhero** [comment]
<img width="755" alt="WechatIMG1143" src="https://github.com/user-attachments/assets/2bc183d0-378a-4389-a5b4-ebaa228b54dc">

**Comment by timtebeek** [comment]
Thanks for that context @HelloDhero ; I'll link a couple relevant sources here.

Anytime we do an HTTP request, we ask the context for the configured client
https://github.com/openrewrite/rewrite/blob/6defd9f96f077948d829cecb7e4b741668cef8d1/rewrite-core/src/main/java/org/openrewrite/HttpSenderExecutionContextView.java#L21

We have one HttpSender interface
https://github.com/openrewrite/rewrite/blob/52c770380b60955facd93db47d91a0aa2ae09462/rewrite-core/src/main/java/org/openrewrite/ipc/http/HttpSender.java#L42

With two implementations
https://github.com/openrewrite/rewrite/blob/52c770380b60955facd93db47d91a0aa2ae09462/rewrite-core/src/main/java/org/openrewrite/ipc/http/HttpUrlConnectionSender.java#L30
https://github.com/openrewrite/rewrite/blob/25d374b7c9500c6651dff001f62ea15cff4f9702/rewrite-core/src/main/java/org/openrewrite/ipc/http/OkHttpSender.java#L30

The fallback/default seems to be that `HttpUrlConnectionSender`.
https://github.com/openrewrite/rewrite/blob/6defd9f96f077948d829cecb7e4b741668cef8d1/rewrite-core/src/main/java/org/openrewrite/HttpSenderExecutionContextView.java#L41-L43

I'm guessing that `HttpUrlConnectionSender` does not follow redirects, whereas that does [appear to be the default](https://square.github.io/okhttp/5.x/okhttp/okhttp3/-ok-http-client/-builder/follow-redirects.html) for OkHttpSender. Might be good to verify the `HttpUrlConnectionSender` indeed does not follow redirects.

I'm not sure how you'd swap between those implementations as a user of OpenRewrite; that's perhaps something we could make configurable in the plugins. Or alternatively we can look at supporting redirects with the default HttpSender, as it would seem like a common enough use case. Any help here appreciated!

**Comment by HelloDhero** [comment]
1、I have read the source code and found that currently does not support switching httpSender
2、I think if the local repository already exists, we should not attempt to download it again

**Comment by HelloDhero** [comment]
Sorry, I raised this bug due to a lack of understanding of the `followredirects` restriction on `HttpURLConnection` , my request network is as follows `send http, server response 302 https` , this is not supported.

**Comment by HelloDhero** [comment]
So, you can close this bug now
