### ISSUE TITLE
`AddOrUpdateAnnotationAttribute` not working with nested annotations

### ISSUE THREAD

**Issue by danielshamis** [openrewrite/rewrite#4765]
I am using

- Maven plugin v5.46.1

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
   <groupId>org.openrewrite.maven</groupId>
   <artifactId>rewrite-maven-plugin</artifactId>
   <version>5.46.1</version>
   <configuration>
      <exportDatatables>true</exportDatatables>
      <activeRecipes>
         <recipe>test.AddOrUpdateAnnotationAttributeExample</recipe>
      </activeRecipes>
   </configuration>
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
@Test({
        @TestFunction(name = "a"),
        @TestFunction(name = "b"),
})
```

## What did you expect to see?

```java
@Test({
        @TestFunction(name = "a", value = ""),
        @TestFunction(name = "b", value = ""),
})
```

## What did you see instead?
I am trying to add an attribute to each nested Annotation but no changes are being made. Updating an existing attribute does not work either.

**Comment by timtebeek** [comment]
Hi @danielshamis ; Looks like the recipe was missing a call to `super.visitAnnotation(..)`. Would you mind trying [our snapshot version](https://docs.openrewrite.org/reference/snapshot-instructions) in ~15 minutes or so? Sorry that took a while to get to.

**Comment by danielshamis** [comment]
Hi, thank you for your quick response! Unfortunately I can't use external Maven repositories. Furthermore I couldn't find the updated snapshot version in nexus.

To give more context to my issue, I am now using the latest available version of the maven plugin (5.46.2) but the problem persists. I am using declarative yaml format like this to add new attributes:

```yaml
recipeList:
-org.openrewrite.java.AddOrUpdateAnnotationAttribute:
annotationType:TestFunction
attributeName:value
attributeValue:'""'
addOnly:true
appendArray:false
```

`AddOrUpdateAnnotationAttribute` works for single annotations but has no effect on nested annotations. However both `ChangeAnnotationAttributeName` and `RemoveAnnotationAttribute` work fine with nested annotations.

Sorry for the trouble!

**Comment by timtebeek** [comment]
If our snapshot versions aren't an option for you then we'll do another release tomorrow that should pick up this change. Hope that helps!

**Comment by danielshamis** [comment]
I've tried the latest release 5.46.3 with this change, but the issue remains.

**Comment by timtebeek** [comment]
There's been a bit of a delay getting the latest release out; We'll finally hope to get it out today with new versions of the plugins to follow

**Comment by danielshamis** [comment]
In version 5.47.3 still unresolved unfortunately

**Comment by timtebeek** [comment]
Hmm, thanks for trying newer versions. Perhaps we'd need to write a unit test for this using the sample you've provided above. Would you mind opening up a draft PR adding a new unit test based on this example? Then we can take it from there.
https://github.com/openrewrite/rewrite/blob/621dcfa15c597b64e365ef69569e344681bb8106/rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java#L25-L54
