### ISSUE TITLE
No error logging when mirror is "faulty"

### ISSUE THREAD

**Issue by svaningelgem** [openrewrite/rewrite#4789]
## What version of OpenRewrite are you using?
- OpenRewrite -- latest HEAD

## How are you running OpenRewrite?
Just running as a test.
I enabled "reading maven settings" like this:
```java
    public static boolean readFromDiskEnabled() {
        return true;
    }
```

And create a copy of a test like this:
```java
    @Test
    void changeParent2() {
        rewriteRun(
          spec -> spec.recipe(new ChangeParentPom(
            "com.example.adm.ws4",
            "com.example.adm.ws5",
            "adm-web-site-4-pom",
            "adm-web-site-5-pom",
            "1.0.6",
            null,
            null,
            null,
            true
          )),
          pomXml(
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
              
                <parent>
                    <groupId>com.example.adm.ws4</groupId>
                    <artifactId>adm-web-site-4-pom</artifactId>
                    <version>2.1.10</version>
                </parent>
              
              
                <groupId>com.mycompany.app</groupId>
                <artifactId>my-app</artifactId>
                <version>1</version>
              </project>
              """,
            """
              <project>
                <modelVersion>4.0.0</modelVersion>
              
                <parent>
                    <groupId>com.example.adm.ws5</groupId>
                    <artifactId>adm-web-site-5-pom</artifactId>
                    <version>1.0.6</version>
                </parent>
              
                <groupId>com.mycompany.app</groupId>
                <artifactId>my-app</artifactId>
                <version>1</version>
              </project>
              """
          )
        );
    }
```

Now inside my `settings.xml` file I have this:
```xml
<settings>
	<servers>
		<server>
	    	<id>Maven_Public</id>
	    	<username>user</username>
	    	<password>pass</password>
	    </server>
	</servers>

	<mirrors>
		<mirror>
			<id>Maven_Public</id>
			<mirrorOf>*</mirrorOf>     
			<url>https://nexus.local:1234/repository/Maven_Public/</url>
		</mirror>
	</mirrors>
</settings>
```

Which should pick up any downloaded artifacts (pom, jar, ...) and fit it through our internal Nexus server.

However, I noticed that during resolution of `downloadMetadata` it is passed `getResolutionResult().getPom().getRepositories()`. Which is further elaborated on in `MavenPomDownloader::distinctNormalizedRepositories`.

But nowhere in this chain are the mirrors taken into account it seems.

## What is the smallest, simplest way to reproduce the problem?
See above for the snippet. You need a mirror-of and an internal nexus server set up. Plus maybe a block on the official maven "repo.maven.apache.org" hostname.

## What did you expect to see?
That the test works :)

## What did you see instead?
```
+  <!--~~(com.example.adm.ws5:adm-web-site-5-pom failed. Unable to download metadata.)~~>--><parent>
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?
Looking how to most easily fix this, but I could use some guidance.

References:
- Discussion #4784
- Issue #130

**Comment by svaningelgem** [comment]
@timtebeek : I finally figured this one out. And it was an issue at my side.

Because the Nexus server is internal, it has an internal certificate. The root certificate wasn't added into the cacerts, and during the check [here](https://github.com/openrewrite/rewrite/blob/d4494909e99fbcad0e884a0f5b418bfac532d74f/rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java#L790) it is not reporting anything.
So the error is silently ignored, leaving the end-user clueless what needs to change.

If I would have gotten the error (it was: `sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`), I would immediately know that I had an update of my JDK, and I needed to re-apply the certificates.

Now, I had to step through the code and look at the debugger to realize what was going on ;).

So my suggestion for this would be (but I don't know how, and I guess it'd be relatively small for you/your team): Add some logging to the default method in [ResolutionEventListener.java](https://github.com/openrewrite/rewrite/blob/d4494909e99fbcad0e884a0f5b418bfac532d74f/rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolutionEventListener.java#L66).

**Comment by svaningelgem** [comment]
Step 0: check out latest version from rewrite & gradlew publishToMavenLocal
Step 1: I removed the internal certificates from cacerts in my jdk
Step 2: mvn rewrite:dryRun

No clue what I did now... But it's working as you described:
```
[WARNING] Failed to access maven repository https://nexus.internal:1234/repository/Maven_Public/ due to: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
Maybe something in the latest version (trunk) changed something for the better compared to the one that is online?

I don't know, but I can't reproduce it anymore. So closing this ticket.

Thanks for the continued support @timtebeek !

**Comment by timtebeek** [comment]
All good; those lines were last changed quite some time ago it seems; but happy to see it's working as expected.
- https://github.com/openrewrite/rewrite-maven-plugin/pull/811

Hope that clears any last hurdles you had in getting started!

**Comment by lilumat** [comment]
Hello, I am newbie with openwrite, just run a simple test from doc with petclinic, but I have always this error : 

[INFO] --- rewrite-maven-plugin:6.3.2:run (default-cli) @ spring-petclinic ---
[INFO] Using active recipe(s) [org.openrewrite.java.OrderImports]
[INFO] Using active styles(s) []
[INFO] Validating active recipes...
[INFO] Project [petclinic] Resolving Poms...
[WARNING] Failed to access maven repository https://oss.sonatype.org/content/repositories/snapshots due to: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I used the version plugin 6.3.2 / open jdk 17 / mvn 3.8.3, normally https://github.com/openrewrite/rewrite-maven-plugin/pull/811 fix the issue no ?
Thanks a lot for job :)

**Comment by timtebeek** [comment]
That sounds like you might have some local certificate configuration that prevents access to that host; I don't know what's necessary to get that resolved, but perhaps @svaningelgem has some hints as he's worked through the same before.

**Comment by lilumat** [comment]
Hello,
Thnaks to take time :)

At the beginning, I was think it is blocked but no, it's very long  with timeout on old repo .... It's immediate if i exclude the parsing of pom. 

Logs with -X :

[DEBUG] file=C:\Users\epetremann\.gitconfig, isRacyClean=false, read=2025-03-26 11:24:08.181336900, lastModified=2025-02-24 10:38:17.575361900, delta=2594750605975000 ns, racy<=2500000000 ns
[DEBUG] file=C:\Users\epetremann\.gitconfig, is unmodified
[INFO] Project [petclinic] Resolving Poms...
[WARNING] Failed to access maven repository https://repository.apache.org/snapshots due to: Connect timed out
[DEBUG]
java.net.SocketTimeoutException: Connect timed out
    at sun.nio.ch.NioSocketImpl.timedFinishConnect (NioSocketImpl.java:551)



I try to add ridiculous timeout in my settings.xml but without effect ?!?

```
...
    <server>
      <id>rao</id>
      <configuration>
        <timeout>1</timeout> <!-- milliseconds -->
        <connectTimeout>1</connectTimeout> <!-- milliseconds -->
        <readTimeout>1</readTimeout> <!-- milliseconds -->
      </configuration>
    </server>
...
<profile>
        <id>myTimeouts</id>
        <repositories>

          <repository>
            <id>rao</id>
            <name>repository-apache-org</name>
            <url>https://repository.apache.org/snapshots</url>
          </repository>
...
```

it's annoying to have these problems when evaluating your solution :(

Regards

**Comment by svaningelgem** [comment]
You're likely behind a corporate proxy, and will need to investigate if and how that behaves. Also adding your certificates inside the JDK you use are necessary (at least if it's a capturing proxy).
I hope this points you in the right direction, but very unlikely it's an issue in openrewrite, but more something on the network level.

**Comment by lilumat** [comment]
Hi @svaningelgem , effectively I'm behind a corporate proxy (no chance of changing anything for me). And you have probably reason about issue but I can build "petclinic" without any problem with command: mvn clean install.

So, openrewrite made more that classic build maven with poms ...

I have added certificate of url  https://repository.apache.org/snapshots to my cacert (open-jdk-17) but no changes. I supposed that proxy modify something in request but I'm not an expert in network :( 

Regards
