### ISSUE TITLE
Regression in SimplifyBooleanExpression ?

### ISSUE THREAD

**Issue by philippe-granet** [openrewrite/rewrite#4821]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.42.3

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a single module project.
```xml
<plugin>
  <groupId>org.openrewrite.maven</groupId>
  <artifactId>rewrite-maven-plugin</artifactId>
    ... 
</plugin>
```

## What is the smallest, simplest way to reproduce the problem?

```java
class A {
    private boolean notNullAndNotEqual(String one, String other) {
        return one != null && !one.equals(other);
    }
}
```

## What did you expect to see?

I except no change

## What did you see instead?

instead, Openrewrite generate this:
```java
class A {
    private boolean notNullAndNotEqual(String one, String other) {
        return one != null;
    }
}
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

No time sorry

**Comment by timtebeek** [comment]
Thanks again @philippe-granet ! Fixed just now in https://github.com/openrewrite/rewrite/commit/9cfddab7dee4de929376839061b22c4e9a363de2
