### ISSUE TITLE
AddField accepts a String initilization expression, likely to come out lacking type-attribution

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#49]
As can be seen in our documented example for [AddField](https://docs.openrewrite.org/java/refactoring-java-source-code/addfield#java-definition) it accepts a `String` which is parsed into the initialization expression for the field. When this string is parsed into an AST, it is unlikely to come out type-attributed. This leads to subtle problems running subsequent visitors which might be looking for that type.

AddField, and any other older visitors which accept a String that gets parsed into AST elements, should be updated to instead accept AST elements. The expectation then is that users would then use `TreeBuilder` to construct type-attributed ASTs.

As part of fixing this, the docs for AddField should be updated and other visitors in rewrite-java should be spot checked to see if they have similar issues.

**Comment by jkschneider** [comment]
Superseded by #119
