### ISSUE TITLE
Repair rocksdb maven pom cache when issues are detected.

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite#491]
In rare cases, the on-disk pom maven cache used by rewrite's maven parser can be corrupt. These files act strictly as a volatile cache and when corruption is encountered, the directory used by the cache can be purged and re-created. 

The cache should catch such exceptions and perform the cache cleanup operation.

**Comment by okundzich** [comment]
The outstanding functionality here is to make the cache directory relative to some base directory, so we could safely delete the cache.

**Comment by jkschneider** [comment]
See Olga's comment above:

> The outstanding functionality here is to make the cache directory relative to some base directory, so we could safely delete the cache.

**Comment by tkvangorder** [comment]
Tracey did make the cache directory "pom" relative to whatever is defined as the root cache folder.

The default relative path is `~/.rewrite/cache` and it creates the `pom` folder relative to that. 

Are you suggesting that we should make the relative path `~/.rewrite` and then create `cache/pom`?

**Comment by tkvangorder** [comment]
and to clarify, if you set the "workspace" to `~/something-else`, it would create the pom cache folder `~/something-else/pom`
