### ISSUE TITLE
J.NewClass doesn't expose the names of a constructor's parameters

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#5]
### Description/ Observed Behavior
[J.NewClass](https://github.com/openrewrite/rewrite/blob/ec71c6339cdd36de64bcf540eb7f307904783a83/rewrite-java/src/main/java/org/openrewrite/java/tree/J.java#L2469) represents the invocation of a constructor, e.g.: `new String("foo")`. This is understandable as at the call site the names of the arguments are not present. 

But it would be useful for recipes which operate on constructors to have this information.

This can be worked around with `TypeUtils.asClass(newClass.getType()).getConstructors()`

### Desired Behavior
J.NewClass should have an `Arguments` field the same as [MethodInvocation](https://github.com/openrewrite/rewrite/blob/ec71c6339cdd36de64bcf540eb7f307904783a83/rewrite-java/src/main/java/org/openrewrite/java/tree/J.java#L2045) does.

**Comment by jkschneider** [comment]
@sambsnyd Just FYI, it's not always known what the parameter names are. For the same reason, Jackson etc. have a hard time with constructor injection. They only are determinable if the constructor is defined in the same repository or if the binary in which the constructor is defined was compiled with `-parameters`, which is unfortunately not the default.
