### ISSUE TITLE
AddImport does not work while inserting method argument

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite#52]
In this test project (https://github.com/guseyn/rewrite-java-definitions), I've create following example:
```java
public class InsertMethodArgumentExample {
    public static void main(String... args) throws IOException {
        InsertMethodArgument ima = new InsertMethodArgument();
        ima.setMethod("org.slf4j.Logger debug(String,..)");
        ima.setIndex(0);
        ima.setSource("MarkerFactory.getMarker(\"CONFIDENTIAL\")");
        ChangePackageName cpn = new ChangePackageName();
        cpn.setNewPackageName("org.openrewrite.after");
        AddImport adi = new AddImport();
        adi.setType("MarkerFactory");
        adi.setOnlyIfReferenced(false);
        RefactorProcessor.run(new ArrayList<RefactorVisitor<?>>(){{
            add(ima);
            add(adi);
            add(cpn);
        }}, "I.java");
    }
}
```

`RefactorProcessor.run()` takes file `I.java` from folder `before`, applies visitors which is in `ArrayList`(as first argument) and then puts updated `I.java` into `after` folder.

This is how `I.java` looks before:
```java
package org.openrewrite.before;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class I {
    public void foo() {
        Logger logger = LoggerFactory.getLogger(G.class);
        logger.debug("message");
    }
}
```

And this is how it looks after:

```java
package org.openrewrite.after;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class I {
    public void foo() {
        Logger logger = LoggerFactory.getLogger(G.class);
        logger.debug(MarkerFactory.getMarker("CONFIDENTIAL"), "message");
    }
}
```

As you can see, `import org.slf4j.MarkerFactory;` is missing although I've explicitly created `new AddImport()` visitor.

**Comment by sambsnyd** [comment]
`AddImport` requires you specify the fully qualified name of the type you wish to add an import for. 
I've created [a PR](https://github.com/Guseyn/rewrite-java-definitions/pull/5) to your repository which updates `InsertMethodArgumentExample` accordingly.

**Comment by Guseyn** [comment]
> `AddImport` requires you specify the fully qualified name of the type you wish to add an import for.
> I've created [a PR](https://github.com/Guseyn/rewrite-java-definitions/pull/5) to your repository which updates `InsertMethodArgumentExample` accordingly.

Got it, thanks
