### ISSUE TITLE
Eager initialization of recipe descriptors in YamlResourceLoader causes validation issues

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#520]
At this point in `YamlResourceLoader`, `listRecipes()` could only have known about the recipes in the same YAML.

https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java#L222

Causes output like this in the maven plugin:

![image](https://user-images.githubusercontent.com/1697736/117582051-fff85a00-b0b4-11eb-9058-c97f1f44569d.png)

**Comment by sambsnyd** [comment]
I haven't seen any issue with spurious recipe validation errors in either build plugin or the saas in quite a few releases, I believe we can consider this fixed.
