### ISSUE TITLE
Clean up recipe to either change non-serializable fields to be either Transient or Serializable.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#527]
Create a clean up recipe that changes fields in Serializable classes to be either transient or serializable.

Note, this may be complex.
see: https://rules.sonarsource.com/java/RSPEC-1948?search=Serializable

**Comment by sambsnyd** [comment]
I suspect this would be quite challenging. Recommend that we skip this unless there's significant demand.
