### ISSUE TITLE
ChangeMethodName works only with static methods

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite#54]
In this test project https://github.com/Guseyn/rewrite-java-definitions, I've created following class with regular and static methods:

```
package org.openrewrite.classes;

public class ClassWithMethods {
    public void foo() {}
    public void bar() {}

    public static void fooStatic() {}
    public static void barStatic() {}
}
```

I decided to include package names since I think it can be important.

Then I've created following test class `E` that contains the class above:

```java
package org.openrewrite.before;

import org.openrewrite.classes.ClassWithMethods;

public class E  {
    void foo() {
        new ClassWithMethods().foo();
        ClassWithMethods.fooStatic();
    }
}
```

My Java Definition for `E` class:

```java
        ChangeMethodName cmn = new ChangeMethodName();
        cmn.setMethod("org.openrewrite.classes.ClassWithMethods foo()");
        cmn.setName("bar");
        ChangeMethodName cmnStatic = new ChangeMethodName();
        cmnStatic.setMethod("org.openrewrite.classes.ClassWithMethods fooStatic()");
        cmnStatic.setName("barStatic");
        ChangePackageName cpn = new ChangePackageName();
        cpn.setNewPackageName("org.openrewrite.after");
        List<RefactorVisitor<?>> visitors = new ArrayList<>(){{
            add(cmn);
            add(cmnStatic);
            add(cpn);
        }};
        RefactorProcessor.run(visitors, "E.java");
```

I explain how `RefactorProcessor` in readme of the project: https://github.com/Guseyn/rewrite-java-definitions

When I run the this Java Definition, I get error:

```bash
Exception in thread "main" java.lang.NoSuchMethodError: org.openrewrite.java.tree.J$NewClass.<init>(Ljava/util/UUID;Lorg/openrewrite/java/tree/J$Ident;Lorg/openrewrite/java/tree/J$NewClass$New;Lorg/openrewrite/java/tree/TypeTree;Lorg/openrewrite/java/tree/J$NewClass$Arguments;Lorg/openrewrite/java/tree/J$Block;Lorg/openrewrite/java/tree/JavaType;Lorg/openrewrite/Formatting;)V
	at org.openrewrite.java.Java11ParserVisitor.visitNewClass(Java11ParserVisitor.java:945)
	at org.openrewrite.java.Java11ParserVisitor.visitNewClass(Java11ParserVisitor.java:56)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1711)
	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
	at org.openrewrite.java.Java11ParserVisitor.convert(Java11ParserVisitor.java:1278)
	at org.openrewrite.java.Java11ParserVisitor.visitMethodInvocation(Java11ParserVisitor.java:734)
```

When I comment regular method:

```java
package org.openrewrite.before;

import org.openrewrite.classes.ClassWithMethods;

public class E  {
    void foo() {
        // new ClassWithMethods().foo();
        ClassWithMethods.fooStatic();
    }
}
```

and run the definition again, I get expected result:

```java
package org.openrewrite.after;

import org.openrewrite.classes.ClassWithMethods;

public class E  {
    void foo() {
        // new ClassWithMethods().foo();
        ClassWithMethods.barStatic();
    }
}
```

It seems to me that this visitor works only with static method, otherwise I get weird parsing error.

**Comment by jkschneider** [comment]
@Guseyn This looks to me like a version misalignment. Are you sure all your rewrite dependencies are on the same version and that they align with the rewrite version provided by the maven plugin?

**Comment by Guseyn** [comment]
@jkschneider  I use the latest version if I am not wrong.
```xml
    <dependency>
      <groupId>org.openrewrite</groupId>
      <artifactId>rewrite-java</artifactId>
      <version>5.4.4</version>
    </dependency>
```

**Comment by sambsnyd** [comment]
When I run this example I don't get any error and it works as expected.
I suspect that what made the difference is that I added a dependency on rewrite-java-11, also present in my [pull request](https://github.com/Guseyn/rewrite-java-definitions/pull/5/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8) to your repository. I'm not sure exactly how your examples were working for you without a dependency on either rewrite-java-11 or rewrite-java-8, none of them would run for me before I added that dependency. 

Try things out with that PR and let me know if this is still an issue.

**Comment by Guseyn** [comment]
> When I run this example I don't get any error and it works as expected.
> I suspect that what made the difference is that I added a dependency on rewrite-java-11, also present in my [pull request](https://github.com/Guseyn/rewrite-java-definitions/pull/5/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8) to your repository. I'm not sure exactly how your examples were working for you without a dependency on either rewrite-java-11 or rewrite-java-8, none of them would run for me before I added that dependency.
> 
> Try things out with that PR and let me know if this is still an issue.

Thanks, I will check it out

**Comment by Guseyn** [comment]
@sambsnyd It worked, thanks
