### ISSUE TITLE
Maven UpgradeDependencyVersion handles dependencies where groupId and or artifactId are property values

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#565]
Discovered while working on `rewrite-quarkus` upgrade recipes on a project generated from the [Quarkus Bootstrapping](https://quarkus.io/guides/getting-started) project.

`UpgradeDependencyVersion` fails to upgrade the following dependency because the `MavenVisitor.isDependencyTag(String groupId, @Nullable String artifactId)` method does not handle cases where the `groupId` or `artifactId` are property values.
```xml
<properties>
  <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
  <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
  <quarkus.platform.version>1.11.7.Final</quarkus.platform.version>
</properties>
<dependency>
    <groupId>${quarkus.platform.group-id}</groupId>
    <artifactId>${quarkus.platform.artifact-id}</artifactId>
    <version>${quarkus.platform.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
```

**Comment by aegershman** [comment]
Real quick notes on this--

I don't think the `type` as `pom` and `scope` as `import` within a `dependency` block is legal maven pom.xml syntax. I think if anything, what would be legal is having it be in a `dependencyManagement` section, like so:

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-universe-bom</artifactId>
            <version>${quarkus.platform.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

worth double-checking in case other issues are hiding each other

**Comment by traceyyoshima** [comment]
Property resolution was added in issue 601, but linking didn't automatically close this issue.
