### ISSUE TITLE
Rewrite-Maven UpgradePluginVersion recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#570]
Add `UpdatePluginVersion` to rewrite-maven
Required for [rewrite-quarkus plugin updates](https://github.com/openrewrite/rewrite-quarkus/issues/6)

**Comment by aegershman** [comment]
Just putting this down for note-taking-- believe the scaffolding to do this is technically already possible with existing behavior of `AddPlugin` https://github.com/openrewrite/rewrite/blob/8fa95fec292e3d78f6a6a09dc41c59c864c25d62/rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddPluginTest.kt#L93 but it wouldn't be conditional, e.g. "only update this version if the plugin is already declared"
