### ISSUE TITLE
Rewrite-Maven update plugin configuration recipe

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#571]
Add recipe for updating maven plugin configuration. 
required for [rewrite-quarkus](https://github.com/openrewrite/rewrite-quarkus/issues/6)

---

Gershman edits:
I'm thinking this can be broken into a fundamental discrete which relies on xpath matcher to include children selection criteria. As in, being able to specify an xpath matcher with predicates such as 

```
/project/build/plugins/plugin[artifactId="rewrite-maven-plugin"]/configuration/activeRecipes
```

This would give us multiple benefits:
- 1.) we'd be able to offer this path selection for adding and removing arbitrary configuration keys, and
- 2.) we'd ostensibly be able to reuse this for `rewrite-yaml`, and thus `rewrite-kubernetes` to be able to do element selection criteria. It's basically impossible to select elements from lists without this.

That might make the most sense

**Comment by aegershman** [comment]
an example of updating plugin configuration can be seen here: (https://github.com/openrewrite/rewrite-quarkus/pull/26)
But it's not some special function to being in a `plugin` block. It's just normal xml tag traversal.

Closing this in general, but opened an issue on observations about declarative path matching in https://github.com/openrewrite/rewrite/issues/593
