### ISSUE TITLE
 ChangePropertyValue Recipe doesn't preserve comment

### ISSUE THREAD

**Issue by shresthaujjwal** [openrewrite/rewrite#575]
org.openrewrite.properties.ChangePropertyKey or org.openrewrite.properties.ChangePropertyValue doesn't preserve comments when you run the recipe below.

```
- org.openrewrite.properties.ChangePropertyValue:
      propertyKey: server.tomcat.accesslog.enabled
      newValue: true
```

**Comment by sambsnyd** [comment]
@shresthaujjwal it would be helpful to see the before & after of running it so I can see where the comment was that wasn't preserved

**Comment by shresthaujjwal** [comment]
Hi @sambsnyd 
Add any application.properties file in resource folder then run this recipe
- org.openrewrite.properties.ChangePropertyKey:
    oldPropertyKey: rewrite.changekey
    newPropertyKey: rewrite.newkey
- org.openrewrite.properties.ChangePropertyValue:
    propertyKey: rewrite.changevalue
    newValue: true

As you can see below all the comments has been removed.

![image](https://user-images.githubusercontent.com/16170098/119588567-141fa500-bd9f-11eb-94f9-8d3c0fc46ae7.png)

**Comment by shresthaujjwal** [comment]
Between I am using the 7.5 rewrite version.

**Comment by shresthaujjwal** [comment]
@sambsnyd Any thoughts on this

**Comment by jkschneider** [comment]
@shresthaujjwal Sorry for the delay, and really appreciate the report. This will roll out shortly with 7.7.0 :)
