### ISSUE TITLE
Gradle Dependency Management

### ISSUE THREAD

**Issue by shanman190** [openrewrite/rewrite#581]
Knowing that Gradle's dependency management uses either Groovy DSL (AST is painful of course) or Kotlin DSL (along with the new TOML version catalogs), it would be useful to be have the same dependency management transformations available for Gradle users.

**Comment by sambsnyd** [comment]
We do want to do this. Keep an eye on this issue on our roadmap! https://github.com/openrewrite/rewrite-roadmap/issues/7

**Comment by jkschneider** [comment]
Good to hear from you again @shanman190!

**Comment by sambsnyd** [comment]
Closing this for now. We'll be doing this soon. Keep an eye on our roadmap entry: openrewrite/rewrite-roadmap#7

**Comment by dzeigler** [comment]
@sambsnyd , the roadmap link you mentioned doesn't seem to work anymore. I get a 404. I found this issue as I was looking to see if the gradle version catalog toml file would be supported. Is this still on the roadmap somewhere? Is there a different link to it that you could share?
 Thanks!
