### ISSUE TITLE
JavaTemplate autoFormatting issue when creating new block having list of statements including comments

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite#582]
Discovered while testing `spring-batch` and the `SpringBoot2JUnit4to5Migration`.
`rewrite-testing-frameworks` `ExpectedExceptionToAssertThrows` recipe formatting issues.

Style: `org.openrewrite.java.SpringFormat`

before:
```java
@Test
	public void testNonExistentResource() {
		// given
		this.expectedException.expect(ItemStreamException.class);
		this.expectedException.expectMessage("Failed to initialize the reader");
		this.expectedException.expectCause(Matchers.instanceOf(IllegalStateException.class));
		this.itemReader = new JsonItemReader<>(new NonExistentResource(), this.jsonObjectReader);

		// when
		this.itemReader.open(new ExecutionContext());

		// then
		// expected exception
	}
```

after:
```java
	@Test
	public void testNonExistentResource() {
        Exception exception = assertThrows(ItemStreamException.class, () -> {
            this.itemReader = new JsonItemReader<>(new NonExistentResource(), this.jsonObjectReader);

    // when
		    this.itemReader.open(new ExecutionContext());

    // then
		    // expected exception
	    }, "Failed to initialize the reader");
        assertThat(exception.getCause(), Matchers.instanceOf(IllegalStateException.class));

// then
		// expected exception
	}

```
https://github.com/spring-projects/spring-batch/blob/92e6f32e52d6d6041feb4444d2cfc9369442939e/spring-batch-infrastructure/src/test/java/org/springframework/batch/item/json/JsonItemReaderTests.java#L70-L83

**Comment by jkschneider** [comment]
@pway From the output it appears that there is an attempt to format the block with spaces instead of tabs. Please reassess whether the style was correct.

**Comment by pway99** [comment]
This issue has been resolved
![image](https://user-images.githubusercontent.com/22326988/122133243-2d8d9d00-cdf1-11eb-9252-0bd864789b2f.png)
