### ISSUE TITLE
Language Refactoring

### ISSUE THREAD

**Issue by shanman190** [openrewrite/rewrite#595]
This would require other ASTs to be available first, but I think that it would be neat to provide refactoring across JVM languages.

Ex.
Groovy <-> Java
Java <-> Kotlin
Groovy <-> Kotlin (this could be a two pass AST transform reliant on the previous two transforms)

**Comment by jkschneider** [comment]
Starting with an ambitious goal I see! In the meantime, are there some lower-hanging-fruit recipes you all would like to see?

**Comment by shanman190** [comment]
Gotta have ambitions you know? I'm still mulling over the various ways that I'm wanting to use or seeing a use for this, but you know I'll be back regularly. 😆

**Comment by sambsnyd** [comment]
Closing this issue for now. We are still planning to create Groovy and Kotlin ASTs to facilitate scenarios like this one. Keep an eye on these roadmap entries:

https://github.com/openrewrite/rewrite-roadmap/issues/11
https://github.com/openrewrite/rewrite-roadmap/issues/12
