### ISSUE TITLE
Template cannot replace a method invoctaion that returns a method reference with just a method reference

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#602]
Found the issue in rewrite-migrate-java NoGuavaDirectExecutorTest.

The JavaTemplate fails to generate a statement when a MethodReference is replacing a MethodInvocation.
The [Space.Location returned](https://github.com/openrewrite/rewrite/blob/87c2553752e68e846d2bc282b3edffaf0264dd4d/rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java#L72) from the JavaCoordinates is STATEMENT_PREFIX.

JavaTemplate [matches](https://github.com/openrewrite/rewrite/blob/87c2553752e68e846d2bc282b3edffaf0264dd4d/rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java#L291) the location, but BlockStatementTemplateGenerator fails anything, since a MethodReference isn't [an instance of a Statement](https://github.com/openrewrite/rewrite/blob/87c2553752e68e846d2bc282b3edffaf0264dd4d/rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java#L95).

Exception:
```
Caused by: java.lang.IllegalArgumentException: Expected a template that would generate exactly one statement to replace one statement, but generated 0
```

**Comment by jkschneider** [comment]
In this context, the method invocation is an expression. Some trees are both expressions and statements depending on the context. The larger question here is whether we should allow the replacement of a statement that happens to be an expression. I'd like to think about this a bit more before closing.
