### ISSUE TITLE
Wrong enum autoformatting

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#620]
Indent looks wrong, and blank lines keep being added after each run

### Expected
```java
public enum TheEnum {
    FIRST,
    SECOND,
}
```

### Actual after first run
```java
public enum TheEnum {
    
        FIRST,
        SECOND,
}
```

### Actual after second run
```java
public enum TheEnum {
    
    
        FIRST,
        SECOND,
}

```

**Comment by jkschneider** [comment]
Appears to be caused by the fact that we haven't correctly normalized the first `EnumValue` prefix outward to the containing `EnumValueSet` like we do for many other things.

**Comment by jkschneider** [comment]
Thanks for the report @murdos. We'll be rolling out 7.7.0 shortly.

**Comment by murdos** [comment]
Thanks for the fix, that was fast!
FYI I'm evaluating open-rewrite on a legacy project that I'm working on, so I'll probably add new issues as I found them.

Do you know if it's possible to use a snapshot version of rewrite with a released version of rewrite-maven-plugin, or if I should also build snapshot version of the maven plugin to test the main branch?
