### ISSUE TITLE
New java recipe: ChangeMethodAccessLevel

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#622]
There are already 3 implementations for the need to change accessibility to package-private (that all deal with comments):
- https://github.com/openrewrite/rewrite-testing-frameworks/blob/main/src/main/java/org/openrewrite/java/testing/junit5/UpdateBeforeAfterAnnotations.java#L83
- https://github.com/openrewrite/rewrite-testing-frameworks/blob/8d50523e171cc10f272af5afd09fce425ba9cbe5/src/main/java/org/openrewrite/java/testing/junit5/UpdateTestAnnotation.java#L178
- https://github.com/openrewrite/rewrite-spring/blob/main/src/main/java/org/openrewrite/java/spring/BeanMethodsNotPublic.java#L62

I was thinking that rather than just handle this use case (* -> package-private), we might benefit from a recipe a bit more generic, that would take before and after levels, and change method accordingly:
- {public,private,protected} -> {public,private,protected} : update access modifier
- {public,private,protected} ->package-private : remove access modifier
- package-private -> {public,private,protected} : add access modifier

Please let know what you think, and I'll try to implement it.

**Comment by jkschneider** [comment]
Sounds useful. I suspect it would be useful to have a separate `ChangeMethodAccessLevelVisitor`, since I suppose the `Recipe` would match on a method pattern. In these three scenarios the matching logic is a bit more complex, even though the action is the same.
