### ISSUE TITLE
MethodPattern("* build()") doesn't match anyhting

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#629]
If my code has `Response.status(200).build()` the pattern isn't matched. However, if the pattern is `"javax.ws.rs.core.Response.ResponseBuilder build()"` it works.
Suspecting `"*"` for the type not making it in properly into regular expression, i.e. `[^.]*` is the regular expression for the type... `^` should be not inside `[]` ?

**Comment by jkschneider** [comment]
The * in AspectJ is not greedy, and we were trying to adhere to that. AspectJ syntax does have something though that supports your use case I think. Either of these would match:

* `*..* build()`
* `javax..* build()`

I'm happy to implement these if this makes sense.

**Comment by jkschneider** [comment]
If we do implement this, the test is:

```kotlin
@Issue("https://github.com/openrewrite/rewrite/issues/629")
@Test
fun wildcardType(jp: JavaParser) {
    assertTrue(MethodMatcher("*..* build()").matchesTargetType(JavaType.Class.build("javax.ws.rs.core.Response")))
    assertTrue(MethodMatcher("javax..* build()").matchesTargetType(JavaType.Class.build("javax.ws.rs.core.Response")))
}
```

**Comment by BoykoAlex** [comment]
We are trying to mark "builder" patterns in the code, i.e. `Response.ok().build()` hence `*..* build()` should do it for us. The test looks good too.

**Comment by sambsnyd** [comment]
The test Jonathan provides passes currently. Since that works for you, Alex, I'm closing this issue.
