### ISSUE TITLE
AutoFormat doesn't separate statements out onto their own lines

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#63]
Given input like:
```java
public class D {public String foo() {String foo = "foo";foo = foo + foo;return foo;}}
```

I expect AutoFormat to produce output like:
```java
public class D {

    public String foo() {
        String foo = "foo";
        foo = foo + foo;
        return foo;
    }
}
```

Instead its actual output is:
```java
public class D {

    public String foo() {String foo = "foo"; foo = foo + foo;return foo;}}
```

Run [AutoFormatTest.separatesStatementsWithEmptyFormatting()](https://github.com/openrewrite/rewrite/commit/ba4d505f2b5c9a98b359254583b55360dbf0a263) to reproduce this issue

**Comment by jkschneider** [comment]
Superseded by #117
