### ISSUE TITLE
Add annotations to Comment model object.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#671]
The body of the Block & JavaDoc comments is a String.
There is logic to interpret the string to handle whitespace changes, create new comments, etc.
But we don't check for annotations in the comment and represent them in the model.

There are several issues related to recipes changing AST elements that may need to either update the annotations and / or leave the AST element alone.

Things like RemoveUnused imports checks for the classes in the CompilationUnit, but leaves the references in the JavaDocs.

Renaming method parameters may leave @param value in place with the wrong name, etc.

**Comment by sambsnyd** [comment]
I believe this is done now that we're fully parsing JavaDoc comments

**Comment by jkschneider** [comment]
Duplicated by #921
