### ISSUE TITLE
UseDiamondOperator does not fix HashMap

### ISSUE THREAD

**Issue by gregorriegler** [openrewrite/rewrite#676]
```
private final Map<X,Y> map = new HashMap<X, Y>();
```
should have been changed to
```
private final Map<X,Y> map = new HashMap<>();
```
but was not

**Comment by jkschneider** [comment]
Thanks @gregorriegler. We also caught the issue about overly aggressive use of diamond when the LHS didn't provide enough of a type hint based on your PR to Eureka. Working on that too.

**Comment by gregorriegler** [comment]
@jkschneider the thing with the LHS is quite subjective in my opinion.
If I applied the recipe in my codebase I would want it to be that aggressive. 

Perhaps having two versions: `UseDiamondOperator` and `PassivelyUseDiamondOperator` or similar would be a solution.

**Comment by tkvangorder** [comment]
See #682 for the fix to the overly aggressive use of diamond operators when the "new" operation is a receiver on a method invocation.
