### ISSUE TITLE
mixed single-line, multiline comment handling

### ISSUE THREAD

**Issue by gadams00** [openrewrite/rewrite#678]
cassandra has this code in `test/unit/org/apache/cassandra/db/commitlog/CommitLogTest.java`

```
protected Void testRecovery(byte[] logData, int version) throws Exception
    {
        File logFile = tmpFile(version);
        try (OutputStream lout = new FileOutputStream(logFile))
        {
            lout.write(logData);
            //statics make it annoying to test things correctly
            CommitLog.instance.recover(logFile.getPath()); //CASSANDRA-1119 / CASSANDRA-1179 throw on failure*/
        }
        return null;
    }
```

running the cleanup recipe (and presumably pretty much any recipe) creates a diff like this:

```
@@ -596,7 +595,7 @@
     }returnnull;
     }

-    protected Void testRecovery(CommitLogDescriptor desc, byte[] logData) throws Exception
+    protected Void testRecovery(CommitLogDescriptor desc, byte[] logData)
     {
         File logFile = tmpFile(desc.version);
         CommitLogDescriptor fromFile = CommitLogDescriptor.fromFileName(logFile.getName());
```

The whitespace around the return is wrong for some reason, I would assume something to do with the multiline comment ending delimiter without a beginning. This causes git apply to error.

**Comment by traceyyoshima** [comment]
@gadams00 I've updated a lot in the TabsAndIndentsVisitor related to comments over the last couple days.
I ran the clean up recipe and don't see this issue in the output.

I plan to close the issue unless you have any further concerns.

**Comment by gadams00** [comment]
@traceyyoshima sounds good
