### ISSUE TITLE
Classpath from MavenModel

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#69]
How would I get the classpath of a Maven project with a help of OpenRewrite?

Currently we're performing the following:

```
        List<Maven.Pom> mavenPoms = MavenParser
                .builder()
                .resolveDependencies(true)
                .build()
                .parse(List.of(buildFilePath), null);
```

Then on the resultant Pom object we'd call `getModel().getTransitiveDependenciesByScope()` and get all scopes dependencies.

These however seem to be more than project's classpath and computation of transitive dependencies (with resolveDependencies flag on) takes ~20s for the project attached below. Transitive dependencies number is huge. Note that all jars are in the local maven repo and are not downloaded.

Whenever, I try to use https://github.com/shrinkwrap/resolver to compute the classpath of the project below it takes less than a second or around a second and return much less dependencies (but their are the same as M2Es in Eclipse).

What is the purpose of transitive dependencies on the MavenModel in OpenRewrite? Is it the classpath or is meant for something else?

[jboss.zip](https://github.com/openrewrite/rewrite/files/5513987/jboss.zip)

**Comment by jkschneider** [comment]
The latest head contains a utility method showing how to perform this operation:

![image](https://user-images.githubusercontent.com/1697736/101114373-30801900-3596-11eb-9110-53d862c2daa7.png)
