### ISSUE TITLE
Single line comments before modifiers cause modifiers to be skipped

### ISSUE THREAD

**Issue by SofiaBrittoSchwartz** [openrewrite/rewrite#70]
When the following is parsed, `"\npublic"` is included in the prefix of `class` rather than being parsed as a modifier. This behavior only occurs with single line comments.
```
@Category()
// Some comment
public class B {
}
```

To recreate this behavior reference [singleLineCommentParsingError](https://github.com/openrewrite/rewrite/commit/491ae9869d117a4965b9b6dabbea476f2998e479).

**Comment by jkschneider** [comment]
More specifically, `public` is on `J.ClassDecl.Kind`, not on the class.
