### ISSUE TITLE
JavaVisitor#visitMethodDeclaration doesn't visit leading annotations in the name prefix.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#726]
Discovered while attempting to remove an annotation between the modifier and the name of a class declaration.

Sample:
```
public @Autowired className {
}
```

The annotation shows up in the AST in J.MethodDeclaration -> name (IdentifierWithAnnotations) -> prefix -> leadingAnnotation.

The J.MethodDeclaration contains a `IdentifierWithAnnotations name`, but isn't directly accessible.
J.MethodDeclaration has a getName() that calls name.getIdentifier(), but no getIdentifierWithAnnotations().

Also, visitAnnotation never triggers on the annotation, seemingly because the JavaVisitor#visitMethodDeclaration code is `m = m.withName(visitAndCast(m.getName(), p));`

**Comment by tkvangorder** [comment]
Closing this, the annotations on the identifier are accessible via the `methodDeclaration.getAnnotations().getName()` wrapper. 

The visitor is correctly being called in this use case.

**Comment by tkvangorder** [comment]
The annotations are the identifier are not being visited.
