### ISSUE TITLE
ImportLayoutStyle#ImportPackage always calls Pattern.compile(packageWildcard).

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#738]
```
            public ImportPackage(Boolean statik, String packageWildcard, boolean withSubpackages) {
                this.statik = statik;
                this.packageWildcard = Pattern.compile(packageWildcard
                        .replace(".", "\\.")
                        .replace("*", withSubpackages ? ".+" : "[^.]+"));
            }
```
Serialization and deserialization replace the "." characters with escaped characters.
The Deserializer calls `builder.importPackage(block)` on a pattern like java\\.\.+, which creates a new ImportPackage.
And generates java\\\.\\.+., so the package wildcard fail to recognize the pattern and everything is grouped into allOtherImports.

**Comment by jkschneider** [comment]
Fixed with 2a77145f649c648a672c30c3c7bf004fdc1f8f91
