### ISSUE TITLE
UpgradeDependencyVersion affecting unexpected dependencies

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#739]
Putting this issue here for now, can move it.

Can reproduce this by cloning https://github.com/pway99/quarkus-demo and doing `./mvnw rewrite:run`

Example:

```xml
    <dependency>
      <groupId>org.mindrot</groupId>
      <artifactId>jbcrypt</artifactId>
      <version>0.4</version>
    </dependency>
```

going to

```xml
    <dependency>
      <groupId>org.mindrot</groupId>
      <artifactId>jbcrypt</artifactId>
      <version>1.13.7</version>
    </dependency>
```

picture example, where the version of the `bom` dependency seems to be added to dependencies which are otherwise receiving their versions from the quarkus universe bom-- including dependencies which shouldn't be upgraded:

<img width="838" alt="upgradeDependencyVersion" src="https://user-images.githubusercontent.com/5619476/124176476-8e190d00-da74-11eb-9cc4-90aa356faf91.png">

**Comment by traceyyoshima** [comment]
I wrote explicit maven tests that use the same pom structure with io.quarkus and tried both upgrade dependency and plugin. In both cases, only the property was updated.

It may be related to a sequence of recipes, but I didn't get the test to recognize quarkus 1 to 2 on the class path.

**Comment by aegershman** [comment]
If it means anything I was able to reproduce it in a test here: https://github.com/openrewrite/rewrite/pull/740 I haven't debugged it yet, I imagine it's something to do with property resolution on dependencies defined in the `bom`.
