### ISSUE TITLE
Recipe validation error in org.openrewrite.java.security.JavaSecurityBestPractices

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite#753]
https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/resources/META-INF/rewrite/security-bugs.yml refers to a recipe that doesn't exist: `org.openrewrite.java.security.ResultOfFileMkdirsIgnored` 

It might be nice to have some unit tests that verify declarative recipes.

**Comment by sambsnyd** [comment]
Good catch and thanks for reporting, @murdos. Agreed we should add some verification of declarative recipes as part of our standard testing.
