### ISSUE TITLE
Support Java assert detail

### ISSUE THREAD

**Issue by breskeby** [openrewrite/rewrite#766]
When a recipe is changing a class with an assertion that contains a string with a semicolon, the generated java source is invalid and results in compile errors.

Here's an example I ran into with the elasticsearch codebase (https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/shard/IndexShard.java#L533-L539):

```
                    assert newRouting.initializing() == false :
                        "a started primary shard should never update its term; "
                            + "shard " + newRouting + ", "
                            + "current term [" + pendingPrimaryTerm + "], "
                            + "new term [" + newPrimaryTerm + "]";
                    assert newPrimaryTerm > pendingPrimaryTerm :
                        "primary terms can only go up; current term [" + pendingPrimaryTerm + "], new term [" + newPrimaryTerm + "]";
```

results in erroneous generated code:

```
                    assert newRouting.initializing() == false :
                        "a started primary shard should never update its term;
                    assert newPrimaryTerm > pendingPrimaryTerm :
                        "primary terms can only go up;
```

As you can see the String in the generated source only contains the first part of the original string. Looking at it closer it seems the issue here seems the semicolon in the String and not the concatenation.

**Comment by jkschneider** [comment]
We didn't yet support assert detail (the stuff after `:`). I didn't even know this was a thing in Java ;)
