### ISSUE TITLE
Replace type with a nested type

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#774]
```kotlin   
 @Test
    fun replaceWithNestedType(jp: JavaParser) = assertChanged(
        jp,
        recipe = ChangeType("java.io.File", "java.util.Map.Entry"),
        before = """
            import java.io.File;
            
            class Test {
                File p;
            }
        """,
        after = """
            import java.util.Map;
            
            class Test {
                Map.Entry p;
            }
        """
    )
```

Currently the following produced:

```java
import java.util.Map.Entry;

class Test {
    Map.Entry p;
}
```

Looks like `ChangeType#visitCompilationUnit(...)` code adding the import should account for nested types... seems like we'd go for `Map.Entry` in the code and `java.util.Map` (top level type as the import. (I was going the other direction but think the one you picked is a better one)

**Comment by BoykoAlex** [comment]
Perhaps this test should actually go in the other direction - the nested type in the import (the targetType of the ChangeType) rather than the top level:
```kotlin
    @Test
    fun replaceWithNestedType(jp: JavaParser) = assertChanged(
        jp,
        recipe = ChangeType("java.io.File", "java.util.Map.Entry"),
        before = """
            import java.io.File;
            
            class Test {
                File p;
            }
        """,
        after = """
            import java.util.Map.Entry;
            
            class Test {
                Entry p;
            }
        """
    )

```
Seemed to me it should easier to adjust `ChangeType` to this expected result rather than the one in the description at the top

**Comment by jkschneider** [comment]
I think we'll stick to the first form @BoykoAlex if that's OK, because that's what the IDE does by default.
