### ISSUE TITLE
Change the type of the type declaration in CU

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#775]
Turns out this test used to work in 7.2.2 it seems:

```kotlin
    @Test
    fun changeTypeInTypeDeclaration(jp: JavaParser) = assertChanged(
        jp,
        recipe = ChangeType("de.Class2", "de.Class1"),
        before = """
            package de;
            public class Class2 {};
        """,
        after = """
            package de;
            public class Class1 {};
        """
    )
```

Is this still supposed to work? This more of a type renaming...

**Comment by sambsnyd** [comment]
Revisiting this, I think it is a mistake to support this functionality in `ChangeType`.

`ChangeType` is about replacing _usage_ of one type with _usage_ of another type.
Renaming class definitions is a separate concern.
