### ISSUE TITLE
Add newline character detection to Autodetect.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#789]
Discovered while looking into an issue in ImportLayoutStyle#orderImports that replaced CRLF prefixes with LF.
The orderImports method always uses LF characters in the import prefixes, which creates large diffs in CRLF repos.

It'd be helpful to know which new character is used in a project for things like TabsAndIndentsVisitor, ImportLayoutStyle, Space, etc.

**Comment by jkschneider** [comment]
@traceyyoshima Can you list some examples here of CRLF repos?

**Comment by traceyyoshima** [comment]
KualiCo/rice is an old repo, but has been a great source of view formatting results. It uses a lot of CRLF.
Currently, most of the OrderImport results on Netflix/Priam are due to CRLF.
