### ISSUE TITLE
Comments don't make into AST generated from snippets

### ISSUE THREAD

**Issue by BoykoAlex** [openrewrite/rewrite#793]
Here is the test for our attempt to add annotation with comment via a java template:

```kotlin
    @Test
    fun replaceClassAnnotationsWithAnnotationWithComment(jp: JavaParser) = assertChanged(
        jp,
        recipe = object : JavaIsoVisitor<ExecutionContext>() {
            val t = JavaTemplate.builder({ cursor }, """
                /**
                 * Do suppress those warnings
                 */
                @SuppressWarnings("other")
            """.trimIndent())
                .doBeforeParseTemplate(print)
                .build()

            override fun visitClassDeclaration(classDecl: J.ClassDeclaration, p: ExecutionContext): J.ClassDeclaration {
                if(classDecl.leadingAnnotations.size == 0 && classDecl.simpleName != "Test") {
                    return classDecl.withTemplate(t, classDecl.coordinates.replaceAnnotations())
                }
                return super.visitClassDeclaration(classDecl, p)
            }
        }.toRecipe(),
        before = """
            class Test {
                static final String WARNINGS = "ALL";
                
                class Inner1 {
                }
            }
        """,
        after = """
            class Test {
                static final String WARNINGS = "ALL";
            
                /**
                 * Do suppress those warnings
                 */
                @SuppressWarnings("other")
                class Inner1 {
                }
            }
        """
    )
```

Not sure if this was meant to work... Perhaps we're better off adding a marker to the result annotation

**Comment by sambsnyd** [comment]
I've looked into this a little bit. Thanks for providing a test case. Made it very easy to get started.

This is the template which gets generated for your test case:
```
class Test{
    class Inner1{}
    static final String WARNINGS;
    /*__TEMPLATE__*//**
     * Do suppress those warnings
     */
    @SuppressWarnings("other")
    static class $Clazz {}
}
```
This is good, the comment is still there.

But the comment is actually attached to the class declaration, not the annotation:
![image](https://user-images.githubusercontent.com/8549033/127081174-e11ab2c8-fbf0-4c20-b4ed-a10088e78255.png)

This is deliberate & normal. JavaParser follows the convention that comments should be attached to the outermost-possible element, which in this case is the class declaration. That convention is very helpful so it isn't going to change.

If there were another annotation _before_ the `@SuppressWarnings` and its comment, that would force the comment to be attached to `@SuppressWarnings` itself. So my idea to fix this is to have `AnnotationTemplateGenerator` put in placeholder annotations before any real annotations.

**Comment by jkschneider** [comment]
Sounds reasonable @sambsnyd
