### ISSUE TITLE
Add ControlFlowIndentation recipe to fix indentation of statements after block-less control flow statements

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#801]
see also: https://rules.sonarsource.com/java/RSPEC-2681

>Curly braces can be omitted from a one-line block, such as with an if statement or for loop, but doing so can be misleading and induce bugs.

```java
if (condition)
  first()
  second();  // executed unconditionally
third(); // outside condition
```

should be

```java
if (condition) 
  first()
second();  // executed unconditionally
third(); // outside condition
```

**Comment by jkschneider** [comment]
A decent solution here is to simply run `TabsAndIndents` (or `AutoFormat` more generally). This kicks the second statement back over to the left. It will be up to the code reviewer of the suggested change to determine whether it was intended to be part of the block.
