### ISSUE TITLE
Maven: not resolving test dependencies of parent dependencies section

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#813]
Missing dependencies like this:

![image](https://user-images.githubusercontent.com/1697736/126364893-057048c6-efa6-4047-adda-0c481d220b9a.png)

**Comment by murdos** [comment]
@jkschneider : could this be the same issue as the one described here? https://github.com/openrewrite/rewrite/issues/646#issuecomment-875938641

**Comment by jkschneider** [comment]
Thank you @murdos. It is indeed a duplicate of #646.
