### ISSUE TITLE
RemoveUnused* recipes should support SuppressWarnings(unused) annotation

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite#841]
E.g., UnusedLocalVariables + UnusedPrivateMethods examples

UnusedLocalVariables:
![Screen Shot 2021-07-26 at 4 34 20 PM](https://user-images.githubusercontent.com/5619476/127062308-cc01708b-01f3-49c5-bb15-eb56199d111f.png)

UnusedPrivateMethods:

![Screen Shot 2021-07-26 at 4 35 24 PM](https://user-images.githubusercontent.com/5619476/127062366-d602a982-2ac5-4a69-a6cb-3ed8c78a4ef8.png)

Is it a bug? Is it an enhancement? It can be _both_.

**Comment by jkschneider** [comment]
This is supported by `RemoveUnusedPrivateMethods` by virtue of the fact that we now ignore all methods that have annotations on them.

**Comment by traceyyoshima** [comment]
@jkschneider not sure if it's worth handling, but there's a case in Netflix/Hollow where the suppression happens at the class declaration:
```
@SuppressWarnings("unused")
public class HollowPrimaryKeyIndexTest extends AbstractStateEngineTest {
...
}
```
