### ISSUE TITLE
Some imports removed if they match java.lang class names

### ISSUE THREAD

**Issue by metron2** [openrewrite/rewrite#859]
Both OrderImports and RemoveUnusedImports remove imports for classes that match java.lang names.

We have data type classes called Thread and Process that get removed, but that breaks the compilation of the class.

**Comment by traceyyoshima** [comment]
Hi @metron2, thanks for reporting the issue!
Could you share more details on what the original source looks like?

**Comment by metron2** [comment]
Yeah it's pretty simple. We have an import statement for a class like so:
`import com.myproject.generated.complex.Process;`
and the code in that class references that Process class.

When I run the imports recipes, that line gets removed and `java.lang.Process` is then implied but since I wasn't using that Process it breaks compilation.
