### ISSUE TITLE
Convert DTO to record

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite#887]
For context: https://twitter.com/MarcusBiel/status/1425488331094302721

**Comment by sebastiankonieczek** [comment]
Could you please assign it to me? I would attempt it in coming weeks...

**Comment by timtebeek** [comment]
Continued in rewrite-migrate-java, considering that's where the other Java language feature migration recipes already live.
- https://github.com/openrewrite/rewrite-migrate-java/issues/391
