### ISSUE TITLE
UnnecessaryThrows should not remove throws from interface implementations and abstract method overrides

### ISSUE THREAD

**Issue by burtbeckwith** [openrewrite/rewrite#897]
Related to https://github.com/openrewrite/rewrite/issues/519 but a different issue.

Removing an unused `throws` from an implementation method breaks subclassing, e.g. for this interface

```
import java.io.IOException;

public interface Foo {
    void bar() throws IOException;
}
```

and this impl

```
public class FooImpl implements Foo {

    @Override
    public void bar() throws IOException {
        // no-op
    }
}
```

If `throws IOException` is removed then I can't extend `FooImpl` and override `bar` with `throws IOException` since it's not in the base class method.

```
public class FooImpl2 extends FooImpl {

    @Override
    public void bar() {
        File.createTempFile("a", "b");
    }
}
```

This would be sort of ok for a RuntimeException since you can add add the `throws` back, but it should probably be consistent with checked exception behavior.

**Comment by jkschneider** [comment]
Interesting case. In the spirit of "do no harm", we can limit the aggressiveness of the recipe in this case.
