### ISSUE TITLE
Execution fails for JDK 16

### ISSUE THREAD

**Issue by burtbeckwith** [openrewrite/rewrite#909]
A user reported https://stackoverflow.com/questions/68841415/upgrading-micronaut-2-x-to-3-x-using-openrewrite-superclass-access-check-failed and I was able to replicate with an empty Micronaut 3.0.0 project with just the `openrewrite` feature. Downgrading to JDK 15 worked.

**Comment by pway99** [comment]
Starting with java 16, the default JVM behavior is not to allow access to protected modules. The workaround for this issue is to add explicit exports for packages used by rewrite's java parser.

You can do this on the command line like this:
```
gw rewriteRun -Dorg.gradle.jvmargs="--add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED"
```
or add the following to your gradle.properties file:
```
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```

**Comment by pway99** [comment]
Hi @burtbeckwith,

I have updated the plugins to check for the necessary JVM-protected module exports and to log a message with instructions on configuring either the Maven or Gradle configuration if necessary.

Also, I have updated the documentation as it turns out that Java 17 requires three additional module exports.

Thanks again for raising this issue.
