### ISSUE TITLE
Parsing error: Out of Memory Exception during visitDocComment

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite#948]
Discovered in the ingest-container [output](https://github.com/moderneinc/moderne-ingest-action/runs/3478015969?check_suite_focus=true#step:5:823) of spring-projects/spring-kafka.

There are several OOM exceptions in the linked output during Java11JavadocVisitor.visitDocComment.

**Comment by jkschneider** [comment]
Fixed with latest HEAD, may be fixed by Javadoc parsing fixes.
