### ISSUE TITLE
Maven resolver doesn't substitute properties recursively.

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite#95]
I'll use spring-cloud-stream-parent and spring-cloud-stream as concrete examples, but the issue is more general than just those poms.

The [spring-cloud-stream-parent](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-stream-parent/2.1.4.RELEASE/spring-cloud-stream-parent-2.1.4.RELEASE.pom) pom uses a dependencyManagement section to set out versions for various org.springframework.cloud dependencies. 
The [spring-cloud-stream](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-stream/2.1.4.RELEASE/spring-cloud-stream-2.1.4.RELEASE.pom) pom entirely omits the <version> tag for dependencies whose versions are coming from the parent's dependencyManagement section, like so:

```xml
<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
        <optional>true</optional>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
...
</dependencies>
```

When encountering this pom RawMavenResolver throws [here](https://github.com/openrewrite/rewrite/blob/ac1b83c3dd12081dbbd4de9318e685306e5f9788/rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawMavenResolver.java#L254).

I've added a `@Disabled` test to [MavenDependencyResolutionIntegTest](https://github.com/openrewrite/rewrite/blob/be069d2c6dbc6c6207925314f3e53c18fa22dbfc/rewrite-maven/src/integTest/kotlin/org/openrewrite/maven/MavenDependencyResolutionIntegTest.kt#L441) to exercise this

**Comment by jkschneider** [comment]
This isn't a general problem with parent dependency management. There is something special here about spring-messaging.

**Comment by jkschneider** [comment]
Guessing it's that we may not be recursively evaluating props:

![image](https://user-images.githubusercontent.com/1697736/100954811-298bd480-34ca-11eb-8f1f-5703ca3bb073.png)

https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.6.RELEASE/spring-boot-dependencies-2.1.6.RELEASE.pom

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/100955127-c9496280-34ca-11eb-838d-90d2a72dc6f0.png)
